### ISSUE TITLE
ControlNet expects added_cond_kwargs to not be null, which pipeline_controlnet_img2img does not respect

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#10030]
### Describe the bug

Please see this code in pipeline_control_img2img.py

https://github.com/huggingface/diffusers/blob/ad5ecd1251472dbc69da1268671d41bc2d8c1caa/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1199-L1203

### Reproduction

I think the pipeline is just straight up bugged since the addition of IPAdapter which likely came after this pipeline. If you try it just won't work. At least, with the models I'm using

* Proteus v0.6 https://huggingface.co/dataautogpt3/Proteus-v0.6
* ControlNet HED https://huggingface.co/Eugeoter/noob-sdxl-controlnet-softedge_hed
* ControlNet Canny https://huggingface.co/Eugeoter/noob-sdxl-controlnet-canny
* ControlNet Depth https://huggingface.co/Eugeoter/noob-sdxl-controlnet-depth

### Logs

```shell
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "/workspace/discore_deploy/src/lib/corelib.py", line 99, in invoke_safe
INFO STDERR:     func(*kargs, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/sessions/diplo-xl/script.py", line 345, in frame
INFO STDERR:     std.render_switch(
INFO STDERR:   File "/workspace/discore_deploy/src/lib/loglib.py", line 291, in trace_wrapper
INFO STDERR:     return _trace_wrapper(func, True, *args, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/src/lib/loglib.py", line 286, in _trace_wrapper
INFO STDERR:     return func(*args, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/src/party/std.py", line 701, in render_switch
INFO STDERR:     rv.img = txt2img(**args)
INFO STDERR:   File "/workspace/discore_deploy/src/common.py", line 60, in wrapped_call
INFO STDERR:     return function(*kargs, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/src/lib/loglib.py", line 298, in trace_wrapper
INFO STDERR:     return _trace_wrapper(func, False, *args, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/src/lib/loglib.py", line 286, in _trace_wrapper
INFO STDERR:     return func(*args, **kwargs)
INFO STDERR:   File "/workspace/discore_deploy/scripts/interfaces/diffusers_turbo.py", line 250, in txt2img
INFO STDERR:     images = lib.pipe_txt(
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
INFO STDERR:     return func(*args, **kwargs)
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 1235, in __call__
INFO STDERR:     down_block_res_samples, mid_block_res_sample = self.controlnet(
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
INFO STDERR:     return self._call_impl(*args, **kwargs)
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
INFO STDERR:     return forward_call(*args, **kwargs)
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/multicontrolnet.py", line 48, in forward
INFO STDERR:     down_samples, mid_sample = controlnet(
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
INFO STDERR:     return self._call_impl(*args, **kwargs)
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
INFO STDERR:     return forward_call(*args, **kwargs)
INFO STDERR:   File "/opt/conda/lib/python3.10/site-packages/diffusers/models/controlnet.py", line 778, in forward
INFO STDERR:     if "text_embeds" not in added_cond_kwargs:
INFO STDERR: TypeError: argument of type 'NoneType' is not iterable
```
```


### System Info

idk I can't run it, this is a straightforward fix though

### Who can help?

_No response_

**Comment by oxysoft** [comment]
After investigating

1. It appears that I would have this bug in the regular ControlNet pipeline as well.
2. It appears that even if an empty dict was passed I would still land an exception because it's expecting `text_embeds`.

So I'm not sure exactly what is going on and where this text_embeds is supposed to come from and be used for.

**Comment by asomoza** [comment]
Hi, that model is a SDXL finetune, why are you trying to use it with the SD pipeline? you should use the `pipeline_controlnet_sd_xl_img2img.py` pipeline.
