### ISSUE TITLE
Testing beta sigmas in EulerDiscreteScheduler passes wrong parameters to torch.linspace

### ISSUE THREAD

**Issue by Vargol** [huggingface/diffusers#10054]
### Describe the bug

Creating a EulerDiscreteScheduler using an existing schedulers config seems to pass a `FrozenDict` for `num_train_timesteps` instead of the expected `int`

e.g.
```py
pipe.scheduler = EulerDiscreteScheduler(pipe.scheduler.config, timestep_spacing="linspace", use_beta_sigmas=True)
```
fails with 
```py
TypeError: linspace() received an invalid combination of arguments - got (float, float, FrozenDict, dtype=torch.dtype), but expected one of:
```

### Reproduction

```py
import torch
from diffusers import AutoPipelineForText2Image, EulerDiscreteScheduler
model_path = "stabilityai/stable-diffusion-xl-base-1.0"

pipe = AutoPipelineForText2Image.from_pretrained(
         model_path,
)
pipe.scheduler = EulerDiscreteScheduler(pipe.scheduler.config, timestep_spacing="linspace", use_beta_sigmas=True)
```

### Logs

```shell
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00,  9.92it/s]
Traceback (most recent call last):
  File "/Volumes/SSD2TB/AI/Diffusers/beta.py", line 8, in <module>
    pipe.scheduler = EulerDiscreteScheduler(pipe.scheduler.config, timestep_spacing="linspace", use_beta_sigmas=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/SSD2TB/AI/Diffusers/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 665, in inner_init
    init(self, *args, **init_kwargs)
  File "/Volumes/SSD2TB/AI/Diffusers/lib/python3.11/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 216, in __init__
    self.betas = torch.linspace(beta_start, beta_end, num_train_timesteps, dtype=torch.float32)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: linspace() received an invalid combination of arguments - got (float, float, FrozenDict, dtype=torch.dtype), but expected one of:
 * (Tensor start, Tensor end, int steps, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Tensor end, int steps, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Tensor start, Number end, int steps, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Number end, int steps, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
```

### System Info

- 🤗 Diffusers version: 0.32.0.dev0
- Platform: macOS-15.1.1-arm64-arm-64bit
- Running on Google Colab?: No
- Python version: 3.11.10
- PyTorch version (GPU?): 2.6.0.dev20241114 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.25.0
- Transformers version: 4.44.2
- Accelerate version: 0.34.2
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: Apple M3
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no
- 

### Who can help?

@yiyixuxu

**Comment by Vargol** [comment]
D'oh sorry, I've just seen what I've done, missing the from_config out, so maybe an parameter verification issue if anything
