### ISSUE TITLE
cogvideox-1.5-5b微调报错

### ISSUE THREAD

**Issue by linwenzhao1** [huggingface/diffusers#10209]
### Describe the bug

你好，请问这个是什么问题？
![image](https://github.com/user-attachments/assets/9265a24c-6fcb-4a41-a0aa-fdbd42594be3)

### Reproduction

einops.EinopsError:  Error while processing rearrange-reduction pattern "b (t o h p w q) c -> b (t h w) (c o p q)".
 Input tensor shape: torch.Size([2, 1036800, 49]). Additional info: {'t': 1, 'h': 240, 'w': 360, 'o': 2, 'p': 2, 'q': 2}.
 Shape mismatch, 1036800 != 691200

### System Info

torch:2.5  python:3.11 cuda:12.0

**Comment by hlky** [comment]
Can you share the full traceback and a minimal reproduction?

**Comment by linwenzhao1** [comment]
> Can you share the full traceback and a minimal reproduction?
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/einops/einops.py", line 523, in reduce
    return _apply_recipe(
           ^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/einops/einops.py", line 234, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/einops/einops.py", line 183, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, {length} != {known_product}")
einops.EinopsError: Shape mismatch, 1036800 != 691200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 157, in training_main
    iteration, skipped = train(model, optimizer,
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 359, in train
    lm_loss, skipped_iter, metrics = train_step(train_data_iterator,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/sat/training/deepspeed_training.py", line 443, in train_step
    forward_ret = forward_step(data_iterator, model, args, timers, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/train_video.py", line 195, in forward_step
    loss, loss_dict = model.shared_step(batch)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/diffusion_video.py", line 170, in shared_step
    loss, loss_dict = self(x, batch)
                      ^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/diffusion_video.py", line 130, in forward
    loss = self.loss_fn(self.model, self.denoiser, self.conditioner, x, batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/sgm/modules/diffusionmodules/loss.py", line 106, in __call__
    model_output = denoiser(network, noised_input, alphas_cumprod_sqrt, cond, **additional_model_inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/sgm/modules/diffusionmodules/denoiser.py", line 38, in forward
    return network(input * c_in, c_noise, cond, **additional_model_inputs) * c_out + input * c_skip
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/sgm/modules/diffusionmodules/wrappers.py", line 35, in forward
    return self.diffusion_model(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/dit_video_concat.py", line 853, in forward
    output = super().forward(**kwargs)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/sat/model/base_model.py", line 138, in forward
    return self.transformer(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/sat/model/transformer.py", line 596, in forward
    hidden_states = self.hooks['word_embedding_forward'](input_ids, output_cross_layer=output_cross_layer, **kw_args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lwz/workspace/CogVideo/sat/dit_video_concat.py", line 34, in word_embedding_forward
    emb = rearrange(
          ^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda_env/cogvideo/lib/python3.11/site-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b (t o h p w q) c -> b (t h w) (c o p q)".
 Input tensor shape: torch.Size([2, 1036800, 49]). Additional info: {'t': 1, 'h': 240, 'w': 360, 'o': 2, 'p': 2, 'q': 2}.
 Shape mismatch, 1036800 != 691200
[rank0]:[W1216 10:45:04.442384891 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

Process finished with exit code 1

python参数: --base configs/cogvideox1.5_5b.yaml configs/sft_5b_t2v.yaml --seed 17796
模型是：CogVideoX1.5-5B-SAT/transformer_t2v ， CogVideoX1.5-5B-SAT/t5-v1_1-xxl， CogVideoX1.5-5B-SAT/vae/3d-vae.pt

**Comment by a-r-r-o-w** [comment]
Hi. This is not a diffusers specific issue and you should open one at https://github.com/THUDM/CogVideo if you're looking for help
