### ISSUE TITLE
Dreambooth Flux with Lora: Tensor Size Mismatch

### ISSUE THREAD

**Issue by dyedd** [huggingface/diffusers#10226]
### Describe the bug

I'm fine-tuning a model with Flux using LoRA and mixed precision (fp16). Initially, I ran into an out-of-memory error, which I solved by upgrading to a larger GPU. Now, during the forward pass, I'm encountering a new issue in the apply_rotary_emb function, where two tensors have mismatched sizes.

### Reproduction

https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_flux.py

### Logs

```shell
12/15/2024 22:52:27 - INFO - __main__ - Distributed environment: DistributedType.NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type t5 to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:40<00:00, 20.21s/it]
{'axes_dims_rope'} was not found in config. Values will be initialized to default values.
12/15/2024 22:55:10 - INFO - __main__ - ***** Running training *****
12/15/2024 22:55:10 - INFO - __main__ -   Num examples = 5
12/15/2024 22:55:10 - INFO - __main__ -   Num batches each epoch = 5
12/15/2024 22:55:10 - INFO - __main__ -   Num Epochs = 1
12/15/2024 22:55:10 - INFO - __main__ -   Instantaneous batch size per device = 1
12/15/2024 22:55:10 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
12/15/2024 22:55:10 - INFO - __main__ -   Gradient Accumulation steps = 4
12/15/2024 22:55:10 - INFO - __main__ -   Total optimization steps = 1
Steps:   0%|                                                                                                                                                                         | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/train_dreambooth_lora_flux.py", line 1926, in <module>
    main(args)
  File "/root/train_dreambooth_lora_flux.py", line 1720, in main
    model_pred = transformer(
                 ^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 500, in forward
    encoder_hidden_states, hidden_states = block(
                                           ^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/diffusers/models/transformers/transformer_flux.py", line 175, in forward
    attn_output, context_attn_output = self.attn(
                                       ^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 495, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 1778, in __call__
    query = apply_rotary_emb(query, image_rotary_emb)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/test/lib/python3.11/site-packages/diffusers/models/embeddings.py", line 734, in apply_rotary_emb
    out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
           ~~~~~~~~~~^~~~~
RuntimeError: The size of tensor a (1536) must match the size of tensor b (768) at non-singleton dimension 2

```

### System Info

- Python 3.11.11
- torch 2.5.1
- diffusers  0.31.0
- NVIDIA L20

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Can you install `diffusers` from the source and retry?

```bash
pip install git+https://github.com/huggingface/diffusers
```

**Comment by dyedd** [comment]
> Can you install `diffusers` from the source and retry?
> 
> ```shell
> pip install git+https://github.com/huggingface/diffusers
> ```

thanks，it work！
