### ISSUE TITLE
Using euler scheduler in fluxfill 

### ISSUE THREAD

**Issue by luna313** [huggingface/diffusers#10277]
### Describe the bug

I am using the customfluxfill function and want to use the Euler scheduler (EulerAncestralDiscreteScheduler) in my code. However, I am encountering the following error:

### Reproduction

from diffusers.schedulers import (
DPMSolverMultistepScheduler,
    EulerAncestralDiscreteScheduler,
)

SAMPLER_MAP = {
    "DPM++ SDE Karras": lambda config: DPMSolverMultistepScheduler.from_config(
        config, use_karras_sigmas=True, algorithm_type="sde-dpmsolver++"
    ),
    "DPM++ 2M Karras": lambda config: DPMSolverMultistepScheduler.from_config(
        config, use_karras_sigmas=True
    ),
    "DPM++ 2M SDE": lambda config: DPMSolverMultistepScheduler.from_config(
        config, algorithm_type="sde-dpmsolver++"
    ),
    "DPM++ 2M SDE Karras": lambda config: DPMSolverMultistepScheduler.from_config(
        config, use_karras_sigmas=True, algorithm_type="sde-dpmsolver++"
    ),
    "Euler a": lambda config: EulerAncestralDiscreteScheduler.from_config(
        config,
    ),
}

def model_fn() -> FluxFillPipeline:
    pipe = FluxFillPipeline.from_pretrained("Planningo/flux-inpaint", torch_dtype=torch.bfloat16).to("cuda")
    # Apply the Euler scheduler
    pipe.scheduler = SAMPLER_MAP["Euler a"](pipe.scheduler.config)
    return pipe

### Logs

```shell
ValueError: The current scheduler class <class 'diffusers.schedulers.scheduling_euler_ancestral_discrete.EulerAncestralDiscreteScheduler'>'s `set_timesteps` does not support custom sigmas schedules. Please check whether you are using the correct scheduler.
```

### System Info

latest(github version diffusers), python3.10, ubuntu with nvidia gpu

### Who can help?

@yiyixuxu

**Comment by hlky** [comment]
Hi @luna313! We are working on supporting more schedulers for Flow Match models like Flux, we support `FlowMatchEulerDiscreteScheduler` for now.

**Comment by luna313** [comment]
@hlky Thank you for your response! I hope that the feature will be supported soon.

**Comment by lcax200000** [comment]
May I ask when this function is planned to be supported? I have encountered a similar problem.


`    pipe = xFuserFluxPipeline.from_pretrained(
        pretrained_model_name_or_path=engine_config.model_config.model,
        engine_config=engine_config,
        torch_dtype=torch.bfloat16,
        text_encoder_2=text_encoder_2,
    )
    pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)`
    
    
    
    `[rank2]: Traceback (most recent call last):
[rank2]:   File "/data/test/xDiT/examples/flux_example.py", line 108, in <module>
[rank2]:     main()
[rank2]:   File "/data/test/xDiT/examples/flux_example.py", line 65, in main
[rank2]:     pipe.prepare_run(input_config, steps=1)
[rank2]:   File "/data/test/xDiT/xfuser/model_executor/pipelines/pipeline_flux.py", line 70, in prepare_run
[rank2]:     self.__call__(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank2]:     return func(*args, **kwargs)
[rank2]:   File "/data/test/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 220, in wrapper
[rank2]:     return func(*args, **kwargs)
[rank2]:   File "/data/test/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 168, in data_parallel_fn
[rank2]:     return func(self, *args, **kwargs)
[rank2]:   File "/data/test/xDiT/xfuser/model_executor/pipelines/base_pipeline.py", line 188, in check_naive_forward_fn
[rank2]:     return func(self, *args, **kwargs)
[rank2]:   File "/data/test/xDiT/xfuser/model_executor/pipelines/pipeline_flux.py", line 276, in __call__
[rank2]:     timesteps, num_inference_steps = retrieve_timesteps(
[rank2]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/flux/pipeline_flux.py", line 127, in retrieve_timesteps
[rank2]:     raise ValueError(
[rank2]: ValueError: The current scheduler class <class 'diffusers.schedulers.scheduling_ddim.DDIMScheduler'>'s `set_timesteps` does not support custom sigmas schedules. Please check whether you are using the correct scheduler.
`
