### ISSUE TITLE
IndexError: list index out of range, stable_diffusion_mega

### ISSUE THREAD

**Issue by adhikjoshi** [huggingface/diffusers#1033]
### Describe the bug

I am using custom_pipeline="stable_diffusion_mega" pipeline, and getting "IndexError: list index out of range" error

Here is traceback of error,

> Traceback (most recent call last):
>   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/workspace/server/tasks.py", line 67, in __call__
>     return self.run(*args, **kwargs)
>   File "/workspace/server/tasks.py", line 121, in txt2img
>     result = self.pipe.text2img("a cat sitting on a bench")
>   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_mega.py", line 209, in text2img
>     return StableDiffusionPipeline(**self.components)(
>   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 84, in __init__
>     self.register_modules(
>   File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 125, in register_modules
>     pipeline_dir = module.__module__.split(".")[-2]
> IndexError: list index out of range

**Stable Diffusion Pipeline**

```
pipe = DiffusionPipeline.from_pretrained(model_id, custom_pipeline="stable_diffusion_mega", use_auth_token=hf_token)
pipe.to("cuda")
pipe.safety_checker = dummy_checker
pipe.enable_attention_slicing()
```

I am calling text2img function of "stable_diffusion_mega"  @patrickvonplaten 
`self.pipe.text2img("a cat sitting on a bench")`

### Reproduction

self.pipe.text2img("a cat sitting on a bench")

### System Info

  - python=3.8.5
  - pip=20.3
  - diffusers==0.6.0

**Comment by adhikjoshi** [comment]
Tried on different GPUs, with different settings, without custom_pipeline="stable_diffusion_mega" works well,
but with custom_pipeline="stable_diffusion_mega", throws error

**Comment by adhikjoshi** [comment]
Able to make it work by removing "pipe.safety_checker"
