### ISSUE TITLE
do_bench fails in HunyuanVideoPipeline

### ISSUE THREAD

**Issue by CrackerHax** [huggingface/diffusers#10341]
### Describe the bug

cannot import do_bench

### Reproduction

import torch
from diffusers import HunyuanVideoPipeline, HunyuanVideoTransformer3DModel
from diffusers.utils import export_to_video

### Logs

```shell
RuntimeError: Failed to import diffusers.pipelines.hunyuan_video.pipeline_hunyuan_video because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.lora_pipeline because of the following error (look up to see its traceback):
cannot import name 'do_bench' from 'torch._inductor.runtime.runtime_utils' (.local/lib/python3.10/site-packages/torch/_inductor/runtime/runtime_utils.py)
```
```


### System Info

diffusers current release

### Who can help?

@DN6 @a-r-r-o-w

**Comment by a-r-r-o-w** [comment]
Could you install diffusers from the `main` branch with `pip install git+https://github.com/huggingface/diffusers` and try?

**Comment by CrackerHax** [comment]
> Could you install diffusers from the `main` branch with `pip install git+https://github.com/huggingface/diffusers` and try?

Thats how I installed it to get the error.

**Comment by a-r-r-o-w** [comment]
Well, you mentioned `diffusers current release`, which is 0.31.0 and doesn't contain anything related to HunyuanVideo. Not sure where the `do_bench` things come from, but likely indicates something to do with environment setup.

**Comment by CrackerHax** [comment]
> Well, you mentioned `diffusers current release`, which is 0.31.0 and doesn't contain anything related to HunyuanVideo. Not sure where the `do_bench` things come from, but likely indicates something to do with environment setup.

Yeah after I posted I tried importing StableDiffusionPipeline and got the same error.

**Comment by CrackerHax** [comment]
Python 3.10.14
Torch 2.6.0.dev20241119+cu124

**Comment by CrackerHax** [comment]
This actually happens anytime I try to import diffusers. I guess this newest version is completely unusable and broken.

**Comment by CrackerHax** [comment]
The only way I could get this to work is if I downgraded to 0.31.0, otherwise:
'''
Traceback (most recent call last):
  File "", line 1, in <module>
    from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/.local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File ".local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
cannot import name 'do_bench' from 'torch._inductor.runtime.runtime_utils' 
'''

**Comment by a-r-r-o-w** [comment]
This seems like an issue with the environment as discussed above. We don't see it being reported by multiple others running Hunyuan, so I think it's safe to say it's not a diffusers-related issue, so marking as closed
