### ISSUE TITLE
safety_checker=None returns None is of type: <class 'NoneType'>, but should be <class 'diffusers.onnx_utils.OnnxRuntimeModel'> (OnnxStableDiffusionPipeline) 

### ISSUE THREAD

**Issue by averad** [huggingface/diffusers#1138]
### Describe the bug

safety_checker=None is not accepted by OnnxStableDiffusionPipeline.from_pretrained due to how its passed to pipeline_utils.py

### Reproduction

```
pipe = OnnxStableDiffusionPipeline.from_pretrained(
    model,
    revision="onnx",
    provider="DmlExecutionProvider", 
    safety_checker=None
)
```

### Logs

```shell
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
2022-11-04 09:24:39.2747512 [W:onnxruntime:, inference_session.cc:491 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2022-11-04 09:24:39.4554147 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2022-11-04 09:24:39.4610289 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Traceback (most recent call last):
  File "D:\ai\txt_to_img.py", line 56, in <module>
    pipe = OnnxStableDiffusionPipeline.from_pretrained(
  File "D:\ai\sd_env\lib\site-packages\diffusers\pipeline_utils.py", line 556, in from_pretrained
    raise ValueError(
ValueError: None is of type: <class 'NoneType'>, but should be <class 'diffusers.onnx_utils.OnnxRuntimeModel'>
```

### Workaround

After initializing OnnxStableDiffusionPipeline.from_pretrained call:

`pipe.safety_checker = None`

### System Info

- `diffusers` version: 0.7.1
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: AMD RX580 via DmlExecutionProvider (onnxruntime-directml)

**Comment by averad** [comment]
Tested and confirmed working using the current main repo, thank you
