### ISSUE TITLE
raise the problem No module named 'exceptions' When train the model

### ISSUE THREAD

**Issue by Lyn-Qiu** [huggingface/diffusers#122]
Traceback (most recent call last):
  File "scripts/train.py", line 1, in <module>
    import diffuser.utils as utils
  File "/mnt/d/RL/UCSC/diffuser/diffuser/utils/__init__.py", line 4, in <module>
    from .setup import *
  File "/mnt/d/RL/UCSC/diffuser/diffuser/utils/setup.py", line 6, in <module>
    from tap import Tap
  File "/home/lyn/anaconda3/envs/diffuser/lib/python3.8/site-packages/tap.py", line 6, in <module>
    from mc_bin_client import mc_bin_client, memcacheConstants as Constants
  File "/home/lyn/anaconda3/envs/diffuser/lib/python3.8/site-packages/mc_bin_client/mc_bin_client.py", line 11, in <module>
    import exceptions
ModuleNotFoundError: No module named 'exceptions'

**Comment by Lyn-Qiu** [comment]
can't solve by pip install python-docs

**Comment by patrickvonplaten** [comment]
Hey @Lyn-Qiu,

How exactly did you install `diffusers` and what command did you use exactly to train the model? It would be great if we could somehow reproduce the error. Also cc @anton-l as it seems related to training

**Comment by anton-l** [comment]
Hi @Lyn-Qiu! Judging by the stack trace, you're using something other than [`diffusers`](https://pypi.org/project/diffusers/) to run your training script, could this be a typo during installation? :slightly_smiling_face:

**Comment by patrickvonplaten** [comment]
Hey @Lyn-Qiu,

Sorry we need better error messages here to understand what's going on - is this related to `diffusers`? 
Sorry I'm not really following the problem here

**Comment by patrickvonplaten** [comment]
Closing due to inactivity
