### ISSUE TITLE
K-LMS scheduler in Flax

### ISSUE THREAD

**Issue by mar-muel** [huggingface/diffusers#1231]
### Describe the bug

Hello everyone! So far very happy with the Flax implementation, great work!

However, I've been struggling to get K-LMS working. Here's what I've tried so far:

```python
import jax
import numpy as np
from flax.jax_utils import replicate
from flax.training.common_utils import shard
from timeit import default_timer as timer

from diffusers import FlaxStableDiffusionPipeline
from diffusers import (
    FlaxPNDMScheduler,
    FlaxLMSDiscreteScheduler,
)

scheduler = FlaxLMSDiscreteScheduler()
pipeline, params = FlaxStableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", scheduler=scheduler, dtype=jax.numpy.bfloat16)

# not sure if this is needed?
scheduler.create_state()
params['scheduler'] = scheduler.state

# more fixes in the hopes it would work 😅
scheduler.init_noise_sigma = 1.0
def scale_model_input(sample, *args, **kwargs):
    return sample
scheduler.scale_model_input = scale_model_input

prompt = "a photo of an astronaut riding a horse on mars"

prng_seed = jax.random.PRNGKey(0)
num_inference_steps = 50

num_samples = jax.device_count()
prompt = num_samples * [prompt]
prompt_ids = pipeline.prepare_inputs(prompt)

# shard inputs and rng
print('Replicating model...')
params = replicate(params)
prng_seed = jax.random.split(prng_seed, jax.device_count())
prompt_ids = shard(prompt_ids)

ts = timer()
print('Generating images...')
images = pipeline(prompt_ids, params, prng_seed, num_inference_steps, jit=True).images
images = pipeline.numpy_to_pil(np.asarray(images.reshape((num_samples,) + images.shape[-3:])))
print(f'...generated images in in {timer()-ts:.2f}s')
```

But this is still failing with
```
Traceback (most recent call last):
  File "example.py", line 26, in <module>
    scheduler.init_noise_sigma = 1.0
  File "/home/martin/miniconda/envs/jd/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 278, in __call__
    images = _p_generate(
  File "/home/martin/miniconda/envs/jd/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 316, in _p_generate
    return pipe._generate(
  File "/home/martin/miniconda/envs/jd/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 210, in _generate
    latents, _ = jax.lax.fori_loop(0, num_inference_steps, loop_body, (latents, scheduler_state))
  File "/home/martin/miniconda/envs/jd/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 186, in loop_body
    jnp.array(latents_input),
  File "/home/martin/miniconda/envs/jd/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1910, in array
    raise TypeError(f"Unexpected input type for array: {type(object)}")
TypeError: Unexpected input type for array: <class 'diffusers.schedulers.scheduling_lms_discrete_flax.LMSDiscreteSchedulerState'>
```

### System Info

- `diffusers` version: 0.7.2
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-glibc2.10
- Python version: 3.8.0
- PyTorch version (GPU?): 1.13.0+cu117 (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

**Comment by pcuenca** [comment]
Hi @mar-muel! Thanks a lot for reporting this. I've been trying it out and it looks like the K-LMS scheduler has not been adapted to the new scheduler API yet, so it can't currently be used as an alternative for stable diffusion, sadly.

In any case, the process to replace an scheduler in a Flax pipeline might not be very straightforward. This is the method I use, where I'm using your code as a template on how to incorporate the new `FlaxDPMSolverMultistepScheduler` scheduler:

```Python
import jax
import numpy as np
from flax.jax_utils import replicate
from flax.training.common_utils import shard
from timeit import default_timer as timer

from diffusers import FlaxStableDiffusionPipeline
from diffusers import (
    FlaxPNDMScheduler,
    FlaxDPMSolverMultistepScheduler,
)

scheduler, scheduler_state = FlaxDPMSolverMultistepScheduler.from_config("runwayml/stable-diffusion-v1-5", subfolder="scheduler")
pipeline, params = FlaxStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    scheduler=scheduler,
    revision="bf16",
    dtype=jax.numpy.bfloat16,
)
params["scheduler"] = scheduler_state

prompt = "a photo of an astronaut riding a horse on mars"

prng_seed = jax.random.PRNGKey(0)
num_inference_steps = 50

num_samples = jax.device_count()
prompt = num_samples * [prompt]
prompt_ids = pipeline.prepare_inputs(prompt)

# shard inputs and rng
print('Replicating model...')
params = replicate(params)
prng_seed = jax.random.split(prng_seed, jax.device_count())
prompt_ids = shard(prompt_ids)

ts = timer()
print('Generating images...')
images = pipeline(prompt_ids, params, prng_seed, num_inference_steps, jit=True).images
images = pipeline.numpy_to_pil(np.asarray(images.reshape((num_samples,) + images.shape[-3:])))
print(f'...generated images in in {timer()-ts:.2f}s')

for i, image in enumerate(images):
    image.save(f"flax_{i}.png")
```
