### ISSUE TITLE
Launch training with accelerate launch arg error

### ISSUE THREAD

**Issue by radames** [huggingface/diffusers#125]
Launching training with `accelerate launch` raise argument errors

```
Traceback (most recent call last):
  File "/usr/local/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 690, in main
    launch_command(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 684, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 280, in simple_launcher
    mixed_precision = PrecisionType(args.mixed_precision.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
``` 

However, you can still start the training by calling the script with python

```
python train_unconditional.py ...
```

**Comment by patrickvonplaten** [comment]
@anton-l could you take a look here?

**Comment by anton-l** [comment]
Hi @radames! You need to run `accelerate config` before launching the scripts for the first time, I've added that step to the training README now: https://github.com/huggingface/diffusers/tree/main/examples#installing-the-dependencies
Thanks for reporting!

**Comment by radames** [comment]
Thanks @anton-l
