### ISSUE TITLE
🐛 AttributeError in OnnxStableDiffusionInpaintPipelineLegacy in 🤗 Diffusers 0.9.0

### ISSUE THREAD

**Issue by averad** [huggingface/diffusers#1445]
## ⚠️ Error: 'OnnxRuntimeModel' object has no attribute 'config'

- Diffusers 0.9.0
- OnnxStableDiffusionInpaintPipelineLegacy throws an AttributeError when loading.

### Reproduction

```
import torch
from PIL import Image
from diffusers import OnnxStableDiffusionInpaintPipelineLegacy

pipe = OnnxStableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", revision="onnx", provider="CPUExecutionProvider", safety_checker=None)

init_image = Image.open("test.png")
init_image = init_image.resize((512, 512))
mask_image = Image.open("mask.png")
mask_image = mask_image.resize((512, 512))
prompt = "cartoon, alien shapes, planets, stars"

image = pipe(prompt=prompt, image=init_image, mask_image=mask_image, strength=0.75, guidance_scale=7.5).images[0] 
image.save("test-output.png")
```

###test.png
![test](https://user-images.githubusercontent.com/640619/204210684-0ed32672-6b7c-4d48-ac3e-ad536f6e1c96.png)

###mask.png
![mask](https://user-images.githubusercontent.com/640619/204210736-e5cea949-5863-4a41-b033-65a2b985edfd.png)

### Logs

```shell
Traceback (most recent call last):
  File "inpaint_legacy.py", line 28, in <module>
    pipe = OnnxStableDiffusionInpaintPipelineLegacy.from_pretrained("./model/sd-onnx-v1-5", provider="DmlExecutionProvider", safety_checker=None)
  File "\lib\site-packages\diffusers\pipeline_utils.py", line 679, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion_inpaint_legacy.py", line 137, in __init__
    is_unet_version_less_0_9_0 = hasattr(unet.config, "_diffusers_version") and version.parse(
AttributeError: 'OnnxRuntimeModel' object has no attribute 'config'
```

### System Info

- `diffusers` version: 0.9.0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.11.0
- Transformers version: 4.24.0

**Comment by patrickvonplaten** [comment]
Uff that's a big bug indeed - @anton-l could you have a look here? Any ideas how to best access the model's config? Guess we should do a patch release for this

**Comment by anton-l** [comment]
Thank you @averad! Missed the legacy pipeline when fixing this in other onnx pipelines for 0.9, catching up with this PR: https://github.com/huggingface/diffusers/pull/1448
