### ISSUE TITLE
from datasets import load_dataset ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by krishnaadithya** [huggingface/diffusers#1463]
Traceback (most recent call last):
  File "train_text_to_image.py", line 17, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 1069, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 551, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image.py', '--pretrained_model_name_or_path=', '--dataset_name=', '--use_ema', '--resolution=512', '--center_crop', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--mixed_precision=fp16', '--max_train_steps=15000', '--learning_rate=1e-05', '--max_grad_norm=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--output_dir=sd-pokemon-model']' returned non-zero exit status 1.

**Comment by averad** [comment]
Are you referring to the following code?

https://huggingface.co/docs/diffusers/training/text2image#finetuning-example

**Comment by krishnaadithya** [comment]
Yes, pip install dataset fixed it, but why is it not part of the main instruction?
