### ISSUE TITLE
Dreambooth example is not compatible with Windows or MacOS

### ISSUE THREAD

**Issue by Dragollla** [huggingface/diffusers#1466]
### Describe the bug

Dreambooth example uses multiprocess DataLoader (`num_workers=1`) and it causes error when pickling `collate_fn` because it is not top-level function.

#### Workaround
Training works if I disable multiprocessing by removing `num_workers` from call to `torch.utils.data.DataLoader`

### Reproduction

try Dreambooth example on MacOS

### Logs

```shell
/opt/homebrew/lib/python3.10/site-packages/diffusers/utils/deprecation_utils.py:35: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  warnings.warn(warning + message, FutureWarning)
Steps:   0%|                                            | 0/400 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/dragollla/diffusers/examples/dreambooth/train_dreambooth.py", line 668, in <module>
    main(args)
  File "/Users/dragollla/diffusers/examples/dreambooth/train_dreambooth.py", line 585, in main
    for step, batch in enumerate(train_dataloader):
  File "/opt/homebrew/lib/python3.10/site-packages/accelerate/data_loader.py", line 373, in __iter__
    dataloader_iter = super().__iter__()
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'main.<locals>.collate_fn'
```

### System Info

diffusers version: v0.9.0
platform: MacOS Ventura (13.0.1)
python: 3.10.8

**Comment by patrickvonplaten** [comment]
@patil-suraj could you take a look here?

**Comment by bbrattoli** [comment]
I am experiencing the same issue on my Mac. Any ideas?

**Comment by patil-suraj** [comment]
Looking into it. Think the `collate_fn` can be removed.

**Comment by vmajor** [comment]
I have this error now and this is with the latest git clone.

Windows 10
Single CPU
