### ISSUE TITLE
Dreambooth cannot determine MODEL_TYPE, CKPTs do not load

### ISSUE THREAD

**Issue by dnwalkup** [huggingface/diffusers#1541]
### Describe the bug

Dreambooth cannot determine what MODEL_TYPE Stable Diffusion v1.5 is and, if one manages to producing a training from the script in spit of the issues, the resulting diffusers are unusable due to TYPE being NONE.

### Reproduction

Complete a dreambooth training:
accelerate launch --mixed_precision='fp16' train_dreambooth.py
--train_text_encoder
--save_steps=500
--pretrained_model_name_or_path=YOUR_VAR
--instance_data_dir=YOUR_VAR
--class_data_dir=YOUR_VAR
--output_dir=YOUR_VAR
--instance_prompt=YOUR_VAR
--with_prior_preservation --prior_loss_weight=1.0
--seed=YOUR_VAR
--resolution=YOUR_VAR
--train_batch_size=1
--gradient_accumulation_steps=1
--use_8bit_adam
--learning_rate=YOUR_VAR
--lr_scheduler="polynomial"
--lr_warmup_steps=10
--max_train_steps=YOUR_VAR

Convert the diffusers to CKPT using your script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_diffusers_to_original_stable_diffusion.py

Attempt to load in favorite WebUI.

### Logs

```shell
Dreambooth training log:
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.

Stable Diffusion WebUI log:
TypeError: argument of type 'NoneType' is not iterable
```

### System Info

diffusers version: 0.9.0
Platform: Linux-5.15.65+-x86_64-with-debian-bullseye-sid
Python version: 3.7.12
PyTorch version (GPU?): 1.12.0+cu113 (True)
Huggingface_hub version: 0.11.1
Transformers version: 4.22.1
Using GPU in script?: A5000
Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Seems to be a duplicate of https://github.com/huggingface/diffusers/issues/1540 no?

**Comment by mpatzner** [comment]
I'm also getting this error on a MacBook Pro M1 Max (64 GB RAM, 32 core GPU) macOS 13.0.1 (22A400). This results in the generated model outputting only black images, no matter where I run it. Converting the model to ckpt works but when loading it into automatic1111 it also outputs only black images. The original stable diffusions models work fine though.
```
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
```

Here's how I run the training
```
.env/bin/accelerate launch examples/dreambooth/train_dreambooth.py \
  --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" \
  --train_text_encoder \
  --instance_data_dir="/Users/user/ai/source_images" \
  --output_dir="/Users/user/ai/output" \
  --instance_prompt="a photo of sks person" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=250
```

Here's the log:
```
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
/Users/user/diffusers/.env/lib/python3.10/site-packages/torch/autograd/__init__.py:197: UserWarning: The operator 'aten::native_group_norm_backward' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 2822.67it/s]
Steps: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [03:58<00:00,  4.78s/it, loss=nan, lr=5e-6]
```

The training is actually proceeding and finishes fine. However, running any prompt with the generated model, a black screen is all I get.

Here's how I run the model:
```
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler
import torch

model_id = "/Users/user/ai/output"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    safety_checker=None
)
pipe = pipe.to("mps")
pipe.enable_attention_slicing()

prompt = "a photo of sks person"

# Warumup
_ = pipe(prompt, num_inference_steps=1)

image = pipe(prompt, num_inference_steps=10, guidance_scale=7.5).images[0]
image.save("sks-person.png")
```

And the environment:
```
Python 3.10.6 (main, Oct  7 2022, 15:17:36) [Clang 12.0.0 ]
pip freeze:
absl-py==1.3.0
accelerate==0.15.0
aiohttp==3.8.3
aiosignal==1.3.1
antlr4-python3-runtime==4.9.3
async-timeout==4.0.2
attrs==22.1.0
bitsandbytes==0.35.4
cachetools==5.2.0
certifi==2022.12.7
charset-normalizer==2.1.1
diffusers @ git+https://github.com/huggingface/diffusers@f1b726e46e7a66771e6321d00a28048effce1389
filelock==3.8.2
frozenlist==1.3.3
fsspec==2022.11.0
ftfy==6.1.1
google-auth==2.15.0
google-auth-oauthlib==0.4.6
grpcio==1.51.1
huggingface-hub==0.11.1
idna==3.4
importlib-metadata==5.1.0
Jinja2==3.1.2
lightning-utilities==0.4.2
Markdown==3.4.1
MarkupSafe==2.1.1
modelcards==0.1.6
multidict==6.0.3
numpy==1.23.5
oauthlib==3.2.2
omegaconf==2.3.0
packaging==22.0
Pillow==9.3.0
protobuf==3.20.1
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytorch-lightning==1.8.4
PyYAML==6.0
regex==2022.10.31
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
six==1.16.0
taming-transformers-rom1504==0.0.6
tensorboard==2.11.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5.1
tokenizers==0.13.2
torch==1.13.0
torchmetrics==0.11.0
torchvision==0.14.0
tqdm==4.64.1
transformers==4.25.1
typing_extensions==4.4.0
urllib3==1.26.13
wcwidth==0.2.5
Werkzeug==2.2.2
yarl==1.8.2
zipp==3.11.0
```

Am I doing something wrong?

**Comment by dnwalkup** [comment]
Your torch version may be the problem. I'm only having success with an earlier commit of the dreambooth script AND a specific torch version.

I personally haven't had success using CUDA 11.7. I downgraded to CUDA 11.6.

I installed torch 1.12.1+cu116 and torchvision 0.13.1+cu116. The specific command for this is:
```
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
```

Note that the CUDA version running in my environment and the CUDA version for torch and torchvision are the same.

Note 1: As I don't have time to test on every system/build, this only represents my experience with Auto1111 WebUI and this specific build. It likely works different with other WebUIs, builds, and non-nvidia GPUs.

**Comment by mpatzner** [comment]
Thanks for your reply! For starters, I've created a new environment and switched to Python 3.9.15.

When running `pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116` I keep getting the error:
```
(p39) ➜  diffusers git:(main) ✗ python -m pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu116 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0)
ERROR: No matching distribution found for torch==1.12.1+cu116
```

Here is my `accelerate env` output:
```
- `Accelerate` version: 0.15.0
- Platform: macOS-13.0.1-arm64-arm-64bit
- Python version: 3.9.15
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.13.0 (False)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MPS
	- mixed_precision: no
	- use_cpu: False
	- dynamo_backend: NO
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: None
	- main_process_ip: None
	- main_process_port: None
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- megatron_lm_config: {}
	- downcast_bf16: no
	- tpu_name: None
	- tpu_zone: None
	- command_file: None
	- commands: None
```

What's wrong? Perhaps the Python version is not compatible with torch==1.12.1+cu116 torchvision==0.13.1+cu116?

**Comment by dnwalkup** [comment]
Ah, sorry, didn't catch that you were running on a mac.

Looks like they only build wheels for Windows and Linux, plus, the CUDA builds are for Nvidia cards, so they wouldn't work for your Mac.

You could try installing Torch and Torchvision with versions 1.12.1 and 0.13.1 (pip install torch==1.12.1 torchvision==0.13.1) and see if you can complete a quick 500 step training and if the resulting ckpt works.

A bit out of my depth here though, hopefully someone with a Mac or the HF team can point you in the right direction.

**Comment by mpatzner** [comment]
That solved it, thank you. The converted .ckpt model loads fine in Automatic1111 and produces proper (non blank-black) images as expected. I used the conversion script from Nitrosocke that you recommended.

However, I still getting the following errors when running:
```
accelerate launch examples/dreambooth/train_dreambooth.py \
  --train_text_encoder \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --instance_data_dir="/Users/user/ai/input" \
  --output_dir="/Users/user/ai/output" \
  --instance_prompt="a photo of sks person" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=200
```

Log:
```
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
/Users/maximilian.patzner/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/schedulers/scheduling_ddpm.py:339: UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  sqrt_alpha_prod = self.alphas_cumprod[timesteps] ** 0.5
```

The training doesn't bail though and completes fine.

**Comment by dnwalkup** [comment]
Cheers!

And I'm happy to hear the error the script is throwing isn't fatal to
training.

Enjoy!

**Comment by mpatzner** [comment]
The problem now is using prior preservation. So when I add these parameters:
```
  --class_prompt="a photo of person" \
  --class_data_dir="/Users/user/ai/classification_images" \
  --with_prior_preservation
  --prior_loss_weight=1.0 \
  --num_class_images=1500 \
```

I get the following fatal error:
```
accelerate launch examples/dreambooth/train_dreambooth.py \
  --train_text_encoder \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --instance_data_dir="/Users/user/ai/input" \
  --output_dir="/Users/user/ai/output" \
  --class_prompt="a photo of person" \
  --class_data_dir="/Users/user/ai/classification_images" \
  --instance_prompt="a photo of sks person" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_checkpointing \
  --learning_rate=2e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=10 \
  --num_class_images=1500 \
  --max_train_steps=500
  
/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/configuration_utils.py:195: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)

/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/schedulers/scheduling_ddpm.py:339: UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  sqrt_alpha_prod = self.alphas_cumprod[timesteps] ** 0.5
Traceback (most recent call last):
  File "/Users/user/Sites/diffusers/examples/dreambooth/train_dreambooth.py", line 672, in <module>
    main(args)
  File "/Users/user/Sites/diffusers/examples/dreambooth/train_dreambooth.py", line 610, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 607, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 600, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/diffusers/models/attention.py", line 478, in forward
    self.norm1(hidden_states, timestep) if self.use_ada_layer_norm else self.norm1(hidden_states)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Traceback (most recent call last):
  File "/Users/user/miniconda/envs/p39/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/Users/user/miniconda/envs/p39/lib/python3.9/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/user/miniconda/envs/p39/bin/python', 'examples/dreambooth/train_dreambooth.py', '--train_text_encoder', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=/Users/user/ai/source_images/cropped', '--output_dir=/Users/user/ai/output_images/profile_1012_1400', '--class_prompt=a photo of person', '--class_data_dir=/Users/user/ai/classification_images', '--instance_prompt=a photo of sks person', '--with_prior_preservation', '--prior_loss_weight=1.0', '--resolution=512', '--train_batch_size=1', '--gradient_checkpointing', '--learning_rate=2e-6', '--lr_scheduler=constant', '--lr_warmup_steps=10', '--num_class_images=1500', '--max_train_steps=25']' returned non-zero exit status 1.
```

This my `accelerate env`:
```
- `Accelerate` version: 0.15.0
- Platform: macOS-13.0.1-arm64-arm-64bit
- Python version: 3.9.15
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.12.1 (False)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MPS
	- mixed_precision: no
	- use_cpu: False
	- dynamo_backend: NO
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: None
	- main_process_ip: None
	- main_process_port: None
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- megatron_lm_config: {}
	- downcast_bf16: no
	- tpu_name: None
	- tpu_zone: None
	- command_file: None
	- commands: None
```

**Comment by dnwalkup** [comment]
I would start with the class images -- did you generate them yourself? are
you using a database? are they all the same size? These questions assume
you have your class images first and that you're not asking Dreambooth to
generate them.

I wouldn't rule out a memory issue either, but would look into those other
questions first.

**Comment by mpatzner** [comment]
I'm using 1500 "person" class images that I downloaded from one of the Colab notebooks. They're all 512x512px.
My source images are 4 PNG images of myself also in 512x512px.

I've just run a quick test with only 200 person classification images and ` --num_class_images=200 \` and I'm getting the same error. If I'm asking dreambooth to genereate the classification images I'm getting the same error.

I'm thinking it has something to do with the version of Torch. I doubt it's a memory issue; my MacBook Pro has 64 GB.

**Comment by dnwalkup** [comment]
It’s more about vram than memory, but again, out of my depth with macs —
would be great if they could use their normal ram as vram!

Honestly, if you’re working with that small a sample size, your results
should be OK without prior preservation loss / regularization images.

We’re you unhappy with your results when you did a full test?

FYI, minimum I’d use to train a subject would be 10 images, 1k steps. For
that I’d probably wouldn’t use prior preservation loss.
