### ISSUE TITLE
Training stops when reaching 500 steps on T4

### ISSUE THREAD

**Issue by ariandemnika** [huggingface/diffusers#1608]
Im using `AWS T4 GPU`, and training always stops when reaching steps `500`

Error im getting:

```
Traceback (most recent call last):
  File "diffusers/examples/dreambooth/train_dreambooth.py", line 719, in <module>
    main(args)
  File "diffusers/examples/dreambooth/train_dreambooth.py", line 638, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/sd/diffusers/src/diffusers/models/unet_2d_condition.py", line 375, in forward
    sample = self.conv_in(sample)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 460, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
Steps:  62%|██████████████████▊           | 500/800 [19:51<11:55,  2.38s/it, loss=0.598, lr=8.15e-7]
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2', '--instance_data_dir=sona', '--class_data_dir=class/Women', '--output_dir=sona_output', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=sona', '--class_prompt=a photo of person', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800']' returned non-zero exit status 1.
```

Train code im using:

```
python3 diffusers/examples/dreambooth/train_dreambooth.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2"  \
  --instance_data_dir="sona" \
  --class_data_dir="class/Women" \
  --output_dir="sona_output" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="sona" \
  --class_prompt="a photo of person" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=2e-6 \
  --lr_scheduler="polynomial" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800
```

I have `15360MiB` of GPU vRAM

**Comment by Turacbey** [comment]
Same for A100. did you find a solution?

**Comment by patrickvonplaten** [comment]
Interesting @williamberman @patil-suraj could you take a look? Its probably because we're evaluating after 500 steps and then there is a style mismatch.

@williamberman could you maybe try to check if it's just a casting error?

**Comment by patrickvonplaten** [comment]
I think the problem here is that the timesteps are not casted to `torch.float16`

**Comment by ariandemnika** [comment]
@patrickvonplaten it is creating checkpoints on every `500 steps`, on `SD 1.5` now it goes further, but when i check the trained folder there are separated in `checkpoint-500`, `checkpoint-1000`, `checkpoint 1500` etc.

**Comment by gordinmitya** [comment]
adding `--save_steps 100000` "fixes" problem, so must be this is an issue with checkpoint saving

**Comment by Turacbey** [comment]
> adding `--save_steps 100000` "fixes" problem, so must be this is an issue with checkpoint saving

It doesn't work.

**Comment by ariandemnika** [comment]
> adding `--save_steps 100000` "fixes" problem, so must be this is an issue with checkpoint saving particularly about resuming training - because checkpoint gets saved

I've fixed the problem, but this one is not splitting the checkpoints in trained folder, can i use this to resume training ?

thank you.

**Comment by kowalgregy** [comment]
Hi, also have this problem on A100 GPU, was also able to solve it by creating a new environment earlier, but the issue reoccurred. Not sure what package install/update/change caused it to resurface. A temporary fix of not using save_steps also works here.
