### ISSUE TITLE
StableDiffusionMegaPipeline in v0.6.0 stopped working with runwayml/stable-diffusion-v1-5

### ISSUE THREAD

**Issue by NiMaZi** [huggingface/diffusers#1611]
### Describe the bug

There following code stopped working since ~3 days ago:
```
DiffusionPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            custom_pipeline="stable_diffusion_mega",
            torch_dtype=torch.float16,
            revision="fp16",
            scheduler=StableDiffusionScheduler[scheduler].value,
            use_auth_token=hf_token,
        )
```
I got the following error message:
```
Traceback (most recent call last):
  /******MY CODE THAT CALLS IT******/
  File "/opt/conda/lib/python3.7/site-packages/diffusers/pipeline_utils.py", line 557, in from_pretrained
    f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
ValueError: Pipeline <class 'diffusers_modules.git.stable_diffusion_mega.StableDiffusionMegaPipeline'> expected {'scheduler', 'vae', 'feature_extractor', 'requires_safety_checker', 'unet', 'safety_checker', 'tokenizer', 'text_encoder'}, but only {'scheduler', 'text_encoder', 'vae', 'feature_extractor', 'unet', 'safety_checker', 'tokenizer'} were passed.
```

### Reproduction

Same code as above? I guess.

### Logs

```shell
Traceback (most recent call last):
  /******MY CODE THAT CALLS IT******/
  File "/opt/conda/lib/python3.7/site-packages/diffusers/pipeline_utils.py", line 557, in from_pretrained
    f"Pipeline {pipeline_class} expected {expected_modules}, but only {passed_modules} were passed."
ValueError: Pipeline <class 'diffusers_modules.git.stable_diffusion_mega.StableDiffusionMegaPipeline'> expected {'scheduler', 'vae', 'feature_extractor', 'requires_safety_checker', 'unet', 'safety_checker', 'tokenizer', 'text_encoder'}, but only {'scheduler', 'text_encoder', 'vae', 'feature_extractor', 'unet', 'safety_checker', 'tokenizer'} were passed.
```

### System Info

Base Image: pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime
Diffusers Version: 0.9.0
Other Relevant Packages:
torch==1.12.1
torchvision==0.13.1

**Comment by patrickvonplaten** [comment]
Hey @NiMaZi,

Could you try again? I think it works now as https://github.com/huggingface/diffusers/blob/c3b2f97534d2f2cd019a3fd2e7b70bcd21958963/examples/community/stable_diffusion_mega.py#L64 has been added.
