### ISSUE TITLE
Error When Training Dreambooth after Saving Weights: RuntimeError: Inference tensors cannot be saved for backward.

### ISSUE THREAD

**Issue by d8ahazard** [huggingface/diffusers#1658]
### Describe the bug

Using my custom version of dreambooth for Auto1111, I've started encountering a new issue after saving a checkpoint that I'm like 95% sure I didn't cause...

https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py

I have a feeling this is similar to or related to #1566 

I tried implementing the fix from 80486c1, but the error persists.

### Reproduction

Install the extension on Auto1111.

Create a new model (v2.1 base, 768-non-ema).

Set max train steps to 50, epochs to 1. Save checkpoint preview after 25 steps.

Train without prior preservation (no class images).

After saving a checkpoint (accelerator.unwrap(unet)), the next time it tries to call "noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample", the following error will occur:

### Logs

```shell
Exception while training: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
 Allocated: 9.2GB
 Reserved: 14.5GB

Traceback (most recent call last):
  File "E:\dev\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1003, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 618, in forward
    hidden_states = downsampler(hidden_states)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 188, in forward
    hidden_states = self.conv(hidden_states)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\dev\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    9383 MB |   13237 MB |    5006 GB |    4996 GB |
|       from large pool |    8993 MB |   12852 MB |    4919 GB |    4910 GB |
|       from small pool |     390 MB |     392 MB |      86 GB |      85 GB |
|---------------------------------------------------------------------------|
| Active memory         |    9383 MB |   13237 MB |    5006 GB |    4996 GB |
|       from large pool |    8993 MB |   12852 MB |    4919 GB |    4910 GB |
|       from small pool |     390 MB |     392 MB |      86 GB |      85 GB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |   14876 MB |   14876 MB |   20502 MB |    5626 MB |
|       from large pool |   14472 MB |   14472 MB |   19960 MB |    5488 MB |
|       from small pool |     404 MB |     404 MB |     542 MB |     138 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |  209023 KB |    2780 MB |    4361 GB |    4361 GB |
|       from large pool |  201712 KB |    2771 MB |    4271 GB |    4271 GB |
|       from small pool |    7311 KB |      22 MB |      90 GB |      90 GB |
|---------------------------------------------------------------------------|
| Allocations           |    5133    |    5140    |    1057 K  |    1052 K  |
|       from large pool |    1119    |    1132    |     426 K  |     425 K  |
|       from small pool |    4014    |    4019    |     631 K  |     627 K  |
|---------------------------------------------------------------------------|
| Active allocs         |    5133    |    5140    |    1057 K  |    1052 K  |
|       from large pool |    1119    |    1132    |     426 K  |     425 K  |
|       from small pool |    4014    |    4019    |     631 K  |     627 K  |
|---------------------------------------------------------------------------|
| GPU reserved segments |     509    |     509    |     737    |     228    |
|       from large pool |     307    |     307    |     466    |     159    |
|       from small pool |     202    |     202    |     271    |      69    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |     153    |     168    |  619209    |  619056    |
|       from large pool |      77    |      90    |  282722    |  282645    |
|       from small pool |      76    |      82    |  336487    |  336411    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
```

### System Info

Windows 11, diffusers 0.10.2, latest transformers, RTX 3080.

**Comment by patrickvonplaten** [comment]
Hey @d8ahazard,

A couple of things here:
- 1. Please add a reproducible code snippet, we don't have time to try to guess what the reproducible was
- 2. Diffusers is not related to AUTO1111 . Please make sure you can single out the error to be related just to `diffusers` and not AUTO1111

**Comment by dennisvos1983** [comment]
if you set 
Save Model Frequency (Epochs)
0
Save Preview(s) Frequency (Epochs)
0
it keep working

**Comment by mrgjbd** [comment]
torch.inference_mode -> torch.no_grad
