### ISSUE TITLE
dreambooth (minor): command line handling: accelerate logger used before being initialized

### ISSUE THREAD

**Issue by timh** [huggingface/diffusers#1673]
### Describe the bug

As I was working on another feature, I realized that parse_args uses `logger`. But `logger` isn't ready until after parse_args returns, as it depends on a configured `Accelerator`.

### Reproduction

Passing `--class_data_dir` but not `--with_prior_preservation` tries to write a warning, but the logger isn't ready yet:

```
$ python train_dreambooth.py --pretrained_model_name_or_path repro \
  --instance_data_dir repro --instance_prompt repro --class_data_dir repro
Traceback (most recent call last):
  File ".../diffusers/examples/dreambooth/train_dreambooth.py", line 748, in <module>
    args = parse_args()
  File ".../diffusers/examples/dreambooth/train_dreambooth.py", line 244, in parse_args
    logger.warning("You need not use --class_data_dir without --with_prior_preservation.")
  File ".../diffusers/lib/python3.10/logging/__init__.py", line 1847, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File ".../diffusers/lib/python3.10/site-packages/accelerate/logging.py", line 48, in log
    if self.isEnabledFor(level) and self._should_log(main_process_only):
  File ".../diffusers/lib/python3.10/site-packages/accelerate/logging.py", line 33, in _should_log
    state = AcceleratorState()
  File ".../diffusers/lib/python3.10/site-packages/accelerate/state.py", line 86, in __init__
    raise ValueError(
ValueError: Please make sure to properly initialize your accelerator via `accelerator = Accelerator()` before using any functionality from the `accelerate` library.
```

### System Info

```
$ git log --format=oneline|head -1
69de9b2eaa3a9047e0074b49753eb7a71aec4a5d [Textual Inversion] Do not update other embeddings (#1665)
```

**Comment by pcuenca** [comment]
Thanks @timh!
