### ISSUE TITLE
train_unconditional.py fails on writing image

### ISSUE THREAD

**Issue by sam598** [huggingface/diffusers#181]
### Describe the bug

After the first epoch `train_unconditional.py` attempts to write an image and fails.
```
Epoch 0: 100%|███████████████████████████████████████████████████████| 5000/5000 [21:13<00:00,  3.93it/s, ema_decay=0.998, loss=0.027, lr=0.0001, step=4999]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:37<00:00,  3.61it/s]
Traceback (most recent call last):
  File "/home/username/Desktop/Diffusion/./diffusers/examples/train_unconditional.py", line 242, in <module>
    main(args)
  File "/home/username/Desktop/Diffusion/./diffusers/examples/train_unconditional.py", line 174, in main
    accelerator.trackers[0].writer.add_images(
IndexError: list index out of range
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2879) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/username/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/username/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/username/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/username/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

Here is an example of the command used:
`accelerate launch ./diffusers/examples/train_unconditional.py --train_data_dir="./CustomImages" --resolution=128 --output_dir="CustomDiffusion" --train_batch_size=4 --num_epochs=120 --gradient_accumulation_steps=1 --learning_rate=1e-4 --lr_warmup_steps=500 --save_model_epochs=10 --mixed_precision="fp16"`

### System Info

```shell
Ubuntu 22.04 Python 3.10.4
```

**Comment by anton-l** [comment]
Hi @sam598! Do you have `tensorboard` installed? Check with `python -c 'import tensorboard as tb; print(tb.__version__)'`
If not, running `pip install diffusers[training]` should install the necessary dependencies and hopefully resolve your issue :slightly_smiling_face:

**Comment by patrickvonplaten** [comment]
@sam598 does this solve your questions here?
