### ISSUE TITLE
Numpy Deprecated types

### ISSUE THREAD

**Issue by Danucas** [huggingface/diffusers#1810]
### Describe the bug

diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py

Numpy latest has been deprecated float for cfloat I think?

### Reproduction

# OnnxStableDiffusionPipeline on CPU

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/bin/docker-entrypoint.py", line 252, in <module>
    main()
  File "/usr/local/bin/docker-entrypoint.py", line 248, in main
    stable_diffusion_inference(pipeline)
  File "/usr/local/bin/docker-entrypoint.py", line 113, in stable_diffusion_inference
    result = p.pipeline(**remove_unused_args(p))
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 250, in __call__
    latents = latents * np.float(self.scheduler.init_noise_sigma)
  File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

### System Info

docker python:3.10-slim-bullseye

**Comment by averad** [comment]
Related PR #1789 - Update ONNX Pipelines to use np.float64 instead of np.float

**Comment by anton-l** [comment]
Thanks for raising the issue! This should be fixed on `main` now: https://github.com/huggingface/diffusers/pull/1789
