### ISSUE TITLE
--train-text-encoder not working with Deepspeed

### ISSUE THREAD

**Issue by OleksandrKorovii** [huggingface/diffusers#1815]
### Describe the bug

Hi, I try to implement the DreamBooth [tutorial](https://huggingface.co/docs/diffusers/v0.11.0/en/training/dreambooth#inference) and when I am adding  parameter --train-text-encoder, pipeline run with error. 

### Reproduction

accelerate launch diffusers/examples/dreambooth/train_dreambooth.py   
--pretrained_model_name_or_path=$MODEL_NAME   
--instance_data_dir=$INSTANCE_DIR   
--output_dir=$OUTPUT_DIR   
--instance_prompt="a photo of stx person"   
--resolution=512   
--train_batch_size=2   
--gradient_accumulation_steps=1   
--learning_rate=5e-6   
--lr_scheduler="constant"   
--lr_warmup_steps=0   
--max_train_steps=800  
--with_prior_preservation 
--prior_loss_weight=1.0 
--class_prompt="a photo of male person"   
--class_data_dir=$CLASS_DIR  
--checkpointing_steps=400

### Logs

```shell
Traceback (most recent call last):
  File "/home/okorovii/image-generation/diffusers/examples/dreambooth/train_dreambooth.py", line 779, in <module>
    main(args)
  File "/home/okorovii/image-generation/diffusers/examples/dreambooth/train_dreambooth.py", line 603, in main
    unet, text_encoder, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 872, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1093, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 330, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1210, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1455, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 532, in __init__
    self._param_slice_mappings = self._create_param_mapping()
  File "/home/okorovii/image-generation/image-venv/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 544, in _create_param_mapping
    lp_name = self.param_names[lp]
KeyError: Parameter containing:
tensor([[[[-0.0277,  0.0744,  0.0869],
          [-0.0260, -0.1979,  0.1300],
          [-0.0211, -0.0179,  0.0277]],

         [[ 0.0527, -0.0802, -0.0054],
          [ 0.1815, -0.1250, -0.0129],
          [ 0.0111, -0.0022, -0.0056]],

         [[ 0.0293, -0.0137,  0.0393],
          [-0.0227,  0.0670,  0.0720],
          [ 0.0018, -0.0084, -0.0357]],

         [[ 0.0177, -0.0427,  0.0400],
          [ 0.0539, -0.1327,  0.0841],
          [ 0.0113, -0.0158,  0.0398]]],


        [[[ 0.0068, -0.0242, -0.0415],
          [ 0.0009,  0.0359,  0.0960],
          [-0.0067,  0.0130,  0.0178]],

         [[ 0.0033,  0.0097, -0.0096],
          [-0.0003,  0.0779,  0.0078],
          [-0.0002,  0.0402,  0.0294]],

         [[ 0.0040,  0.0555,  0.0145],
          [ 0.0290, -0.2053,  0.0252],
          [ 0.0178, -0.0556,  0.0139]],

         [[-0.0215, -0.0398,  0.0134],
          [-0.0195,  0.0733,  0.0031],
          [-0.0216,  0.0121, -0.0248]]],


        [[[-0.0575, -0.0882, -0.0252],
          [ 0.0351,  0.0478, -0.0005],
          [ 0.0336,  0.0589,  0.0355]],

         [[-0.0174,  0.0733,  0.0362],
          [ 0.0231, -0.0811, -0.0469],
          [-0.0097,  0.0183, -0.0050]],

         [[-0.0088,  0.0701, -0.0149],
          [-0.0662,  0.1957, -0.0243],
          [-0.0040, -0.0781, -0.0062]],

         [[-0.0085, -0.0071, -0.0057],
          [-0.0124,  0.0617,  0.0589],
          [-0.0389,  0.0230, -0.0192]]],


        ...,


        [[[-0.0246,  0.0540, -0.0010],
          [ 0.0029,  0.0789, -0.0111],
          [ 0.0051, -0.0343,  0.0104]],

         [[ 0.0196,  0.0138,  0.0347],
          [ 0.0481,  0.0743, -0.0214],
          [-0.0099,  0.0361, -0.0042]],

         [[ 0.0260,  0.0057,  0.0068],
          [ 0.0565,  0.0179,  0.0941],
          [ 0.0259, -0.0188,  0.0770]],

         [[ 0.0624,  0.0430,  0.0416],
          [ 0.0500, -0.0971,  0.0154],
          [ 0.0142, -0.0010,  0.0361]]],


        [[[-0.0080,  0.0128,  0.0240],
          [ 0.0523, -0.0236,  0.0471],
          [ 0.0051,  0.0701, -0.0412]],

         [[-0.0341, -0.0099,  0.0170],
          [ 0.0423,  0.0528,  0.0423],
          [ 0.0280,  0.0321, -0.0062]],

         [[ 0.0724, -0.0127,  0.0501],
          [-0.0168,  0.0410, -0.0084],
          [-0.0517, -0.1157, -0.0875]],

         [[-0.0047,  0.0076, -0.0166],
          [ 0.0224, -0.0092,  0.0033],
          [ 0.0440,  0.0742,  0.0037]]],


        [[[-0.1189, -0.0777,  0.0020],
          [ 0.0878, -0.0176,  0.0412],
          [ 0.0530,  0.0336,  0.0539]],

         [[ 0.1082,  0.0403,  0.0084],
          [ 0.0436, -0.0081, -0.0076],
          [-0.0882,  0.0224, -0.0451]],

         [[-0.0520, -0.0442, -0.0200],
          [-0.0201,  0.0561, -0.0250],
          [ 0.0207,  0.0166, -0.0081]],

         [[-0.0401, -0.0420, -0.0073],
          [ 0.0336,  0.0244,  0.0278],
          [ 0.0489, -0.0019,  0.0122]]]], device='cuda:0', requires_grad=True)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 13551) of binary: /home/okorovii/image-generation/image-venv/bin/python3
```

### System Info

- `diffusers` version: 0.12.0.dev0
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: 2xRTX3090Ti
- Using distributed or parallel set-up in script?: no
- RAM: 64GB

Accelerate config:

command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

**Comment by patrickvonplaten** [comment]
cc @patil-suraj @pcuenca

**Comment by pcuenca** [comment]
Pinging @williamberman too, as I believe he's worked with Deepspeed recently.

**Comment by patil-suraj** [comment]
Yes, `deepspeed` doens't work if we are training `text_encoder`. I think, this is because the `deepspeed` accelerate plugin doesn't play well when training multiple models. I would recommend using `xformers` for memory efficient training.

**Comment by OleksandrKorovii** [comment]
@patil-suraj can you provide the example training dream booth `text_encoder` based on `xformers`?

**Comment by patil-suraj** [comment]
Sure, 

- first install xformers either using these instruction https://huggingface.co/docs/diffusers/optimization/xformers or from source https://github.com/facebookresearch/xformers#installing-xformers
- Then to enable it during training, pass the `--enable_xformers_memory_efficient_attention` arg to the script.

**Comment by liuyugeng** [comment]
Yes, Deepspeed doesn't support two models. I go deep into the code of Deepspeed ```python3.8/site-packages/accelerate/accelerator.py``` and find
```
for obj in result:
            if isinstance(obj, torch.nn.Module):
                model = obj
            elif isinstance(obj, (torch.optim.Optimizer, DummyOptim)):
                optimizer = obj
            elif (isinstance(obj, (LRScheduler, DummyScheduler))) or (
                type(obj).__name__ in deepspeed.runtime.lr_schedules.VALID_LR_SCHEDULES
            ):
                scheduler = obj
```
It will ignore the first model. The ```result``` is the input of ```accelerate.prepare```
