### ISSUE TITLE
dreambooth example missing datasets from requirements.txt

### ISSUE THREAD

**Issue by murphyk** [huggingface/diffusers#1919]
### Describe the bug

In the example https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#dog-toy-example,
the script  fails since `datasets` is missing from requirements.txt

### Reproduction

```
git clone https://github.com/huggingface/diffusers
cd diffusers
pip install -e .
cd examples/dreambooth
pip install -r requirements.txt
accelerate config default

export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="path-to-instance-images"
export OUTPUT_DIR="path-to-save-model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400
```

### Logs

```shell
dreambooth) root@nyky0wbkef:/notebooks/diffusers/examples/dreambooth# accelerate launch train_dreambooth.py \
>   --pretrained_model_name_or_path=$MODEL_NAME  \
>   --instance_data_dir=$INSTANCE_DIR \
>   --output_dir=$OUTPUT_DIR \
>   --instance_prompt="a photo of my cute dog" \
>   --resolution=512 \
>   --train_batch_size=1 \
>   --gradient_accumulation_steps=1 \
>   --learning_rate=5e-6 \
>   --lr_scheduler="constant" \
>   --lr_warmup_steps=0 \
>   --max_train_steps=400
Traceback (most recent call last):
  File "/notebooks/diffusers/examples/dreambooth/train_dreambooth.py", line 16, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'
Traceback (most recent call last):
  File "/dreambooth/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/dreambooth/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/dreambooth/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/dreambooth/lib/python3.9/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/dreambooth/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=dog', '--output_dir=dog-model', '--instance_prompt=a photo of my cute dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.
```
```


### System Info


- `diffusers` version: 0.10.2
- Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.0+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.20.1
- Using GPU in script?: P6000
- Using distributed or parallel set-up in script?:  no

**Comment by murphyk** [comment]
After installing datasets, I can fine tune the model on the dog images, but I cannot use them for inference - I get the error `module transformers has no attribute CLIPImageProcessor`. 

Input code:
```
from diffusers import StableDiffusionPipeline
import torch

model_id = "/notebooks/diffusers/examples/dreambooth/dog-model"
pipe = StableDiffusionPipeline.from_pretrained(model_id).to("cuda")
#pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

prompt = "A photo of my cute dog in a bucket"
image = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]
```
Error log
```
--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 5>()
      2 import torch
      4 model_id = "/notebooks/diffusers/examples/dreambooth/dog-model"
----> 5 pipe = StableDiffusionPipeline.from_pretrained(model_id).to("cuda")
      6 #pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
      8 prompt = "A photo of my cute dog in a bucket"

File /usr/local/lib/python3.9/dist-packages/diffusers/pipeline_utils.py:660, in DiffusionPipeline.from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    656 else:
    657     # else we just import it from the library.
    658     library = importlib.import_module(library_name)
--> 660     class_obj = getattr(library, class_name)
    661     importable_classes = LOADABLE_CLASSES[library_name]
    662     class_candidates = {c: getattr(library, c, None) for c in importable_classes.keys()}

File /usr/local/lib/python3.9/dist-packages/transformers/utils/import_utils.py:898, in _LazyModule.__getattr__(self, name)
    896     value = getattr(module, name)
    897 else:
--> 898     raise AttributeError(f"module {self.__name__} has no attribute {name}")
    900 setattr(self, name, value)
    901 return value

AttributeError: module transformers has no attribute CLIPImageProcessor
```

**Comment by camenduru** [comment]
Hi @murphyk 👋 maybe because you trained with 0.10.2 but some how saved with 0.12.0.dev0 and maybe the transformers library was not updated when you installed  0.12.0.dev0

>### System Info
>diffusers version: 0.10.2

>model_index.json 
>_diffusers_version": "0.12.0.dev0",

**Comment by pcuenca** [comment]
Hi @murphyk! There are two sets of requirements: training requirements, and dreambooth-specific requirements. Training requirements can be installed if you clone the repo and then `pip install -e ".[training]"`, or from the git url like so: `pip install git+https://github.com/huggingface/diffusers#egg=diffusers\[training\`. I think we should improve those details in our documentation and will open a PR for that.

If you install the training dependencies, I believe transformers should have been upgraded. Can you please try to upgrade it manually and see if the problem is resolved?

**Comment by murphyk** [comment]
I did a fresh install on  a new VM, but seem to be hitting some problem with the github installation.

I get the error `ModuleNotFoundError: No module named 'diffusers'`
This is what I did (Starting in /notebooks directory)
```
    git clone https://github.com/huggingface/diffusers
    cd diffusers
    pip install -e ".[training]"
    cd diffusers/examples/dreambooth/
    pip install -r requirements.txt
    cd /notebooks
 export MODEL_NAME="CompVis/stable-diffusion-v1-4"
  export OUTPUT_DIR="/notebooks/model-dog"
  export INSTANCE_DIR="/notebooks/dog"
accelerate config default
    accelerate launch /notebooks/diffusers/examples/dreambooth/train_dreambooth.py   --pretrained_model_name_or_path=$MODEL_NAME    --instance_data_dir=$INSTANCE_DIR   --output_dir=$OUTPUT_DIR   --instance_prompt="a photo of sks dog"   --resolution=512   --train_batch_size=1   --gradient_accumulation_steps=1   --learning_rate=5e-6   --lr_scheduler="constant"   --lr_warmup_steps=0   --max_train_steps=400
```
Error log:
```
File "/notebooks/diffusers/examples/dreambooth/train_dreambooth.py", line 17, in <module>
    import diffusers
ModuleNotFoundError: No module named 'diffusers'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '/notebooks/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/notebooks/dog', '--output_dir=/notebooks/model-dog', '--instance_prompt=a photo of sks dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.
```
When I open python and type `import diffusers`, it does find the library.
But `pip -list` does not show it since it's not in `/usr/local/lib/python3.9/dist-packages/`.

I'm not sure what I am doing wrong. After I run `pip install -e ".[training]"` I see
```
Obtaining file:///notebooks/diffusers
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting huggingface-hub>=0.10.0
...
nstalling collected packages: huggingface-hub, accelerate, modelcards, diffusers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.8.1
    Uninstalling huggingface-hub-0.8.1:
      Successfully uninstalled huggingface-hub-0.8.1
  Running setup.py develop for diffusers
Successfully installed accelerate-0.15.0 diffusers huggingface-hub-0.11.1 modelcards-0.1.6
```
(I'm not using a venv since the VM already has pytorch 1.12 and cuda installed and I don't want to reinstall that....)

**Comment by murphyk** [comment]
I did a fresh install in a venv and now it seems to work :)
(It seems to ignore the prompt, except for the special token, but that is a different matter - at least it runs :)
