### ISSUE TITLE
stable-diffusion-2-inpainting half precision not working

### ISSUE THREAD

**Issue by Actis92** [huggingface/diffusers#1925]
### Describe the bug

I'm trying to use stabilityai/stable-diffusion-2-inpainting but it gives an error due to half precision `RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`

### Reproduction

I'm using the example described in the [guide](https://huggingface.co/stabilityai/stable-diffusion-2-inpainting )

`from diffusers import StableDiffusionInpaintPipeline
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
)
prompt = "Face of a yellow cat, high resolution, sitting on a park bench"
#image and mask_image should be PIL images.
#The mask structure is white for inpainting and black for keeping as is
image = pipe(prompt=prompt, image=image, mask_image=mask_image).images[0]
image.save("./yellow_cat_on_park_bench.png")
`

### Logs
```
Traceback (most recent call last):
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-8f9f47519381>", line 1, in <module>
    image = inpaint(prompt=prompt, image=image, mask_image=mask_image).images[0]
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 642, in __call__
    text_embeddings = self._encode_prompt(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 345, in _encode_prompt
    text_embeddings = self.text_encoder(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 811, in forward
    return self.text_model(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 721, in forward
    encoder_outputs = self.encoder(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 650, in forward
    layer_outputs = encoder_layer(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 378, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/wizard/mambaforge/envs/dawnainew/lib/python3.9/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```
_No response_

### System Info

- `diffusers` version: 0.11.1
- Platform: Linux-5.10.107+-x86_64-with-glibc2.31
- Python version: 3.9.15
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?:yes (Nvidia A100)
- Using distributed or parallel set-up in script?: No

**Comment by anton-l** [comment]
Hi @Actis92! The example snippet was missing `pipe.to("cuda")` after loading the pipeline, so the model was running on CPU (where float16 isn't supported). Thanks for reporting! 
Opened a PR on the model card: https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/discussions/18/files

**Comment by rupertmenneer** [comment]
Hi @anton-l seems that although your PR from 4 months ago is ready to merge it has never actually been merged.. so this issue still exists for new users looking at the stable diffusion in-painting model card.

your PR can be found here:
https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/discussions/18

is there a way to merge that PR?

**Comment by patrickvonplaten** [comment]
Merged!
