### ISSUE TITLE
Generating images in text to image trainer example w/ fp16/bf16: RuntimeError Input type and bias type should be the same

### ISSUE THREAD

**Issue by Cyberes** [huggingface/diffusers#1988]
### Describe the bug

I added a simple function train_text_to_image.py to generate a sample at a checkpointing step:

```python3
def save_in_progress():
    nonlocal unet
    if accelerator.is_main_process:
        unet = accelerator.unwrap_model(unet)
        if args.use_ema:
            ema_unet.copy_to(unet.parameters())
        pipeline = StableDiffusionPipeline.from_pretrained(
            args.pretrained_model_name_or_path,
            text_encoder=text_encoder.cuda(),
            vae=vae.cuda(),
            unet=unet.cuda(),
            revision=args.revision,
        )
        pipeline.to(accelerator.device)
        pipeline.enable_xformers_memory_efficient_attention()
        pipeline.enable_attention_slicing()
        # pipeline.enable_sequential_cpu_offload()
        image = pipeline('testing1234').images[0]
        image.save('/home/whatever/test.png')
```

But when I generate an image I receive this error.

```
Traceback (most recent call last):                                                                                                                                                          | 0/50 [00:00<?, ?it/s]
  File "/home/paperspace/infra/test.py", line 820, in <module>
    main()
  File "/home/paperspace/infra/test.py", line 788, in main
    save_in_progress()
  File "/home/paperspace/infra/test.py", line 682, in save_in_progress
    image = pipeline('testing1234').images[0]
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 533, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 432, in forward
    sample = self.conv_in(sample)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```

As I was tweaking the script the error would sometimes be on the training first step after inference (I think this traceback was when I was running in full precision):

```
  File "/home/paperspace/.stablediffusion/train_text_to_image.py", line 217, in training_loop                                                              
    latents = self.vae.encode(batch["pixel_values"].to(self.weight_dtype)).latent_dist.sample()                                                                                                                    
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 105, in encode                                                                                              
    h = self.encoder(x)                                                                                                                                                                                            
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                 
    return forward_call(*input, **kwargs)                                                                                                                                                                          
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/vae.py", line 101, in forward                                                                                                        
    sample = self.conv_in(sample)                                                                                                                                                                                  
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                 
    return forward_call(*input, **kwargs)                                                                                                                                                                          
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward                                                                                                       
    return self._conv_forward(input, self.weight, self.bias)                                                                                                                                                       
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward                                                                                                 
    return F.conv2d(input, weight, bias, self.stride,                                                                                                                                                              
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same       
```

If I add `keep_fp32_wrapper=True` to `unet = accelerator.unwrap_model(unet)` then the error becomes this:

```
Traceback (most recent call last):
  File "/home/paperspace/infra/test.py", line 819, in <module>
    main()
  File "/home/paperspace/infra/test.py", line 787, in main
    save_in_progress()
  File "/home/paperspace/infra/test.py", line 681, in save_in_progress
    image = pipeline('testing1234').images[0]
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 550, in __call__
    image = self.decode_latents(latents)
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 354, in decode_latents
    image = self.vae.decode(latents).sample
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 144, in decode
    decoded = self._decode(z).sample
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 115, in _decode
    z = self.post_quant_conv(z)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/paperspace/.local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::Half) should be the same
```

I've got more examples of this error in other places but I think you get the point.

I've done this sort of `save_in_progress()` function for textual inversion and DreamBooth training but never had any issues. I'm reporting this as a bug because of the inconsistent behavior I've seen.

### Reproduction

Add the code above to the training script.

### Logs

```shell
See above.
```

### System Info

- `diffusers` version: 0.12.0.dev0
- Platform: Linux-5.4.0-136-generic-x86_64-with-glibc2.31
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 0.15.0.dev0
- Accelerate version: not installed
- xFormers version: 0.0.14.dev
- Using GPU in script?: A5000
- Using distributed or parallel set-up in script?: no

**Comment by Cyberes** [comment]
`accelerate launch --mixed_precision="no"` seems to work.

**Comment by Cyberes** [comment]
Forgot `with torch.autocast('cuda'):`

**Comment by Cyberes** [comment]
I did some googling for the error I was facing and found a recent post on the HF forums describing somewhat a somewhat similar issue. I hate to turn this into a tech support thread, but can anyone offer any insight on this odd behavior?

https://discuss.huggingface.co/t/oom-error-after-creating-pipeline/29443/2

**Comment by patrickvonplaten** [comment]
cc @patil-suraj @pcuenca @williamberman could you take a look?

**Comment by patil-suraj** [comment]
This is because, if `mixed_precision=="fp16"` the `vae` and `text_encoder` are casted to `fp16` but the `unet` is in `fp32`. 
To fix this you could wrap your generation in `torch.autocast("cuda")`. Also in your code you are calling `.cuda` on the models, which won't be necessary as the models are already on the device. 

Also cc @patrickvonplaten , we'll need to handle this when adding generation in training scripts.

**Comment by Cyberes** [comment]
Thanks for the help everyone. Closing this as completed.
