### ISSUE TITLE
Sampling >= 1 image per device broke between v0.9.0 and v0.11.1? [flax]

### ISSUE THREAD

**Issue by jannerm** [huggingface/diffusers#2016]
### Describe the bug

I am sampling from the `FlaxStableDiffusionPipeline` using a script almost identical to that in [the jax section of the README](https://github.com/huggingface/diffusers/tree/b2ea8a84e9db71c207d28687722d241447bde81e#jaxflax); the only modification is that I am sampling more than 1 image per device. Specifically, I have replaced:
```
num_samples = jax.device_count()
```
with
```
num_samples = jax.device_count() * batch_size_per_device
```

The full script is provided in the **Reproduction** section. This script works with `diffusers[flax]==0.9.0`, but fails with `diffusers[flax]=0.11.1` with the error:
```
jax.core.InconclusiveDimensionOperation: Cannot divide evenly the sizes of shapes (8,) and (8, 2)
```

The full stack trace is provided in the **Logs** section below.

### Reproduction

```
import jax
import numpy as np
from flax.jax_utils import replicate
from flax.training.common_utils import shard

from diffusers import FlaxStableDiffusionPipeline

pipeline, params = FlaxStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", revision="flax", dtype=jax.numpy.bfloat16
)

prompt = "a photo of an astronaut riding a horse on mars"

prng_seed = jax.random.PRNGKey(0)
num_inference_steps = 50
batch_size_per_device = 2

num_samples = jax.device_count() * batch_size_per_device
prompt = num_samples * [prompt]
prompt_ids = pipeline.prepare_inputs(prompt)

# shard inputs and rng
params = replicate(params)
prng_seed = jax.random.split(prng_seed, jax.device_count())
prompt_ids = shard(prompt_ids)

print('prompt:', prompt_ids.shape)
images = pipeline(prompt_ids, params, prng_seed, num_inference_steps, jit=True).images
print('n images:', len(images) * len(images[0]))
```

### Logs

```shell
Output with v0.9.0:
prompt: (8, 2, 77)
n images: 16

Output with v0.11.1
prompt: (8, 2, 77)
Traceback (most recent call last):
  File "/nfs/nfs1/users/janner/rldiff/stable/sample_debug.py", line 28, in <module>
    images = pipeline(prompt_ids, params, prng_seed, num_inference_steps, jit=True).images
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 340, in __call__
    guidance_scale = guidance_scale.reshape(prompt_ids.shape[:2])
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 793, in _reshape
    return lax.reshape(a, newshape, None)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 883, in reshape
    return reshape_p.bind(
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/dispatch.py", line 113, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/dispatch.py", line 197, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/dispatch.py", line 445, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2077, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2027, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/dispatch.py", line 192, in prim_fun
    out = prim.bind(*args, **params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1712, in process_primitive
    return custom_staging_rules[primitive](self, *tracers, **params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 3354, in _reshape_staging_rule
    return trace.default_process_primitive(reshape_p, (x,), params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1717, in default_process_primitive
    out_avals, effects = primitive.abstract_eval(*avals, **params)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 365, in abstract_eval_
    return abstract_eval(*args, **kwargs), no_effects
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/lax/utils.py", line 66, in standard_abstract_eval
    return core.ShapedArray(shape_rule(*avals, **kwargs),
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 3293, in _reshape_shape_rule
    not core.same_shape_sizes(np.shape(operand), new_sizes)):
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 1847, in same_shape_sizes
    return 1 == divide_shape_sizes(s1, s2)
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 1844, in divide_shape_sizes
    return handler.divide_shape_sizes(ds[:len(s1)], ds[len(s1):])
  File "/nfs/nfs1/users/janner/utils/anaconda3/envs/nfs/lib/python3.9/site-packages/jax/core.py", line 1740, in divide_shape_sizes
    raise InconclusiveDimensionOperation(f"Cannot divide evenly the sizes of shapes {tuple(s1)} and {tuple(s2)}")
jax.core.InconclusiveDimensionOperation: Cannot divide evenly the sizes of shapes (8,) and (8, 2)
```

### System Info

TPU v3 VM

**Comment by jannerm** [comment]
The problem seems to be caused by [these lines dealing with sharded guidance scales](https://github.com/huggingface/diffusers/blob/v0.11.1/src/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py#L338-L340). For what it's worth simply removing these three lines solves the issue.

Normally I'd just submit a pull request with this fix, but I assume those lines are there for a reason.

**Comment by pcuenca** [comment]
Hi @jannerm! Thanks a lot for reporting this. The issue has already been resolved in `main`. We are planning to do a PyPi release soon; meanwhile, I'd recommend you install diffusers from github:

```
pip install git+https://github.com/huggingface/diffusers
```

By the way, your snippet was running out of memory when attempting to generate 16 images in a v3-8. I had success using revision `bf16` from model `CompVis/stable-diffusion-v1-4`.

Please, let us know if that helps.

**Comment by jannerm** [comment]
Got it, thank you @pcuenca!
