### ISSUE TITLE
Cannot use multiple generators and DDIMScheduler with eta > 0

### ISSUE THREAD

**Issue by xenova** [huggingface/diffusers#2083]
### Describe the bug

As described in the call function of any pipeline (e.g., [pipeline_stable_diffusion_img2img.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py)), one may specify a single generator, or a list of generators:
https://github.com/huggingface/diffusers/blob/a66f2baeb782e091dde4e1e6394e46f169e5ba58/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L483

However, this is not accounted for in the DDIMScheduler, which will crash if more than one generator is specified, due to the following code: https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddim.py#L317-L330

### Reproduction

```python
import torch
from diffusers import StableDiffusionPipeline
from diffusers import DDIMScheduler

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", 
    revision="fp16", 
    torch_dtype=torch.float16,
    use_auth_token=HF_AUTH_TOKEN
)
pipe = pipe.to('cuda')
pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)

num_images_per_prompt = 2
eta = 1


# generator = torch.Generator('cuda').manual_seed(0) # THIS WORKS
generator = [torch.Generator('cuda').manual_seed(i) for i in range(num_images_per_prompt)] # THIS DOESN'T WORK

prompt = "a lone skyscraper landscape vista photography by Carr Clifton & Galen Rowell, 16K resolution, Landscape veduta photo by Dustin Lefevre & tdraw, 8k resolution, detailed landscape painting by Ivan Shishkin, DeviantArt, Flickr, rendered in Enscape, Miyazaki, Nausicaa Ghibli, Breath of The Wild,"
pipe.enable_attention_slicing()
with torch.autocast("cuda"):
    images = pipe(
        prompt,

        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        eta=eta,
    ).images

```

### Logs

```shell
Traceback (most recent call last):
  File "diffusers_test.py", line 28, in <module>
    images = pipe(
  File "...\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "...\Python\Python38\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 537, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "...\Python\Python38\lib\site-packages\diffusers\schedulers\scheduling_ddim.py", line 324, in step
    variance_noise = torch.randn(
TypeError: randn() received an invalid combination of arguments - got (torch.Size, generator=list, dtype=torch.dtype, device=torch.device), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

### System Info

- `diffusers` version: 0.11.1
- Platform: Windows-10-10.0.19041-SP0
- Python version: 3.8.3
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.25.1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

**Comment by xenova** [comment]
Well - it looks like this has been fixed on the dev branch (0.12.0.dev0) with the introduction of `randn_tensor`.

Nevermind then :)
