### ISSUE TITLE
dataloader in text_to_image example

### ISSUE THREAD

**Issue by JunMa11** [huggingface/diffusers#2099]
Hi,

Thanks for sharing this out-of-the-box example for text-to-image generation.

https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py

I followed the guidance to prepare the dataset but the `load_dataset` cannot load the text information.

https://huggingface.co/docs/datasets/v2.4.0/en/image_load#image-captioning

```python
from datasets import load_dataset
img_path = 'path_to/train_folder'
dataset = load_dataset("imagefolder", data_dir=img_path, split="train")
print(dataset)
```
output:

```bash
Dataset({
    features: ['image'],
    num_rows: 2
})
```

Here are the files in the `train_folder`
```
img1.png
img2.png
metadata.json1
```

metadata.json1
```
{"file_name": "img1.png", "text": "This is a first value of a text feature you added to your images"}
{"file_name": "img2.png", "text": "This is a second value of a text feature you added to your images"}
```

BTW, why does the meta files is metadata.json1 rather than metadata.json? However, changing the filename to `metadata.json` also doesn't work.

**Comment by RoyiRa** [comment]
It seems that you are using _metadata.json1_, while it should be _metadata.jsonl_, when I tried your example with the latter it worked fine

**Comment by JunMa11** [comment]
Hi @RoyiRa ,

Thanks for your help very much! Finally, it works!

I have a question on how to generate such json files. 

Assume that I have 1000 paired files and texts, where are two `list` variables `img_names, prompts`. 
I save them into dict and contact the dict in a list. 

```json
[{"file_name": "10112_000004.png", "text": "a T2 image of 2 year old male with adrenal pseudocyst"}, {"file_name": "10112_000011.png", "text": "a T2 image of 2 year old male with adrenal pseudocyst"}]
```

```python
json_path = join(img_path, 'metadata.jsonl')
json_data = []
for name, text in zip(img_names, prompts):
    if os.path.isfile(join(img_path, name)):
        json_data.append({'file_name': name, 'text': text})

with open(json_path, 'w') as f:
    json.dump(json_data, f)
```

How can I generate a json file like this

```json
{"file_name": "10112_000004.png", "text": "a T2 image of 2 year old male with adrenal pseudocyst"}
{"file_name": "10112_000011.png", "text": "a T2 image of 2 year old male with adrenal pseudocyst"}
```

**Comment by Skquark** [comment]
Ran into the same question to convert json to jsonl... Here's how I did it:
```python
    with open(os.path.join(save_path, "metadata.jsonl"), "w") as f:
        for meta in metadata_jsonl:
          print(json.dumps(meta), file=f)
```
or for your example, it'd be:
```python
    with open(json_path, "w") as f:
        for data in json_data:
          print(json.dumps(data), file=f)
```
Simple enough... Got the train_text_to_image_lora.py script running, thought I was in the clear, but then I got this error:
```
Generating train split: 0 examples [00:00, ? examples/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1570, in _prepare_split_single
    for key, record in generator:
  File "/usr/local/lib/python3.8/dist-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 325, in _generate_examples
    raise ValueError(
ValueError: image at Cygana.png doesn't have metadata in /content/my_model/metadata.jsonl.

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "train_text_to_image_lora.py", line 824, in <module>
    main()
  File "train_text_to_image_lora.py", line 513, in main
    dataset = load_dataset(
  File "/usr/local/lib/python3.8/dist-packages/datasets/load.py", line 1757, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 860, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1611, in _download_and_prepare
    super()._download_and_prepare(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 953, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1449, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/usr/local/lib/python3.8/dist-packages/datasets/builder.py", line 1606, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```
Not sure what I did wrong.. Anyone else get an error like this when trying to train?

**Comment by patrickvonplaten** [comment]
cc @williamberman or @patil-suraj

**Comment by JunMa11** [comment]
Thanks for your help very much:)

**Comment by patil-suraj** [comment]
Thanks a lot @Skquark !
