### ISSUE TITLE
keyError : Parameter containing:

### ISSUE THREAD

**Issue by YJ-142150** [huggingface/diffusers#2240]
Hello, thanks for your great work.
I tried multi_subject_dreambooth with DeepSpeed. But this error showed up. 
```
Traceback (most recent call last):
  File "train_multi_subject_dreambooth.py", line 869, in <module>
    main(args)
  File "train_multi_subject_dreambooth.py", line 694, in main
    unet, text_encoder, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 872, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/accelerate/accelerator.py", line 1093, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1291, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1542, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 529, in __init__
    self._param_slice_mappings = self._create_param_mapping()
  File "/home/lambdasix/anaconda3/envs/diffusers/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 541, in _create_param_mapping
    lp_name = self.param_names[lp]
KeyError: Parameter containing:
tensor([[[[-2.9978e-02,  1.6412e-02,  7.8307e-02],
          [-1.7548e-02, -1.2453e-01,  1.0206e-01],
          [-1.0419e-02, -1.7165e-02,  3.1280e-02]],

         [[ 4.3467e-02, -6.2368e-02,  2.4400e-03],
          [ 1.2211e-01, -9.7347e-02, -4.1649e-02],
          [ 1.2320e-02, -8.7301e-03,  1.0303e-02]],

         [[ 1.8298e-02, -2.1204e-02,  3.0268e-02],
          [-1.9939e-02,  1.8145e-02,  3.8008e-02],
          [-4.0331e-03, -7.0512e-03, -1.6380e-02]],

         [[ 2.5887e-02, -3.5401e-02,  2.0769e-02],
          [ 2.0130e-02, -7.7295e-02,  6.2782e-02],
          [-5.5730e-04, -2.4972e-02,  1.9109e-02]]],


        [[[ 9.4357e-03, -6.7663e-03, -2.8575e-02],
          [ 8.4005e-03,  2.0499e-02,  8.7173e-02],
          [-4.8202e-04,  4.0411e-03,  1.2875e-02]],

         [[ 9.3415e-04,  9.0679e-03, -1.0146e-02],
          [-2.5179e-03,  5.1361e-02,  1.1227e-02],
          [-8.5428e-03,  2.3411e-02,  2.3630e-02]],

         [[-2.1263e-03,  2.9357e-02,  3.9300e-03],
          [ 1.5399e-02, -1.2048e-01, -1.3731e-03],
          [ 1.7035e-02, -3.4069e-02, -1.1204e-03]],

         [[-2.3321e-03, -2.7916e-02,  1.5098e-02],
          [-2.5094e-02,  5.2156e-02, -4.1579e-03],
          [-1.9066e-02,  1.4639e-02, -2.0956e-02]]],


        [[[-4.6981e-02, -3.8749e-02, -2.0999e-02],
          [ 3.5369e-02,  4.7643e-02, -7.9302e-03],
          [ 1.3395e-02,  2.6929e-02,  3.5141e-02]],

         [[ 2.2279e-03,  3.8312e-02,  1.9400e-02],
          [ 3.1406e-02, -7.0895e-02, -3.9135e-02],
          [-2.0107e-02,  1.0871e-02,  8.6377e-05]],

         [[-3.9156e-04,  4.7171e-02, -2.2027e-03],
          [-4.2334e-02,  8.7425e-02, -2.7522e-02],
          [ 1.4673e-04, -4.2375e-02, -1.3966e-02]],

         [[-6.9832e-03, -2.1773e-03,  1.7350e-02],
          [-2.7035e-02,  3.4484e-02,  3.7099e-02],
          [-3.3415e-02,  2.2710e-02, -2.0440e-02]]],


        ...,


        [[[ 1.6812e-02,  5.7600e-02,  6.4191e-03],
          [ 5.0254e-02,  8.9605e-02,  1.2213e-02],
          [ 3.2238e-02,  6.1869e-03,  3.3683e-02]],

         [[ 1.4772e-02,  4.0796e-02,  4.1941e-02],
          [ 3.5273e-02,  8.8862e-02, -1.2634e-02],
          [-3.3538e-04,  6.4882e-02,  4.5664e-04]],

         [[ 3.4997e-02,  1.6928e-02,  3.8501e-02],
          [ 4.8755e-02, -4.0986e-03,  7.0170e-02],
          [ 3.6926e-02,  5.7167e-03,  8.1857e-02]],

         [[ 5.3984e-02,  5.4586e-02,  6.4554e-02],
          [ 5.0859e-02, -2.6170e-02,  3.4888e-02],
          [ 4.4568e-02, -1.0269e-02,  5.2855e-02]]],


        [[[-8.1608e-03,  6.9869e-03,  8.8394e-03],
          [ 5.4054e-02, -3.8970e-02,  3.5248e-02],
          [ 1.2766e-02,  4.2209e-02, -5.8504e-02]],

         [[-4.6291e-02, -1.3647e-02, -8.2918e-03],
          [ 2.4299e-02,  4.5169e-02,  4.5072e-02],
          [ 1.2837e-02,  3.1326e-02, -4.8022e-03]],

         [[ 4.7700e-02, -1.7678e-02,  2.6846e-02],
          [-4.6568e-03,  1.8613e-02, -5.4419e-03],
          [-3.2698e-02, -6.0188e-02, -7.8278e-02]],

         [[ 4.2939e-03,  8.0452e-03, -1.7496e-02],
          [ 2.1941e-02, -1.3214e-02,  4.0895e-02],
          [ 2.6663e-02,  3.5255e-02, -1.1545e-02]]],


        [[[-1.0213e-01, -8.2644e-02, -2.5634e-02],
          [ 6.8527e-02, -2.7996e-02,  3.2233e-02],
          [ 3.6630e-02,  1.7087e-02,  3.9457e-02]],

         [[ 1.1020e-01,  5.8558e-02,  2.9449e-02],
          [ 8.2259e-02,  2.6701e-02,  2.7452e-03],
          [-4.2937e-02,  1.0915e-02, -4.7717e-02]],

         [[-3.5919e-02, -4.6858e-02, -3.6328e-02],
          [-2.2640e-02,  2.4219e-03, -2.6891e-02],
          [ 1.3711e-02, -6.5323e-03, -2.6707e-03]],

         [[-3.9279e-02, -3.4127e-02, -9.1058e-03],
          [ 3.0562e-02,  1.3739e-02,  3.3620e-02],
          [ 3.7918e-02,  5.8561e-03,  2.1757e-02]]]], device='cuda:0',
       requires_grad=True)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 564936) of binary: /home/lambdasix/anaconda3/envs/diffusers/bin/python
```

**Comment by patrickvonplaten** [comment]
Gently pinging @kopsahlong here :-) as this is a not-officially maintained example script: https://github.com/huggingface/diffusers/tree/main/examples/research_projects/multi_subject_dreambooth
