### ISSUE TITLE
stable-diffusion-v1-4 link in release v0.2.3 is broken

### ISSUE THREAD

**Issue by leszekhanusz** [huggingface/diffusers#228]
### Describe the bug

@anton-l  the link (https://huggingface.co/CompVis/stable-diffusion-v1-4) in the [release v0.2.3](https://github.com/huggingface/diffusers/releases/tag/v0.2.3) returns a 404.

### System Info

```shell
N/A
```

**Comment by leszekhanusz** [comment]
It seems the repo is still private:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(
  File "/home/leszek/miniconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 153, in from_pretrained
    cached_folder = snapshot_download(
  File "/home/leszek/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/_snapshot_download.py", line 182, in snapshot_download
    repo_info = _api.repo_info(
  File "/home/leszek/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1289, in repo_info
    return self.model_info(
  File "/home/leszek/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1136, in model_info
    _raise_for_status(r)
  File "/home/leszek/miniconda3/envs/ldm/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 60, in _raise_for_status
    raise RepositoryNotFoundError(
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error: Repository Not Found for url: https://huggingface.co/api/models/CompVis/stable-diffusion-v1-4/revision/main. If the repo is private, make sure you are authenticated. (Request ID: 6Ac71IJ1-d8KfsXGMKt49)
```

**Comment by anton-l** [comment]
@leszekhanusz we're slightly ahead of schedule, the model repositories will be made public later today :)

**Comment by TingTingin** [comment]
do you have a scheduled time?

**Comment by loopyd** [comment]
Looking forward to it.  Thanks so much everyone for doing this!  This is going to change the way the world creates once more!!! -- saber7ooth#7527  💖

**Comment by hlky** [comment]
> we're slightly ahead of schedule, the model repositories will be made public later today :)

good morning ser

please redeem model now :)

**Comment by m-hammad-khan** [comment]
Any update on when will you guys release the model?

**Comment by furmanlukasz** [comment]
Does the same apply to license acceptance? Many people get 404 even though they are logged in on both github and hugginface. Is there a special procedure for linking both accounts?

**Comment by natolambert** [comment]
Should all be visible now. Feel free to re-open if not the case.

**Comment by leszekhanusz** [comment]
:fire: :fire: :rocket: :rocket: IT'S NOW AVAILABLE :fire: :fire: :rocket: :rocket: 

Thank you!

Code used to test:

```python
import torch                                                                                                            
import sys                                                                                                              
from torch import autocast                                                                                              
from diffusers import StableDiffusionPipeline, LMSDiscreteScheduler                                                     
                                                                                                                        
# this will substitute the default PNDM scheduler for K-LMS                                                             
lms = LMSDiscreteScheduler(                                                                                             
    beta_start=0.00085,                                                                                                 
    beta_end=0.012,                                                                                                     
    beta_schedule="scaled_linear"                                                                                       
)                                                                                                                       
                                                                                                                        
pipe = StableDiffusionPipeline.from_pretrained(                                                                         
    "CompVis/stable-diffusion-v1-4",                                                                                    
    revision="fp16",                                                                                                    
    torch_dtype=torch.float16,                                                                                          
    scheduler=lms,                                                                                                      
    use_auth_token=True                                                                                                 
).to("cuda")                                                                                                            
                                                                                                                        
while(True):                                                                                                            
    prompt = input("Prompt: ")                                                                                          
                                                                                                                        
    if len(prompt) == 0:                                                                                                
        break                                                                                                           
                                                                                                                        
    with autocast("cuda"):                                                                                              
        image = pipe(prompt)["sample"][0]                                                                               
                                                                                                                        
    image.show()                                                                                                        
    image.save(prompt + ".png")
```

**Comment by Dufftwt** [comment]
Hey! I'm looking to get the ckpt file, since I don't want to use the diffusers library. Anyone has got it? I thought the weights were open.

**Comment by m-hammad-khan** [comment]
> Hey! I'm looking to get the ckpt file, since I don't want to use the diffusers library. Anyone has got it? I thought the weights were open.

-original versions repos have ckpt files IIRC.

**Comment by Dufftwt** [comment]
> > Hey! I'm looking to get the ckpt file, since I don't want to use the diffusers library. Anyone has got it? I thought the weights were open.
> 
> @Dufftwt Original version repos have ckpt files IIRC. https://huggingface.co/CompVis/stable-diffusion-v-1-4-original

@m-hammad-khan Thanks a lot!! It was not clear to me. Really, thanks.
