### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by notdanilo** [huggingface/diffusers#2402]
### Describe the bug

I followed the guidelines in the README.md file and tried to run the pipeline with CUDA enabled. I am getting the following error:

```python
python main.py
C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Traceback (most recent call last):
  File "C:\dev\notdanilo\diffusers\main.py", line 5, in <module>
    pipe = pipe.to("cuda")
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 272, in to
    module.to(torch_device)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\notdanilo\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Reproduction

I am installing it with this command:
`pip install --upgrade diffusers[torch] transformers accelerate`

Content of main.py:

```python
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("./stable-diffusion-v1-5")
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]
```

### System Info

$ python --version
Python 3.10.6

Windows 10

**Comment by williamberman** [comment]
hey @notdanilo this is a part of your pytorch installation, not diffusers :)

googling around I see a few threads about the error message

https://github.com/pytorch/pytorch/issues/30664 
https://discuss.pytorch.org/t/torch-not-compiled-with-cuda-enabled/112467/12

I use the torch install commands from the table on the pytorch website https://pytorch.org/
