### ISSUE TITLE
Changing the scheduler from UniPC or DEIS to DPM or DPM multistep results in error

### ISSUE THREAD

**Issue by brurpo** [huggingface/diffusers#2534]
### Describe the bug

Hello there!
Whenever I try to change the scheduler from UniPC or DEIS to DPM or DPM multistep I get the following error:
UnboundLocalError: local variable 'x_t' referenced before assignment

full error:
```
Traceback (most recent call last):
  File "E:\sd\output_gui2\sdiff_GUI.py", line 833, in <module>
    image = pipe.text2img(window, prompt=prompt,negative_prompt=nprompt, width=dim[0], height=dim[1], num_inference_steps=int(values["_IMAGE_SL_"]), guidance_scale=guidance_scale, generator=generator).images
  File "C:\Users\brurp/.cache\huggingface\modules\diffusers_modules\local\pipeline.py", line 990, in text2img
    return self.__call__(
  File "C:\Users\brurp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\brurp/.cache\huggingface\modules\diffusers_modules\local\pipeline.py", line 858, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "C:\Users\brurp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\diffusers\schedulers\scheduling_dpmsolver_singlestep.py", line 559, in step
    prev_sample = self.singlestep_dpm_solver_update(
  File "C:\Users\brurp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\diffusers\schedulers\scheduling_dpmsolver_singlestep.py", line 502, in singlestep_dpm_solver_update
    return self.singlestep_dpm_solver_second_order_update(
  File "C:\Users\brurp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\diffusers\schedulers\scheduling_dpmsolver_singlestep.py", line 402, in singlestep_dpm_solver_second_order_update
    return x_t
UnboundLocalError: local variable 'x_t' referenced before assignment
```
likewise, if I change from DPM/DPM multistep to DEIS or UniPC I get notimplemented error

### Reproduction

Change to UniPC or DEIS scheduller, run an inference, then change to DPM and try to run an inference

### System Info

2990wx
2080ti

**Comment by patrickvonplaten** [comment]
Hey @brurpo,

Can you please try to copy-paste a reproducible code snippet?

**Comment by brurpo** [comment]
Hi @patrickvonplaten!
Its happening inside my gui, I will try to work up a snippet today outside of it!
Thanks!

**Comment by brurpo** [comment]
Hey @patrickvonplaten 
here is the simplifyed code code:
```
import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler, UniPCMultistepScheduler

pipe = StableDiffusionPipeline.from_pretrained("E:\\BRP_STABLE_DIFFUSION\\bin\\models\\anything-v3.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")


prompt = "a photo of an astronaut riding a horse on mars"

pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
image = pipe(prompt).images[0]

pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
image = pipe(prompt).images[0]
```
I can freely change between scedulers, except when including UniPC or DEIS.

**Comment by patrickvonplaten** [comment]
I can reproduce the error - thanks for the code snippet! Checking now

**Comment by patrickvonplaten** [comment]
Ok PR #2595 should fix it :-) Should be merged soon!

**Comment by CrazyBoyM** [comment]
I have the same problem now during changing schedulers with diffusers==0.14.0.

**Comment by brurpo** [comment]
> I have the same problem now during changing schedulers with diffusers==0.14.0.

This is already fixed and merged, but not yet released. You can install the dev version by git cloning this github repository where this issue is fixed

**Comment by CrazyBoyM** [comment]
> 

Great! thanks !
