### ISSUE TITLE
SD 2.0 Based UNet2DConditionModel doesn't work

### ISSUE THREAD

**Issue by chavinlo** [huggingface/diffusers#2549]
### Describe the bug

I am trying to use a SD 2.x based model by loading it as UNet2DConditionModel just like the pipeline does. However upon inference I am met with the following error:

```python
Traceback (most recent call last):
  File "/workspace/node/threads/base.py", line 215, in image_generator
    noise_pred = curr_unet(latent_model_input, timestep, encoder_hidden_states=text_embeddings).sample
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 837, in forward
    hidden_states = attn(
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 265, in forward
    hidden_states = block(
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/attention.py", line 307, in forward
    attn_output = self.attn2(
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 205, in forward
    return self.processor(
  File "/workspace/env/lib/python3.10/site-packages/diffusers/models/cross_attention.py", line 449, in __call__
    key = attn.to_k(encoder_hidden_states)
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/env/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x768 and 1024x320)
```

Although I am using part of the LPW prompt encoder, It still doesn't work when given a normal prompt.

### Reproduction

```python
for step_index, timestep in enumerate(scheduler.timesteps):
                    # expand the latents if we are doing classifier free guidance
                    latent_model_input = torch.cat([latents] * 2)
                    latent_model_input = scheduler.scale_model_input(latent_model_input, timestep)

                    # predict the noise residual
                    dtype = np.float16
                    if timestep.dtype != torch.float32:
                        timestep_float = timestep.float()
                    else:
                        timestep_float = timestep

                    print("TE:", text_embeddings.shape)
                    
                    noise_pred = curr_unet(latent_model_input, timestep, encoder_hidden_states=text_embeddings).sample

                    # Perform guidance
                    noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                    noise_pred = noise_pred_uncond + cfg * (noise_pred_text - noise_pred_uncond)

                    # Denoise?
                    if data['scheduler'] in ['DEIS', 'DPM2', 'HEUN', 'DPM++', 'DPM', 'PNDM', 'SING-DPM']:
                        latents = scheduler.step(
                                model_output=noise_pred, 
                                timestep=timestep, 
                                sample=latents).prev_sample
                    else:
                        latents = scheduler.step(
                                model_output=noise_pred, 
                                timestep=timestep, 
                                sample=latents,
                                generator=generator).prev_sample
```

### System Info

- `diffusers` version: 0.14.0
- Platform: Linux-5.4.0-144-generic-x86_64-with-glibc2.31
- Python version: 3.10.10
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.16
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

**Comment by chavinlo** [comment]
I've read #1802 and they mention the need of passing encoder_hidden_states which I do.

**Comment by patrickvonplaten** [comment]
Hey @chavinlo,

When copy-pasting:

```py
for step_index, timestep in enumerate(scheduler.timesteps):
                    # expand the latents if we are doing classifier free guidance
                    latent_model_input = torch.cat([latents] * 2)
                    latent_model_input = scheduler.scale_model_input(latent_model_input, timestep)

                    # predict the noise residual
                    dtype = np.float16
                    if timestep.dtype != torch.float32:
                        timestep_float = timestep.float()
                    else:
                        timestep_float = timestep

                    print("TE:", text_embeddings.shape)
                    
                    noise_pred = curr_unet(latent_model_input, timestep, encoder_hidden_states=text_embeddings).sample

                    # Perform guidance
                    noise_pred_uncond, noise_pred_text = noise_pred.chunk(2)
                    noise_pred = noise_pred_uncond + cfg * (noise_pred_text - noise_pred_uncond)

                    # Denoise?
                    if data['scheduler'] in ['DEIS', 'DPM2', 'HEUN', 'DPM++', 'DPM', 'PNDM', 'SING-DPM']:
                        latents = scheduler.step(
                                model_output=noise_pred, 
                                timestep=timestep, 
                                sample=latents).prev_sample
                    else:
                        latents = scheduler.step(
                                model_output=noise_pred, 
                                timestep=timestep, 
                                sample=latents,
                                generator=generator).prev_sample
```

into a console, I'm getting:

```
NameError: name 'scheduler' is not defined
```

Could you try to post a **complete**, **copy-pastable** repro?
