### ISSUE TITLE
Non Huggingface models from Dreambooth (i.e. civit.ai)

### ISSUE THREAD

**Issue by bluusun** [huggingface/diffusers#2572]
What's the workflow (if it exists) for non Hugginface models?

I downloaded and used the local ckpt file but got this error (no JSON conf files are provided for most civit.ai models)

Traceback (most recent call last):                                                                                                                                                  
  File "/home/ubuntu/.cache/diffusers/src/diffusers/configuration_utils.py", line 380, in load_config                                                                               
    config_dict = cls._dict_from_json_file(config_file)                                                                                                                             
  File "/home/ubuntu/.cache/diffusers/src/diffusers/configuration_utils.py", line 480, in _dict_from_json_file
    text = reader.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_dreambooth.py", line 1032, in <module>
    main(args)
  File "train_dreambooth.py", line 633, in main
    pipeline = DiffusionPipeline.from_pretrained(
  File "/home/ubuntu/.cache/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 589, in from_pretrained
    config_dict = cls.load_config(
  File "/home/ubuntu/.cache/diffusers/src/diffusers/configuration_utils.py", line 382, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at '/home/ubuntu/.cache/hassan.ckpt' is not a valid JSON file.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by patrickvonplaten** [comment]
Hey @bluusun, 

You need to convert such models first using https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py

**Comment by bluusun** [comment]
No, no these I am creating Dreambooth from existing SafeTensor models listed on civit.ai :)
