### ISSUE TITLE
Support to convert between ControlNet 2.1 checkpoints and diffusers

### ISSUE THREAD

**Issue by tonetechnician** [huggingface/diffusers#2581]
### Describe the bug

I'm unable to convert a 2.1 trained ControlNet model using `scripts/convert_original_stable_diffusion_to_diffusers.py`

The ControlNet models in question are here:

https://huggingface.co/furusu/ControlNet

It would seem this ControlNet models have been created by subtracting them out from the original model 

<img width="935" alt="image" src="https://user-images.githubusercontent.com/13471797/223371791-252ea996-1497-4f9c-b804-344a985d39d2.png">

This could also be a culprit that is causing weird behaviour in the script.

### Reproduction

1. Pull the ControlNet repo
2. In diffusers run 
```
python scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./furusu/ControlNet/diff_control_wd15beta2_depth.safetensors --original_config_file ./furusu/ControlNet/diff_control_wd15beta2_depth.yaml --image_size 768 --prediction_type v_prediction --device mps --controlnet --dump_path ./furusu/ControlNet/depth-diffusers --from_safetensors
```

I get an error that there are missing keys in the config (logs attached).

Upon digging into the script, I've tried to force controlnet to be active when recreating the unet model upon initially loading 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/13471797/223370470-0eae4932-85b4-4f8e-b224-f57ca2f7b46b.png">

But I get the log as attached

There are a couple things I've noticed in the script. 

The script says that ControlNet can't be used with FrozenOpenClip text model, however, SD 2.1 uses the OpenClip model as we can see in the config .yaml

<img width="814" alt="image" src="https://user-images.githubusercontent.com/13471797/223371379-f7597c50-4c49-4f0a-9166-a68937733733.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/13471797/223370781-efd294ff-1865-4887-8665-95cc90ca626b.png">

So from what I can gather, I think there are potentially two issues here:

1. We need a case where the the script converts ONLY the ControlNet part of the model, and not the full model. Or a way to manage this.
2. We need to allow FrozenOpenClip to be used with ControlNet

### Logs

```shell
Traceback (most recent call last):
  File "/Users/threaded/git-repos/machine-learning/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 130, in <module>
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(
  File "/Users/threaded/git-repos/machine-learning/diffusers/.venv/lib/python3.10/site-packages/diffusers-0.15.0.dev0-py3.10.egg/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1140, in load_pipeline_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "/Users/threaded/git-repos/machine-learning/diffusers/.venv/lib/python3.10/site-packages/diffusers-0.15.0.dev0-py3.10.egg/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 383, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
```

When running with controlnet forced in `convert_from_ckpt.py`. 

```
Traceback (most recent call last):
  File "/Users/threaded/git-repos/machine-learning/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 130, in <module>
    pipe = load_pipeline_from_original_stable_diffusion_ckpt(
  File "/Users/threaded/git-repos/machine-learning/diffusers/.venv/lib/python3.10/site-packages/diffusers-0.15.0.dev0-py3.10.egg/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1144, in load_pipeline_from_original_stable_diffusion_ckpt
    unet.load_state_dict(converted_unet_checkpoint)
  File "/Users/threaded/git-repos/machine-learning/diffusers/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        Missing key(s) in state_dict: "up_blocks.0.resnets.0.norm1.weight", "up_blocks.0.resnets.0.norm1.bias", "up_blocks.0.resnets.0.conv1.weight", "up_blocks.0.resnets.0.conv1.bias", "up_blocks.0.resnets.0.time_emb_proj.weight", "up_blocks.0.resnets.0.time_emb_proj.bias", "up_blocks.0.resnets.0.norm2.weight", "up_blocks.0.resnets.0.norm2.bias", "up_blocks.0.resnets.0.conv2.weight", "up_blocks.0.resnets.0.conv2.bias", "up_blocks.0.resnets.0.conv_shortcut.weight", "up_blocks.0.resnets.0.conv_shortcut.bias", "up_blocks.0.resnets.1.norm1.weight", "up_blocks.0.resnets.1.norm1.bias", "up_blocks.0.resnets.1.conv1.weight", "up_blocks.0.resnets.1.conv1.bias", "up_blocks.0.resnets.1.time_emb_proj.weight", "up_blocks.0.resnets.1.time_emb_proj.bias" ....
```
```


### System Info


- `diffusers` version: 0.15.0.dev0
- Platform: macOS-13.2.1-arm64-arm-64bit
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.1 (False)
- Huggingface_hub version: 0.12.1
- Transformers version: 4.26.1
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: no, using mps
- Using distributed or parallel set-up in script?: no

**Comment by tonetechnician** [comment]
If anyone has any initial thoughts here on potential solutions, please let me know. 

So far I'm planning to try duplicate the current script to allow for controlnet only segments and allow OpenClip to be used when recreating the pipeline. The only issue that I see is using `create_unet_diffusers_config` with `controlnet=True` param, as that is always throwing an error with the configs.

**Comment by apolinario** [comment]
I also had the same bug at
```py 
new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
```

While trying to convert this 2-1 controlnet https://huggingface.co/thibaud/controlnet-canny-sd21 following @takuma104's guide here https://github.com/huggingface/diffusers/issues/2550#issuecomment-1454980881

Here's a colab for repro: https://colab.research.google.com/drive/18bOJjpBOcZSQYIT-85z6EnE-2RMaFsW7

**Comment by takuma104** [comment]
I personally tried converting Furusu's weight a little while ago. The code is on my local machine, so I will upload it later.

**Comment by patrickvonplaten** [comment]
Thanks for the issue! @williamberman could you check this?

**Comment by tonetechnician** [comment]
Amazing! Thanks @takuma104 

I made some progress aswell. I have been able to output controlnet weights out by using the default SD 2.1 pipeline as reference for unet, vae and text_encoder, also disabling the check for OpenClip + controlnet. 

Going to test the weights shortly to see if they actually work!

**Comment by takuma104** [comment]
With Furusu's weights, one thing that is strange is that there is a difference with WD1.5b2's Unet. The details are written in the model card, but it became completely meaningless without restoring that difference. (I was really confused about this point.) When I restored it and then converted it, it worked properly at that time.

**Comment by takuma104** [comment]
Here is the code for Diffusers that was used at that time. Since it was about four days ago, it is quite outdated compared to the current main. The changes are that when converting ControlNet, only the necessary parts are converted without creating a pipeline. However, I didn't upload it because I thought the implementation was still lacking for a PR.
https://github.com/takuma104/diffusers/tree/controlnet_sd2

This is an example of code to revert the conversion of Furusu's weight diff. It simply changes '-' back to '+' in the script for taking the diff, but it worked with this.
https://gist.github.com/takuma104/bece6ce2e6ac55b101a82ac5f61c9398

**Comment by tonetechnician** [comment]
Ah, thanks for sharing your repo! I've just tested my implementation and indeed, got some strange output. Sort of looks like it's working but there's no dynamic range in the output.

> The changes are that when converting ControlNet, only the necessary parts are converted without creating a pipeline. However, I didn't upload it because I thought the implementation was still lacking for a PR.

Loading only the necessary parts for controlnet makes sense to me. I'll test your implementation out and feedback here. 

With Furusu's weights, did you first convert back from the diff, before converting to diffusers format using your script?

**Comment by tonetechnician** [comment]
Thanks @takuma104 

Just to confirm your script worked great! I just ran through the merge process, using the control nets + the original wd-1.5beta2 weights (diff_control_wd15beta2_depth.safetensors). After that I had a checkpoint. After that I got a safetensors output that included both control net + the original model. From there I used your modified controlnet script to generate the controlnet weights. Worked like a charm! 

I'm doing quite a bit of work with different models from all over the place, so will likely be trying this method with more models. Will feedback on my experience with it, it would be nice to get this merged into diffusers. Super useful script! Especially with all the models coming out on Civitai

**Comment by takuma104** [comment]
@tonetechnician Thanks for the report! I'm glad it worked out well. Although SD1.5 ControlNet is still mainstream, [a new checkpoint for SD2.1](http://huggingface.co/thibaud/controlnet-canny-sd21) seems to have been released today, so it looks like there will be more in the future. I'm thinking of opening a PR after organizing the code a little more.

> With Furusu's weights, did you first convert back from the diff, before converting to diffusers format using your script?

Sorry for the late response, but I also did it this way.

**Comment by tonetechnician** [comment]
I think having support for all models will be welcomed @takuma104 ! Nice, let me know if I can help you in anyway.

**Comment by williamberman** [comment]
Nice! This should be pretty straightforward.

We'll do a separate script for converting checkpoints which only have a controlnet, `scripts/convert_original_controlnet_to_diffusers.py`. 

 I'd appreciate some help testing this on known checkpoints. I'm getting good results with https://huggingface.co/thibaud/controlnet-canny-sd21 but not so much with https://huggingface.co/furusu/ControlNet. As we don't have a canonical set of sd2 control net models, I'd like to have community consensus if the conversion script works as expected.

https://github.com/huggingface/diffusers/pull/2593/files

**Comment by tonetechnician** [comment]
Great, thanks @williamberman 

I'll be testing Thibaud's today. I agree, furusu's output worked, but I don't think it was trained on enough images. Most of the output was coming out quite flat as if it only understood comics/anime. Maybe to do with the wd-1.5 model.

**Comment by tonetechnician** [comment]
Definitely seem to be getting better results, but still not amazing . Will play around with a few more options here

![output](https://user-images.githubusercontent.com/13471797/223751853-176832b9-c5d0-4802-87ef-40c2f0e6cedf.png)

**Comment by tonetechnician** [comment]
following prompts from https://huggingface.co/blog/controlnet.

Definitely looking good! 

![output](https://user-images.githubusercontent.com/13471797/223752974-2e4460fc-ea94-4051-8004-c4c838ec90fa.png)

**Comment by tonetechnician** [comment]
> I want to make some test locally but I got some issue to run the script.
> 
> File "D:...\diffusers\scripts\convert_original_controlnet_to_diffusers.py", line 19, in from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_controlnet_from_original_ckpt
> 
> ```
> Will try more later.
> ```

Ah yes, you need to use this PR to try https://github.com/huggingface/diffusers/pull/2593

**Comment by thibaudart** [comment]
> > I want to make some test locally but I got some issue to run the script.
> > File "D:...\diffusers\scripts\convert_original_controlnet_to_diffusers.py", line 19, in from diffusers.pipelines.stable_diffusion.convert_from_ckpt import load_controlnet_from_original_ckpt
> 
> Ah yes, you need to use this PR to try #2593

Thanks but how I use it? (sorry I know it's sounds dumb but... I never use PR always main branch...)

**Comment by tonetechnician** [comment]
No worries! 

Follow these steps:
1. `git clone https://github.com/williamberman/diffusers/tree/controlnet_sd21_checkpoint_conversion`
2. `git checkout controlnet_sd21_checkpoint_conversion`
3. `python -m venv ./.venv`
4. if on linux/mac `source ./.venv/bin/activate` if on windows `./.venv/Scripts/activate.ps1`
5. install required dependencies 
6. `python setup.py install` to install diffusers 
7. then run the script 

This should work if I'm not mistaken.

**Comment by thibaudart** [comment]
Thanks a lot! I'll try a bit later. I'm launching the training of a new controlnet!

**Comment by tonetechnician** [comment]
Exciting @thibaudart !! 

I was wondering something, is there any reason you decided to train the control net on 512? In ideal world, I guess it would be good to have controlnets trained for both 768 and 512? Super curious to know if you have thoughts on that?

**Comment by thibaudart** [comment]
Yes having the both could be very nice. 
 I use the 512 in my artistic process, so I use this one 😅

**Comment by thepowerfuldeez** [comment]
Hi guys! Just found your discussion here. I have converted great checkpoint from @thibaudart to diffusers format and saved only ControlNet part in fp16 so it only takes 700mb of space.
Both 2.1 and 2.1-base work, but 2.1-base seems to work better

In order to convert I manually took part starting from [this](https://github.com/huggingface/diffusers/blob/445a176bdea9111bf725719b5eeb1abef8f9d3ad/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1249) line and saved model.

It is here: https://huggingface.co/thepowefuldeez/sd21-controlnet-canny 
Usage:
```
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, DEISMultistepScheduler
import cv2
from PIL import Image
import numpy as np

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1-base",
    safety_checker=None,
    # revision='fp16',
    # torch_dtype=torch.float16,
    controlnet=ControlNetModel.from_pretrained("thepowefuldeez/sd21-controlnet-canny")
).to('cuda')
pipe.scheduler = DEISMultistepScheduler.from_config(pipe.scheduler.config)

image = np.array(Image.open("10.png"))

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)

im = pipe(
    "beautiful woman", image=canny_image, num_inference_steps=30, 
    negative_prompt="ugly, blurry, bad, deformed, bad anatomy", 
    generator=torch.manual_seed(42)
).images[0]
```

**Comment by thibaudart** [comment]
I got the convert to safetensors working but when I use it on automatic1111, I got errors: 

RuntimeError: Error(s) in loading state_dict for ControlNet:
        Missing key(s) in state_dict: "time_embed.0.weight", "time_embed.0.bias", "time_embed.2.weight", "time_embed.2.bias", "input_blocks.0.0.weight", "input_blocks.0.0.bias", "input_blocks.1.0.in_layers.0.weight", "input_blocks.1.0.in_layers.0.bias", "input_blocks.1.0.in_layers.2.weight", "input_blocks.1.0.in_layers.2.bias", ...

maybe someone have a solution!

**Comment by williamberman** [comment]
@thibaudart our model definitions aren't compatible with automatic1111. So a safetensors output from the conversion script would have to be re-converted back to the original format. If you want a safetensors version of the the original format, it's not necessary to use the conversion script and instead you should directly save the original checkpoint in safetensors format https://github.com/huggingface/safetensors#getting-started

**Comment by thibaudart** [comment]
The original ckpt is 9go.
The diffusers versions is 700mb.
I don't find a way to pruned the ckpt and save it in safetensors (or smaller ckpt). 
In the doc https://github.com/huggingface/safetensors#getting-started, I don't understand how to do that.

**Comment by williamberman** [comment]
I merged the PR, so I'm going to close this issue. Note that we don't have canonical 2.1 checkpoints that we can test so it's definitely possible there are other issues with converting 2.1 controlnet checkpoints. If/when other issues arise, feel free to file them separately :)

**Comment by patrickvonplaten** [comment]
Hey @thibaudart, 

Note that for diffusers you can just save the `.safetensors` checkpoint as follows:

```py
from diffusers import ControlNetModel

model = ControlNetModel.from_pretrained("thibaud/controlnet-sd21-canny-diffusers")
model.save_pretrained("./controlnet", safe_serialization=True)
```

**Comment by patrickvonplaten** [comment]
Also note that we have a "Diffusers convert to safetensors" space that does this automatically for you. You can try it here: https://huggingface.co/spaces/diffusers/convert . I've used it to open a PR for your repo here: https://huggingface.co/thibaud/controlnet-sd21-openpose-diffusers/discussions/2

**Comment by goodspb** [comment]
@williamberman hi, I try to convert [safetensors file](https://huggingface.co/thibaud/controlnet-sd21/resolve/main/openpose-sd21-safe.safetensors) , but still got error like:  
`new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]`

but converting [ckpt](https://huggingface.co/thibaud/controlnet-sd21/resolve/main/openpose-sd21.ckpt) is fine.

**Comment by patrickvonplaten** [comment]
cc @williamberman

**Comment by williamberman** [comment]
hey @goodspb thank you for the report, can you open a separate issue?

**Comment by goodspb** [comment]
#2774  @williamberman thanks.

**Comment by andysingal** [comment]
> python diffusers/scripts/convert_original_controlnet_to_diffusers.py --checkpoint_path ./thibaud/controlnet-canny-sd21/canny-sd21.ckpt --original_config_file ./cldm21.yaml --image_size 768 --device mps --dump_path ./thibaud/controlnet-canny-sd21-diffusers

@tonetechnician were you able to resolve it?
