### ISSUE TITLE
UniPC solver_p function throws an error on validation steps with train_controlnet.py 

### ISSUE THREAD

**Issue by Leomn1234** [huggingface/diffusers#2700]
I notice when using the UniPC scheduler it works fine for training, but then as soon it hits the validation steps the solver_p is missing arguments which I don't know how to add. This  breaks the training, the same when you use it for regular inference. I lost the log before I decided  to post this but will try to get it again when my current model completes. I just removed solver_p for now. 

I think is something along the lines of missing (set_timesteps, noise, sample ) or very similar arguments. I'm not sure how to add these in an inference cell or the train_controlnet.py.

**Comment by patrickvonplaten** [comment]
Hey @Leomn1234, 

Could you provide a reproducible code snippet?

**Comment by Leomn1234** [comment]
Seems to work now, like I said I lost the log. I ran it again with the default settings and didn't get the same error. It seems as though solver_p is no longer in the default scheduler_config.json or I just made some mistake, but here I can show you what happens when it is, using custom config.  
from diffusers import (
    AutoencoderKL,
    ControlNetModel,
    DDPMScheduler,
    StableDiffusionControlNetPipeline,
    UNet2DConditionModel,
    EulerAncestralDiscreteScheduler,
    UniPCMultistepScheduler,
)

UN = "/content/s1/"
pipeline.scheduler = UniPCMultistepScheduler.from_config(UN)

Custom scheduler_config:
{
  "_class_name": "UniPCMultistepScheduler",
  "_diffusers_version": "0.13.0.dev0",
  "beta_end": 0.02,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.0001,
  "num_train_timesteps": 1000,
  "prediction_type": "epsilon",
  "solver_order": 2,
  "set_alpha_to_one": false,
  "steps_offset": 1,
  "thresholding": false, 
  "clip_sample": false, 
  "predict_x0": true, 
  "solver_type": "bh2",
  "disable_corrector": [0], 
  "lower_order_final": true, 
  "trained_betas": null,
  "solver_p": "EulerAncestralDiscreteScheduler"

}

Error log:
Traceback (most recent call last):
  File "/content/train_controlnet.py", line 1064, in <module>
    main(args)
  File "/content/train_controlnet.py", line 1031, in main
    log_validation(
  File "/content/train_controlnet.py", line 116, in log_validation
    image = pipeline(
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py", line 886, in __call__
    self.scheduler.set_timesteps(num_inference_steps, device=device)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/schedulers/scheduling_unipc_multistep.py", line 211, in set_timesteps
    self.solver_p.set_timesteps(num_inference_steps, device=device)
AttributeError: 'str' object has no attribute 'set_timesteps'

Seems like I reported the error wrong the first time, I guess the only issue is the set_timesteps

**Comment by wl-zhao** [comment]
The solver_p passed to the UniPCMultistepScheduler should be a scheduler instead of a string. Please first create a scheduler and then pass it to the UniPCMultistepScheduler.

**Comment by Leomn1234** [comment]
> The solver_p passed to the UniPCMultistepScheduler should be a scheduler instead of a string. Please first create a scheduler and then pass it to the UniPCMultistepScheduler.

Okay, you will have to forgive me but I am not a coder, I just learn little bits and pieces as I go. Sometimes things that may seem simple are more difficult for me. 

I tried creating an instance of the scheduler in train_dreambooth.py and passing it in the config:

EA_config = "/content/s2/"
solver_p_scheduler = EulerAncestralDiscreteScheduler.from_config(EA_config)

scheduler_config.json: "solver_p":  "solver_p_scheduler"

Ran into the same timesteps issue as before. I usually learn by example, I often read the huggingface docs but I haven't found much on solver_p. Maybe if you have a minute sometime you can provide  clearer instructions on how this function works, how to create and call the scheduler in scheduler_config.json, for airheads like me.

Thanks for all you efforts regardless.

**Comment by wl-zhao** [comment]
You can try the following steps:
1. first create the UniPC scheduler by ```unipc_scheduler = UniPCMultistepScheduler.from_config(UniPC_config)```, 
2. and then create the Euler scheduler via ```ea_scheduler = EulerAncestralDiscreteScheduler.from_config(EA_config)```
3. finally, set the solver_p of UniPC scheduler by `unipc_scheduler.solver_p = ea_scheduler `
