### ISSUE TITLE
{'norm_num_groups'} was not found in config. Values will be initialized to default values.

### ISSUE THREAD

**Issue by amine-boukriba** [huggingface/diffusers#2712]
### Describe the bug

I am trying to fine-tune a stable diffusion model on my custom dataset.
I am following Hugging face s documentation https://huggingface.co/docs/diffusers/training/text2image
I only changed the script file (you will find below my version)
for the train.py file you will find it here:https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py

### Reproduction

```
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export TRAIN_DIR="/images/metadata.jsonl"
export OUTPUT_DIR="/images/image_generation_model"

accelerate launch train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$TRAIN_DIR \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --mixed_precision="fp16" \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir=${OUTPUT_DIR}
```

### Logs

```shell
{'norm_num_groups'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 101, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Mohamed Amine\\.cache\\huggingface\\hub\\models--CompVis--stable-diffusion-v1-4\\snapshots\\249dd2d739844dea6a0bc7fc27b3c1d014720b28\\vae\\diffusion_pytorch_model.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\train_text_to_image.py", line 788, in <module>
    main()
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\train_text_to_image.py", line 402, in main
    vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae", revision=args.revision)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 571, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 106, in load_state_dict
    with open(checkpoint_file) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Mohamed Amine\\.cache\\huggingface\\hub\\models--CompVis--stable-diffusion-v1-4\\snapshots\\249dd2d739844dea6a0bc7fc27b3c1d014720b28\\vae\\diffusion_pytorch_model.bin'
Traceback (most recent call last):
  File "C:\Users\Anaconda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Anaconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\accelerate\commands\launch.py", line 915, in launch_command
    simple_launcher(args)
  File "C:\Users\Mohamed Amine\Desktop\dataset_image\assembled_dataset\venv\lib\site-packages\accelerate\commands\launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Mohamed Amine\\Desktop\\dataset_image\\assembled_dataset\\venv\\Scripts\\python.exe', 'train_text_to_image.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--train_data_dir=C:/Users/Anaconda/Library/images/metadata.jsonl', '--use_ema', '--resolution=512', '--center_crop', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--mixed_precision=fp16', '--max_train_steps=15000', '--learning_rate=1e-05', '--max_grad_norm=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--output_dir=C:/Users/Anaconda/Library/images/image_generation_model']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.9.13
- PyTorch version (GPU?): 2.0.0+cpu (False)
- Huggingface_hub version: 0.13.2
- Transformers version: 4.27.1
- Accelerate version: 0.17.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
It seems like the bug is stemming from 

```
vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae", revision=args.revision)
```

Could it be because of caching problems that were surfaced recently from `huggingface_hub` Cc: @Wauplin?

**Comment by Wauplin** [comment]
Yes that could definitely be the case, thanks for the ping @sayakpaul.

@amine-boukriba would you mind trying to upgrade huggingface_hub to it's latest version (`0.13.3` from yesterday), delete the cache folder (`"C:\\Users\\Mohamed Amine\\.cache\\huggingface\\hub\\models--CompVis--stable-diffusion-v1-4"`) and try again?

If that doesn't work, another possibility is that your Windows is detecting the file as "potential security issue" as reported by another user in https://github.com/huggingface/transformers/pull/22228#issuecomment-1476708234. In that case you can switch to using safetensors weights that are safer than pytorch bin files (`pip install safetensors`).  


Please let me know if that helps you :)

**Comment by amine-boukriba** [comment]
I disabled windows defender and deleted the cache folder and it works thanks guys
