### ISSUE TITLE
How to load checkpoint model?

### ISSUE THREAD

**Issue by 0xhelloweb3** [huggingface/diffusers#2716]
### Describe the bug

I want to load checkpoint 2000 model for space.
Here is my mode:
https://huggingface.co/ethers/avril15s02-lora-model

### Reproduction

```
import gradio as gr
gr.Interface.load("models/ethers/avril15s02-lora-model/checkpoint-2500").launch()
```
This code cannot work.

### Logs

```shell
5p86f 2023-03-17T03:35:35.758Z Fetching model from: https://huggingface.co/ethers/avril15s02-lora-model/checkpoint-2500
5p86f 2023-03-17T03:35:35.800Z Traceback (most recent call last):
5p86f 2023-03-17T03:35:35.800Z   File "app.py", line 3, in <module>
5p86f 2023-03-17T03:35:35.800Z     gr.Interface.load("models/ethers/avril15s02-lora-model/checkpoint-2500").launch()
5p86f 2023-03-17T03:35:35.800Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 99, in load
5p86f 2023-03-17T03:35:35.800Z     return super().load(name=name, src=src, api_key=api_key, alias=alias, **kwargs)
5p86f 2023-03-17T03:35:35.800Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1210, in load
5p86f 2023-03-17T03:35:35.800Z     return external.load_blocks_from_repo(name, src, api_key, alias, **kwargs)
5p86f 2023-03-17T03:35:35.800Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 70, in load_blocks_from_repo
5p86f 2023-03-17T03:35:35.800Z     blocks: gradio.Blocks = factory_methods[src](name, api_key, alias, **kwargs)
5p86f 2023-03-17T03:35:35.800Z   File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 109, in from_model
5p86f 2023-03-17T03:35:35.800Z     assert (
5p86f 2023-03-17T03:35:35.800Z AssertionError: Could not find model: ethers/avril15s02-lora-model/checkpoint-2500. If it is a private or gated model, please provide your Hugging Face access token (https://huggingface.co/settings/tokens) as the argument for the `api_key` parameter.
```

### System Info

differuser: v0.14.0

**Comment by sayakpaul** [comment]
This works:

```bash
pipe.unet.load_attn_procs("ethers/avril15s02-lora-model")
```

**Comment by patrickvonplaten** [comment]
Hey @0xhelloweb3, 

If you're trying to load from a intermediate checkpoint could you try the following:

```py
from diffusers import StableDiffusionPipeline
import torch

device = "cuda"

# load model
model_path = "ethers/avril15s02-lora-model"
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16,
    safety_checker=None,
    feature_extractor=None,
    requires_safety_checker=False
)

# load lora weights
pipe.unet.load_attn_procs(model_path, subfolder="checkpoint-2500", weight_name="pytorch_model.bin")
```

This should work :-)

**Comment by pedr0sorio** [comment]
> Hey @0xhelloweb3,
> 
> If you're trying to load from a intermediate checkpoint could you try the following:
> 
> ```python
> from diffusers import StableDiffusionPipeline
> import torch
> 
> device = "cuda"
> 
> # load model
> model_path = "ethers/avril15s02-lora-model"
> pipe = StableDiffusionPipeline.from_pretrained(
>     "CompVis/stable-diffusion-v1-4",
>     torch_dtype=torch.float16,
>     safety_checker=None,
>     feature_extractor=None,
>     requires_safety_checker=False
> )
> 
> # load lora weights
> pipe.unet.load_attn_procs(model_path, subfolder="checkpoint-2500", weight_name="pytorch_model.bin")
> ```
> 
> This should work :-)

How do i acheive the same effect but while using checkpoints from the regular finetuning script (_train_text_to_image.py_), no LoRa. I can´t find it anywhere.
