### ISSUE TITLE
Cannot Build Docs Locally on WSL2 Ubuntu

### ISSUE THREAD

**Issue by dg845** [huggingface/diffusers#2803]
### Describe the bug

I tried generating the docs locally via

```bash
doc-builder preview diffusers docs/source/en
```
after following the instructions for [generating the documentation](https://github.com/huggingface/diffusers/tree/main/docs) and the [instructions for installing Node.js v14.x](https://github.com/nodesource/distributions#using-ubuntu-3) on Ubuntu 22.04 in WSL2, and got an error. The docs cannot be viewed from [http://localhost:3000/](http://localhost:3000/).

### Reproduction

In a WSL2 Ubuntu 22.04 environment, [install Node.js v14.x](https://github.com/nodesource/distributions#using-ubuntu-3):

```bash
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - &&\
sudo apt-get install -y nodejs
```
Inside a Python environment, follow the steps to [generate the documentation](https://github.com/huggingface/diffusers/tree/main/docs):

```bash
pip install -e ".[docs]"
pip install git+https://github.com/huggingface/doc-builder
pip install watchdog
```
Finally, preview the documentation:

```bash
doc-builder preview diffusers docs/source/en
```

### Logs

```shell
Initial build docs for diffusers docs/source/en /tmp/tmp4xwqzj08/diffusers/main/en
Building the MDX files: 100%|█████████████████████████████████████████████████████████████| 130/130 [00:03<00:00, 41.72it/s]
Resolving internal links: 100%|██████████████████████████████████████████████████████████| 115/115 [00:00<00:00, 183.82it/s]
Generating frontmatter: 100%|███████████████████████████████████████████████████████████| 115/115 [00:00<00:00, 1250.09it/s]
Installing node dependencies

Watching for changes in: /home/tamamo/code/diffusers

npm ERR! Cannot read property 'js-yaml' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tamamo/.npm/_logs/2023-03-24T03_30_03_338Z-debug.log
Exception in thread Thread-2 (start_sveltekit_dev):
Traceback (most recent call last):
  File "/home/tamamo/miniconda3/envs/diffusers-dev/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tamamo/miniconda3/envs/diffusers-dev/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tamamo/miniconda3/envs/diffusers-dev/lib/python3.10/site-packages/doc_builder/commands/preview.py", line 133, in start_sveltekit_dev
    subprocess.run(
  File "/home/tamamo/miniconda3/envs/diffusers-dev/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['npm', 'ci']' returned non-zero exit status 1.
```

NPM logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'ci' ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose npm-session 6dd331b77c400f52
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /tmp/tmp4xwqzj08/kit
8 verbose prepare using package-lock.json
9 verbose checkLock verifying package-lock data
10 verbose teardown shutting down workers.
11 info teardown Done in 0s
12 verbose stack TypeError: Cannot read property 'js-yaml' of undefined
12 verbose stack     at /usr/lib/node_modules/npm/node_modules/lock-verify/index.js:27:40
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at /usr/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25
13 verbose cwd /tmp/tmp4xwqzj08/kit
14 verbose Linux 5.15.90.1-microsoft-standard-WSL2
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci"
16 verbose node v14.21.3
17 verbose npm  v6.14.18
18 error Cannot read property 'js-yaml' of undefined
19 verbose exit [ 1, true ]
```

### System Info

- `diffusers` version: 0.15.0.dev0
- Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.13.3
- Transformers version: 4.26.1
- Accelerate version: 0.16.0
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

(the Ubuntu version is Ubuntu 22.04.1 LTS)

**Comment by sayakpaul** [comment]
@mishig25 could you look into it?

**Comment by patrickvonplaten** [comment]
Thanks for the issue @dg845, this might also be better suited in https://github.com/huggingface/doc-builder maybe?

**Comment by dg845** [comment]
Would it be better if I made an issue in the [`doc-builder`](https://github.com/huggingface/doc-builder) repository (and possibly close this one)?

**Comment by sayakpaul** [comment]
I think so, yes.

**Comment by sayakpaul** [comment]
Closing this here. Feel free to re-open.

**Comment by dg845** [comment]
Created an issue at [doc-builder #363](https://github.com/huggingface/doc-builder/issues/363).
