### ISSUE TITLE
Can't convert a sd model to diffusers

### ISSUE THREAD

**Issue by 0n0gard** [huggingface/diffusers#2856]
When I use the script to convert a sd model to diffusers:
`python diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./AOM3_orangemixs.safetensors --extract_ema --dump_path AbyssOrangeMix --from_safetensors`

I got this error:
```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "E:\tools\diffusers\scripts\convert_original_stable_diffusion_to_diffusers.py", line 128, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "D:\App\miniconda\envs\aigc\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1042, in download_from_original_stable_diffusion_ckpt
    raise ValueError(BACKENDS_MAPPING["safetensors"][1])
KeyError: 'safetensors'
```

Could someone help me?
Any help is appreciated!!!

**Comment by 0n0gard** [comment]
I solved this by `pip install safetensors `
🤣🤣🤣
