### ISSUE TITLE
PackageNotFoundError: No package metadata was found for bitsandbytes

### ISSUE THREAD

**Issue by EnricoBeltramo** [huggingface/diffusers#3194]
### Describe the bug

I have a working configuration to load a text2img diffuser model with diffuser 0.12.1.
When I switch of diffuser version >= 0.13.0, I have an error:
PackageNotFoundError: No package metadata was found for bitsandbytes

Some dependencies are changed?

### Reproduction

- a working configuration for 0.12.1
- switch to version >= 0.13.0
- load model "runwayml/stable-diffusion-v1-5

### Logs

```shell
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py:381 in from_name           │
│                                                                                                  │
│   378 │   │   if not name:                                                                       │
│   379 │   │   │   raise ValueError("A distribution name is required.")                           │
│   380 │   │   try:                                                                               │
│ ❱ 381 │   │   │   return next(cls.discover(name=name))                                           │
│   382 │   │   except StopIteration:                                                              │
│   383 │   │   │   raise PackageNotFoundError(name)                                               │
│   384                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
StopIteration

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /tmp/ipykernel_72/4245135796.py:2 in <module>                                                    │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_72/4245135796.py'                           │
│                                                                                                  │
│ /tmp/ipykernel_72/36998241.py:86 in loadModelText2Img                                            │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_72/36998241.py'                             │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.py:1037 in             │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1034 │   │                                                                                     │
│   1035 │   │   Args:                                                                             │
│   1036 │   │   │   slice_size (`str` or `int`, *optional*, defaults to `"auto"`):                │
│ ❱ 1037 │   │   │   │   When `"auto"`, halves the input to the attention heads, so attention wil  │
│   1038 │   │   │   │   `"max"`, maxium amount of memory will be saved by running only one slice  │
│   1039 │   │   │   │   provided, uses as many slices as `attention_head_dim // slice_size`. In   │
│   1040 │   │   │   │   must be a multiple of `slice_size`.                                       │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.py:445 in              │
│ load_sub_model                                                                                   │
│                                                                                                  │
│    442 │   │   │   │   To have Accelerate compute the most optimized `device_map` automatically  │
│    443 │   │   │   │   more information about each option see [designing a device                │
│    444 │   │   │   │   map](https://hf.co/docs/accelerate/main/en/usage_guides/big_modeling#des  │
│ ❱  445 │   │   │   low_cpu_mem_usage (`bool`, *optional*, defaults to `True` if torch version >  │
│    446 │   │   │   │   Speed up model loading by not initializing the weights and only loading   │
│    447 │   │   │   │   also tries to not use more than 1x model size in CPU memory (including p  │
│    448 │   │   │   │   model. This is only supported when torch version >= 1.9.0. If you are us  │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py:2177 in from_pretrained    │
│                                                                                                  │
│   2174 │   │   use_safetensors = kwargs.pop("use_safetensors", None if is_safetensors_available  │
│   2175 │   │                                                                                     │
│   2176 │   │   if is_bitsandbytes_available():                                                   │
│ ❱ 2177 │   │   │   is_8bit_serializable = version.parse(importlib_metadata.version("bitsandbyte  │
│   2178 │   │   else:                                                                             │
│   2179 │   │   │   is_8bit_serializable = False                                                  │
│   2180                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py:832 in version             │
│                                                                                                  │
│   829 │   :return: The version string for the package as defined in the package's                │
│   830 │   │   "Version" metadata key.                                                            │
│   831 │   """                                                                                    │
│ ❱ 832 │   return distribution(distribution_name).version                                         │
│   833                                                                                            │
│   834                                                                                            │
│   835 _unique = functools.partial(                                                               │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py:805 in distribution        │
│                                                                                                  │
│   802 │   :param distribution_name: The name of the distribution package as a string.            │
│   803 │   :return: A ``Distribution`` instance (or subclass thereof).                            │
│   804 │   """                                                                                    │
│ ❱ 805 │   return Distribution.from_name(distribution_name)                                       │
│   806                                                                                            │
│   807                                                                                            │
│   808 def distributions(**kwargs):                                                               │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py:383 in from_name           │
│                                                                                                  │
│   380 │   │   try:                                                                               │
│   381 │   │   │   return next(cls.discover(name=name))                                           │
│   382 │   │   except StopIteration:                                                              │
│ ❱ 383 │   │   │   raise PackageNotFoundError(name)                                               │
│   384 │                                                                                          │
│   385 │   @classmethod                                                                           │
│   386 │   def discover(cls, **kwargs):                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PackageNotFoundError: No package metadata was found for bitsandbytes
```

### System Info

- `diffusers` version: 0.13.0
- Platform: Linux-5.15.90+-x86_64-with-debian-bullseye-sid
- Python version: 3.7.12
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: 0.0.16
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: NO

**Comment by EnricoBeltramo** [comment]
I fixed with a little workaround. 
In my env I use dreambooth too, and to let it work I need to specify the cuda version i.e.:
pip install bitsandbytes-cuda110
this wasn't an issue for diffuser 0.12 but raise an error on >=0.13

At moment I fixed installing both version of bitsandbytes:
pip install bitsandbytes-cuda110 bitsandbytes

There are a better solution?

**Comment by vladimircape** [comment]
also have such problem

**Comment by liu906** [comment]
same issue.


(llama) lxt@amax:/data/lxt$ python trl/examples/scripts/sft.py     --model_name meta-llama/Llama-2-7b-hf     --dataset_name timdettmers/openassistant-guanaco     --load_in_4bit     --use_peft     --batch_size 4     --gradient_accumulation_steps 2
Traceback (most recent call last):
  File "/data/lxt/trl/examples/scripts/sft.py", line 87, in <module>
    quantization_config = BitsAndBytesConfig(
  File "/data/lxt/miniconda/envs/llama/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 212, in __init__
    self.post_init()
  File "/data/lxt/miniconda/envs/llama/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 238, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
  File "/data/lxt/miniconda/envs/llama/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/data/lxt/miniconda/envs/llama/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/data/lxt/miniconda/envs/llama/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes

**Comment by patrickvonplaten** [comment]
Can someone add a link to a google colab that reproduces this issue? I'm using PyPI (and not `conda`) and have Pytorch 2.x installed. I cannot reproduce the issue

**Comment by chiragjn** [comment]
I think it does not matter now because `bitsandbytes` ships with libs for all cuda versions and one is picked according to whatever torch is using or installed on the system. So practically `bitsandbytes-cuxxx` packages are no longer needed

**Comment by RyanKoech** [comment]
@patrickvonplaten Experiencing it running [this](https://github.com/suryanshgupta9933/Law-GPT/tree/main) repo.

**Comment by VikramTiwari** [comment]
Experiencing it while trying to run this finetuning example: https://huggingface.co/blog/g-ronimo/phinetuning

I have created a small sample colab for folks to repro: https://colab.research.google.com/drive/1e3vfyQx8HCnAiYpmzaca7xH545uvtCC9?usp=sharing

**Comment by ahyunsoo3** [comment]
@VikramTiwari You can easily solve the problem by installing.

`pip install bitsandbytes`

I think the unfamiliar error message confused people.

**Comment by TanetiSanjay** [comment]
Try using 
```
pip install bitsandbyes
```
I ran through the same error and this command fixed the errors for me

**Comment by Shorya22** [comment]
Hello All,

I have done a simple project which is Text Summarization and I used T5 Model and I successfully fine tuned my model and also inference it on notebook.i have installed bitsandbytes, accelerate,trl and all.

But when push it on hugginface and inference it on server less API. I get error "No package metadata was found for bitsandbytes".

Please suggest me how I can resolve this issue.

**Comment by UnauthorizedShelley** [comment]
> Try using
> 
> ```
> pip install bitsandbytes
> ```
> 
> I ran through the same error and this command fixed the errors for me

I don't know why but this really works!!!

**Comment by Shorya22** [comment]
Yes because we need to install bitsandbytes then only we can use
Quantization in LLM.

**Comment by Heinrich-XIAO** [comment]
For me, it says 
```
Traceback (most recent call last):
  File "/home/heinzketchup/Documents/manim_gen/test.py", line 4, in <module>
    model = AutoModelForCausalLM.from_pretrained("thanhkt/codegemma-7B-ManimGen")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heinzketchup/Documents/manim_gen/.env/lib64/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heinzketchup/Documents/manim_gen/.env/lib64/python3.12/site-packages/transformers/modeling_utils.py", line 3657, in from_pretrained
    hf_quantizer.validate_environment(
  File "/home/heinzketchup/Documents/manim_gen/.env/lib64/python3.12/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 74, in validate_environment
    raise ImportError(
ImportError: Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`
```

And when I go to update, it can't find updates. It tells me to update pip, and after doing so, it still can't find the update.

**Comment by Shorya22** [comment]
Yes install bitsandbytes using pip

**Comment by charchit7** [comment]
for me this issue was there when I was installing via conda.

**Comment by Heinrich-XIAO** [comment]
I don't have anaconda installed on my system. And I used pip. Was I supposed to `dnf install python3-bitsandbytes`

**Comment by Tanish-0001** [comment]
Still getting this issue despite installing bitsandbytes via pip

**Comment by blx0102** [comment]
Already pip install -U bitsandbytes, but still got the `ImportError: Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`` error

**Comment by lepotatoguy** [comment]
> pip install bitsandbytes

This works.
