### ISSUE TITLE
AttributeError: 'StableDiffusionControlNetPipeline' object has no attribute 'enable_vae_tiling'

### ISSUE THREAD

**Issue by alejobrainz** [huggingface/diffusers#3202]
### Describe the bug

I am trying to enable vae tiling an a Control Net Pipeline but get this issue.  This option seems to work on StableDiffusionPipeline but does not on ControlNetPipeline.  Please advice.

### Reproduction

```
pipeline = StableDiffusionControlNetPipeline.from_pretrained(models[model_index]["path"], torch_dtype=torch.float16,)
cached_pipeline.enable_vae_tiling()
cached_pipeline.enable_xformers_memory_efficient_attention()
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/AI-Spaces-Server/app.py", line 65, in panorama
    info = run_panorama(prompt, space, weight, style, model, num_images, width, seed, cfg_scale, sampling_steps, image_quality, image, url)
  File "/home/ubuntu/AI-Spaces-Server/common.py", line 46, in run_panorama
    images, info, seeds, error = inference.render(**args)
  File "/home/ubuntu/AI-Spaces-Server/inference.py", line 31, in render
    pipe = load_model(
  File "/home/ubuntu/AI-Spaces-Server/models.py", line 94, in load_model
    cached_pipeline.enable_vae_tiling()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionControlNetPipeline' object has no attribute 'enable_vae_tiling'
```

### System Info

diffusers 0.15.0
ubuntu linux

**Comment by init-22** [comment]
@alejobrainz I will look into this, but for that can you please share what's in models[model_index]["path"] and what is cached_pipeline?

**Comment by alejobrainz** [comment]
Ah sure.  Sorry about that!    Here is a minimal repro code:

```
import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel

control_net_model = ControlNetModel.from_pretrained("./models/controlnet-depth/", torch_dtype=torch.float16) 
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet = control_net_model
    torch_dtype=torch.float16,
)
pipe.enable_vae_tiling()
pipe.enable_xformers_memory_efficient_attention()
```
This generates the following error:

`AttributeError: 'StableDiffusionControlNetPipeline' object has no attribute 'enable_vae_tiling'. Did you mean: 'enable_vae_slicing'?`

If you try to do this with a Stable Diffusion pipeline ( non control net), it works:

```
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
)
pipe.enable_vae_tiling()
pipe.enable_xformers_memory_efficient_attention()
```

**Comment by init-22** [comment]
@alejobrainz You are correct enable_vae_tiling and disable_vae_tiling functions are not present, I will create a PR to add them @yiyixuxu

**Comment by alejobrainz** [comment]
I just tried it and it works great!  Memory consumption was reduced significantly when inferring a large 2048x1024 image using a control net.  Thanks.

**Comment by yiyixuxu** [comment]
thanks @init-22! 

Closing this issue since the PR is merged
