### ISSUE TITLE
AttributeError: 'StableDiffusionMegaPipeline' object has no attribute 'requires_safety_checker'

### ISSUE THREAD

**Issue by KevinColemanInc** [huggingface/diffusers#3211]
### Describe the bug

Sample code in the readme throws an error

[stable_diffusion_mega](https://github.com/huggingface/diffusers/blob/7e6886f5e93ca9bb1e6d4beece46fe1e43b819c2/examples/community/README.md#stable-diffusion-mega)

AttributeError: 'StableDiffusionMegaPipeline' object has no attribute 'requires_safety_checker'

### Reproduction

Run the sample code in the readme. I changed the pipeline to use `mips`, b/c I have an m1

```
pipe.to("mps")
pipe.enable_attention_slicing()
```

### Logs

```shell
/opt/homebrew/Caskroom/miniforge/base/envs/replate_env/lib/python3.10/site-packages/huggingface_hub/file_download.py:637: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
vae/diffusion_pytorch_model.safetensors not found
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
/opt/homebrew/Caskroom/miniforge/base/envs/replate_env/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/kevin/projects/replate/py/inpaintdenoisemega.py:14 in <module>                            │
│                                                                                                  │
│   11 │   return PIL.Image.open(BytesIO(response.content)).convert("RGB")                         │
│   12                                                                                             │
│   13 pipe = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", custom_pipeli    │
│ ❱ 14 pipe.to("mps")                                                                              │
│   15 # pipe.enable_attention_slicing()                                                           │
│   16                                                                                             │
│   17                                                                                             │
│                                                                                                  │
│ /opt/homebrew/Caskroom/miniforge/base/envs/replate_env/lib/python3.10/site-packages/diffusers/pi │
│ pelines/pipeline_utils.py:623 in to                                                              │
│                                                                                                  │
│    620 │   │                                                                                     │
│    621 │   │   # .to("cuda") would raise an error if the pipeline is sequentially offloaded, so  │
│    622 │   │   pipeline_is_sequentially_offloaded = any(                                         │
│ ❱  623 │   │   │   module_is_sequentially_offloaded(module) for _, module in self.components.it  │
│    624 │   │   )                                                                                 │
│    625 │   │   if pipeline_is_sequentially_offloaded and torch.device(torch_device).type == "cu  │
│    626 │   │   │   raise ValueError(                                                             │
│                                                                                                  │
│ /Users/kevin/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_mega.py:94 in     │
│ components                                                                                       │
│                                                                                                  │
│    91 │                                                                                          │
│    92 │   @property                                                                              │
│    93 │   def components(self) -> Dict[str, Any]:                                                │
│ ❱  94 │   │   return {k: getattr(self, k) for k in self.config.keys() if not k.startswith("_")   │
│    95 │                                                                                          │
│    96 │   def enable_attention_slicing(self, slice_size: Optional[Union[str, int]] = "auto"):    │
│    97 │   │   r"""                                                                               │
│                                                                                                  │
│ /Users/kevin/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_mega.py:94 in     │
│ <dictcomp>                                                                                       │
│                                                                                                  │
│    91 │                                                                                          │
│    92 │   @property                                                                              │
│    93 │   def components(self) -> Dict[str, Any]:                                                │
│ ❱  94 │   │   return {k: getattr(self, k) for k in self.config.keys() if not k.startswith("_")   │
│    95 │                                                                                          │
│    96 │   def enable_attention_slicing(self, slice_size: Optional[Union[str, int]] = "auto"):    │
│    97 │   │   r"""                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionMegaPipeline' object has no attribute 'requires_safety_checker'
```

### System Info

```
- `diffusers` version: 0.15.0
- Platform: macOS-13.3.1-arm64-arm-64bit
- Python version: 3.10.10
- PyTorch version (GPU?): 2.1.0.dev20230415 (False)
- Huggingface_hub version: 0.13.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by yiyixuxu** [comment]
@williamberman 
is this also related to https://github.com/huggingface/diffusers/issues/3199#issuecomment-1518739355 ?

**Comment by nickkolok** [comment]
Everything is broken again, see #3199 
```
/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py:645: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(

Downloading (…)_stable_diffusion.py:   0%|          | 0.00/10.5k [00:00<?, ?B/s]Could not locate the pipeline.py inside lpw_stable_diffusion.
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "/home/user/.local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 856, in from_pretrained
    cached_folder = cls.download(
  File "/home/user/.local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1227, in download
    pipeline_class = _get_pipeline_class(
  File "/home/user/.local/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 335, in _get_pipeline_class
    return get_class_from_dynamic_module(
  File "/home/user/.local/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py", line 445, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/user/.local/lib/python3.8/site-packages/diffusers/utils/dynamic_modules_utils.py", line 285, in get_cached_module_file
    resolved_module_file = cached_download(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 788, in cached_download
    http_get(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 543, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 10495 but has size 57300 ((…)_stable_diffusion.py).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

Downloading (…)_stable_diffusion.py: 57.3kB [00:00, 502kB/s]        
```

```
pipe = DiffusionPipeline.from_pretrained(
    model_name,
    custom_pipeline="lpw_stable_diffusion",
    custom_revision='0.15.1',
    torch_dtype=torch.float32
)
```

**Comment by nickkolok** [comment]
Looks like downloading any executable code from github on the fly is a very, very, very bad idea! Instead, if we want the community pipelines to be distributed separately, we should create a PyPI package named `diffusers-community-pipelines` with the same version numbers as the main `diffusers` package. That's totally insane that the library downloads some code on demand! I can (still hardly) understand that for models, but pipelines? Really? (However, it would be really great to be able to download the required models - if they are known - in advance...)
By the idea and common sense, a software for turning prompts into images is self-sufficient as offline software. Once properly installed, it should not be dependent on Internet connection.

**Comment by nickkolok** [comment]
> @nickkolok
> 
> Can we have a separate issue, please? you already used `custom_revision` so the error is probably not related to version mismatch

Thank you for your advice! Here you are: #3213

**Comment by patrickvonplaten** [comment]
Closing to continue discussion on #3213

**Comment by yiyixuxu** [comment]
@patrickvonplaten 

but I asked them to open a separate issue because it's not related to this one
maybe we shouldn't close this issue 😂
