### ISSUE TITLE
train_dreambooth_lora.py resume from checkpoint errors.

### ISSUE THREAD

**Issue by JaLnYn** [huggingface/diffusers#3279]
### Describe the bug

I get the following issue when trying to resume from checkpoint. 
`KeyError: 'unet.down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor'`
There was also a naming issue where I had to change pytorch_lora_weights.bin to pytorch_model.bin in the checkpoint folders

### Reproduction

accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=100 \
  --learning_rate=1e-4 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=50 \
  --seed="0" \
  --push_to_hub \
  --resume_from_checkpoint="<checkpoint folder>" \

### Logs

```shell
(most recent call last):
  File "/home/rip/git/diffusers/examples/dreambooth/train_dreambooth_lora.py", line 1093, in <module>
    main(args)
  File "/home/rip/git/diffusers/examples/dreambooth/train_dreambooth_lora.py", line 881, in main
    accelerator.load_state(os.path.join(args.output_dir, path))
  File "/home/rip/.local/lib/python3.11/site-packages/accelerate/accelerator.py", line 2396, in load_state
    load_accelerator_state(
  File "/home/rip/.local/lib/python3.11/site-packages/accelerate/checkpointing.py", line 140, in load_accelerator_state
    models[i].load_state_dict(torch_mod, **load_model_func_kwargs)
  File "/home/rip/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2027, in load_state_dict
    load(self, state_dict)
  File "/home/rip/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2009, in load
    module._load_from_state_dict(
  File "/home/rip/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1909, in _load_from_state_dict
    hook(state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/rip/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 69, in __call__
    return self.hook(module, *args, **kwargs)
  File "/home/rip/git/diffusers/src/diffusers/loaders.py", line 84, in map_from
    new_key = key.replace(replace_key, f"layers.{module.rev_mapping[replace_key]}")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'unet.down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor'
```

### System Info

- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.11.3
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.14.0
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by JaLnYn** [comment]
I've added ` replace_key = replace_key.replace('unet.', ''") ` to diffusers/src/diffusers/loaders.py:84 and now I get this error:

`Missing key(s) in state_dict: "layers.0.to_q_lora.down.weight", "layers.0.to_q_lora.up.weight", "layers.0.t...`
`Unexpected kiy(s) in state_dico: "unet.layers.0."o_q_aora.down.weight", "unet.layers.0.to_q_lora.up.weight", "unet.`

**Comment by JaLnYn** [comment]
I've added new_key = new_key.replace('unet.', ''") to diffusers/src/diffusers/loaders.py:86 and now I get this error:
```
raceback (most recent call last):                                                                                                                                                          File "/home/rip/git/diffusers/examples/dreambooth/train_dreambooth_lora.py", line 1093, in <module>                                                                                         main(args)                                                                                                                                                                              File "/home/rip/git/diffusers/examples/dreambooth/train_dreambooth_lora.py", line 881, in main                                                                                          
    accelerator.load_state(os.path.join(args.output_dir, path))
  File "/home/rip/.local/lib/python3.11/site-packages/accelerate/accelerator.py", line 2396, in load_state                                                                                    load_accelerator_state(                                                                                                                                                                 File "/home/rip/.local/lib/python3.11/site-packages/accelerate/checkpointing.py", line 145, in load_accelerator_state                                                                   
    optimizers[i].load_state_dict(torch.load(input_optimizer_file, map_location="cpu")) 
```

**Comment by JaLnYn** [comment]
Removed previous 2 changes because `accelerator.load_state(os.path.join(args.output_dir, path))` is not the correct approach for loading lora wieghts. Attempting to modify unet variable

**Comment by fractaldna22** [comment]
im getting the same error after it worked the first time, trained with lora layers as the processor, saved the pipeline as normal, then the next time i try to load it says key error. 

```
  text_encoder = CLIPTextModel.from_pretrained(
        args.pretrained_model_name_or_path,
        subfolder="text_encoder",
        revision=args.revision,
    )
    vae = AutoencoderKL.from_pretrained(
        args.pretrained_model_name_or_path,
        subfolder="vae",
        revision=args.revision,
    )
    unet = UNet2DConditionModel.from_pretrained(
        args.pretrained_model_name_or_path,
        subfolder="unet",
        revision=args.revision,
        torch_dtype=torch.float32
    )
######################################
File "/content/diffusers/src/diffusers/models/modeling_utils.py", line 602, in from_pretrained
    if empty_state_dict[param_name].shape != param.shape:
KeyError: 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight'
```
I take this to mean that the last 2 hours of training i did is now trashed.

**Comment by patrickvonplaten** [comment]
I cannot reproduce this error cc @sayakpaul maybe also for visibility

**Comment by JaLnYn** [comment]
I think the issue is related to me setting the fp16 in the accelerate config. I'm also not sure how to cc...

**Comment by JaLnYn** [comment]
> I cannot reproduce this error cc @sayakpaul maybe also for visibility

This line should require, optimizer and other accelerate.load_state files, Using the default lora saves, it only saves the lora_wieghts.bin. I think if you're using the newest train_dreambooth_lora file you should run into this error
` 876              accelerator.load_state(os.path.join(args.output_dir, path)) `

**Comment by sayakpaul** [comment]
Hmm, I think the resuming logic needs to be modified for LoRA training examples. I don't think it's related to FP16. Cc: @williamberman any suggestions on how to best approach this?

**Comment by JaLnYn** [comment]
> Hmm, I think the resuming logic needs to be modified for LoRA training examples. I don't think it's related to FP16. Cc: @williamberman any suggestions on how to best approach this?

I attempted to add
unet.load_attn_procs(path to weights) to line 872 
But get gradient clipping error, which I found might be because of I need to convert fp16 to fp32 after reading a few posts online.

I also attempted to replace 709 - 727 with

**Comment by JaLnYn** [comment]
Accidentally closed

**Comment by markrmiller** [comment]
>  I don't think it's related to FP16.

I don't think it is either, and I don't think it's quite as simple as just using the standard way to load lora weights.

I believe when it saves the checkpoints, it writes some kind of semi-bespoke format to store both unet and text_encoder weights in one file I think, and accelerator.load_state has no clue about it. I think there is loader for it on a pipeline, so you can load it for inference, and I've tried to grab the models off that and I've tried to massage the weight names correctly, but some minor detail kept remaining elusive as I went and I so I stopped.

**Comment by sayakpaul** [comment]
Thanks for sharing your findings. Yeah, we need to look deeper into resuming from a checkpoint when doing LoRA. Let's wait for @williamberman's comments.

**Comment by JaLnYn** [comment]
It's not a fp16 problem, I converted to fp32 and got dtype mismatch.

**Comment by fractaldna22** [comment]
I found that when it saves the Lora weights as weights.bin, it is saving a
state dict that begins the name of every parameter with "unet."
 "unet.down_blocks.attn.transformer" etc.  It is necessary when saving, or
when loading this statedict into attention processor to drop the "unet.",
because it is looking for

"down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight"

not
"unet.down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight"

one possible work around would be this function i just made (untested. but
Bing and ChatGPT say its good. I just wrote the part that creates the new
dict with the "unet" removed from the keys.

```python

def load_lora(path: str, unet=None, save_new: bool = True) -> dict:
    """
    Load a torch file from the given path and return a dictionary
containing the loaded data.

    Args:
        path (str): The path of the torch file to load.
        unet (object): An optional object with a load_attn_procs method.
        save_new (bool): Whether to save the loaded data to a new file.

    Returns:
        dict: A dictionary containing the loaded data.
    """
    try:
        # Load the torch file from the given path
        with open(path, 'rb') as f:
            procs = torch.load(f, map_location=torch.device('cuda'))

        # Extract the 'unet' key from procs and store it in a new dictionary
        new_procs = {}
        for key, value in procs.items():
            if key.startswith("unet"):
                s = key.partition(".")[2]
                new_procs[s] = value
            else:
                new_procs[key] = value

        # Save the new dictionary to a new file if save_new is True
        if save_new:
            with open(f'{path}.2.bin', 'wb') as f:
                torch.save(new_procs, f)

        # Call the load_attn_procs method of unet with the new
dictionary if unet is not None
        if unet is not None:
            unet.load_attn_procs(new_procs)

        return new_procs

    except Exception as e:
        print(f"Error loading {path}: {e}")
```

**Comment by fractaldna22** [comment]
I found that when it saves the Lora weights as weights.bin, it is saving a
state dict that begins the name of every parameter with "unet."
 "unet.down_blocks.attn.transformer" etc.  It is necessary when saving, or
when loading this statedict into attention processor to drop the "unet.",
because it is looking for

"down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight"

not
"unet.down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight"

one possible work around would be this function i just made (untested. but
Bing and ChatGPT say its good. I just wrote the part that creates the new
dict with the "unet" removed from the keys.

```py

def load_lora(path: str, unet=None, save_new: bool = True) -> dict:
    """
    Load a torch file from the given path and return a dictionary
containing the loaded data.

    Args:
        path (str): The path of the torch file to load.
        unet (object): An optional object with a load_attn_procs method.
        save_new (bool): Whether to save the loaded data to a new file.

    Returns:
        dict: A dictionary containing the loaded data.
    """
    try:
        # Load the torch file from the given path
        with open(path, 'rb') as f:
            procs = torch.load(f, map_location=torch.device('cuda'))

        # Extract the 'unet' key from procs and store it in a new dictionary
        new_procs = {}
        for key, value in procs.items():
            if key.startswith("unet"):
                s = key.partition(".")[2]
                new_procs[s] = value
            else:
                new_procs[key] = value

        # Save the new dictionary to a new file if save_new is True
        if save_new:
            with open(f'{path}.2.bin', 'wb') as f:
                torch.save(new_procs, f)

        # Call the load_attn_procs method of unet with the new
dictionary if unet is not None
        if unet is not None:
            unet.load_attn_procs(new_procs)

        return new_procs

    except Exception as e:
        print(f"Error loading {path}: {e}")
```

**Comment by fractaldna22** [comment]
Although, I save as  .pt, not "bin" so i dont know if the same torch.load / save applies to .bin. let me know if it works.

**Comment by JaLnYn** [comment]
> because it is looking for
> "down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor.to_q_lora.down.weight"

How did you get this?

**Comment by fractaldna22** [comment]
That would be from loading the weights with 

```python
lora_weights = torch.load(filepath, 'cuda')
#returns a dict
#empty = {}
for key, value in lora_weights.items()
    print(key)
    #key = key.partition(".")[2] #to split it at the first decimal point between 'unet', '.' , 'rest_of_string'
    #empty[key] = value  #empty is the weights without the 'unet' at the start of each parameter. 
```
although now that i see your first post, in your error it actually already included 'unet' in the KeyError, which i thinks means it could possibly mean it is actually looking for , it IS looking for a key that begins with 'unet' as in  'unet.down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor', but was unable to find a key with that name.  Maybe yours are missing the unet, or maybe your keys have another additional word like 'model.unet.down_blocks...' but was only looking for ones named unet.down_blocks.0 etc. 

For my case it was looking for 'down_blocks.0.attentions.0.transformer_blocks.0.attn1.processor' but got ones starting with 'unet'.   I confirmed that by printing each key and comparing it to the key in the key error and figured out that by splitting it at the first '.' and only using the ('unet', '.', 'remaining key)[2] ## or -1, ended up making it work. 

Once you get the key names to match in the new dict, you can load that directly into the unet like this
unet.load_attn_procs(new_dict)

the resulting attention_processor in the unet will be the loaded lora weights..  

i think the cause of this bug is from saving the model while its loaded into a "pipeline" instead of by itself. If it loaded the lora_weights as a solo unet, or created the lora weights separately and added it into the solo unet, but then unfold the unet into the diffuser pipeline before saving it, the key names in the lora dict might not be updating with the fact its in a new pipeline context and thus when you go to load the weights its all messed up. 

a possible idea (im no expert) is saving the lora_weights and loading them only when the unet is solo, like 

```python
pipelines.from_pretrained(model_folder_or_path_or_dict).to(device)
unet = pipelines.unet
unet.load_attn_procs(lora_weights_dict_or_path)# the torch.load('lora_weights.bin'))  
#and
unet.save_attn_procs(path)
pipeline.unet = unet 
```
However, before all that id just print those keys and see what keys it did actually save

**Comment by patrickvonplaten** [comment]
I can reproduce the error here - looking into it

**Comment by patrickvonplaten** [comment]
Working on a fix: https://github.com/huggingface/diffusers/pull/3353 . Hope to be done by Monday

**Comment by actionless** [comment]
> AssertionError: No inf checks were recorded for this optimizer.

i can still reproduce it when loading checkpoint in train_lora

**Comment by DStarEpoch** [comment]
> > AssertionError: No inf checks were recorded for this optimizer.
> 
> i can still reproduce it when loading a trained (with the same version of the script) checkpoint in `train_dreambooth_lora.py` (using latest git version)

I can also got this error with latest version script, when resume from checkpoint, have you solve this?

**Comment by sayakpaul** [comment]
We have made a couple of fixes here so, we should be good here. @williamberman as well.

**Comment by kosukekurimoto** [comment]
I can also got this error with latest version script, when resume from checkpoint.

!accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --pretrained_vae_model_name_or_path=$VAE_PATH \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --instance_prompt="XXXX style" \
  --class_prompt="style" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-5 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=5000 \
  --validation_prompt="a illustration of a woman" \
  --validation_epochs=25 \
  --resume_from_checkpoint="latest" \
  --seed="0"

Steps:  70% 3500/5000 [00:02<?, ?it/s, loss=0.0251, lr=1e-5]Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1372, in <module>
    main(args)
  File "/content/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1164, in main
    optimizer.step()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/optimizer.py", line 132, in step
    self.scaler.step(self.optimizer, closure)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py", line 413, in step
    len(optimizer_state["found_inf_per_device"]) > 0
AssertionError: No inf checks were recorded for this optimizer.
Steps:  70% 3500/5000 [00:03<?, ?it/s, loss=0.0251, lr=1e-5]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=/content/drive/Shareddrives/XXXX/train-images', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--output_dir=/content/drive/Shareddrives/XXXX/output', '--mixed_precision=fp16', '--instance_prompt=ausantacm style', '--class_prompt=style', '--resolution=1024', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--learning_rate=1e-5', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=5000', '--validation_prompt=a illustration of a woman', '--validation_epochs=25', '--resume_from_checkpoint=latest', '--seed=0']' returned non-zero exit status 1.

**Comment by sayakpaul** [comment]
Can you check if going back to a previous version of `accelerate` helps solve the issue? If so, could you open a new issue on `accelerate`?
