### ISSUE TITLE
Diffusers on HuggingFace are broken

### ISSUE THREAD

**Issue by dpyy** [huggingface/diffusers#3300]
### Describe the bug

Diffusers broken

### Reproduction

pipe = DiffusionPipeline.from_pretrained(
        pretrained_model_name_or_path=model,
        safety_checker=None,
        custom_pipeline="lpw_stable_diffusion",
    )

### Logs

```shell
Traceback (most recent call last):
  File "/src/script/download-weights", line 20, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 528, in from_pretrained
    pipeline_class = get_class_from_dynamic_module(
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/diffusers/dynamic_modules_utils.py", line 456, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/site-packages/diffusers/dynamic_modules_utils.py", line 163, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/root/.pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion.py", line 13, in <module>
    from diffusers.image_processor import VaeImageProcessor
ModuleNotFoundError: No module named 'diffusers.image_processor'
ⅹ exit status 1
```

### System Info

Latest version

**Comment by patrickvonplaten** [comment]
Hey @dpyy, 

Please attach a reproducible code snippet. We cannot run:

```py
pipe = DiffusionPipeline.from_pretrained(
pretrained_model_name_or_path=model,
safety_checker=None,
custom_pipeline="lpw_stable_diffusion",
)
```

You can probably fix your problem by updating `diffusers`:

```
pip install --upgrade diffusers
```

**Comment by dpyy** [comment]
@patrickvonplaten any ideas?

**Comment by yiyixuxu** [comment]
@dpyy I think this might be related https://github.com/huggingface/diffusers/issues/3213#event-9156536022

it is a bug in hub `0.14.0`, you need to make sure  `huggingface_hub>=0.14.1`

**Comment by patrickvonplaten** [comment]
hmmm @dpyy, if you have `diffusers >= 0.16.0` this problem should not happen anymore (also cannot reproduce it sadly). Could you maybe try reproducing it in a google colab and share here?
