### ISSUE TITLE
Problem with img2img & text guided inpainting

### ISSUE THREAD

**Issue by KevinGoodman** [huggingface/diffusers#337]
### Describe the bug

When I try img2img & text guided inpainting，I got the same problems as follows. The text to image code works perfectly in the same environment. 

### Reproduction
I git clone this repo and run the image_to_image.py as follows:
```python
from torch import autocast
import requests
import torch
from PIL import Image
from io import BytesIO

from src.diffusers import StableDiffusionImg2ImgPipeline

# load the pipeline
device = "cuda"
model_id_or_path = "./stable-diffusion-v1-4"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    model_id_or_path,
    revision="fp16", 
    torch_dtype=torch.float16,
    use_auth_token=True
)
# or download via git clone https://huggingface.co/CompVis/stable-diffusion-v1-4
# and pass `model_id_or_path="./stable-diffusion-v1-4"` without having to use `use_auth_token=True`.
pipe = pipe.to(device)

# let's download an initial image
url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"

response = requests.get(url)
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image = init_image.resize((768, 512))
print('-- Get input --')

prompt = "A fantasy landscape, trending on artstation"

with autocast("cuda"):
    images = pipe(prompt=prompt, init_image=init_image, strength=0.75, guidance_scale=7.5)["sample"]

images[0].save("fantasy_landscape.png")
```

### Logs

```shell
Traceback (most recent call last):
  File "image_to_image.py", line 33, in <module>
    images = pipe(prompt=prompt, init_image=init_image, strength=0.75, guidance_scale=7.5)["sample"]
  File "/home/xx/anaconda3/envs/stable_diffusion/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xx/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py", line 87, in __call__
    init_latents = self.vae.encode(init_image.to(self.device)).sample(generator=generator)
TypeError: sample() got an unexpected keyword argument 'generator'
```

### System Info
I am using pytorch 1.12.1 with cuda 11.3 on RTX 3090
src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py is from this repo
I used pip to install diffusers==0.2.4
I try 
```python
from diffusers import StableDiffusionInpaintPipeline
```
(as well as StableDiffusionImg2ImgPipeline) but got log like this:

```shell
Traceback (most recent call last):
  File "inpainting.py", line 7, in <module>
    from diffusers import StableDiffusionInpaintPipeline
ImportError: cannot import name 'StableDiffusionInpaintPipeline' from 'diffusers' (/home/xx/anaconda3/envs/sd_playground/lib/python3.8/site-packages/diffusers/__init__.py)
```

**Comment by KevinGoodman** [comment]
#305
