### ISSUE TITLE
StableDiffusionControlNetInpaintPipeline doesn't work with Diffusion pipeline

### ISSUE THREAD

**Issue by AmanKishore** [huggingface/diffusers#3420]
### Describe the bug

DiffusionPipeline does not expect control_image argument

### Reproduction

```
DiffusionPipeline.from_pretrained(
    pretrained_model_name_or_path=stable_model_path,
    controlnet=controlnet,
    custom_pipeline="stable_diffusion_controlnet_inpaint",
    safety_checker=None,
    torch_dtype=torch.float16,
)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/amankishore/.local/lib/python3.8/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/amankishore/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/home/amankishore/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1048, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/amankishore/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/amankishore/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/amankishore/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "cannyinpaint.py", line 164, in generate_image
    output = pipe(
  File "/home/amankishore/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'control_image'
```
```


### System Info

- `diffusers` version: 0.16.1
- Platform: Linux-4.19.0-24-cloud-amd64-x86_64-with-debian-10.13
- Python version: 3.7.12
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.25.1
- Accelerate version: 0.16.0
- xFormers version: 0.0.16
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by AmanKishore** [comment]
Whoops used legacy code: argument is `controlnet_conditioning_image`
