### ISSUE TITLE
Dreambooth training with DeepFloyd

### ISSUE THREAD

**Issue by mahendra0203** [huggingface/diffusers#3647]
### Describe the bug

I have been trying to get dreambooth working with Deepfloyd IF model. Following the instructions mentioned at https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#full-dreambooth.

Script and instructions aren't working, tried with a few alternatives cli options, everything fails with the same error. Training images with 64x64, 128x128 or 512x512 gives the same error.

Attaching the stacktrace here, any pointers to solve this would be really helpful.

### Reproduction

accelerate launch diffusers/examples/dreambooth/train_dreambooth.py --pretrained_model_name_or_path=$MODEL_NAME --instance_data_dir=$INSTANCE_DIR --output_dir=$OUTPUT_DIR --instance_prompt="a photo of sks man" --resolution=64  --train_batch_size=4 --gradient_accumulation_steps=1 --learning_rate=1e-7 --max_train_steps=150 --text_encoder_use_attention_mask --tokenizer_max_length=77 --pre_compute_text_embeddings --use_8bit_adam --set_grads_to_none --skip_save_text_encoder

Run the above command with the MODEL_NAME as "DeepFloyd/IF-I-XL-v1.0" 

Same error when using training images of 64x64, 128x128, 256x256 or 512x512.

### Logs

```shell
Traceback (most recent call last):
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth.py", line 1324, in <module>
    main(args)
  File "/workspace/diffusers/examples/dreambooth/train_dreambooth.py", line 1195, in main
    model_pred = unet(noisy_model_input, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 813, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 1582, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 308, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 766, in __call__
    encoder_hidden_states = attn.norm_encoder_hidden_states(encoder_hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 421, in norm_encoder_hidden_states
    encoder_hidden_states = self.norm_cross(encoder_hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 273, in forward
    return F.group_norm(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2530, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [2816] and input of shape [4, 4096, 77]
Steps:   0%|                                                                                                                                                                                          | 0/150 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 918, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 580, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=DeepFloyd/IF-I-XL-v1.0', '--instance_data_dir=/workspace/data_downloads/training_data', '--output_dir=/workspace/data_downloads/model_output', '--instance_prompt=a photo of sks man', '--resolution=64', '--train_batch_size=4', '--gradient_accumulation_steps=1', '--learning_rate=1e-7', '--max_train_steps=150', '--text_encoder_use_attention_mask', '--tokenizer_max_length=77', '--pre_compute_text_embeddings', '--use_8bit_adam', '--set_grads_to_none', '--skip_save_text_encoder']' returned non-zero exit status 1.
```

### System Info

ubuntu, gpu - 48GB,

**Comment by williamberman** [comment]
hey @mahendra0203 could you send me a fully reproducible snippet including what training data you're using or equivalent training data that results in the same error

**Comment by mahendra0203** [comment]
[birme-64x64.zip](https://github.com/huggingface/diffusers/files/11638025/birme-64x64.zip)

Attaching the training set. The command to reproduce it is added in the description. Let me know if you need anything else.

**Comment by williamberman** [comment]
hey @mahendra0203 I can't reproduce this. What versions of diffusers, cuda, and pytorch are you using?

**Comment by mahendra0203** [comment]
@williamberman   The training method for Dreambooth on DeepFloyd IF has been changed since I raised the bug report, and I will update this thread once I run the new scripts again. 
Thanks.
