### ISSUE TITLE
StableDiffusionPipeline.from_ckpt() cannot recognition remote(Hugging Face) model (SD Checkpoint)

### ISSUE THREAD

**Issue by AndrewHan0457** [huggingface/diffusers#3718]
### Describe the bug

my code is:
```python
pipe = StableDiffusionPipeline.from_ckpt(
        "https://huggingface.co/andite/anything-v4.0/blob/main/anything-v4.0-pruned-fp16.ckpt",
        # torch_dtype=torch.float16
)
``` 
just like [Diffusers Doc](https://huggingface.co/docs/diffusers/v0.16.0/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.from_ckpt) t2i.from_ckpt() page
```python
from diffusers import StableDiffusionPipeline

# Download pipeline from huggingface.co and cache.
pipeline = StableDiffusionPipeline.from_ckpt(
    "https://huggingface.co/WarriorMama777/OrangeMixs/blob/main/Models/AbyssOrangeMix/AbyssOrangeMix.safetensors"
)

# Download pipeline from local file
# file is downloaded under ./v1-5-pruned-emaonly.ckpt
pipeline = StableDiffusionPipeline.from_ckpt("./v1-5-pruned-emaonly")

# Enable float16 and move to GPU
pipeline = StableDiffusionPipeline.from_ckpt(
    "https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt",
    torch_dtype=torch.float16,
)
pipeline.to("cuda")
```
but error below:
```python
Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2023.1.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm Community Edition 2023.1.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\webui_api\test\load_ckpt_test.py", line 13, in <module>
    pipe = StableDiffusionPipeline.from_ckpt(
  File "E:\webui_api\venv\lib\site-packages\diffusers\loaders.py", line 1272, in from_ckpt
    pretrained_model_link_or_path = hf_hub_download(
  File "E:\webui_api\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "E:\webui_api\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and
 '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'andite\anything-v4.0'.
```
after debug I found this in `_validator.py` file:
```python
    if not REPO_ID_REGEX.match(repo_id):
        raise HFValidationError(
            "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are"
            " forbidden, '-' and '.' cannot start or end the name, max length is 96:"
            f" '{repo_id}'."
        )
```
and `REPO_ID_REGEX` is:
```python
REPO_ID_REGEX = re.compile(
    r"""
    ^
    (\b[\w\-.]+\b/)? # optional namespace (username or organization)
    \b               # starts with a word boundary
    [\w\-.]{1,96}    # repo_name: alphanumeric + . _ -
    \b               # ends with a word boundary
    $
    """,
    flags=re.VERBOSE,
)
```
It seems my `repo_id` `andite\anything-v4.0` conforms to the pattern, but an HFValidationError still occurs.
And the error seems not caused by special repo name, cuz when I try to use another sd-ckpt:
```python
pipe = StableDiffusionPipeline.from_ckpt(
        "https://huggingface.co/LarryAIDraw/refslaveV1_v1/blob/main/refslaveV1_v1.safetensors"
        # "andite/anything-v4.0/blob/main/anything-v4.0-pruned-fp16.ckpt",
        # torch_dtype=torch.float16
)
```
Totally same error. 
How can I adjust my code to let sdpipeline load ckpt/safetensors.

### Reproduction

just run the file, you can get error above.
```python
from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_ckpt(
        "andite/anything-v4.0/blob/main/anything-v4.0-pruned-fp16.ckpt",
        # torch_dtype=torch.float16
)
```

### System Info

diffuser 0.16.1
window 10
Python 3.10.10
PyCharm Community Edition 2023.1.1

**Comment by patrickvonplaten** [comment]
Checking! Thanks for the in-detail error description!

**Comment by patrickvonplaten** [comment]
Hey @AndrewHan0457,

Your code snippet works for me on Linux and I sadly don't have a Windows computer to verify. Could you double check if the error is gone with #3746?
