### ISSUE TITLE
Using torch.compile as instructed in 0.17 release note results in BackendCompilerFailed: cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by oxysoft** [huggingface/diffusers#3764]
### Describe the bug

Strange Numba errors print out upon running inference if I've compiled the models as described in 0.17

### Reproduction

Unfortunately it is quite a big codebase and I have not reproduced it yet in a small minimal project. I will do so ASAP and update this issue, however I am posting it in advance in case someone already has a clue and could be a simple fix.

Alternatively, perhaps try installing Numba to see if that will trigger it. I'm not doing anything special with it, I simply have it installed for librosa.

I am using the same method highlighted in the 0.17 release note for compiling the unet and controlnet models, here is a snippet from my codebase

```
        self.pcontrolnet.unet.to(memory_format=torch.channels_last)
        self.pcontrolnet.controlnet.to(memory_format=torch.channels_last)
        print("Diffusers.init_controlnet: compiling unet ...")
        self.pcontrolnet.unet = torch.compile(self.pcontrolnet.unet, mode="reduce-overhead", fullgraph=True)
        print("Diffusers.init_controlnet: compiling controlnet ...")
        self.pcontrolnet.controlnet = torch.compile(self.pcontrolnet.controlnet, mode="reduce-overhead", fullgraph=True)
```

### Logs

```shell
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.
Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.

Exception in thread Thread-1 (loop_thread):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 401, in compile_fx
    return compile_fx(
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2805, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2498, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1713, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/opt/conda/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1326, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/graph.py", line 575, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 528, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/tq/ctqlf5v47evot3fsy6hz7qev6fa27ng3hmykb3stgyvfuewzebke.py", line 20, in <module>
    triton__0 = async_compile.triton('''
  File "/opt/conda/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 683, in triton
    future = self.process_pool().submit(
  File "/opt/conda/lib/python3.10/concurrent/futures/process.py", line 724, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/discore_deploy/src/renderer.py", line 476, in loop_thread
    run_loop(lo, hi, inner=True, callback=callback)
  File "/workspace/discore_deploy/src/renderer.py", line 512, in run_loop
    iter_loop()
  File "/workspace/discore_deploy/src/renderer.py", line 664, in iter_loop
    loop.frame_callback(session.f)
  File "/workspace/discore_deploy/scripts/r.py", line 149, in iter
    renderer.frame()
  File "/workspace/discore_deploy/src/lib/printlib.py", line 221, in trace_wrapper
    return _trace_wrapper(func, True, *args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 217, in _trace_wrapper
    return func(*args, **kwargs)
  File "/workspace/discore_deploy/src/renderer.py", line 767, in frame
    invoke_frame()
  File "/workspace/discore_deploy/src/renderer.py", line 373, in invoke_frame
    frame_error = not _invoke_safe(_emit, 'frame', failsleep=0.25)
  File "/workspace/discore_deploy/src/renderer.py", line 199, in _invoke_safe
    return invoke_safe(*args, unsafe=enable_unsafe, **kwargs)
  File "/workspace/discore_deploy/src/lib/corelib.py", line 86, in invoke_safe
    func(*kargs, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 221, in trace_wrapper
    return _trace_wrapper(func, True, *args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 217, in _trace_wrapper
    return func(*args, **kwargs)
  File "/workspace/discore_deploy/src/renderer.py", line 194, in _emit
    func()
  File "/workspace/discore_deploy/sessions/pinchsky-cre-dance_4/script.py", line 273, in frame
    std.render_switch(diffusers, get_detail=get_cn_detail)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 221, in trace_wrapper
    return _trace_wrapper(func, True, *args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 217, in _trace_wrapper
    return func(*args, **kwargs)
  File "/workspace/discore_deploy/src/party/std.py", line 292, in render_switch
    rv.img = diffusers.txt2img_cn(
  File "/workspace/discore_deploy/src/plugins.py", line 91, in wrapped_call
    return function(*kargs, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 221, in trace_wrapper
    return _trace_wrapper(func, True, *args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 217, in _trace_wrapper
    return func(*args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 226, in trace_wrapper
    return _trace_wrapper(func, False, *args, **kwargs)
  File "/workspace/discore_deploy/src/lib/printlib.py", line 217, in _trace_wrapper
    return func(*args, **kwargs)
  File "/workspace/discore_deploy/src_plugins/sd_diffusers/HFDiffusersPlugin.py", line 429, in txt2img_cn
    images = self.pcontrolnet(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 938, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: cannot schedule new futures after interpreter shutdown
```

### System Info

- `diffusers` version: 0.17.1
- Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.27.4
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: not sure what this is or if this is relevant here

### Other useful details

```
- Model: https://huggingface.co/SG161222/Paragon_V1.0
- ControlNet 1: lllyasviel/control_v11p_sd15_softedge
- ControlNet 2: CiaraRowles/TemporalNet
- ControlNet 3: lllyasviel/control_v11f1p_sd15_depth
```

**Comment by oxysoft** [comment]
If I set the threading layer for Numba like this

```
numba_config.THREADING_LAYER = 'workqueue'
```

Then these cryptic errors don't show up anymore, however this exception remains so this seems to be the true problem

```
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: cannot schedule new futures after interpreter shutdown
```
