### ISSUE TITLE
Textual Inversion DiagonalGaussianDistribution

### ISSUE THREAD

**Issue by AmanKishore** [huggingface/diffusers#378]
### Describe the bug

When running `accelerate launch textual_inversion.py`
getting the following error:
```
Traceback (most recent call last):
  File "textual_inversion.py", line 579, in <module>
    main()
  File "textual_inversion.py", line 501, in main
    latents = vae.encode(batch["pixel_values"]).latent_dist.sample().detach()
AttributeError: 'DiagonalGaussianDistribution' object has no attribute 'latent_dist'
```

### Reproduction

Running the following command in 
https://github.com/huggingface/diffusers/tree/main/examples/textual_inversion
```
python3 textual_inversion.py   --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --use_auth_token   --train_data_dir=data/   --learnable_property="object"   --placeholder_token="<object>" --initializer_token="toy"   --resolution=512   --train_batch_size=1   --gradient_accumulation_steps=4   --max_train_steps=3000   --learning_rate=5.0e-04 --scale_lr   --lr_scheduler="constant"   --lr_warmup_steps=0   --output_dir="textual_inversion_toy"
```

### Logs

```shell
textual_inversion.py:259: DeprecationWarning: LINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  "linear": PIL.Image.LINEAR,
textual_inversion.py:260: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  "bilinear": PIL.Image.BILINEAR,
textual_inversion.py:261: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  "bicubic": PIL.Image.BICUBIC,
textual_inversion.py:262: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  "lanczos": PIL.Image.LANCZOS,
Steps:   0%|                                                                                                                                                | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "textual_inversion.py", line 579, in <module>
    main()
  File "textual_inversion.py", line 501, in main
    latents = vae.encode(batch["pixel_values"]).latent_dist.sample().detach()
AttributeError: 'DiagonalGaussianDistribution' object has no attribute 'latent_dist'
```
```


### System Info

diffusers v0.2.4

**Comment by mallorbc** [comment]
This is due to pip not having a new enough diffusers install.

To fix for now until an update:

```
pip uninstall diffusers
pip install git+https://github.com/huggingface/diffusers.git
```

**Comment by AmanKishore** [comment]
Ah thank you!
