### ISSUE TITLE
training controlnet with stabilityai/stable-diffusion-xl-base-0.9 does not seem to be working

### ISSUE THREAD

**Issue by yutongli** [huggingface/diffusers#4086]
### Describe the bug

training controlnet with the latest stabilityai/stable-diffusion-xl-base-0.9 does not seem to be working

### Reproduction

Firstly install all needed packages, including whatever mentioned in the official model card https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9

Then follow the generation instruction to train controlnet, it works for me with sd1.5 and sd2.1 models, but not for sd-xl model. Please kindly see the logs, the training job failed when 'Initializing controlnet weights from unet'

### Logs

```shell
07/13/2023 23:39:40 - INFO - __main__ - Initializing controlnet weights from unet
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/controlnettrain/diffusers/examples/controlnet/train_controlnet.py", line 1127, in <module>
    main(args)
  File "/home/ec2-user/SageMaker/controlnettrain/diffusers/examples/controlnet/train_controlnet.py", line 782, in main
    controlnet = ControlNetModel.from_unet(unet)
  File "/home/ec2-user/SageMaker/controlnettrain/diffusers/src/diffusers/models/controlnet.py", line 393, in from_unet
    controlnet.down_blocks.load_state_dict(unet.down_blocks.state_dict())
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModuleList:
        Unexpected key(s) in state_dict: "1.attentions.0.transformer_blocks.1.norm1.weight", "1.attentions.0.transformer_blocks.1.norm1.bias", "1.attentions.0.transformer_blocks.1.attn1.to_q.weight", "1.attentions.0.transformer_blocks.1.attn1.to_k.weight", "1.attentions.0.transformer_blocks.1.attn1.to_v.weight", "1.attentions.0.transformer_blocks.1.attn1.to_out.0.weight", "1.attentions.0.transformer_blocks.1.attn1.to_out.0.bias", "1.attentions.0.transformer_blocks.1.norm2.weight", "1.attentions.0.transformer_blocks.1.norm2.bias", "1.attentions.0.transformer_blocks.1.attn2.to_q.weight", "1.attentions.0.transformer_blocks.1.attn2.to_k.weight", "1.attentions.0.transformer_blocks.1.attn2.to_v.weight", "1.attentions.0.transformer_blocks.1.attn2.to_out.0.weight", "1.attentions.0.transformer_blocks.1.attn2.to_out.0.bias", "1.attentions.0.transformer_blocks.1.norm3.weight", "1.attentions.0.transformer_blocks.1.norm3.bias", "1.attentions.0.transformer_blocks.1.ff.net.0.proj.weight", "1.attentions.0.transformer_blocks.1.ff.net.0.proj.bias", "1.attentions.0.transformer_blocks.1.ff.net.2.weight", "1.attentions.0.transformer_blocks.1.ff.net.2.bias", "1.attentions.1.transformer_blocks.1.norm1.weight", "1.attentions.1.transformer_blocks.1.norm1.bias", "1.attentions.1.transformer_blocks.1.attn1.to_q.weight", "1.attentions.1.transformer_blocks.1.attn1.to_k.weight", "1.attentions.1.transformer_blocks.1.attn1.to_v.weight", "1.attentions.1.transformer_blocks.1.attn1.to_out.0.weight", "1.attentions.1.transformer_blocks.1.attn1.to_out.0.bias", "1.attentions.1.transformer_blocks.1.norm2.weight", "1.attentions.1.transformer_blocks.1.norm2.bias", "1.attentions.1.transformer_blocks.1.attn2.to_q.weight", "1.attentions.1.transformer_blocks.1.attn2.to_k.weight", "1.attentions.1.transformer_blocks.1.attn2.to_v.weight", "1.attentions.1.transformer_blocks.1.attn2.to_out.0.weight", "1.attentions.1.transformer_blocks.1.attn2.to_out.0.bias", "1.attentions.1.transformer_blocks.1.norm3.weight", "1.attentions.1.transformer_blocks.1.norm3.bias", "1.attentions.1.transformer_blocks.1.ff.net.0.proj.weight", "1.attentions.1.transformer_blocks.1.ff.net.0.proj.bias", "1.attentions.1.transformer_blocks.1.ff.net.2.weight", "1.attentions.1.transformer_blocks.1.ff.net.2.bias", "2.attentions.0.transformer_blocks.1.norm1.weight", "2.attentions.0.transformer_blocks.1.norm1.bias", "2.attentions.0.transformer_blocks.1.attn1.to_q.weight", "2.attentions.0.transformer_blocks.1.attn1.to_k.weight", "2.attentions.0.transformer_blocks.1.attn1.to_v.weight", "2.attentions.0.transformer_blocks.1.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.1.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.1.norm2.weight", "2.attentions.0.transformer_blocks.1.norm2.bias", "2.attentions.0.transformer_blocks.1.attn2.to_q.weight", "2.attentions.0.transformer_blocks.1.attn2.to_k.weight", "2.attentions.0.transformer_blocks.1.attn2.to_v.weight", "2.attentions.0.transformer_blocks.1.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.1.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.1.norm3.weight", "2.attentions.0.transformer_blocks.1.norm3.bias", "2.attentions.0.transformer_blocks.1.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.1.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.1.ff.net.2.weight", "2.attentions.0.transformer_blocks.1.ff.net.2.bias", "2.attentions.0.transformer_blocks.2.norm1.weight", "2.attentions.0.transformer_blocks.2.norm1.bias", "2.attentions.0.transformer_blocks.2.attn1.to_q.weight", "2.attentions.0.transformer_blocks.2.attn1.to_k.weight", "2.attentions.0.transformer_blocks.2.attn1.to_v.weight", "2.attentions.0.transformer_blocks.2.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.2.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.2.norm2.weight", "2.attentions.0.transformer_blocks.2.norm2.bias", "2.attentions.0.transformer_blocks.2.attn2.to_q.weight", "2.attentions.0.transformer_blocks.2.attn2.to_k.weight", "2.attentions.0.transformer_blocks.2.attn2.to_v.weight", "2.attentions.0.transformer_blocks.2.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.2.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.2.norm3.weight", "2.attentions.0.transformer_blocks.2.norm3.bias", "2.attentions.0.transformer_blocks.2.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.2.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.2.ff.net.2.weight", "2.attentions.0.transformer_blocks.2.ff.net.2.bias", "2.attentions.0.transformer_blocks.3.norm1.weight", "2.attentions.0.transformer_blocks.3.norm1.bias", "2.attentions.0.transformer_blocks.3.attn1.to_q.weight", "2.attentions.0.transformer_blocks.3.attn1.to_k.weight", "2.attentions.0.transformer_blocks.3.attn1.to_v.weight", "2.attentions.0.transformer_blocks.3.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.3.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.3.norm2.weight", "2.attentions.0.transformer_blocks.3.norm2.bias", "2.attentions.0.transformer_blocks.3.attn2.to_q.weight", "2.attentions.0.transformer_blocks.3.attn2.to_k.weight", "2.attentions.0.transformer_blocks.3.attn2.to_v.weight", "2.attentions.0.transformer_blocks.3.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.3.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.3.norm3.weight", "2.attentions.0.transformer_blocks.3.norm3.bias", "2.attentions.0.transformer_blocks.3.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.3.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.3.ff.net.2.weight", "2.attentions.0.transformer_blocks.3.ff.net.2.bias", "2.attentions.0.transformer_blocks.4.norm1.weight", "2.attentions.0.transformer_blocks.4.norm1.bias", "2.attentions.0.transformer_blocks.4.attn1.to_q.weight", "2.attentions.0.transformer_blocks.4.attn1.to_k.weight", "2.attentions.0.transformer_blocks.4.attn1.to_v.weight", "2.attentions.0.transformer_blocks.4.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.4.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.4.norm2.weight", "2.attentions.0.transformer_blocks.4.norm2.bias", "2.attentions.0.transformer_blocks.4.attn2.to_q.weight", "2.attentions.0.transformer_blocks.4.attn2.to_k.weight", "2.attentions.0.transformer_blocks.4.attn2.to_v.weight", "2.attentions.0.transformer_blocks.4.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.4.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.4.norm3.weight", "2.attentions.0.transformer_blocks.4.norm3.bias", "2.attentions.0.transformer_blocks.4.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.4.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.4.ff.net.2.weight", "2.attentions.0.transformer_blocks.4.ff.net.2.bias", "2.attentions.0.transformer_blocks.5.norm1.weight", "2.attentions.0.transformer_blocks.5.norm1.bias", "2.attentions.0.transformer_blocks.5.attn1.to_q.weight", "2.attentions.0.transformer_blocks.5.attn1.to_k.weight", "2.attentions.0.transformer_blocks.5.attn1.to_v.weight", "2.attentions.0.transformer_blocks.5.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.5.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.5.norm2.weight", "2.attentions.0.transformer_blocks.5.norm2.bias", "2.attentions.0.transformer_blocks.5.attn2.to_q.weight", "2.attentions.0.transformer_blocks.5.attn2.to_k.weight", "2.attentions.0.transformer_blocks.5.attn2.to_v.weight", "2.attentions.0.transformer_blocks.5.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.5.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.5.norm3.weight", "2.attentions.0.transformer_blocks.5.norm3.bias", "2.attentions.0.transformer_blocks.5.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.5.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.5.ff.net.2.weight", "2.attentions.0.transformer_blocks.5.ff.net.2.bias", "2.attentions.0.transformer_blocks.6.norm1.weight", "2.attentions.0.transformer_blocks.6.norm1.bias", "2.attentions.0.transformer_blocks.6.attn1.to_q.weight", "2.attentions.0.transformer_blocks.6.attn1.to_k.weight", "2.attentions.0.transformer_blocks.6.attn1.to_v.weight", "2.attentions.0.transformer_blocks.6.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.6.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.6.norm2.weight", "2.attentions.0.transformer_blocks.6.norm2.bias", "2.attentions.0.transformer_blocks.6.attn2.to_q.weight", "2.attentions.0.transformer_blocks.6.attn2.to_k.weight", "2.attentions.0.transformer_blocks.6.attn2.to_v.weight", "2.attentions.0.transformer_blocks.6.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.6.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.6.norm3.weight", "2.attentions.0.transformer_blocks.6.norm3.bias", "2.attentions.0.transformer_blocks.6.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.6.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.6.ff.net.2.weight", "2.attentions.0.transformer_blocks.6.ff.net.2.bias", "2.attentions.0.transformer_blocks.7.norm1.weight", "2.attentions.0.transformer_blocks.7.norm1.bias", "2.attentions.0.transformer_blocks.7.attn1.to_q.weight", "2.attentions.0.transformer_blocks.7.attn1.to_k.weight", "2.attentions.0.transformer_blocks.7.attn1.to_v.weight", "2.attentions.0.transformer_blocks.7.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.7.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.7.norm2.weight", "2.attentions.0.transformer_blocks.7.norm2.bias", "2.attentions.0.transformer_blocks.7.attn2.to_q.weight", "2.attentions.0.transformer_blocks.7.attn2.to_k.weight", "2.attentions.0.transformer_blocks.7.attn2.to_v.weight", "2.attentions.0.transformer_blocks.7.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.7.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.7.norm3.weight", "2.attentions.0.transformer_blocks.7.norm3.bias", "2.attentions.0.transformer_blocks.7.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.7.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.7.ff.net.2.weight", "2.attentions.0.transformer_blocks.7.ff.net.2.bias", "2.attentions.0.transformer_blocks.8.norm1.weight", "2.attentions.0.transformer_blocks.8.norm1.bias", "2.attentions.0.transformer_blocks.8.attn1.to_q.weight", "2.attentions.0.transformer_blocks.8.attn1.to_k.weight", "2.attentions.0.transformer_blocks.8.attn1.to_v.weight", "2.attentions.0.transformer_blocks.8.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.8.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.8.norm2.weight", "2.attentions.0.transformer_blocks.8.norm2.bias", "2.attentions.0.transformer_blocks.8.attn2.to_q.weight", "2.attentions.0.transformer_blocks.8.attn2.to_k.weight", "2.attentions.0.transformer_blocks.8.attn2.to_v.weight", "2.attentions.0.transformer_blocks.8.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.8.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.8.norm3.weight", "2.attentions.0.transformer_blocks.8.norm3.bias", "2.attentions.0.transformer_blocks.8.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.8.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.8.ff.net.2.weight", "2.attentions.0.transformer_blocks.8.ff.net.2.bias", "2.attentions.0.transformer_blocks.9.norm1.weight", "2.attentions.0.transformer_blocks.9.norm1.bias", "2.attentions.0.transformer_blocks.9.attn1.to_q.weight", "2.attentions.0.transformer_blocks.9.attn1.to_k.weight", "2.attentions.0.transformer_blocks.9.attn1.to_v.weight", "2.attentions.0.transformer_blocks.9.attn1.to_out.0.weight", "2.attentions.0.transformer_blocks.9.attn1.to_out.0.bias", "2.attentions.0.transformer_blocks.9.norm2.weight", "2.attentions.0.transformer_blocks.9.norm2.bias", "2.attentions.0.transformer_blocks.9.attn2.to_q.weight", "2.attentions.0.transformer_blocks.9.attn2.to_k.weight", "2.attentions.0.transformer_blocks.9.attn2.to_v.weight", "2.attentions.0.transformer_blocks.9.attn2.to_out.0.weight", "2.attentions.0.transformer_blocks.9.attn2.to_out.0.bias", "2.attentions.0.transformer_blocks.9.norm3.weight", "2.attentions.0.transformer_blocks.9.norm3.bias", "2.attentions.0.transformer_blocks.9.ff.net.0.proj.weight", "2.attentions.0.transformer_blocks.9.ff.net.0.proj.bias", "2.attentions.0.transformer_blocks.9.ff.net.2.weight", "2.attentions.0.transformer_blocks.9.ff.net.2.bias", "2.attentions.1.transformer_blocks.1.norm1.weight", "2.attentions.1.transformer_blocks.1.norm1.bias", "2.attentions.1.transformer_blocks.1.attn1.to_q.weight", "2.attentions.1.transformer_blocks.1.attn1.to_k.weight", "2.attentions.1.transformer_blocks.1.attn1.to_v.weight", "2.attentions.1.transformer_blocks.1.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.1.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.1.norm2.weight", "2.attentions.1.transformer_blocks.1.norm2.bias", "2.attentions.1.transformer_blocks.1.attn2.to_q.weight", "2.attentions.1.transformer_blocks.1.attn2.to_k.weight", "2.attentions.1.transformer_blocks.1.attn2.to_v.weight", "2.attentions.1.transformer_blocks.1.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.1.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.1.norm3.weight", "2.attentions.1.transformer_blocks.1.norm3.bias", "2.attentions.1.transformer_blocks.1.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.1.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.1.ff.net.2.weight", "2.attentions.1.transformer_blocks.1.ff.net.2.bias", "2.attentions.1.transformer_blocks.2.norm1.weight", "2.attentions.1.transformer_blocks.2.norm1.bias", "2.attentions.1.transformer_blocks.2.attn1.to_q.weight", "2.attentions.1.transformer_blocks.2.attn1.to_k.weight", "2.attentions.1.transformer_blocks.2.attn1.to_v.weight", "2.attentions.1.transformer_blocks.2.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.2.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.2.norm2.weight", "2.attentions.1.transformer_blocks.2.norm2.bias", "2.attentions.1.transformer_blocks.2.attn2.to_q.weight", "2.attentions.1.transformer_blocks.2.attn2.to_k.weight", "2.attentions.1.transformer_blocks.2.attn2.to_v.weight", "2.attentions.1.transformer_blocks.2.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.2.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.2.norm3.weight", "2.attentions.1.transformer_blocks.2.norm3.bias", "2.attentions.1.transformer_blocks.2.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.2.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.2.ff.net.2.weight", "2.attentions.1.transformer_blocks.2.ff.net.2.bias", "2.attentions.1.transformer_blocks.3.norm1.weight", "2.attentions.1.transformer_blocks.3.norm1.bias", "2.attentions.1.transformer_blocks.3.attn1.to_q.weight", "2.attentions.1.transformer_blocks.3.attn1.to_k.weight", "2.attentions.1.transformer_blocks.3.attn1.to_v.weight", "2.attentions.1.transformer_blocks.3.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.3.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.3.norm2.weight", "2.attentions.1.transformer_blocks.3.norm2.bias", "2.attentions.1.transformer_blocks.3.attn2.to_q.weight", "2.attentions.1.transformer_blocks.3.attn2.to_k.weight", "2.attentions.1.transformer_blocks.3.attn2.to_v.weight", "2.attentions.1.transformer_blocks.3.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.3.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.3.norm3.weight", "2.attentions.1.transformer_blocks.3.norm3.bias", "2.attentions.1.transformer_blocks.3.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.3.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.3.ff.net.2.weight", "2.attentions.1.transformer_blocks.3.ff.net.2.bias", "2.attentions.1.transformer_blocks.4.norm1.weight", "2.attentions.1.transformer_blocks.4.norm1.bias", "2.attentions.1.transformer_blocks.4.attn1.to_q.weight", "2.attentions.1.transformer_blocks.4.attn1.to_k.weight", "2.attentions.1.transformer_blocks.4.attn1.to_v.weight", "2.attentions.1.transformer_blocks.4.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.4.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.4.norm2.weight", "2.attentions.1.transformer_blocks.4.norm2.bias", "2.attentions.1.transformer_blocks.4.attn2.to_q.weight", "2.attentions.1.transformer_blocks.4.attn2.to_k.weight", "2.attentions.1.transformer_blocks.4.attn2.to_v.weight", "2.attentions.1.transformer_blocks.4.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.4.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.4.norm3.weight", "2.attentions.1.transformer_blocks.4.norm3.bias", "2.attentions.1.transformer_blocks.4.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.4.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.4.ff.net.2.weight", "2.attentions.1.transformer_blocks.4.ff.net.2.bias", "2.attentions.1.transformer_blocks.5.norm1.weight", "2.attentions.1.transformer_blocks.5.norm1.bias", "2.attentions.1.transformer_blocks.5.attn1.to_q.weight", "2.attentions.1.transformer_blocks.5.attn1.to_k.weight", "2.attentions.1.transformer_blocks.5.attn1.to_v.weight", "2.attentions.1.transformer_blocks.5.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.5.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.5.norm2.weight", "2.attentions.1.transformer_blocks.5.norm2.bias", "2.attentions.1.transformer_blocks.5.attn2.to_q.weight", "2.attentions.1.transformer_blocks.5.attn2.to_k.weight", "2.attentions.1.transformer_blocks.5.attn2.to_v.weight", "2.attentions.1.transformer_blocks.5.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.5.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.5.norm3.weight", "2.attentions.1.transformer_blocks.5.norm3.bias", "2.attentions.1.transformer_blocks.5.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.5.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.5.ff.net.2.weight", "2.attentions.1.transformer_blocks.5.ff.net.2.bias", "2.attentions.1.transformer_blocks.6.norm1.weight", "2.attentions.1.transformer_blocks.6.norm1.bias", "2.attentions.1.transformer_blocks.6.attn1.to_q.weight", "2.attentions.1.transformer_blocks.6.attn1.to_k.weight", "2.attentions.1.transformer_blocks.6.attn1.to_v.weight", "2.attentions.1.transformer_blocks.6.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.6.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.6.norm2.weight", "2.attentions.1.transformer_blocks.6.norm2.bias", "2.attentions.1.transformer_blocks.6.attn2.to_q.weight", "2.attentions.1.transformer_blocks.6.attn2.to_k.weight", "2.attentions.1.transformer_blocks.6.attn2.to_v.weight", "2.attentions.1.transformer_blocks.6.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.6.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.6.norm3.weight", "2.attentions.1.transformer_blocks.6.norm3.bias", "2.attentions.1.transformer_blocks.6.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.6.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.6.ff.net.2.weight", "2.attentions.1.transformer_blocks.6.ff.net.2.bias", "2.attentions.1.transformer_blocks.7.norm1.weight", "2.attentions.1.transformer_blocks.7.norm1.bias", "2.attentions.1.transformer_blocks.7.attn1.to_q.weight", "2.attentions.1.transformer_blocks.7.attn1.to_k.weight", "2.attentions.1.transformer_blocks.7.attn1.to_v.weight", "2.attentions.1.transformer_blocks.7.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.7.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.7.norm2.weight", "2.attentions.1.transformer_blocks.7.norm2.bias", "2.attentions.1.transformer_blocks.7.attn2.to_q.weight", "2.attentions.1.transformer_blocks.7.attn2.to_k.weight", "2.attentions.1.transformer_blocks.7.attn2.to_v.weight", "2.attentions.1.transformer_blocks.7.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.7.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.7.norm3.weight", "2.attentions.1.transformer_blocks.7.norm3.bias", "2.attentions.1.transformer_blocks.7.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.7.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.7.ff.net.2.weight", "2.attentions.1.transformer_blocks.7.ff.net.2.bias", "2.attentions.1.transformer_blocks.8.norm1.weight", "2.attentions.1.transformer_blocks.8.norm1.bias", "2.attentions.1.transformer_blocks.8.attn1.to_q.weight", "2.attentions.1.transformer_blocks.8.attn1.to_k.weight", "2.attentions.1.transformer_blocks.8.attn1.to_v.weight", "2.attentions.1.transformer_blocks.8.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.8.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.8.norm2.weight", "2.attentions.1.transformer_blocks.8.norm2.bias", "2.attentions.1.transformer_blocks.8.attn2.to_q.weight", "2.attentions.1.transformer_blocks.8.attn2.to_k.weight", "2.attentions.1.transformer_blocks.8.attn2.to_v.weight", "2.attentions.1.transformer_blocks.8.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.8.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.8.norm3.weight", "2.attentions.1.transformer_blocks.8.norm3.bias", "2.attentions.1.transformer_blocks.8.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.8.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.8.ff.net.2.weight", "2.attentions.1.transformer_blocks.8.ff.net.2.bias", "2.attentions.1.transformer_blocks.9.norm1.weight", "2.attentions.1.transformer_blocks.9.norm1.bias", "2.attentions.1.transformer_blocks.9.attn1.to_q.weight", "2.attentions.1.transformer_blocks.9.attn1.to_k.weight", "2.attentions.1.transformer_blocks.9.attn1.to_v.weight", "2.attentions.1.transformer_blocks.9.attn1.to_out.0.weight", "2.attentions.1.transformer_blocks.9.attn1.to_out.0.bias", "2.attentions.1.transformer_blocks.9.norm2.weight", "2.attentions.1.transformer_blocks.9.norm2.bias", "2.attentions.1.transformer_blocks.9.attn2.to_q.weight", "2.attentions.1.transformer_blocks.9.attn2.to_k.weight", "2.attentions.1.transformer_blocks.9.attn2.to_v.weight", "2.attentions.1.transformer_blocks.9.attn2.to_out.0.weight", "2.attentions.1.transformer_blocks.9.attn2.to_out.0.bias", "2.attentions.1.transformer_blocks.9.norm3.weight", "2.attentions.1.transformer_blocks.9.norm3.bias", "2.attentions.1.transformer_blocks.9.ff.net.0.proj.weight", "2.attentions.1.transformer_blocks.9.ff.net.0.proj.bias", "2.attentions.1.transformer_blocks.9.ff.net.2.weight", "2.attentions.1.transformer_blocks.9.ff.net.2.bias".
```

### System Info

- `diffusers` version: 0.19.0.dev0
- Platform: Linux-5.10.178-162.673.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.8
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.30.2
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: ?

### Who can help?

@patrickvonplaten @sayakpaul @williamberman

**Comment by sayakpaul** [comment]
Please refer to: https://github.com/huggingface/diffusers/pull/4038
