### ISSUE TITLE
UnboundLocalError: local variable 'images' referenced before assignment

### ISSUE THREAD

**Issue by bharadwaj-kg** [huggingface/diffusers#4092]
I was fine-tuning stable-diffusion model using train_text_to_image_lora.py. Faced this error once the training is done and could not push model to hub.

Steps: 100% 500/500 [14:51<00:00,  1.76s/it, lr=0, step_loss=0.0177]      Model weights saved in finetune-stable-diffusion-v1-4-planogram-lora/pytorch_lora_weights.bin

Traceback (most recent call last):
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora.py", line 949, in <module>
    main()
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora.py", line 899, in main
    images=images,
UnboundLocalError: local variable 'images' referenced before assignment

**Comment by patrickvonplaten** [comment]
Hey @bharadwaj-kg,

Can you please provide a fully reproducible code snippet?
