### ISSUE TITLE
bug:convert controlnet model(custom datasets train) to diffusers failure

### ISSUE THREAD

**Issue by chenjingcheng** [huggingface/diffusers#4101]
I trained a controlnet model based on sd1.5 or sd2.1 using my own data. The trained controlnet model performs inference correctly. However, when I try to convert it using the scripts/convert_original_controlnet_to_diffusers.py script, I encounter the following error:
Traceback (most recent call last):
  File "/home/jacky/aiproject/diffusers/scripts/convert_original_controlnet_to_diffusers.py", line 96, in <module>
    controlnet = download_controlnet_from_original_ckpt(
  File "/home/jacky/anaconda3/envs/diffusers/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1557, in download_controlnet_from_original_ckpt
    controlnet_model = convert_controlnet_checkpoint(
  File "/home/jacky/anaconda3/envs/diffusers/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1038, in convert_controlnet_checkpoint
    controlnet_model = ControlNetModel(**ctrlnet_config)
  File "/home/jacky/anaconda3/envs/diffusers/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 614, in inner_init
    init(self, *args, **init_kwargs)
TypeError: ControlNetModel.__init__() got an unexpected keyword argument 'addition_embed_type'

**Comment by patrickvonplaten** [comment]
Hey @chenjingcheng,

Can you please provide a reproducible code snippet?

**Comment by LhaoH** [comment]
same question!
![图片](https://github.com/huggingface/diffusers/assets/50076227/571c363a-a826-4ced-8791-8d08e818091e)

**Comment by patrickvonplaten** [comment]
cc @sayakpaul is this related to https://github.com/huggingface/diffusers/pull/4119

Will try to fix later in https://github.com/huggingface/diffusers/pull/4084

**Comment by sayakpaul** [comment]
Yeah seems to be related.

**Comment by patrickvonplaten** [comment]
Ok took a look, I think this will be fixed with https://github.com/huggingface/diffusers/pull/4038

**Comment by patrickvonplaten** [comment]
Should be fixed now - can you check @chenjingcheng ?
