### ISSUE TITLE
Apple M1 Max (MPS) Tensor Size Not Matching For ControlNet From Pretrained Model

### ISSUE THREAD

**Issue by b2jant** [huggingface/diffusers#4134]
### Describe the bug

I am unable to run the above despite ControlNet showing support for MPS in the python code.

### Reproduction

controlnet = ControlNetModel.from_pretrained(
    "DionTimmer/controlnet_qrcode-control_v11p_sd21",
    torch_dtype=torch.float32,
)

pipe = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1",
    controlnet=controlnet,
    safety_checker=None,
    torch_dtype=torch.float32,
).to("mps")

pipe.enable_attention_slicing()

def resize_for_condition_image(input_image: Image, resolution: int):
    input_image = input_image.convert("RGB")
    W, H = input_image.size
    k = float(resolution) / min(H, W)
    H *= k
    W *= k
    H = int(round(H / 64.0)) * 64
    W = int(round(W / 64.0)) * 64
    img = input_image.resize((W, H), resample=Image.LANCZOS)
    return img

source_image = load_image("./images/qr_codes/youtube_qr.png")

init_image = load_image("./images/base_images/beach.jpg")
condition_image = resize_for_condition_image(source_image, 768)
init_image = resize_for_condition_image(init_image, 768)
generator = torch.Generator(device="mps").manual_seed(-1)
image = pipe(
    prompt="a bilboard in NYC with a qrcode",
    negative_prompt="ugly, disfigured, low quality, blurry, nsfw",
    image=init_image,
    control_image=condition_image,
    width=768,
    height=768,
    guidance_scale=20,
    controlnet_conditioning_scale=1.5,
    generator=generator,
    strength=0.9,
    num_inference_steps=150,
)

image.images[0]

### Logs

```shell
Traceback (most recent call last):
  File "/Users/bijantavakoli/Documents/testing_qr_codes/demo.py", line 50, in <module>
    image = pipe(
            ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 1073, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
                                                   ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/diffusers/models/controlnet.py", line 637, in forward
    sample = sample + controlnet_cond
             ~~~~~~~^~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (128) must match the size of tensor b (96) at non-singleton dimension 2
```

### System Info

- `diffusers` version: 0.18.2
- Platform: macOS-13.4.1-arm64-arm-64bit
- Python version: 3.11.4
- PyTorch version (GPU?): 2.0.1 (False)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.30.2
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: Yes (MPS)
- Using distributed or parallel set-up in script?: Not Sure

**Comment by b2jant** [comment]
I have tested above code using cuda on 3070ti and got same exact error message

**Comment by korzen** [comment]
I have got this on A100 80GB:

`Running prediction...
Using seed: 1
  0%|          | 0/16 [00:00<?, ?it/s]
0%|          | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/cog/server/worker.py", line 209, in _predict
result = self._predictor.predict(**payload)
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/src/predict.py", line 264, in predict
sd_output = self.pipe(
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py", line 1073, in __call__
down_block_res_samples, mid_block_res_sample = self.controlnet(
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/root/.pyenv/versions/3.10.12/lib/python3.10/site-packages/diffusers/models/controlnet.py", line 637, in forward
sample = sample + controlnet_cond
RuntimeError: The size of tensor a (64) must match the size of tensor b (96) at non-singleton dimension 3`

**Comment by b2jant** [comment]
Can close, error was not in controlnet for MPS but rather in input size of pictures. The function I used to resize the photos didnt resize them correctly

Confirming I can get the above to run with MPS

**Comment by pcuenca** [comment]
Thanks @b2jant!

**Comment by usamaehsan** [comment]
> Can close, error was not in controlnet for MPS but rather in input size of pictures. The function I used to resize the photos didnt resize them correctly
> 
> Confirming I can get the above to run with MPS

@b2jant can you share your resize function?
