### ISSUE TITLE
Support to convert between ControlNet 2.1 checkpoints

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#4219]
### Describe the bug

Hello everyone,
I was trying to download: https://civitai.com/models/38784?modelVersionId=44716 
https://github.com/Mikubill/sd-webui-controlnet

```
I did : 
!python ./diffusers/scripts/convert_original_controlnet_to_diffusers.py --checkpoint_path ./test_model.safetensors --original_config_file ./sd-webui-controlnet/models/control_sd15_openpose.yaml --dump_path ./test_model --to_safetensors --use_linear_projection True --device cuda

```

and getting error:

```
2023-07-23 15:53:57.933361: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_controlnet_to_diffusers.py", line 96, in <module>
    controlnet = download_controlnet_from_original_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1595, in download_controlnet_from_original_ckpt
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```
Love to hear what i am doing wrong here.
Thanks,
Andy

### Reproduction

```
I did : 
!python ./diffusers/scripts/convert_original_controlnet_to_diffusers.py --checkpoint_path ./test_model.safetensors --original_config_file ./sd-webui-controlnet/models/control_sd15_openpose.yaml --dump_path ./test_model --to_safetensors --use_linear_projection True --device cuda

```

and getting error:

```
2023-07-23 15:53:57.933361: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_controlnet_to_diffusers.py", line 96, in <module>
    controlnet = download_controlnet_from_original_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1595, in download_controlnet_from_original_ckpt
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```

### System Info

working on free version of colab 

### Who can help?

@williamberman @say

**Comment by sayakpaul** [comment]
Seems like there's a problem with your download: https://stackoverflow.com/questions/35879096/pickle-unpicklingerror-could-not-find-mark. 

Could you provide the Colab Notebook you're using to run the conversion?

**Comment by andysingal** [comment]
> Seems like there's a problem with your download: https://stackoverflow.com/questions/35879096/pickle-unpicklingerror-could-not-find-mark.
> 
> Could you provide the Colab Notebook you're using to run the conversion?

Thank you @sayakpaul for your response , here is the link to the Notebook https://colab.research.google.com/drive/1znwYc4K7lGyLhmjYXj6W6E0TTEDSPkVe?usp=sharing

**Comment by sayakpaul** [comment]
I can reproduce the error:

```bash
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_controlnet_to_diffusers.py", line 96, in <module>
    controlnet = download_controlnet_from_original_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1595, in download_controlnet_from_original_ckpt
    checkpoint = torch.load(checkpoint_path, map_location=device)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK
```

The error indicates there's something wrong in line 1595. It's funny 'cause the 1595 line actually tells us about something else:

https://github.com/huggingface/diffusers/blob/09fab5610e639ea9d63833921b57a5eae0154f10/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1595

This is happening because we're installing the stable version of diffusers first and then we're using the conversion script from the `main` branch. Additionally, I think the command you were using needed some fixes:

```python
!python ./diffusers/scripts/convert_original_controlnet_to_diffusers.py \
    --checkpoint_path ./test_model.safetensors \
    --original_config_file ./sd-webui-controlnet/models/control_sd15_openpose.yaml \
    --from_safetensors \
    --dump_path ./test_model --to_safetensors --device cuda

```

Here's my Colab Notebook for your reference: https://colab.research.google.com/gist/sayakpaul/5af00e0143101bf398a445ae283f5770/untitled113.ipynb

**Comment by andysingal** [comment]
Thanks for your instant reply @sayakpaul but i am still getting error:(This time a new one)
```
2023-07-24 03:13:52.174712: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_controlnet_to_diffusers.py", line 96, in <module>
    controlnet = download_controlnet_from_original_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1610, in download_controlnet_from_original_ckpt
    controlnet_model = convert_controlnet_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1058, in convert_controlnet_checkpoint
    controlnet_model = ControlNetModel(**ctrlnet_config)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 614, in inner_init
    init(self, *args, **init_kwargs)
TypeError: ControlNetModel.__init__() got an unexpected keyword argument 'addition_embed_type'

```

Please find colab notebook as attached 
https://colab.research.google.com/drive/1znwYc4K7lGyLhmjYXj6W6E0TTEDSPkVe?usp=sharing
