### ISSUE TITLE
[SDXL Refiner] Refiner doesn't register text encoder? 

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#4236]
## Code:

Taken from https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl

```python
import torch
from diffusers import StableDiffusionXLImg2ImgPipeline
from diffusers.utils import load_image

pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-0.9", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe = pipe.to("cuda")
url = "https://huggingface.co/datasets/patrickvonplaten/images/resolve/main/aa_xl/000000009.png"

init_image = load_image(url).convert("RGB")
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt, image=init_image).images[0]
```

## Error: 

```bash
Traceback (most recent call last):
  File "/home/sayak/test_refiner.py", line 13, in <module>
    image = pipe(prompt, image=init_image).images[0]
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sayak/diffusers/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 829, in __call__
    ) = self.encode_prompt(
  File "/home/sayak/diffusers/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 386, in encode_prompt
    prompt_embeds = prompt_embeds.to(dtype=self.text_encoder.dtype, device=device)
AttributeError: 'NoneType' object has no attribute 'dtype'
```

## Version:

```
- `diffusers` version: 0.19.0.dev0 (installed from `main`)
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: no
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no
```

Cc: @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Reason: https://github.com/huggingface/diffusers/pull/4099

**Comment by patrickvonplaten** [comment]
Fix: https://github.com/huggingface/diffusers/issues/4236
