### ISSUE TITLE
Torch 2 compile causes crash during inference

### ISSUE THREAD

**Issue by frankjoshua** [huggingface/diffusers#4375]
### Describe the bug

I was able to create this using StableDiffusionXL and StableDiffusion pipelines. The crash happens during inference.
  
  File "test.py", line 11, in <module>
    image = pipe(prompt=prompt).images[0]
  File "/opt/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 814, in __call__
    noise_pred = self.unet(
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 539, in step
    unimplemented(f"missing: {inst.opname}")
  File "/opt/venv/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 71, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: missing: BUILD_MAP_UNPACK_WITH_CALL

### Reproduction

from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
pipe.to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image = pipe(prompt=prompt).images[0]

### System Info

- `diffusers` version: 0.19.2
- Platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

absl-py==1.4.0
accelerate==0.21.0
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
anyio==3.7.1
appdirs==1.4.4
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
audioread==3.0.0
backoff==2.2.1
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
cmake==3.27.0
compel==2.0.1
datasets==2.14.1
decorator==5.1.1
diffusers==0.19.2
dill==0.3.7
exceptiongroup==1.1.2
fastapi==0.100.1
fastjsonschema==2.18.0
filelock==3.12.2
flatbuffers==23.5.26
frozenlist==1.4.0
fsspec==2023.6.0
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
gql==3.4.1
graphql-core==3.2.3
grpcio==1.56.2
h11==0.14.0
h5py==3.9.0
hf-doc-builder==0.4.0
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
invisible-watermark==0.2.0
Jinja2==3.1.2
joblib==1.3.1
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter_core==5.3.1
keras==2.11.0
lazy_loader==0.3
libclang==16.0.6
librosa==0.10.0.post2
lightning-utilities==0.9.0
lit==16.0.6
llvmlite==0.40.1
Markdown==3.4.4
MarkupSafe==2.1.3
mpmath==1.3.0
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.15
mypy-extensions==1.0.0
nbformat==5.9.1
networkx==3.1
nsfw-detector==1.1.1
numba==0.57.1
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
omegaconf==2.3.0
opencv-python==4.8.0.74
opt-einsum==3.3.0
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
pkg_resources==0.0.0
pkgutil_resolve_name==1.3.10
platformdirs==3.10.0
pooch==1.6.0
protobuf==3.19.6
psutil==5.9.5
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pynvml==11.5.0
pyparsing==3.1.0
pyre-extensions==0.0.29
python-dateutil==2.8.2
pytorch-lightning==2.0.6
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0.1
referencing==0.30.0
regex==2023.6.3
requests==2.31.0
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
rpds-py==0.9.2
rsa==4.9
safetensors==0.3.1
scikit-learn==1.3.0
scipy==1.10.1
sentry-sdk==1.28.1
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
soundfile==0.12.1
soxr==0.3.5
starlette==0.27.0
sympy==1.12
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.1
tensorflow-estimator==2.11.0
tensorflow-hub==0.7.0
tensorflow-io-gcs-filesystem==0.32.0
termcolor==2.3.0
threadpoolctl==3.2.0
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
torchmetrics==1.0.1
torchvision==0.15.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.31.0
triton==2.0.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
uvicorn==0.23.1
validators==0.20.0
Werkzeug==2.3.6
wrapt==1.15.0
xformers==0.0.20
xxhash==3.3.0
yarl==1.9.2
zipp==3.16.2

**Comment by patrickvonplaten** [comment]
Hey @frankjoshua,

Thanks for the issue. I cannot reproduce the issue on my side sadly - it works just fine for me.

```py
from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
pipe.to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image = pipe(prompt=prompt).images[0]
```

achieves speeds of ~8.2 iterations / s. I'm running on the following environment:

```
- `diffusers` version: 0.20.0.dev0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.15.1
- Transformers version: 4.32.0.dev0
- Accelerate version: 0.21.0
- xFormers version: 0.0.20
- Using GPU in script?: RTX4090
```

on a RTX4090.

Could you maybe try updating your CUDA environment to > 11.7 (11.8 should work)?

**Comment by frankjoshua** [comment]
I'm using this Dockerfile https://github.com/huggingface/diffusers/blob/main/docker/diffusers-pytorch-cuda/Dockerfile
Can you share what you are using? I tried nvidia/cuda:12.2.0-runtime-ubuntu20.04 but had issues with finding cuda devices and nvidia/cuda:11.8.0-runtime-ubuntu22.04 but that could not find python3.8 and even make it past the build. I could keep going but I thought you might already have a working container.

**Comment by frankjoshua** [comment]
Yes, I can confirm that cuda 11.8 fixes the issue.

Here is a working Dockerfile
```
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
LABEL maintainer="Hugging Face"
LABEL repository="diffusers"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y bash \
                   build-essential \
                   git \
                   git-lfs \
                   curl \
                   ca-certificates \
                   libsndfile1-dev \
                   libgl1 \
                   python3 \
                   python3-pip \
                   python3-venv && \
    rm -rf /var/lib/apt/lists

# make sure to use venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# pre-install the heavy dependencies (these can later be overridden by the deps from setup.py)
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir \
        torch \
        torchvision \
        torchaudio \
        invisible_watermark && \
    python3 -m pip install --no-cache-dir \
        accelerate \
        datasets \
        hf-doc-builder \
        huggingface-hub \
        Jinja2 \
        librosa \
        numpy \
        scipy \
        tensorboard \
        transformers \
        omegaconf \
        pytorch-lightning \
        xformers

COPY requirements.txt requirements.txt
RUN python3 -m pip install --no-cache-dir -r requirements.txt
```

**Comment by patrickvonplaten** [comment]
Which GPU are you using?

**Comment by frankjoshua** [comment]
I am using a RTX 3090

**Comment by patrickvonplaten** [comment]
Hmm I still can't reproduce sadly (also tried on a RTX3090) - is there any way you could try to reproduce the error on a google colab and share here?

**Comment by carvychen** [comment]
I encountered the same error, have you solved this problem?
<img width="823" alt="image" src="https://github.com/huggingface/diffusers/assets/30137344/f19c77d1-14c8-43a3-82e7-f549d09ff4a5">

**Comment by frankjoshua** [comment]
@carvychen I upgraded to cuda 11.8 and it fixed the issue.

**Comment by jackalcooper** [comment]
@carvychen I think this has something to do with the python version. you might want to try 3.10

**Comment by shadowkkk** [comment]
I encountered the same error.
python version is 3.8，RTX3090，CUDA11.3

**Comment by patrickvonplaten** [comment]
Seems like we need to use CUDA 11.8

**Comment by andreemic** [comment]
I'm getting an error in the `unet_2d_condition.py` file when using torch.compile. Not the exact same error though.


```python
>>> pipe('a', image=img)
  0%|                                                                                                                                                                                              | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py", line 343, in __call__
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
           ^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
        ^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1728, in CALL
    self.call_function(fn, args, kwargs)
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/variables/builtin.py", line 645, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/variables/base.py", line 306, in call_function
    unimplemented(f"call_function {self} {args} {kwargs}")
  File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_function BuiltinVariable(any) [ListIteratorVariable()] {}

from user code:
   File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/diffusers/models/unet_2d_condition.py", line 849, in forward
    if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```


@patrickvonplaten even with CUDA 11.8:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by patrickvonplaten** [comment]
Uff this will be difficult to reproduce - can you send a code snippet?

**Comment by frankjoshua** [comment]
I just recreated it with diffusers 0.21.4 and 0.22.0.dev0

```
from diffusers import StableDiffusionXLPipeline
import torch

pipe = StableDiffusionXLPipeline.from_pretrained(
"stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
pipe.to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image = pipe(prompt=prompt).images[0]
```

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.0
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: RTX3090
- Using distributed or parallel set-up in script?: no

here is my Dockerfile
```
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
LABEL maintainer="Hugging Face"
LABEL repository="diffusers"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y --no-install-recommends bash \
                   build-essential \
                   git \
                   git-lfs \
                   curl \
                   ca-certificates \
                   libsndfile1-dev \
                   libgl1 \
                   python3 \
                   python3-pip \
                   python3-venv && \
    rm -rf /var/lib/apt/lists

# make sure to use venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

ENV PIP_FLAGS="--no-cache-dir"

COPY requirements.txt requirements.txt
RUN python3 -m pip install $PIP_FLAGS --upgrade pip && \
    python3 -m pip install $PIP_FLAGS -r requirements.txt
```

Here is my requirements.txt
```
nsfw-detector
protobuf==3.19.6
sentry-sdk
compel
fastapi
uvicorn

validators
pynvml

opencv-contrib-python-headless
opencv-python-headless
controlnet_aux
matplotlib
# diffusers[torch]
git+https://github.com/huggingface/diffusers.git@533771fb7c34c4b864507210692046b9a2fece38#egg=diffusers[torch]
omegaconf
transformers
```

**Comment by patrickvonplaten** [comment]
I don't fully understand why PyTorch is downloaded as CUDA 12.1 but then a CUDA 11.8 image is used. I think the PyTorch version
> PyTorch version (GPU?): 2.1.0+cu121 (True)
has to match the docker cuda image:
> FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

Also cc @DN6 could you check here?

**Comment by frankjoshua** [comment]
I was able to get things working using this Dockerfile with cuda 12.1. Interestingly The newest cuda 12.2.2 did not work.
[](https://github.com/huggingface/diffusers/blob/7c3a75a1ce7bdae1632dbcfd0bf2fda349a6fa36/docker/diffusers-pytorch-cuda/Dockerfile)
