### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by domef** [huggingface/diffusers#4390]
### Describe the bug

When I try to use `StableDiffusionControlNetPipeline` or `StableDiffusionControlNetImg2ImgPipeline` I get an error. If I install `transformers` it works correctly.
My question is: why `transformers` is not in the requirements of `diffusers` if it is necessary to load some models?

### Reproduction

```python
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth")
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet
)
```

```python
from diffusers import ControlNetModel, StableDiffusionControlNetImg2ImgPipeline

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth")
pipe = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet
)
```

### Logs

```shell
Traceback (most recent call last):
  File "program.py", line 22, in <module>
    pipe = StableDiffusionControlNetPipeline.from_pretrained(
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/utils/dummy_torch_and_transformers_objects.py", line 572, in from_pretrained
    requires_backends(cls, ["torch", "transformers"])
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/utils/import_utils.py", line 544, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
StableDiffusionControlNetPipeline requires the transformers library but it was not found in your environment. You can install it with pip: `pip
install transformers`
```

```shell
Traceback (most recent call last):
  File "program.py", line 8, in <module>
    pipe = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/utils/dummy_torch_and_transformers_objects.py", line 542, in from_pretrained
    requires_backends(cls, ["torch", "transformers"])
  File "/home/federico/Desktop/bug_diffusers/.venv/lib/python3.8/site-packages/diffusers/utils/import_utils.py", line 544, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
StableDiffusionControlNetImg2ImgPipeline requires the transformers library but it was not found in your environment. You can install it with pip: `pip
install transformers`
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
- Python version: 3.8.17
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: not installed
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @domef,

`transformers` is not needed for all models. E.g. the DIT model doesn't need `transformers` => therefore it's a soft dependency and not a hard dependency.

**Comment by domef** [comment]
Thank you for the answer, is there a way to know the dependencies of a model before instantiating it?

**Comment by sayakpaul** [comment]
You can follow the `__init__.py` of the pipelines/models to get a handle beforehand :)

**Comment by seven-dev** [comment]
I'm having a similar issue. I tried to install transformers in many different ways but none of them worked...
`pip install transformers[torch]`

This occurred while trying to run this model:
https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0


```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[56], line 13
      8 controlnet = ControlNetModel.from_pretrained(
      9     "diffusers/controlnet-canny-sdxl-1.0",
     10     torch_dtype=torch.float16
     11 )
     12 vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
---> 13 pipe = StableDiffusionControlNetPipeline.from_pretrained(
     14     "stabilityai/stable-diffusion-base-1.0",
     15     controlnet=controlnet,
     16     vae=vae,
     17     torch_dtype=torch.float16,
     18 )
     19 pipe.enable_model_cpu_offload()
     21 image = np.array(image)

File /usr/local/lib/python3.8/dist-packages/diffusers/utils/dummy_torch_and_transformers_objects.py:572, in StableDiffusionControlNetPipeline.from_pretrained(cls, *args, **kwargs)
    570 @classmethod
    571 def from_pretrained(cls, *args, **kwargs):
--> 572     requires_backends(cls, ["torch", "transformers"])

File /usr/local/lib/python3.8/dist-packages/diffusers/utils/import_utils.py:544, in requires_backends(obj, backends)
    542 failed = [msg.format(name) for available, msg in checks if not available()]
    543 if failed:
--> 544     raise ImportError("".join(failed))
    546 if name in [
    547     "VersatileDiffusionTextToImagePipeline",
    548     "VersatileDiffusionPipeline",
   (...)
    551     "UnCLIPPipeline",
    552 ] and is_transformers_version("<", "4.25.0"):
    553     raise ImportError(
    554         f"You need to install `transformers>=4.25` in order to use {name}: \n```\n pip install"
    555         " --upgrade transformers \n```"
    556     )

ImportError: 
StableDiffusionControlNetPipeline requires the transformers library but it was not found in your environment. You can install it with pip: `pip
install transformers`
```
