### ISSUE TITLE
Loading Lora safetensor: local variable 'state_dict' referenced before assignment

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#4504]
### Describe the bug

There are 2 errors: 
1.
```
!python ./diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./loras/test_model.safetensors  --dump_path ./test_model --from_safetensors

2023-08-07 04:40:53.152295: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 138, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1233, in download_from_original_stable_diffusion_ckpt
    checkpoint = safe_load(checkpoint_path, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```
2 
```
pipeline.load_lora_weights("/content/loras/test_model.safetensors")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-32-62067cfbdb85>](https://localhost:8080/#) in <cell line: 1>()
----> 1 pipeline.load_lora_weights("/content/loras/test_model.safetensors")

1 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py](https://localhost:8080/#) in lora_state_dict(cls, pretrained_model_name_or_path_or_dict, **kwargs)
   1082                 or k.startswith("lora_te2_")
   1083             )
-> 1084             for k in state_dict.keys()
   1085         ):
   1086             # Map SDXL blocks correctly.

UnboundLocalError: local variable 'state_dict' referenced before assignment
```

### Reproduction

```
pip install -q 'git+https://github.com/huggingface/diffusers'
pip install omegaconf torchvision safetensors

!wget -O test_model.safetensors https://civitai.com/models/7094/arcane-style-lora
!mkdir loras && mv test_model.safetensorss loras

!git clone https://github.com/huggingface/diffusers

!python ./diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./loras/test_model.safetensors  --dump_path ./test_model --from_safetensors

import torch
from diffusers import StableDiffusionPipeline

pipeline = StableDiffusionPipeline.from_pretrained(
    "stablediffusionapi/deliberate-v2"
    , torch_dtype = torch.float16
    , safety_checker = None
).to("cuda:0")

# lora_path = "./test_model.safetensors"
# text2img_pipe.load_lora_weights(lora_path)
pipeline.scheduler = DPMSolverMultistepScheduler.from_config(
    pipeline.scheduler.config, use_karras_sigmas=True
)

pipeline.load_lora_weights("/content/loras/test_model.safetensors")
```
i have also looked at https://github.com/huggingface/diffusers/issues/4348 but was not able to address the issue 

### Logs

```shell
2023-08-07 04:40:53.152295: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/./diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 138, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1233, in download_from_original_stable_diffusion_ckpt
    checkpoint = safe_load(checkpoint_path, device="cpu")
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-32-62067cfbdb85> in <cell line: 1>()
----> 1 pipeline.load_lora_weights("/content/loras/test_model.safetensors")

1 frames
/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py in lora_state_dict(cls, pretrained_model_name_or_path_or_dict, **kwargs)
   1082                 or k.startswith("lora_te2_")
   1083             )
-> 1084             for k in state_dict.keys()
   1085         ):
   1086             # Map SDXL blocks correctly.

UnboundLocalError: local variable 'state_dict' referenced before assignment
```
```


### System Info

colab notebook 

### Who can help?

@sayakpaul @patrickvonplaten @williamberman

**Comment by sayakpaul** [comment]
Should be fixed in https://github.com/huggingface/diffusers/pull/4523.
