### ISSUE TITLE
LoRA scale kwarg doesn't work with Attention Slicing

### ISSUE THREAD

**Issue by soten355** [huggingface/diffusers#4520]
### Describe the bug

When I try to use LoRA scale with Attention Slicing, it results in this error:
```shell
TypeError: SlicedAttnProcessor.__call__() got an unexpected keyword argument 'scale'
```
### Reproduction

Here's a simplified reproduction:

I load my pipeline and then LoRA weights.

After my pipeline is set up, I run:
```python
self.pipeline.enable_attention_slicing(1)
```

Then I perform inference:

```python
decoded = self.pipeline(
    prompt_embeds = promptEmbedding,
    negative_prompt_embeds = negativeEmbedding,
    num_inference_steps = num_steps,
    guidance_scale = unconditional_guidance_scale,
    generator = seed,
    num_images_per_prompt = batch_size,
    cross_attention_kwargs = {"scale" : loraScale}
)
```

When diffusers starts doing inference, the error occurs.

### Logs

```shell
Traceback (most recent call last):
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/dream.py", line 645, in create
    result = self.generateArt(sampleMethod = self.sampleMethod, vPrediction = vPrediction)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/dream.py", line 770, in generateArt
    imgs = self.generator.generate(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/stableDiffusionDiffusers/stableDiffusion.py", line 532, in generate
    decoded = self.pipeline(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 735, in __call__
    noise_pred = self.unet(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 905, in forward
    sample, res_samples = downsample_block(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 993, in forward
    hidden_states = attn(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 291, in forward
    hidden_states = block(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/tomesd/patch.py", line 111, in forward
    attn_output = self.attn1(
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Volumes/Andy-2021/Programming/Python/MetalDiffusion/venv/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 321, in forward
    return self.processor(
TypeError: SlicedAttnProcessor.__call__() got an unexpected keyword argument 'scale'
```

### System Info

- `diffusers` version: 0.18.1
- Platform: macOS-13.4.1-x86_64-i386-64bit
- Python version: 3.10.10
- PyTorch version (GPU?): 2.0.1 (False)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: not installed
- Using GPU in script?: MPS (MacOS)
- Using distributed or parallel set-up in script?: No

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Is it possible for you to use `xformers` to enable memory-efficient attention computation? If you are on PyTorch 2.0 and CUDA 11.7 (at least), we by default leverage SDPA which gives `xformers`-like performance already. 

So, when either of SDPA or `xformers`-honed memory-efficient attention computation is enabled we really don't need to do attention slicing.

**Comment by soten355** [comment]
> Is it possible for you to use `xformers` to enable memory-efficient attention computation? If you are on PyTorch 2.0 and CUDA 11.7 (at least), we by default leverage SDPA which gives `xformers`-like performance already.
> 
> So, when either of SDPA or `xformers`-honed memory-efficient attention computation is enabled we really don't need to do attention slicing.

Unfortunately I can't use xformers because I'm developing for Mac Users and can only use Metal Performance Shaders (MPS).

**Comment by soten355** [comment]
> Is it possible for you to use `xformers` to enable memory-efficient attention computation? If you are on PyTorch 2.0 and CUDA 11.7 (at least), we by default leverage SDPA which gives `xformers`-like performance already.
> 
> So, when either of SDPA or `xformers`-honed memory-efficient attention computation is enabled we really don't need to do attention slicing.

Unfortunately I can't use `xformers` because I'm developing for Mac users and rely on MPS (Metal).

EDIT: Apologies for re-opening, accidentally closed on prior comment

**Comment by soten355** [comment]
Unfortunately I can't use xformers because I'm developing for Mac users and rely on MPS (Metal).

EDIT: Apologies for re-opening, accidentally closed on prior commen

**Comment by sayakpaul** [comment]
How about SDPA?

**Comment by soten355** [comment]
> How about SDPA?

I'll give it a try! Seems like it's activated automatically because I'm using Pytorch 2.0

For reference (to anyone reading): https://pytorch.org/blog/accelerated-diffusers-pt-20/


EDIT:

Tried it. When I explicitly call `self.pipeline.unet.set_attn_processor(AttnProcessor2_0())`, I get the same error.

However, when I don't explicitly call, then it works fine. Maybe something you need to add the keyword arg to AttnProcessor2_0?

**Comment by sayakpaul** [comment]
Hmm not sure about that, honestly. 

So, if things are working as expected, do you think it's worth closing the issue?

**Comment by soten355** [comment]
I think it's an issue that should still be addressed, especially if I'm explicitly calling a specific attention processor or using attention slicing.

**Comment by sayakpaul** [comment]
I think I know what is happening here. For operating with LoRAs, we make use of specialized attention processors (such as LoRAAttnProcessor which has its xformers as well as SDPA variants). 

These processors have the scale argument supported, however, LoRA doesn't have any sliced attention processor as it doesn't need to since we're dealing with decomposed matrices. 

So, I think the current behaviour is expected.

**Comment by soten355** [comment]
Ah, that makes sense!

So, the answer is:

Don't use attention slicing when using LoRA's with PyTorch 2.0 because Diffusers inherently already does that?

**Comment by sayakpaul** [comment]
And xformers too (when applicable). 

Since SDPA and xformers hiked attention processors are already optimised, no need to use slicing. 

Does that make sense?

**Comment by soten355** [comment]
Absolutely, thank you! Closing now.
