### ISSUE TITLE
TensorRT inpainting bug .

### ISSUE THREAD

**Issue by kelisiya** [huggingface/diffusers#4525]
When I load Engine model , there is a error  when I inference single image ok . 
`cost time , 1.0900559425354004
inference ok .
Exception ignored in: <function Engine.__del__ at 0x7f90f32c44c0>
Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in __del__
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in <listcomp>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
Exception ignored in: <function Engine.__del__ at 0x7f90f32c44c0>
Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in __del__
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in <listcomp>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
Exception ignored in: <function Engine.__del__ at 0x7f90f32c44c0>
Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in __del__
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in <listcomp>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
Exception ignored in: <function Engine.__del__ at 0x7f90f32c44c0>
Traceback (most recent call last):
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in __del__
  File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_inpaint.py", line 116, in <listcomp>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union`

**Comment by sayakpaul** [comment]
We don't maintain the TensorRT integrations. Feel free to ping the original author for that purpose. 

Closing this issue hence.
