### ISSUE TITLE
`NotImplementedError` for `aten::index.Tensor` when using `mps`

### ISSUE THREAD

**Issue by fabianmax** [huggingface/diffusers#455]
### Describe the bug

I tried to use `StableDiffusionPipeline` with the lately added support for M1 (`mps`) as described in this [tweet](https://twitter.com/pcuenq/status/1567927480253808647).

Despite having installed the latest (preview) nighly PyTorch Build via 
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`, I ran into an `NotImplementedError` that hints that `aten::index.Tensor` is currently not implemented for MPS device. 

From the [official PyTorch issue on MPS support](https://github.com/pytorch/pytorch/issues/77764), it is not clear to me if `aten::index.Tensor` is already implemented (even in the nightly). Because more people there reporting issues about it.

Hardware: 2021 Macbook Pro 16" with M1 Pro

### Reproduction

```
import torch
from diffusers import StableDiffusionPipeline

token = '...'

device = "mps" if torch.backends.mps.is_available() else "cpu"
model_id = 'CompVis/stable-diffusion-v1-4'

pipe = StableDiffusionPipeline.from_pretrained(model_id, use_auth_token=token)
pipe = pipe.to(device)

prompt = "a photo of a cat trending on artstation"
image = pipe(prompt).images[0]
```

### Logs

```shell
Traceback (most recent call last):
  File "/Users/fabianmueller/.pyenv/versions/3.10.3/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 19, in <module>
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 182, in __call__
    text_embeddings = self.text_encoder(text_input.input_ids.to(self.device))[0]
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 728, in forward
    return self.text_model(
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/fabianmueller/Projekte/intern-stable-diffusion/.venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 663, in forward
    pooled_output = last_hidden_state[torch.arange(last_hidden_state.shape[0]), input_ids.argmax(dim=-1)]
NotImplementedError: The operator 'aten::index.Tensor' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

### System Info

- `diffusers` version: 0.3.0
- Platform: macOS-12.5.1-arm64-arm-64bit
- Python version: 3.10.3
- PyTorch version (GPU?): 1.12.1 (False)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.21.3
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

**Comment by fabianmax** [comment]
PyTorch 1.13.x is not available as pre-built binary, correct? So installing from source is the only option I guess?

**Comment by abesmon** [comment]
You can get it from nightly builds:

`pip3 install --upgrade --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

**Comment by fabianmax** [comment]
yes thanks, now it's working on `mps`.
