### ISSUE TITLE
convert_lora_safetensor_to_diffusers.py for SDXL not working 

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#4616]
### Describe the bug

```
Downloading (…)ch_model.safetensors: 100% 10.3G/10.3G [02:35<00:00, 66.2MB/s]
Fetching 19 files: 100% 19/19 [02:36<00:00,  8.23s/it]
Loading pipeline components...: 100% 5/5 [00:04<00:00,  1.01it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 55, in convert
    curr_layer = curr_layer.__getattr__(temp_name)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 185, in __getattr__
    return super().__getattr__(name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'input_blocks_4_1_proj_in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 125, in <module>
    pipe = convert(base_model_path, checkpoint_path, lora_prefix_unet, lora_prefix_text_encoder, alpha)
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 62, in convert
    temp_name += "_" + layer_infos.pop(0)
IndexError: pop from empty list
```

### Reproduction

civitai:
```
https://civitai.com/models/126751/xl-fantasy-warriors-by-hailoknight
```

```
!python /content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py \
--base_model_path stabilityai/stable-diffusion-xl-base-1.0 \
--checkpoint_path /content/gdrive/MyDrive/lora_sdxl/Lora/XL_Fantasy_warriors_by_HailoKnight/XLKnightV1.safetensors \
--dump_path ./test_model \
--device='cuda:0'

```

### Logs

```shell
2023-08-15 10:22:53.757682: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading pipeline components...: 100% 5/5 [00:02<00:00,  2.12it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 55, in convert
    curr_layer = curr_layer.__getattr__(temp_name)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 185, in __getattr__
    return super().__getattr__(name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'input_blocks_4_1_proj_in'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 125, in <module>
    pipe = convert(base_model_path, checkpoint_path, lora_prefix_unet, lora_prefix_text_encoder, alpha)
  File "/content/diffusers/scripts/convert_lora_safetensor_to_diffusers.py", line 62, in convert
    temp_name += "_" + layer_infos.pop(0)
IndexError: pop from empty list
```
```


### System Info

google pro notebook

### Who can help?

@sayakpaul @patrickvonplaten @willia

**Comment by sayakpaul** [comment]
It's not supposed to work as SDXL support is not incorporated in that script. Use `load_lora_weights()` instead. Guidance: https://huggingface.co/docs/diffusers/main/en/training/lora#supporting-a1111-themed-lora-checkpoints-from-diffusers
