### ISSUE TITLE
Question about accelerator.end_training()

### ISSUE THREAD

**Issue by w-yibo** [huggingface/diffusers#4671]
It is ok when I use single gpu to run my code. When I use 4 GPU to run my code, when run `accelerator.end_training()`, I always gets this Error(although it has no influence on my training):

```
Traceback (most recent call last):
  File "/home/ma/anaconda3/envs/Geo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/site-packages/accelerate/commands/launch.py", line 906, in launch_command
    multi_gpu_launcher(args)
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/site-packages/accelerate/commands/launch.py", line 606, in multi_gpu_launcher
    raise
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/site-packages/accelerate/utils/other.py", line 119, in patch_environment
    del os.environ[key.upper()]
  File "/home/ma/anaconda3/envs/Geo/lib/python3.8/os.py", line 691, in __delitem__
    raise KeyError(key) from None
```
My env:
diffusers == 0.19.0
4 * Tesla V100S-PCIE-32GB

**Comment by sayakpaul** [comment]
Seems more like an `accelerate` issue. So, I would recommend opening it up on that repository.
