### ISSUE TITLE
script in official Text-guided image-inpainting doc reports an error

### ISSUE THREAD

**Issue by realliujiaxu** [huggingface/diffusers#4677]
### Describe the bug

Running script in official Text-guided image-inpainting doc(https://huggingface.co/docs/diffusers/using-diffusers/inpaint) reports an error

### Reproduction

```python
import PIL
import requests
import torch
from io import BytesIO

from diffusers import StableDiffusionInpaintPipeline

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=True,
)
pipeline = pipeline.to("cuda") 
```

### Logs

```shell
safety_checker/model.safetensors not found
safety_checker/model.safetensors not found
False
Traceback (most recent call last):
  File "inpainting.py", line 8, in <module>
    pipeline = StableDiffusionInpaintPipeline.from_pretrained(
  File "/root/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 933, in from_pretrained
    cached_folder = cls.download(
  File "/root/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1444, in download
    raise EnvironmentError(
OSError: Could not found the necessary `safetensors` weights in {'safety_checker/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'unet/diffusion_pytorch_model.bin', 'vae/diffusion_pytorch_model.bin'} (variant=None)
```

### System Info

diffusers: 0.21.0.dev0
python: 3.8.10

**Comment by realliujiaxu** [comment]
I find that adding `variant="fp16"` to `StableDiffusionInpaintPipeline.from_pretrained(...)` or removing `use_safetensors=True` fixes this problem. 
Given that the community recommends using safetensor by default in the documentation, I would recommend adding the parameter `variant="fp16"`.

**Comment by sayakpaul** [comment]
Cc: @stevhliu
