### ISSUE TITLE
Issue with UNet2DConditionModel memory?

### ISSUE THREAD

**Issue by ChristopherOoi** [huggingface/diffusers#4692]
### Describe the bug

tried running the UNet2DConditionModel with image input size of [512,512] but it keeps producing OOM error that is abnormally huge.

### Reproduction

```import torch
from diffusers import UNet2DConditionModel

def UNet2DCond (image_size):
    model = UNet2DConditionModel(
        sample_size=image_size,  # the target image resolution
        in_channels=3,  # the number of input channels, 3 for RGB images
        out_channels=3,  # the number of output channels
        layers_per_block=2,  # how many ResNet layers to use per UNet block
        encoder_hid_dim_type = "text_proj",
        encoder_hid_dim=2,
        block_out_channels=(320, 640, 640, 1280, 1280),  # the number of output channes for each UNet block
        down_block_types=(
            "CrossAttnDownBlock2D",
            "CrossAttnDownBlock2D",
            "CrossAttnDownBlock2D",  # a regular ResNet downsampling block
            "DownBlock2D",
            "DownBlock2D"
        ),
        up_block_types=(
            "UpBlock2D",
            "UpBlock2D",  # a regular ResNet upsampling block
            "CrossAttnUpBlock2D",  # a ResNet upsampling block with spatial self-attention
            "CrossAttnUpBlock2D",
            "CrossAttnUpBlock2D"
        ),
    )
    return model

model = UNet2DCond (512).to('cuda')

input_noise = torch.rand(1,3,512,512).to('cuda')
ts = torch.Tensor([10]).to('cuda')
emb = torch.rand(1, 2, 2).to('cuda')

print(model(input_noise, ts, emb)[0])
```
### Logs

```shell
Traceback (most recent call last):
  File "models.py", line 149, in <module>
    print(model(torch.rand(1,3,512,512).to('cuda'), torch.Tensor([10]).to('cuda'), torch.rand(1, 2, 2).to('cuda'))[0])
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 930, in forward
    sample, res_samples = downsample_block(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 1053, in forward
    hidden_states = attn(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 309, in forward
    hidden_states = block(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention.py", line 194, in forward
    attn_output = self.attn1(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 491, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 357, in get_attention_scores
    baddbmm_input = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2048.00 GiB (GPU 0; 23.99 GiB total capacity; 7.08 GiB already allocated; 13.86 GiB free; 7.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

- `diffusers` version: 0.20.0
- Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.17
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: not installed
- Using GPU in script?: 4090
- Using distributed or parallel set-up in script?: <fill in>

**Comment by sayakpaul** [comment]
Can I have a Colab Notebook instance reproducing the problem?

**Comment by ChristopherOoi** [comment]
Hm... Can't reproduce it on Colab.

We did further testing on two other machines, which did not show the same degree of error. The out of memory error was to be expected, but the amount of memory it tried to allocate was the problem. One was an ubuntu which ran up ~200mb, another 4090 showed 2.5gb, and Colab showing 1.25gb.

Tested without using WSL, showed the same excess in memory (128gb this time). 

Fresh install of the environment and packages yielded no results. Suspect it has to do with my specific computer and configurations... Will have to dig in further. 

Do let me know if there are any ideas or problems to target.

**Comment by sayakpaul** [comment]
Nothing that comes to mind. If this is a machine-specific problem, I think we can close this. But if you observe similar things across different machines, then definitely there could be a problem. 

> One was an ubuntu which ran up ~200mb, another 4090 showed 2.5gb, and Colab showing 1.25gb.

All of them had exact similar software libraries? I guess not, no?

**Comment by ChristopherOoi** [comment]
Not exact, but we tried to match them as best as we could. The inconsistency in sizes is the most interesting issue. 

Indeed seems to be machine specific, and will look into it separately then. Thanks for your time!

**Comment by sayakpaul** [comment]
Please keep us posted with your findings!

**Comment by ChristopherOoi** [comment]
Some progress... I think?

Managed to reproduce it in collab here: https://colab.research.google.com/drive/1hPdpCMAW3sIKli1wKEjsGOXUj-dyGwt2?usp=sharing

Still quite new to all this so...

```
Traceback (most recent call last):
  File "/home/krise/diffusion_custom/models.py", line 149, in <module>
    print(model(torch.rand(1,3,512,512).to('cuda'), torch.Tensor([10]).to('cuda'), torch.rand(1, 2, 2).to('cuda'))[0])
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 930, in forward
    sample, res_samples = downsample_block(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1053, in forward
    hidden_states = attn(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 309, in forward
    hidden_states = block(
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/attention.py", line 242, in forward
    ff_output = self.ff(norm_hidden_states)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/attention.py", line 300, in forward
    hidden_states = module(hidden_states)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/attention.py", line 347, in forward
    return hidden_states * self.gelu(gate)
  File "/home/krise/anaconda3/envs/ldm/lib/python3.10/site-packages/diffusers/models/attention.py", line 341, in gelu
    return F.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 640.00 MiB (GPU 0; 23.99 GiB total capacity; 36.59 GiB already allocated; 0 bytes free; 36.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

Installing torch 2.0.1 gave me an error of allocating 128gb, and downgrading to 2.0.0 produces the more reasonable 640 above.

Still not sure what this all points to as torch 2.0.1 does not have such a large memory need in colab.

**Comment by sayakpaul** [comment]
Why are you reinstalling the cuda drivers?

**Comment by ChristopherOoi** [comment]
I am simply following the instructions listed on the Pytorch website : https://pytorch.org/get-started/previous-versions/

Am under the impression that doing the installation for Pytorch this way is what allows for the use of GPU capabilities. Why would that pose an issue?

**Comment by sayakpaul** [comment]
Colab comes pre-installed with those things.

**Comment by ChristopherOoi** [comment]
Indeed, but it comes with version 2.0.1. To replicate the issue I had to downgrade to the version that was on my machine, 1.13.1.
