### ISSUE TITLE
import diffusers.utils error

### ISSUE THREAD

**Issue by kkwhale7** [huggingface/diffusers#4708]
### Describe the bug

Traceback (most recent call last):
  File "demo_controlnet.py", line 9, in <module>
    from diffusers.utils import load_image
  File "/usr/local/lib/python3.8/dist-packages/diffusers/__init__.py", line 30, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/__init__.py", line 49, in <module>
    from .audioldm2 import AudioLDM2Pipeline, AudioLDM2ProjectionModel, AudioLDM2UNet2DConditionModel
ImportError: cannot import name 'AudioLDM2Pipeline' from 'diffusers.pipelines.audioldm2' (/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/audioldm2/__init__.py)

### Reproduction

1

### System Info

1

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by nickovchinnikov** [comment]
I can reproduce this in my local env

diffusers==0.20.2
transformers==4.32.1

`from diffusers import AudioLDM2Pipeline`

As the result:

```
ImportError                               Traceback (most recent call last)
[d:\Projects\TTS\experiments\audioldm2.py](file:///D:/Projects/TTS/experiments/audioldm2.py) in line 7
      [5](file:///d%3A/Projects/TTS/experiments/audioldm2.py?line=4) import scipy
      [6](file:///d%3A/Projects/TTS/experiments/audioldm2.py?line=5) import torch
----> [7](file:///d%3A/Projects/TTS/experiments/audioldm2.py?line=6) from diffusers import AudioLDM2Pipeline
      [9](file:///d%3A/Projects/TTS/experiments/audioldm2.py?line=8) repo_id = "cvssp/audioldm2"
     [10](file:///d%3A/Projects/TTS/experiments/audioldm2.py?line=9) pipe = AudioLDM2Pipeline.from_pretrained(repo_id, torch_dtype=torch.float16)

ImportError: cannot import name 'AudioLDM2Pipeline' from 'diffusers' (d:\Program Files\anaconda3\Lib\site-packages\diffusers\__init__.py)
```
