### ISSUE TITLE
Failed to establish a new connection

### ISSUE THREAD

**Issue by YoucanBaby** [huggingface/diffusers#4866]
I have cached the model locally before. But I get this error.

```sh
Traceback (most recent call last):
  File "/root/data/xyf/Personalization/sd-scripts/inpaint_img.py", line 26, in <module>
    pipe = StableDiffusionInpaintPipeline.from_single_file(
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/diffusers/loaders.py", line 2100, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1277, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries 
exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by 
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7963817400>: 
Failed to establish a new connection: [Errno 111] Connection refused'))
```

Source code:

```python
model_path = "https://huggingface.co/SG161222/Realistic_Vision_V2.0/blob/main/Realistic_Vision_V2.0-inpainting.ckpt"

pipe = StableDiffusionInpaintPipeline.from_single_file(
    pretrained_model_link_or_path=model_path,
    # cache_dir=cache_dir,
    # use_safetensors=True,
    # local_files_only=True,
    safety_checker=None,
    requires_safety_checker=False,
).to(device)
```

**Comment by YoucanBaby** [comment]
Actually, I've never successfully loaded any local `.safetensors` or `.ckpt` using `from_single_file()`.

**Comment by patrickvonplaten** [comment]
Duplicate of https://github.com/huggingface/diffusers/issues/4828 

I'm having a hard time reproducing this issue. Could you try to reproduce it on a Google Colab?

**Comment by YoucanBaby** [comment]
> Duplicate of #4828
> 
> I'm having a hard time reproducing this issue. Could you try to reproduce it on a Google Colab?

Same question.

https://discuss.huggingface.co/t/unable-to-run-diffusers-while-offline/50968

**Comment by Damarcreative** [comment]
Same problem as before, Hope this helps
https://github.com/huggingface/diffusers/issues/4868

**Comment by YoucanBaby** [comment]
> Same problem as before, Hope this helps #4868

Thx for your code!~  But I still get the same error on my computer. I think it seems to be a network problem.

**Comment by patrickvonplaten** [comment]
For everyone here - make sure to add `local_files_only=True` when running `from_pretrained(...)` if you don't want to connect to the internet (we do this to automatically check for updates)
