### ISSUE TITLE
AttributeError: 'super' object has no attribute '__getattr__'. Did you mean: '__setattr__'?

### ISSUE THREAD

**Issue by Kuchizu** [huggingface/diffusers#4868]
### Describe the bug

I'm getting this error after running quickstart code on Arch:

```
Traceback (most recent call last):
  File "/home/kuchizu/Desktop/StableDiffusion/main.py", line 4, in <module>
    pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 932, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1449, in download
    use_onnx = use_onnx if use_onnx is not None else pipeline_class._is_onnx
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/utils/import_utils.py", line 571, in __getattr__
    return super().__getattr__(cls, key)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute '__getattr__'. Did you mean: '__setattr__'?
```

### Reproduction

```
import torch
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipeline.to("cuda")
pipeline("An image of a squirrel in Picasso style").images[0]
```

### System Info

- `diffusers` version: 0.20.2
- Platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38
- Python version: 3.11.5
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: not installed
- Accelerate version: 0.22.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by Kuchizu** [comment]
I don't understand should I put model path to to that? Then I'm getting this:

```
import torch
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("runwayml/v1-5-pruned-emaonly.ckpt", torch_dtype=torch.float16)
pipeline.to("cuda")
pipeline("An image of a squirrel in Picasso style").images[0]
```

```
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-64f25875-4856086e31f46da258307ee4;6d65e8c1-525e-4cf2-8572-9d0c98bc6ae0)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/v1-5-pruned-emaonly.ckpt.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password..
Will try to load from local cache.
Traceback (most recent call last):
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/runwayml/v1-5-pruned-emaonly.ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1349, in download
    info = model_info(
           ^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1678, in model_info
    hf_raise_for_status(r)
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64f25875-4856086e31f46da258307ee4;6d65e8c1-525e-4cf2-8572-9d0c98bc6ae0)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/v1-5-pruned-emaonly.ckpt.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuchizu/Desktop/StableDiffusion/main.py", line 4, in <module>
    pipeline = DiffusionPipeline.from_pretrained("runwayml/v1-5-pruned-emaonly.ckpt", torch_dtype=torch.float16)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 932, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "/home/kuchizu/Desktop/StableDiffusion/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1552, in download
    raise EnvironmentError(
OSError: Cannot load model runwayml/v1-5-pruned-emaonly.ckpt: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
```

**Comment by Damarcreative** [comment]
Try downloading the model first, then navigate to the path to the model

`pipeline = StableDiffusionPipeline.from_single_file("/content/model/model.safetensors" ,torch_dtype=torch.float16).to('cuda')`

Try my code:
https://colab.research.google.com/drive/1I91Jr_pWgGBISrMzl3AiFj_W8tIKLfBw?usp=sharing

**Comment by Kuchizu** [comment]
> Try downloading the model first, then navigate to the path to the model
> 
> `pipeline = StableDiffusionPipeline.from_single_file("/content/model/model.safetensors" ,torch_dtype=torch.float16).to('cuda')`
> 
> Try my code: https://colab.research.google.com/drive/1I91Jr_pWgGBISrMzl3AiFj_W8tIKLfBw?usp=sharing

It worked, thank you.
