### ISSUE TITLE
CUDA out of memory on T4 Colab in SDXL finetuning

### ISSUE THREAD

**Issue by EnricoBeltramo** [huggingface/diffusers#4872]
### Describe the bug

   I'm trying to fine tuning  a SDXL model using a T4 (Colab notebook)

here the command:
 !accelerate launch train_text_to_image_lora_sdxl.py \
      --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
      --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
      --dataset_name="$INSTANCE_DIR_PARSED" \
      --caption_column="text" \
      --resolution=1024 \
      --train_batch_size=1 \
      --num_train_epochs=$TRAIN_EPOCHS \
      --checkpointing_steps=10 \
      --learning_rate=$LEARNING_RATE \
      --lr_scheduler="constant" \
      --lr_warmup_steps=0 \
      --seed=42 \
      --output_dir="$OUTPUT_DIR" \
      --enable_xformers_memory_efficient_attention \
      --gradient_checkpointing \
      --mixed_precision="fp16" \
      --use_8bit_adam

But I run in CUDA out of memory.
- if I use accellerate 0.22.0, OOM when start the training
- if I use accellerate 0.21.0, train start, but I havv OOM when try to store the first checkpoint

### Reproduction

Run:
 !accelerate launch train_text_to_image_lora_sdxl.py \
      --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
      --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
      --dataset_name="$INSTANCE_DIR_PARSED" \
      --caption_column="text" \
      --resolution=1024 \
      --train_batch_size=1 \
      --num_train_epochs=$TRAIN_EPOCHS \
      --checkpointing_steps=10 \
      --learning_rate=$LEARNING_RATE \
      --lr_scheduler="constant" \
      --lr_warmup_steps=0 \
      --seed=42 \
      --output_dir="$OUTPUT_DIR" \
      --enable_xformers_memory_efficient_attention \
      --gradient_checkpointing \
      --mixed_precision="fp16" \
      --use_8bit_adam

Wait start train or first checkpoint

### Logs

```shell
Error on start training (accellerate 0.22.0):

2023-09-02 08:00:47.790561: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-09-02 08:00:53.072209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
09/02/2023 08:00:55 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'dynamic_thresholding_ratio', 'thresholding', 'variance_type', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'attention_type'} was not found in config. Values will be initialized to default values.
Resolving data files: 100% 155/155 [00:00<00:00, 308844.24it/s]
Downloading data files: 100% 155/155 [00:00<00:00, 50782.47it/s]
Downloading data files: 0it [00:00, ?it/s]
Extracting data files: 0it [00:00, ?it/s]
Generating train split: 154 examples [00:00, 1444.48 examples/s]
09/02/2023 08:02:40 - INFO - __main__ - ***** Running training *****
09/02/2023 08:02:40 - INFO - __main__ -   Num examples = 154
09/02/2023 08:02:40 - INFO - __main__ -   Num Epochs = 1
09/02/2023 08:02:40 - INFO - __main__ -   Instantaneous batch size per device = 1
09/02/2023 08:02:40 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
09/02/2023 08:02:40 - INFO - __main__ -   Gradient Accumulation steps = 1
09/02/2023 08:02:40 - INFO - __main__ -   Total optimization steps = 154
Steps:   0% 0/154 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1271, in <module>
    main(args)
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1051, in main
    model_pred = unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 632, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 620, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 985, in forward
    sample = upsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 2187, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/transformer_2d.py", line 309, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention.py", line 215, in forward
    attn_output = self.attn2(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 322, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 1345, in __call__
    hidden_states = attn.to_out[0](hidden_states) + scale * self.to_out_lora(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 14.75 GiB total capacity; 13.21 GiB already allocated; 832.00 KiB free; 13.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0% 0/154 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--dataset_name=/content/instancefolder_parsed', '--caption_column=text', '--resolution=1024', '--train_batch_size=1', '--num_train_epochs=1', '--checkpointing_steps=10', '--learning_rate=5e-05', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/content/lora-trained-xl-colab', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--mixed_precision=fp16', '--use_8bit_adam']' returned non-zero exit status 1.
/content





Error on checkpoints (accellerate 0.21.0):
/content/diffusers/examples/text_to_image
2023-09-02 07:53:18.049038: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-09-02 07:53:25.951662: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
09/02/2023 07:53:27 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'dynamic_thresholding_ratio', 'clip_sample_range', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
{'attention_type'} was not found in config. Values will be initialized to default values.
Resolving data files: 100% 155/155 [00:00<00:00, 290101.35it/s]
Downloading data files: 100% 155/155 [00:00<00:00, 74248.19it/s]
Downloading data files: 0it [00:00, ?it/s]
Extracting data files: 0it [00:00, ?it/s]
Generating train split: 154 examples [00:00, 1721.80 examples/s]
09/02/2023 07:55:02 - INFO - __main__ - ***** Running training *****
09/02/2023 07:55:02 - INFO - __main__ -   Num examples = 154
09/02/2023 07:55:02 - INFO - __main__ -   Num Epochs = 1
09/02/2023 07:55:02 - INFO - __main__ -   Instantaneous batch size per device = 1
09/02/2023 07:55:02 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
09/02/2023 07:55:02 - INFO - __main__ -   Gradient Accumulation steps = 1
09/02/2023 07:55:02 - INFO - __main__ -   Total optimization steps = 154
Steps:   6% 10/154 [00:25<05:41,  2.37s/it, lr=5e-5, step_loss=0.0237]09/02/2023 07:55:27 - INFO - accelerate.accelerator - Saving current state to /content/lora-trained-xl-colab/checkpoint-10
Traceback (most recent call last):
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1271, in <module>
    main(args)
  File "/content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py", line 1131, in main
    accelerator.save_state(save_path)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2551, in save_state
    weights.append(self.get_state_dict(model, unwrap=False))
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 2851, in get_state_dict
    state_dict[k] = state_dict[k].float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 14.75 GiB total capacity; 13.82 GiB already allocated; 36.81 MiB free; 14.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   6% 10/154 [00:25<06:11,  2.58s/it, lr=5e-5, step_loss=0.0237]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--dataset_name=/content/instancefolder_parsed', '--caption_column=text', '--resolution=1024', '--train_batch_size=1', '--num_train_epochs=1', '--checkpointing_steps=10', '--learning_rate=5e-05', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--seed=42', '--output_dir=/content/lora-trained-xl-colab', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--mixed_precision=fp16', '--use_8bit_adam']' returned non-zero exit status 1.
/content
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-5.15.109+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.1
- Accelerate version: 0.21.0 (or 0.22.0)
- xFormers version: 0.0.21
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: no

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Don't use checkpointing.

**Comment by EnricoBeltramo** [comment]
I need checkpoint because for limits of kaggle/colab that I use I can't complete the training in only a single run and I need to restart starting from last checkpoint. But why the checkpoint cause a OOM?
And about the acellerate version will be changed or 0.22.0 version will use more memory?
