### ISSUE TITLE
StableDiffusionXLControlNetImg2ImgPipeline doesn't load LoRA weights

### ISSUE THREAD

**Issue by clixff** [huggingface/diffusers#4885]
### Describe the bug

I get `object has no attribute` error when I use `load_lora_weights()` in the `StableDiffusionXLControlNetImg2ImgPipeline`
Other pipelines such as `StableDiffusionXLPipeline` are working.

### Reproduction

```python
import torch
from diffusers import (
    ControlNetModel,
    AutoencoderKL,
    StableDiffusionXLControlNetImg2ImgPipeline,
)

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16, use_safetensors=True)

controlnet = ControlNetModel.from_pretrained(
     "diffusers/controlnet-canny-sdxl-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
).to("cuda")

pipe = StableDiffusionXLControlNetImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    vae=vae,
    controlnet=controlnet,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
).to("cuda")

pipe.load_lora_weights(
    "stabilityai/stable-diffusion-xl-base-1.0", 
    weight_name="sd_xl_offset_example-lora_1.0.safetensors"
)
print("Loading is done")
```

### Logs
If I load "sd_xl_offset_example-lora_1.0.safetensors":
```shell
Traceback (most recent call last):
  File "D:\source\sdxl-error\main.py", line 31, in <module>
    pipe.load_lora_weights("stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors")
  File "D:\source\sdxl-error\env\lib\site-packages\diffusers\loaders.py", line 950, in load_lora_weights
    self.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=self.unet)
  File "D:\source\sdxl-error\env\lib\site-packages\diffusers\loaders.py", line 1288, in load_lora_into_unet
    unet.load_attn_procs(state_dict, network_alphas=network_alphas)
  File "D:\source\sdxl-error\env\lib\site-packages\diffusers\loaders.py", line 398, in load_attn_procs
    attn_processor = getattr(attn_processor, sub_key)
  File "D:\source\sdxl-error\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CrossAttnDownBlock2D' object has no attribute '0'
```

If I load any other LoRA .safetensors file, I get this error:
```shell
  File "D:\source\sdxl-error\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '4'
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.1
- Accelerate version: 0.22.0

**Comment by patrickvonplaten** [comment]
Thanks for the nice bug report! Should be fixed in: #4896
