### ISSUE TITLE
SDXL CUDA OOM at end of training with BF16 but not with FP16

### ISSUE THREAD

**Issue by austinmw** [huggingface/diffusers#5006]
### Describe the bug

Hi, I'm attempting to run `train_dreambooth_lora_sdxl.py` on SageMaker with an A10 GPU (ml.g5.2xlarge).

When I set `--mixed_precision` to `fp16` the training completes without error, however, when I set it to `bf16`, I get a CUDA out of memory error at the very end of training. 

Should I be using `bf16` for the best speed and performance with DreamBooth LoRA on an A10 GPU? I also see an option for `--allow_tf32`, but I have not tried it.

### Reproduction

```python
from sagemaker.pytorch import PyTorch

hyperparameters = {
    # https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora_sdxl.py
    'pretrained_model_name_or_path': 'stabilityai/stable-diffusion-xl-base-1.0',
    # https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md#specifying-a-better-vae
    'pretrained_vae_model_name_or_path': 'madebyollin/sdxl-vae-fp16-fix',
    'instance_data_dir': '/opt/ml/code/dog',
    'output_dir': '/opt/ml/model',
    'instance_prompt': '"a photo of sks dog"',
    'resolution': 1024,
    'train_batch_size': 1,
    'gradient_accumulation_steps': 4,
    'checkpointing_steps': 100,
    'checkpoints_total_limit': 3,
    'learning_rate': 1e-5,
    'report_to': 'tensorboard',
    'lr_scheduler': 'constant',
    'lr_warmup_step': 0,
    'max_train_steps': 500,
    'validation_prompt': '"A photo of sks dog in a bucket"',
    'num_validation_images': 4,
    'validation_epochs': 25,
    'seed': '0',
    'mixed_precision': 'fp16',  # Setting to 'bf16' causes CUDA OOM error
}

estimator = PyTorch(entry_point='train_dreambooth_lora_sdxl.py',
                    source_dir='train_scripts',
                    dependencies=['dog'],  # local data directory
                    role=role,
                    framework_version='2.0',
                    py_version='py310',
                    train_instance_count=1,
                    train_instance_type='ml.g5.2xlarge',
                    output_path=output_path,
                    sagemaker_session=sagemaker_session,
                    hyperparameters=hyperparameters)

estimator.fit()
```

### Logs

```shell
Traceback (most recent call last):
  File "/opt/ml/code/train_dreambooth_lora_sdxl.py", line 1384, in <module>
main(args)
  File "/opt/ml/code/train_dreambooth_lora_sdxl.py", line 1343, in main
images = [
  File "/opt/ml/code/train_dreambooth_lora_sdxl.py", line 1344, in <listcomp>
pipeline(args.validation_prompt, num_inference_steps=25, generator=generator).images[0]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 867, in __call__
image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False)[0]
  File "/opt/conda/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
return method(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 286, in decode
decoded = self._decode(z).sample
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py", line 273, in _decode
dec = self.decoder(z)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/vae.py", line 272, in forward
sample = up_block(sample, latent_embeds)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 2375, in forward
hidden_states = upsampler(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/resnet.py", line 164, in forward
hidden_states = hidden_states.to(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 22.19 GiB total capacity; 20.92 GiB already allocated; 143.50 MiB free; 21.70 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps: 100%|██████████| 500/500 [46:46<00:00,  5.61s/it, loss=0.249, lr=1e-5]
```
```


### System Info

Running on SageMaker with ml.g5.2xlarge instance type

### Who can help?

@sayakpaul @williamberman @patrickvonplaten

**Comment by sayakpaul** [comment]
Would suggest using FP16 all times probably as I haven't seen any significant performance gaps.

**Comment by bghira** [comment]
it's the VAE specifically causing the error. likely your training completed just fine, it just crashed during validation.

most likely there is some subtle issue in the autocasting or weight casting of the VAE.
