### ISSUE TITLE
wuerstchen error

### ISSUE THREAD

**Issue by flozi00** [huggingface/diffusers#5009]
### Describe the bug

```
Traceback (most recent call last):
  File "/home/primeline-ai/atra/w.py", line 28, in <module>
    height=1024,
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/diffusers/pipelines/wuerstchen/pipeline_wuerstchen.py", line 369, in __call__
    predicted_latents = self.decoder(
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_diffnext.py", line 225, in forward
    level_outputs = self._down_encode(x, r_embed, effnet, clip)
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_diffnext.py", line 176, in _down_encode
    x = block(x, skip)
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/primeline-ai/.local/lib/python3.10/site-packages/diffusers/pipelines/wuerstchen/modeling_wuerstchen_diffnext.py", line 252, in forward
    x = torch.cat([x, x_skip], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 2 for tensor number 1 in the list.
```

### Reproduction

```
import torch
from diffusers import WuerstchenDecoderPipeline, WuerstchenPriorPipeline
from diffusers.pipelines.wuerstchen import DEFAULT_STAGE_C_TIMESTEPS

device = "cuda"
dtype = torch.float16
num_images_per_prompt = 2

prior_pipeline = WuerstchenPriorPipeline.from_pretrained(
    "warp-ai/wuerstchen-prior", torch_dtype=dtype
).to(device)
decoder_pipeline = WuerstchenDecoderPipeline.from_pretrained(
    "warp-ai/wuerstchen", torch_dtype=dtype
).to(device)


caption = "Anthropomorphic cat dressed as a fire fighter"
negative_prompt = ""

prior_output = prior_pipeline(
    prompt=caption,
    height=1024,
    width=1536,
    timesteps=DEFAULT_STAGE_C_TIMESTEPS,
    negative_prompt=negative_prompt,
    guidance_scale=4.0,
    num_images_per_prompt=num_images_per_prompt,
)
decoder_output = decoder_pipeline(
    image_embeddings=prior_output.image_embeddings,
    prompt=caption,
    negative_prompt=negative_prompt,
    num_images_per_prompt=num_images_per_prompt,
    guidance_scale=0.0,
    output_type="pil",
).images

for i, image in enumerate(decoder_output):
    image.save(f"image_{i}.png")

```

### System Info

Master branch diffusers
Latest torch
cuda 11.8
Python 3.10

### Who can help?

@patrickvonplaten @dome272

**Comment by flozi00** [comment]
Solution is setting guidance_scale and num_images_per_prompt to the same value in prior_pipeline

**Comment by flozi00** [comment]
okay, I was wrong
fix was setting tokenizers parallel to false
