### ISSUE TITLE
How to give number of inference steps to Wuerstchen prior pipeline

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/diffusers#5042]
**this below working with default DEFAULT_STAGE_C_TIMESTEPS but it always generates with exactly 29 number of prior inference steps** 

```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		num_inference_steps=prior_num_inference_steps,
        timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )
```

when i make it like below i got this error

```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		prior_num_inference_steps = prior_num_inference_steps,
        # timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )
```

`TypeError: WuerstchenPriorPipeline.__call__() got an unexpected keyword argument 'prior_num_inference_steps'`

But the documentation showing it???

https://huggingface.co/docs/diffusers/main/en/api/pipelines/wuerstchen

`prior_num_inference_steps (Union[int, Dict[float, int]], optional, defaults to 30) — The number of prior denoising steps. More denoising steps usually lead to a higher quality image at the expense of slower inference. For more specific timestep spacing, you can pass customized prior_timesteps`

@sayakpaul  @dome272  @patrickvonplaten @williamberman

**Here below entire code. what I want is being able to set any number of prior and decoder number of inference steps**

```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		prior_num_inference_steps = prior_num_inference_steps,
        # timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )

    if PREVIEW_IMAGES:
        for _ in range(len(DEFAULT_STAGE_C_TIMESTEPS)):
            r = next(prior_output)
            if isinstance(r, list):
                yield r
        prior_output = r
    
    decoder_output = decoder_pipeline(
        image_embeddings=prior_output.image_embeddings,
        prompt=prompt,
		num_inference_steps = decoder_num_inference_steps,
        # timesteps=decoder_timesteps,
        guidance_scale=decoder_guidance_scale,
        negative_prompt=negative_prompt,
        generator=generator,
        output_type="pil",
    ).images
    yield decoder_output
```

**Comment by dome272** [comment]
```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		prior_num_inference_steps = prior_num_inference_steps,
        # timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )
```
Should be num_inference_steps instead of prior_num_inference_steps :
```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		num_inference_steps = prior_num_inference_steps,
        # timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )
```

**Comment by FurkanGozukara** [comment]
@dome272 i had tested this

here another test

here below my code

```
    prior_output = prior_pipeline(
        prompt=prompt,
        height=height,
        width=width,
		num_inference_steps  = prior_num_inference_steps,
        # timesteps=DEFAULT_STAGE_C_TIMESTEPS,
        negative_prompt=negative_prompt,
        guidance_scale=prior_guidance_scale,
        num_images_per_prompt=num_images_per_prompt,
        generator=generator,
        callback=callback_prior,
    )

    if PREVIEW_IMAGES:
        for _ in range(len(DEFAULT_STAGE_C_TIMESTEPS)):
            r = next(prior_output)
            if isinstance(r, list):
                yield r
        prior_output = r
```

this is the error i get

```
To create a public link, set `share=True` in `launch()`.
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 29/30 [00:06<00:00,  4.48it/s]
Traceback (most recent call last):
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 508, in async_iteration
    return await iterator.__anext__()
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 501, in __anext__
    return await anyio.to_thread.run_sync(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 484, in run_sync_iterator_async
    return next(iterator)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 853, in gen_wrapper
    yield from f(*args, **kwargs)
  File "G:\Würstchen\Wuerstchen\app.py", line 102, in generate
    image_embeddings=prior_output.image_embeddings,
AttributeError: 'list' object has no attribute 'image_embeddings'

```

**Comment by FurkanGozukara** [comment]
@dome272 after that change the error is happening at this line

        image_embeddings=prior_output.image_embeddings,

**Comment by FurkanGozukara** [comment]
@patrickvonplaten when num_inference_steps   is used instead of timesteps=DEFAULT_STAGE_C_TIMESTEPS

this part of the decoder is giving error

image_embeddings=prior_output.image_embeddings


```
To create a public link, set `share=True` in `launch()`.
 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 29/30 [00:06<00:00,  4.48it/s]
Traceback (most recent call last):
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 508, in async_iteration
    return await iterator.__anext__()
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 501, in __anext__
    return await anyio.to_thread.run_sync(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 484, in run_sync_iterator_async
    return next(iterator)
  File "G:\Würstchen\Wuerstchen\venv\lib\site-packages\gradio\utils.py", line 853, in gen_wrapper
    yield from f(*args, **kwargs)
  File "G:\Würstchen\Wuerstchen\app.py", line 102, in generate
    image_embeddings=prior_output.image_embeddings,
AttributeError: 'list' object has no attribute 'image_embeddings'
```

**Comment by patrickvonplaten** [comment]
Hey @FurkanGozukara, 

The second snippet in this section: https://huggingface.co/docs/diffusers/main/en/api/pipelines/wuerstchen#texttoimage-generation

(copy-pasting here so that it's easier for you):

```py
import torch
from diffusers import WuerstchenDecoderPipeline, WuerstchenPriorPipeline
from diffusers.pipelines.wuerstchen import DEFAULT_STAGE_C_TIMESTEPS

device = "cuda"
dtype = torch.float16
num_images_per_prompt = 2

prior_pipeline = WuerstchenPriorPipeline.from_pretrained(
    "warp-ai/wuerstchen-prior", torch_dtype=dtype
).to(device)
decoder_pipeline = WuerstchenDecoderPipeline.from_pretrained(
    "warp-ai/wuerstchen", torch_dtype=dtype
).to(device)

caption = "Anthropomorphic cat dressed as a fire fighter"
negative_prompt = ""

prior_output = prior_pipeline(
    prompt=caption,
    height=1024,
    width=1536,
    timesteps=DEFAULT_STAGE_C_TIMESTEPS,
    negative_prompt=negative_prompt,
    guidance_scale=4.0,
    num_images_per_prompt=num_images_per_prompt,
)
decoder_output = decoder_pipeline(
    image_embeddings=prior_output.image_embeddings,
    prompt=caption,
    negative_prompt=negative_prompt,
    guidance_scale=0.0,
    output_type="pil",
).images
```

works as is. I don't understand how you get these errors. Can you try to add a **fully-reproducible** code snippet?

**Comment by FurkanGozukara** [comment]
> ```python
> DEFAULT_STAGE_C_TIMESTEPS
> ```

because you are using DEFAULT_STAGE_C_TIMESTEPS

DEFAULT_STAGE_C_TIMESTEPS is working

But when you change it to give any number of steps you want it is getting broken

Actually after installing latest diffusers and removing preview code it started working

I was working on the Gradio demo space you put on hugging face : https://huggingface.co/spaces/warp-ai/Wuerstchen
