### ISSUE TITLE
Out of space while using refiner for inference.

### ISSUE THREAD

**Issue by PrakharSaxena24** [huggingface/diffusers#5064]
### Describe the bug

After training, dreambooth_lora_sdxl, when I try to infer using refiner, the device runs out of space.
Initially I was using 100GB in my cloud provider, so I though maybe I need to increase the sapce. 
However, after increasing the space to 256 GB and running the inference using refiner, I get the same error.
The inference runs fine without using refiner.
But when I  use refiner ther is no space.
```refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0", torch_dtype=torch.float16, use_safetensors=True, variant="fp16"
)```

### Reproduction

from huggingface_hub.repocard import RepoCard
from diffusers import DiffusionPipeline, StableDiffusionXLImg2ImgPipeline
import torch

lora_model_id = <"lora-sdxl-dreambooth-id">
card = RepoCard.load(lora_model_id)
base_model_id = card.data.to_dict()["base_model"]

# Load the base pipeline and load the LoRA parameters into it. 
pipe = DiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id)

# Load the refiner.
refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0", torch_dtype=torch.float16, use_safetensors=True, variant="fp16"
)
refiner.to("cuda")

prompt = "A picture of a sks dog in a bucket"
generator = torch.Generator("cuda").manual_seed(0)

# Run inference.
image = pipe(prompt=prompt, output_type="latent", generator=generator).images[0]
image = refiner(prompt=prompt, image=image[None, :], generator=generator).images[0]
image.save("refined_sks_dog.png")

### Logs

```shell
(stable) root@41549ac893e6:/workspace/diffusers/examples/dreambooth# python infer.py Traceback (most recent call last): File "/workspace/diffusers/examples/dreambooth/infer.py", line 6, in <module> card = RepoCard.load(lora_model_id) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/repocard.py", line 176, in load hf_hub_download( File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn validate_repo_id(arg_value) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id raise HFValidationError( huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './lora_trained_xl/pytorch_lora_weights.safetensors'. Use `repo_type` argument if needed. (stable) root@41549ac893e6:/workspace/diffusers/examples/dreambooth# python infer.py Downloading (…)d76f/vae/config.json: 100%|█████████████████████████████████████| 642/642 [00:00<00:00, 11.1MB/s] Downloading (…)ch_model.safetensors: 100%|███████████████████████████████████| 335M/335M [00:03<00:00, 97.3MB/s] Fetching 19 files: 100%|████████████████████████████████████████████████████████| 19/19 [00:03<00:00,  5.12it/s] Loading pipeline components...: 100%|█████████████████████████████████████████████| 7/7 [00:04<00:00,  1.66it/s] Traceback (most recent call last): File "/workspace/diffusers/examples/dreambooth/infer.py", line 12, in <module> pipe.load_lora_weights(lora_model_id) File "/workspace/diffusers/src/diffusers/loaders.py", line 2612, in load_lora_weights state_dict, network_alphas = self.lora_state_dict( File "/workspace/diffusers/src/diffusers/loaders.py", line 1145, in lora_state_dict weight_name = cls._best_guess_weight_name( File "/workspace/diffusers/src/diffusers/loaders.py", line 1220, in _best_guess_weight_name files_in_repo = model_info(pretrained_model_name_or_path_or_dict).siblings File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn validate_repo_id(arg_value) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id raise HFValidationError( huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './lora_trained_xl/pytorch_lora_weights.safetensors'. Use `repo_type` argument if needed. (stable) root@41549ac893e6:/workspace/diffusers/examples/dreambooth# python infer.py Loading pipeline components...: 100%|█████████████████████████████████████████████| 7/7 [00:02<00:00,  3.16it/s] Downloading (…)ain/model_index.json: 100%|█████████████████████████████████████| 612/612 [00:00<00:00, 9.99MB/s] Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████| 460/460 [00:00<00:00, 5.37MB/s] Downloading (…)ncoder_2/config.json: 100%|█████████████████████████████████████| 575/575 [00:00<00:00, 11.4MB/s] Downloading (…)cheduler_config.json: 100%|█████████████████████████████████████| 479/479 [00:00<00:00, 9.75MB/s] Downloading (…)f86/unet/config.json: 100%|█████████████████████████████████| 1.71k/1.71k [00:00<00:00, 28.4MB/s] Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████| 725/725 [00:00<00:00, 14.7MB/s] Downloading (…)kenizer_2/merges.txt:   0%|                                           | 0.00/525k [00:00<?, ?B/s/workspace/stable/lib/python3.10/site-packages/huggingface_hub/file_download.py:980: UserWarning: Not enough free disk space to download the file. The expected file size is: 4519.21 MB. The target location /root/.cache/huggingface/hub only has 4489.36 MB free disk space. warnings.warn( /workspace/stable/lib/python3.10/site-packages/huggingface_hub/file_download.py:980: UserWarning: Not enough free disk space to download the file. The expected file size is: 4519.21 MB. The target location /root/.cache/huggingface/hub/models--stabilityai--stable-diffusion-xl-refiner-1.0/blobs only has 4489.36 MB free disk space. warnings.warn( Downloading (…)ef86/vae/config.json: 100%|█████████████████████████████████████| 642/642 [00:00<00:00, 4.44MB/s] Downloading (…)kenizer_2/merges.txt: 100%|███████████████████████████████████| 525k/525k [00:00<00:00, 10.8MB/s] Downloading (…)kenizer_2/vocab.json: 100%|█████████████████████████████████| 1.06M/1.06M [00:00<00:00, 18.2MB/s] Downloading (…)del.fp16.safetensors: 100%|███████████████████████████████████| 167M/167M [00:04<00:00, 36.4MB/s] Downloading (…)del.fp16.safetensors: 100%|███████████████████████████████████| 167M/167M [00:07<00:00, 21.3MB/s] Downloading model.fp16.safetensors: 100%|██████████████████████████████████| 1.39G/1.39G [00:28<00:00, 48.7MB/s] Fetching 13 files:  69%|███████████████████████████████████████▍                 | 9/13 [00:44<00:19,  4.93s/it] Traceback (most recent call last):s:  31%|██████████                       | 1.38G/4.52G [00:28<00:57, 54.3MB/s] File "/workspace/diffusers/examples/dreambooth/infer.py", line 15, in <module>77G/4.52G [00:42<00:17, 102MB/s] refiner = StableDiffusionXLImg2ImgPipeline.from_pretrained( File "/workspace/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 937, in from_pretrained cached_folder = cls.download( File "/workspace/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 1596, in download cached_folder = snapshot_download( File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 239, in snapshot_download thread_map( File "/workspace/stable/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs) File "/workspace/stable/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs)) File "/workspace/stable/lib/python3.10/site-packages/tqdm/std.py", line 1182, in __iter__ for obj in iterable: File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator yield _result_or_cancel(fs.pop()) File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel return fut.result(timeout) File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result return self.__get_result() File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result raise self._exception File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 214, in _inner_hf_hub_download return hf_hub_download( File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1429, in hf_hub_download http_get( File "/workspace/stable/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 554, in http_get temp_file.write(chunk) File "/usr/lib/python3.10/tempfile.py", line 622, in func_wrapper return func(*args, **kwargs) OSError: [Errno 28] No space left on device Downloading (…)del.fp16.safetensors:  61%|████████████████████▏            | 2.77G/4.52G [00:43<00:27, 63.3MB/s] (stable) root@41549ac893e6:/workspace/diffusers/examples/dreambooth#
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.1
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@williamberman @saya

**Comment by PrakharSaxena24** [comment]
Apologies, my cache was being stored in the wrongplace.
