### ISSUE TITLE
Using Prompt Embeddings with SDXL Refiner Triggers RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x2048 and 1280x768)

### ISSUE THREAD

**Issue by alexisrolland** [huggingface/diffusers#5075]
### Describe the bug

I'm following SDXL code provided in the documentation here: [Base + Refiner Model](https://huggingface.co/docs/diffusers/using-diffusers/sdxl#base-refiner-model), except that I'm combining it with Compel to get the prompt embeddings. The refiner inference triggers the error:

> RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x2048 and 1280x768)

### Reproduction

```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch
import os

MODEL_PATH = os.getenv('MODEL_PATH')
base = DiffusionPipeline.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
).to("cuda")

MODEL_PATH_REFINER = os.getenv('MODEL_PATH_REFINER')
refiner = DiffusionPipeline.from_pretrained(
    MODEL_PATH_REFINER,
    text_encoder_2=base.text_encoder_2,
    vae=base.vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
).to("cuda")

compel = Compel(
    tokenizer=[base.tokenizer, base.tokenizer_2],
    text_encoder=[base.text_encoder, base.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)

prompts = ["a cat playing with a (ball)++++ in the forest"]
negative_prompts = [""]
prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)

image = base(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    num_inference_steps=40,
    denoising_end=0.8,
    output_type="latent"
).images
image = refiner(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    num_inference_steps=40,
    denoising_start=0.8,
    image=image
).images[0]
```

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 982, in __call__
    noise_pred = self.unet(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 956, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 1086, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/transformer_2d.py", line 315, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/attention.py", line 218, in forward
    attn_output = self.attn2(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 420, in forward
    return self.processor(
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 1026, in __call__
    key = attn.to_k(encoder_hidden_states, scale=scale)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/lora.py", line 224, in forward
    out = super().forward(hidden_states)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x2048 and 1280x768)
```

### System Info

- `diffusers` version: 0.21.1
- Platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.36
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.1
- Transformers version: 4.33.1
- Accelerate version: 0.23.0
- xFormers version: 0.0.21
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@patrickvonplaten , @sayakpaul

**Comment by sayakpaul** [comment]
Could you maybe provide a Colab Notebook for us that helps to reproduce the issue?

**Comment by hosnasn1987** [comment]
> Could you maybe provide a Colab Notebook for us that helps to reproduce the issue?
I have the same issue and my code is in this colab link:

https://colab.research.google.com/drive/1bUWkE__PrYwnsxoQMHqwk7S0lZQS8Qgc?usp=sharing

could you help me to solve this issue?

**Comment by sayakpaul** [comment]
The Colab is very convoluted to navigate through. Would appreciate some way more minimal.

**Comment by patrickvonplaten** [comment]
@alexisrolland, can you check this entry here: https://github.com/huggingface/diffusers/issues/5060#issuecomment-1722230429 

In short the reason why this fails is because the refiner and base model use different text encodings. The base model has two text encoders while the refiner has only one. I suggest to simply build to prompt embeddings here as shown in the issue linked above

**Comment by linnanwang** [comment]
@sayakpaul thanks for the pointer. But I'm a bit confused about this solution, "I suggest to simply build to prompt embeddings here as shown in the issue linked above". Does this mean I should only build prompt embedding, ignoring negative embedding? If so, there is another error raised. Just want to make sure I'm on the right track. Thanks.

**Comment by alexisrolland** [comment]
Thank you @patrickvonplaten it worked. I am resharing here the code from my original issue with the modifications to solve the error:

```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch
import os

prompts = ["a cat playing with a (ball)++++ in the forest"]
negative_prompts = [""]

MODEL_PATH = os.getenv('MODEL_PATH')
base = DiffusionPipeline.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
).to("cuda")

MODEL_PATH_REFINER = os.getenv('MODEL_PATH_REFINER')
refiner = DiffusionPipeline.from_pretrained(
    MODEL_PATH_REFINER,
    torch_dtype=torch.float16,
    variant="fp16",
    vae=base.vae,
    text_encoder_2=base.text_encoder_2,
    use_safetensors=True,
).to("cuda")

compel = Compel(
    tokenizer=[base.tokenizer, base.tokenizer_2],
    text_encoder=[base.text_encoder, base.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)

prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)

compel_refiner = Compel(
  tokenizer=refiner.tokenizer_2,
  text_encoder=refiner.text_encoder_2,
  returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
  requires_pooled=True,
)

refiner_prompt_embeds, refiner_pooled_prompt_embeds = compel_refiner(prompts)
refiner_negative_prompt_embeds, refiner_negative_pooled_prompt_embeds = compel_refiner(negative_prompts)

image = base(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    num_inference_steps=40,
    denoising_end=0.8,
    output_type="latent"
).images
image = refiner(
    prompt_embeds=refiner_prompt_embeds,
    pooled_prompt_embeds=refiner_pooled_prompt_embeds,
    negative_prompt_embeds=refiner_negative_prompt_embeds,
    negative_pooled_prompt_embeds=refiner_negative_pooled_prompt_embeds,
    num_inference_steps=40,
    denoising_start=0.8,
    image=image
).images[0]
```

**Comment by nicollegah** [comment]
Is it also possible to do this without compel and to calculate the prompt embeddings directly? Compel is very slow.

**Comment by sayakpaul** [comment]
You can do the computation yourself but we don't provide tools internally from diffusers for that.

**Comment by nicollegah** [comment]
Do you know if there's any code example for that somewhere? Can't find it
