### ISSUE TITLE
Support for Loading Lyrocis by load_lora_weights

### ISSUE THREAD

**Issue by George0726** [huggingface/diffusers#5079]
**Is your feature request related to a problem? Please describe.**
I am trying to load Lyrocis from https://civitai.com/models/76404/lycoris-couture-an-edg-collection  by load_lora_weights. It shows the error.

**Describe the solution you'd like**
We can successfully load LyROCIS

![image](https://github.com/huggingface/diffusers/assets/38740075/1fec718b-f6fc-425f-af20-95c54f110455)

**Comment by George0726** [comment]
It works on SDXL LyRICOS but fails on SD1.5 LyRICOS

**Comment by patrickvonplaten** [comment]
cc @sayakpaul here, think it could make sense to now allow all kinds of LoRAs

**Comment by sayakpaul** [comment]
Checking.

**Comment by sayakpaul** [comment]
@George0726 could you please let us know how was `pipe` initialized in your code? It would be helpful for me to have minimally reproducible code snippet.

**Comment by George0726** [comment]
Sure, Thanks for your reply! I just used the simple way to load the LyRocis downloaded from https://civitai.com/models/76404/lycoris-couture-an-edg-collection 
```
  from diffusers import StableDiffusionPipeline,DiffusionPipeline
  MODEL_NAME = "models--runwayml--stable-diffusion-v1-5/snapshots/aa9ba505e1973ae5cd05f5aedd345178f52f8e6a/"
  pipe = StableDiffusionPipeline.from_pretrained(
          MODEL_NAME,
          safety_checker=None,
          variant="fp16")
  pipe.load_lora_weights('loras/edg',  weight_name='edgLycorisMugler-light.safetensors')
```


Output logs:
```
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  8.01it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Traceback (most recent call last):
  File "/home/richal/DenseDiffusion/test.py", line 68, in <module>
    pipe.load_lora_weights('loras/edg',  weight_name='edgLycorisMugler-light.safetensors')
  File "/home/richal/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/loaders.py", line 1030, in load_lora_weights
    self.load_lora_into_unet(
  File "/home/richal/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/loaders.py", line 1387, in load_lora_into_unet
    unet.load_attn_procs(state_dict, network_alphas=network_alphas, low_cpu_mem_usage=low_cpu_mem_usage)
  File "/home/richal/miniconda3/envs/diffusion/lib/python3.10/site-packages/diffusers/loaders.py", line 420, in load_attn_procs
    attn_processor = getattr(attn_processor, sub_key)
  File "/home/richal/miniconda3/envs/diffusion/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute 'time'
```
