### ISSUE TITLE
CUDA error: invalid configuration argument when using XFormersAttnProcessor

### ISSUE THREAD

**Issue by wren93** [huggingface/diffusers#5125]
### Describe the bug

Hi, I'm trying to make a custom attention module by inheriting `diffusers.models.attention_processor.Attention`. The attention module works fine in the default case when the `AttnProcessor` is being used. However, when I tried to use xformers and the `Attention` class changed the processor to the `XFormersAttnProcessor`, I got a CUDA error: 
```
Traceback (most recent call last):
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/root/dreambooth/test.py", line 57, in <module>
    hidden_states_2 = attn(input, video_length=16)
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/dreambooth/test.py", line 32, in forward
    hidden_states = self.processor(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 955, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 193, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 296, in _memory_efficient_attention
    return _fMHA.apply(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 42, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 324, in _memory_efficient_attention_forward_requires_grad
    out = op.apply(inp, needs_gradient=True)
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 186, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/ML-A100/home/weiming/conda/envs/animatediff/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
This happens for diffusers==0.21.2, xformers==0.0.21 and pytorch==2.0.1.

I previously used diffusers==0.21.2, pytorch==1.13.1 and xformers==0.0.16, there were no errors when executing the program but the results from `XFormersAttnProcessor` and the default `AttnProcessor` are not identical. I realized that the `xformers.ops.memory_efficient_attention` requires q, k, v input with the shape of [B, M, H, K], where B is the batch size, M the sequence length, H the number of heads, and K the embeding size per head. If inputs have dimension 3, it is assumed that the dimensions are [B, M, K] and H=1. I then tried to modify the code in
https://github.com/huggingface/diffusers/blob/v0.21.2/src/diffusers/models/attention_processor.py#L951
so that query, key and value have the shape of [B, M, H, K] instead of [BH, M, K] (after calling the function `head_to_batch_dim()`) as currently defined in the code and the program worked fine. I'm wondering if this suggests a bug in `XFormersAttnProcessor`, or if I am doing something wrong when using it?

### Reproduction

This script should be able to reproduce the error:
```
import torch
from diffusers.models.attention_processor import Attention
from einops import rearrange, repeat

class MyAttention(Attention):
    def __init__(
            self,
            attention_mode                     = None,
            cross_frame_attention_mode         = None,
            temporal_position_encoding         = False,
            temporal_position_encoding_max_len = 24,            
            *args, **kwargs
        ):
        super().__init__(*args, **kwargs)
        assert attention_mode == "Temporal"

        self.attention_mode = attention_mode
        self.is_cross_attention = kwargs["cross_attention_dim"] is not None

    def extra_repr(self):
        return f"(Module Info) Attention_Mode: {self.attention_mode}, Is_Cross_Attention: {self.is_cross_attention}"

    def forward(self, hidden_states, encoder_hidden_states=None, attention_mask=None, video_length=None, **cross_attention_kwargs):
        batch_size, sequence_length, _ = hidden_states.shape

        if self.attention_mode == "Temporal":
            d = hidden_states.shape[1]
            hidden_states = rearrange(hidden_states, "(b f) d c -> (b d) f c", f=video_length)
            
            encoder_hidden_states = repeat(encoder_hidden_states, "b n c -> (b d) n c", d=d) if encoder_hidden_states is not None else encoder_hidden_states
        
        hidden_states = self.processor(
            self,
            hidden_states,
            encoder_hidden_states=encoder_hidden_states,
            attention_mask=attention_mask,
            **cross_attention_kwargs,
        )

        if self.attention_mode == "Temporal":
            hidden_states = rearrange(hidden_states, "(b d) f c -> (b f) d c", d=d)

        return hidden_states


kwargs = {'cross_attention_dim': None, 'query_dim': 320, 'heads': 8, 'dim_head': 40, 'dropout': 0.0, 'bias': False, 'upcast_attention': False}
attn = MyAttention("Temporal", **kwargs).to("cuda")

input = torch.randn((32, 4096, 320)).to("cuda")

# default processor (AttnProcessor) works fine
hidden_states_1 = attn(input, video_length=16)

attn.set_use_memory_efficient_attention_xformers(True, None)

# switch to XFormersAttnProcessor
hidden_states_2 = attn(input, video_length=16)

assert torch.equal(hidden_states_1, hidden_states_2)
```

### System Info

- `diffusers` version: 0.21.2
- Platform: Linux-5.4.143-2-velinux1-amd64-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.25.1
- Accelerate version: 0.23.0
- xFormers version: 0.0.21
- Using GPU in script?: Nvidia A800
- Using distributed or parallel set-up in script?: Single GPU

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Can't you use SDPA to achieve similar efficiency gains? Sadly, there might be consequences of using xformers with the new PyTorch versions that we aren't aware of.

**Comment by wren93** [comment]
even if I'm using an older pytorch version (1.13.1) I still get inconsistent results with or without using xformers.
