### ISSUE TITLE
TypeError: StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker

### ISSUE THREAD

**Issue by andysingal** [huggingface/diffusers#5171]
### Describe the bug

```
Traceback (most recent call last):
  File "/workspace/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1584, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker'
```

### Reproduction

```
!python diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py \
--checkpoint_path majicmixRealistic_betterV2V25.safetensors \
--dump_path output_folder \
--pipeline_class_name StableDiffusionXLPipeline \
--from_safetensors \
--device='cuda:0'
```

### Logs

```shell
Downloading (…)lve/main/config.json: 100%|█| 4.52k/4.52k [00:00<00:00, 29.7MB/s]
Downloading (…)okenizer_config.json: 100%|█████| 905/905 [00:00<00:00, 5.32MB/s]
Downloading (…)olve/main/vocab.json: 100%|███| 961k/961k [00:00<00:00, 5.94MB/s]
Downloading (…)olve/main/merges.txt: 100%|███| 525k/525k [00:00<00:00, 3.15MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████| 389/389 [00:00<00:00, 2.57MB/s]
Downloading (…)/main/tokenizer.json: 100%|█| 2.22M/2.22M [00:00<00:00, 13.3MB/s]
Loading the tokenizer from the `special_tokens_map.json` and the `added_tokens.json` will be removed in `transformers 5`,  it is kept for forward compatibility, but it is recommended to update your `tokenizer_config.json` by uploading it again. You will see the new `added_tokens_decoder` attribute that will store the relevant information.
Downloading (…)lve/main/config.json: 100%|█| 4.55k/4.55k [00:00<00:00, 19.8MB/s]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Downloading pytorch_model.bin: 100%|████████| 1.22G/1.22G [00:10<00:00, 114MB/s]
Downloading (…)rocessor_config.json: 100%|█████| 342/342 [00:00<00:00, 1.98MB/s]
/usr/local/lib/python3.10/dist-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1584, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: StableDiffusionXLPipeline.__init__() got an unexpected keyword argument 'safety_checker'
```
```


### System Info

RTX 3090

### Who can help?

@sayakpaul @patrickvonplaten @will

**Comment by patrickvonplaten** [comment]
As you can see here https://civitai.com/models/43331/majicmix-realistic is not a StableDiffusionXLPipeline but a StableDiffusionPipeline
