### ISSUE TITLE
StableDiffusionXLAdapterPipeline does not work with load_lora_weights

### ISSUE THREAD

**Issue by ziniuwan** [huggingface/diffusers#5226]
### Describe the bug

StableDiffusionXLAdapterPipeline does not work with load_lora_weights

### Reproduction

```
import torch
from diffusers import StableDiffusionXLAdapterPipeline, T2IAdapter
from PIL import Image

adapter = T2IAdapter.from_pretrained(
        "TencentARC/t2i-adapter-openpose-sdxl-1.0", 
        torch_dtype=torch.float16)
pipe = StableDiffusionXLAdapterPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        adapter=adapter, 
        torch_dtype=torch.float16).to("cuda")
pipe.load_lora_weights(
        ".", 
        weight_name="myLora.safetensors")

control = Image.open("./pose.png")

images = pipe(
        prompt="1girl",
        image=control,
    ).images
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/ziniu/code/test.py", line 12, in <module>
    pipe.load_lora_weights(
  File "/home/ziniu/.conda/envs/sdxl/lib/python3.10/site-packages/diffusers/loaders.py", line 1100, in load_lora_weights
    self.load_lora_into_unet(
  File "/home/ziniu/.conda/envs/sdxl/lib/python3.10/site-packages/diffusers/loaders.py", line 1456, in load_lora_into_unet
    unet.load_attn_procs(
  File "/home/ziniu/.conda/envs/sdxl/lib/python3.10/site-packages/diffusers/loaders.py", line 422, in load_attn_procs
    attn_processor = getattr(attn_processor, sub_key)
  File "/home/ziniu/.conda/envs/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '4
```

### System Info

- `diffusers` version: 0.21.3
- Platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.2
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@williamberman @patrickvonplaten @sayakpaul

**Comment by patrickvonplaten** [comment]
@yiyixuxu can you check this?

**Comment by yiyixuxu** [comment]
hi 
@ziniuwan I tried reproducing your error with this script, but it works.

let me know if I missed anything here 

```python
import torch
from diffusers import StableDiffusionXLAdapterPipeline, T2IAdapter
from PIL import Image

adapter = T2IAdapter.from_pretrained(
        "TencentARC/t2i-adapter-openpose-sdxl-1.0", 
        torch_dtype=torch.float16)
pipe = StableDiffusionXLAdapterPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        adapter=adapter, 
        torch_dtype=torch.float16).to("cuda")

pipe.load_lora_weights("stabilityai/stable-diffusion-xl-base-1.0", weight_name="sd_xl_offset_example-lora_1.0.safetensors")

control = Image.open("./pose.png")

images = pipe(
        prompt="a couple",
        image=control,
    ).images

```

**Comment by yiyixuxu** [comment]
@ziniuwan please make sure to install from source 
```bash
pip install accelerate
pip install git+https://github.com/huggingface/diffusers
```

**Comment by ziniuwan** [comment]
> @ziniuwan please make sure to install from source
> 
> ```shell
> pip install accelerate
> pip install git+https://github.com/huggingface/diffusers
> ```

Installing from source solved the problem. Thanks!
