### ISSUE TITLE
Support for Multi-Controlnet in Controlnet Inpaint Pipeline

### ISSUE THREAD

**Issue by kadirnar** [huggingface/diffusers#5254]
### Describe the bug

```bash
  0%|                                                                                                                                                                                    | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\Users\kadir\Desktop\kadirnar\work\deneme.py", line 78, in <module>
    outputv0 = pipe(
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet_inpaint.py", line 1273, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\diffusers\pipelines\controlnet\multicontrolnet.py", line 48, in forward
    down_samples, mid_sample = controlnet(
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\kadir\miniconda3\envs\diffusers_gpu\lib\site-packages\diffusers\models\controlnet.py", line 771, in forward
    sample = sample + controlnet_cond
RuntimeError: The size of tensor a (67) must match the size of tensor b (96) at non-singleton dimension 3
```

### Reproduction

Code:

```python
import torch
from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetInpaintPipeline,
    EulerAncestralDiscreteScheduler,
)
from diffusers.models import AutoencoderKL
from transformers import pipeline
import numpy as np
from PIL import Image
from controlnet_aux import OpenposeDetector


def depth_image(image: Image.Image) -> Image.Image:
    """
    Estimates depth from a 2D image.

    Args:
        image (Image.Image): Input 2D image.

    Returns:
        Image.Image: Depth image.
    """
    estimator = pipeline("depth-estimation", model="Intel/dpt-hybrid-midas")
    depth = estimator(image)["depth"]
    depth = np.array(depth)[:, :, None]
    depth = np.concatenate([depth, depth, depth], axis=2)
    return Image.fromarray(depth)

def open_pose_image(image: Image.Image) -> Image.Image:
    open_pose = OpenposeDetector.from_pretrained("lllyasviel/Annotators")
    processed_image_open_pose = open_pose(image, hand_and_face=False)
    
    return processed_image_open_pose


image = Image.open("data/1.jpg")
control_depth_image = Image.open("data/control_depth_image.png")
control_pose_image = Image.open("data/control_pose_image.png")
control_mask = Image.open("data/control_mask.png")


controlnet_depth = ControlNetModel.from_pretrained(
    "lllyasviel/control_v11f1p_sd15_depth", 
    torch_dtype=torch.float16
)

controlnet_pose = ControlNetModel.from_pretrained(
    "lllyasviel/control_v11p_sd15_openpose", 
    torch_dtype=torch.float16
)

controlnet = [controlnet_depth, controlnet_pose]

control_images = [control_depth_image, control_pose_image]

vae = AutoencoderKL.from_pretrained(
    "stabilityai/sd-vae-ft-ema",
    torch_dtype=torch.float16
    )

pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
    "kadirnar/Realistic51-Inpaint",
    controlnet=controlnet, 
    torch_dtype=torch.float16,
    vae=vae,
    variant="fp16",
)

pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention()
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

prompt = "a girl"
negative_prompt = "bad"
generator = torch.manual_seed(42)

output = pipe(
    prompt=prompt, 
    negative_prompt=negative_prompt,
    image=[image],
    control_image=control_images,
    mask_image=[control_mask],
    controlnet_conditioning_scale=[1.0, 0.8],
    ).images
```

### System Info

- `diffusers` version: 0.21.3
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.17.2
- Transformers version: 4.33.3
- Accelerate version: 0.23.0
- xFormers version: 0.0.21

### Who can help?

@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu could you take a look here?

**Comment by usamaehsan** [comment]
@kadirnar are you able to solve this error? I am struggling with same error

**Comment by yiyixuxu** [comment]
@usamaehsan @kadirnar 

sorry I'm very very late to this issue - can any of you provide the inputs you used? 
YiYi

**Comment by kadirnar** [comment]
> @usamaehsan @kadirnar
> 
> sorry I'm very very late to this issue - can any of you provide the inputs you used? YiYi

It doesn't matter which picture it is. Controlnet pose model doesn't work. I may try again.

**Comment by czc2000** [comment]
Has this problem been solved? I'm stuck with the same problem.

**Comment by kadirnar** [comment]
No. @sayakpaul Can you help?

**Comment by yiyixuxu** [comment]
Hi:

the reason I asked for inputs is because the error looks like a size mismatch
if your `image` and `control_image` has different size, you can resize them before passing them to the pipeline.

and once this PR https://github.com/huggingface/diffusers/pull/5665 is merged, you will be able to just pass `image` and `control_image` in different sizes and specify the `height` and `width` of your output - the pipeline can automatically resize for you

Thanks

YiYi
