### ISSUE TITLE
StableDiffusionXLControlNetInpaintPipeline with refiner model

### ISSUE THREAD

**Issue by rb-synth** [huggingface/diffusers#5258]
### Describe the bug

I can use StableDiffusionXLControlNetInpaintPipeline with the base SDXL 1.0 model, but not the refiner model.

### Reproduction

```python
from diffusers import ControlNetModel, StableDiffusionXLControlNetInpaintPipeline
import torch
from PIL import Image
import requests
from io import BytesIO
from controlnet_aux.processor import Processor


def download_image(url):
    response = requests.get(url)
    return Image.open(BytesIO(response.content)).convert("RGB")


controlnet = ControlNetModel.from_pretrained("diffusers/controlnet-depth-sdxl-1.0", torch_dtype=torch.float16)
processor = Processor("depth_leres", params=dict(detect_resolution=1024, image_resolution=1024))

base = StableDiffusionXLControlNetInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
    controlnet=controlnet,
)
base.to("cuda")

refiner = StableDiffusionXLControlNetInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    text_encoder_2=base.text_encoder_2,
    vae=base.vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
    controlnet=controlnet,
)
refiner.to("cuda")

base_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/"
img_url = base_url + "overture-creations-5sI6fQgYIuo.png"
mask_url = base_url + "overture-creations-5sI6fQgYIuo_mask.png"

init_image = download_image(img_url).resize((1024, 1024)).convert("RGB")
mask_image = download_image(mask_url).resize((1024, 1024)).convert("L")
controlnet_image = processor(init_image)

n_steps = 3
strength = 0.8
prompt = "Face of a yellow cat, high resolution, sitting on a park bench"

use_latents = True

if use_latents:
    base_output = base(
        prompt=prompt,
        num_inference_steps=n_steps,
        denoising_start=strength,
        image=init_image,
        mask_image=mask_image,
        control_image=controlnet_image,
        output_type="latent",
    ).images

else:
    base_output = base(
        prompt=prompt,
        num_inference_steps=n_steps,
        denoising_start=strength,
        image=init_image,
        mask_image=mask_image,
        control_image=controlnet_image,
    ).images[0]

refiner(
    prompt=prompt,
    num_inference_steps=n_steps,
    denoising_start=strength,
    image=base_output,
    mask_image=mask_image,
    control_image=controlnet_image,
)
```

### Logs

If `use_latents`:

```
Traceback (most recent call last):
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/richardbrown/Documents/Code/Recolour/src/recolour/stable_diffusion/quick.py", line 84, in <module>
    main()
  File "/home/richardbrown/Documents/Code/Recolour/src/recolour/stable_diffusion/quick.py", line 73, in main
    refiner(
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py", line 1252, in __call__
    masked_image = init_image * (mask < 0.5)
RuntimeError: The size of tensor a (128) must match the size of tensor b (1024) at non-singleton dimension 3
```

If not `use_latents`:
```
Traceback (most recent call last):
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/richardbrown/.vscode-server/extensions/ms-python.python-2023.16.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/richardbrown/Documents/Code/Recolour/src/recolour/stable_diffusion/quick.py", line 72, in <module>
    refiner(
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py", line 1419, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/diffusers/models/controlnet.py", line 761, in forward
    aug_emb = self.add_embedding(add_embeds)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/diffusers/models/embeddings.py", line 192, in forward
    sample = self.linear_1(sample)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/richardbrown/mambaforge/envs/recolour/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2560 and 2816x1280)
```

### System Info

- `diffusers` version: 0.21.2
- Platform: Linux-5.15.0-1043-aws-x86_64-with-glibc2.31
- Python version: 3.9.18
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.2
- Transformers version: 4.33.2
- Accelerate version: 0.23.0
- xFormers version: 0.0.21
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by patrickvonplaten** [comment]
None of the controlnets were trained on the refiner, so I'm not sure whether it makes sense to add this functionality at the moment. I don' think we'll get good results

**Comment by rb-synth** [comment]
That's a shame, it seems like a legitimate use case to want refiner with controlnet, not just the base. But thanks for the hard work and for the info!
