### ISSUE TITLE
OSError: Error no file named model_index.json found in directory

### ISSUE THREAD

**Issue by Louis24** [huggingface/diffusers#5259]
### Describe the bug

I download the weight from civitai, and the format is safetensor, the folder structure is like this:
A/cuteyukimixAdorable.safetensors
B/Koreandoll.safetensors

### Reproduction

from diffusers import StableDiffusionPipeline
import torch

# print(torch.__version__)

base_model_id = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\A"
lora_model_id = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\B"
lora_filename = "Koreandoll.safetensors"

pipe = StableDiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16, use_safetensors=True)
pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model_id,lora_filename=lora_filename)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("haha.jpg")

### Logs

```shell
C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python>"c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/python/python.exe" "c:/Zero/Python/AIGC/Stable Diffusion 
WebUI Q v4.4/test.py"
Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\test.py", line 17, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float16, use_safetensors=True)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 903, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\configuration_utils.py", line 350, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory C:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/A.
```

### System Info

Platform: Win10
Python version: 3.10.11
PyTorch version (GPU?): 2.0.1+cu118
diffusers version: 0.16.1
Transformers version: 4.26.0
Accelerate version: 0.15.0
xFormers version: not installed
Using GPU in script?: 3070
Using distributed or parallel set-up in script?: No

### Who can help?

@patrickvonplaten, @sayakpaul, and @williamberman

**Comment by patrickvonplaten** [comment]
Instead of using `from_pretrained` can you use `from_single_file` ?

**Comment by Louis24** [comment]
> Instead of using `from_pretrained` can you use `from_single_file` ?

Hi, it replied AttributeError: type object 'StableDiffusionPipeline' has no attribute 'from_single_file'

**Comment by Louis24** [comment]
I think it is api for the xl "StableDiffusionXLPipeline.from_single_file"

**Comment by patrickvonplaten** [comment]
You should update your `diffusers` version (0.10 is quite old)

**Comment by Louis24** [comment]
yep after I take your advice, I modified the code like this.

import os
import torch
from diffusers import StableDiffusionPipeline

os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'

# print(torch.__version__)
# print(diffusers.__version__)
# https://huggingface.co/docs/transformers/installation#offline-mode


base_model = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\A\cuteyukimixAdorable.safetensors"
lora_model = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\B\Koreandoll.safetensors"
pipe = StableDiffusionPipeline.from_single_file(base_model, torch_dtype=torch.float16, use_safetensors=True)

pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("haha.jpg")

And get the  error like this:

C:\Zero\Python>"c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/python/python.exe" "c:/Zero/Python/AIGC/Stable Diffusion We
Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 703, in u
    httplib_response = self._make_request(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 449, in _
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 444, in _
    httplib_response = conn.getresponse()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 787, in u
    retries = retries.increment(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\util\retry.py", line 550, in incre
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\packages\six.py", line 769, in rer
    raise value.with_traceback(tb)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 703, in u
    httplib_response = self._make_request(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 449, in _
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\urllib3\connectionpool.py", line 444, in _
    httplib_response = conn.getresponse()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\test.py", line 23, in <module>
    pipe = StableDiffusionPipeline.from_single_file(base_model, torch_dtype=torch.float16, use_safetensors=True)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\loaders.py", line 2308, in from_
    pipe = download_from_original_stable_diffusion_ckpt(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\pipelines\stable_diffusion\conve_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
    r = adapter.send(request, **kwargs)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

C:\Zero\Python>"c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/python/python.exe" "c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/test.py"
Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\test.py", line 23, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(base_model, torch_dtype=torch.float16, use_safetensors=True)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 939, in from_pretrained
    cached_folder = cls.download(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1441, in download
    info = model_info(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or endnd the name, max length is 96: 'C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\A\cuteyukimixAdorable.safetensors'.

C:\Zero\Python>"c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/python/python.exe" "c:/Zero/Python/AIGC/Stable Diffusion WebUI Q v4.4/test.py"
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000171BF923A30>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting 
HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/vocab.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000171BF9E9780>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/vocab.json
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /CompVis/stable-diffusion-safety-checker/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017336C73700>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/CompVis/stable-diffusion-safety-checker/resolve/main/config.json
Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\test.py", line 23, in <module>
    pipe = StableDiffusionPipeline.from_single_file(base_model, torch_dtype=torch.float16, use_safetensors=True)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\loaders.py", line 2308, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1562, in download_from_original_stable_diffusion_ckpt
    safety_checker = StableDiffusionSafetyChecker.from_pretrained(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\modeling_utils.py", line 2305, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\python\lib\site-packages\transformers\utils\hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

But I searched the files in the project folder, 
![image](https://github.com/huggingface/diffusers/assets/18719360/adbebe90-da20-4a05-a972-4d10a4e34c0d)

I have these file but possiblely the did not link them together

**Comment by Louis24** [comment]
import os
import torch
from diffusers import StableDiffusionPipeline

os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['TRANSFORMERS_OFFLINE'] = '1'

# print(torch.__version__)
# print(diffusers.__version__)
# https://huggingface.co/docs/transformers/installation#offline-mode


base_model = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\A\cuteyukimixAdorable.safetensors"
lora_model = "C:\Zero\Python\AIGC\Stable Diffusion WebUI Q v4.4\B\Koreandoll.safetensors"
pipe = StableDiffusionPipeline.from_single_file(base_model, torch_dtype=torch.float16, use_safetensors=True, local_files_only=True, requires_safety_checker=False)

pipe = pipe.to("cuda")
pipe.load_lora_weights(lora_model)
image = pipe("A picture of a sks dog in a bucket", num_inference_steps=25).images[0]
image.save("haha.jpg")
![image](https://github.com/huggingface/diffusers/assets/18719360/cc8f12c5-aabb-4931-a72b-1205ded0ac10)
I have already baned the safety check why this popup again..

**Comment by Louis24** [comment]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior 
or auditing its results. For more information,

**Comment by Louis24** [comment]
Dont know every times it pops different error

**Comment by Louis24** [comment]
![haha](https://github.com/huggingface/diffusers/assets/18719360/75a1736a-632e-46de-aa5f-02438373747b)
ok it is done ugly & funny image

**Comment by Louis24** [comment]
hi, I got 1 more question, when I search the code, there is no safety_checker, 
![image](https://github.com/huggingface/diffusers/assets/18719360/76dbe6ba-4d2e-4f1a-b2fc-5cbf70ebea16),
how does it work?

**Comment by Louis24** [comment]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior 
or auditing its results.

**Comment by Louis24** [comment]
oh inherit DiffusionPipeline

**Comment by Louis24** [comment]
![image](https://github.com/huggingface/diffusers/assets/18719360/fae47b6c-8336-461c-b180-d7352cd90b3b)
Should I add .to("cuda") everytime for add a weight into it?

**Comment by Louis24** [comment]
@patrickvonplaten
