### ISSUE TITLE
Using `enable_model_cpu_offload` with multiple XL pipelines triggers error Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by alexisrolland** [huggingface/diffusers#5281]
Hello,

I am having difficulties to use `enable_model_cpu_offload` in the context of my application where I am loading multiple pipelines in memory (`StableDiffusionXLPipeline`, `StableDiffusionXLImg2ImgPipeline` and `StableDiffusionXLControlNetPipeline`). I read through the documentation here: [Model offloading for fast inference and memory savings](https://huggingface.co/docs/diffusers/v0.21.0/en/optimization/fp16#model-offloading-for-fast-inference-and-memory-savings) and I also read through this issue which seemed similar to what I am facing: [Diffusers 0.21 breaks model offloading](https://github.com/huggingface/diffusers/issues/5060#). I couldn't find a complete code snippet that could help...

The error I am facing:

> Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

It is triggered when calling `pipeline_controlnet`:

```py
import torch
from compel import Compel, ReturnedEmbeddingsType
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, StableDiffusionXLPipeline

pipeline = StableDiffusionXLPipeline.from_pretrained('stabilityai/stable-diffusion-xl-base-1.0', torch_dtype=torch.float16, variant='fp16', use_safetensors=True)
pipeline.enable_model_cpu_offload()

controlnet = ControlNetModel.from_pretrained('diffusers/controlnet-depth-sdxl-1.0', torch_dtype=torch.float16)
pipeline_controlnet = StableDiffusionXLControlNetPipeline(controlnet=controlnet, **pipeline.components)

compel = Compel(
    tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2],
    text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)

prompts = ["a cat playing with a (ball)++++ in the forest"]
negative_prompts = [""]
prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)
seed = 123456
generators = torch.Generator(device='cuda').manual_seed(seed)

image = pipeline(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    num_inference_steps=30,
    num_images_per_prompt=1,
    generator=generators
).images[0]

torch.cuda.empty_cache()
torch.cuda.ipc_collect()

image = pipeline_controlnet(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    image=image,
    controlnet_conditioning_scale=0.5,
    num_inference_steps=30,
    num_images_per_prompt=1,
    generator=generators
).images[0]

torch.cuda.empty_cache()
torch.cuda.ipc_collect()
```

I have tried to add `pipeline_controlnet.enable_model_cpu_offload()` like this:

```py
[...]
MODEL_PATH_CONTROLNET = os.getenv('MODEL_PATH_CONTROLNET_DEPTH')
controlnet = ControlNetModel.from_pretrained(MODEL_PATH_CONTROLNET, torch_dtype=torch.float16)
pipeline_controlnet = StableDiffusionXLControlNetPipeline(controlnet=controlnet, **pipeline.components)
pipeline_controlnet.enable_model_cpu_offload() 
[...]
```

But then calling the StableDiffusionXLPipeline `pipeline` triggers:

> ValueError: Cannot generate a cpu tensor from a generator of type cuda.

@sayakpaul @patrickvonplaten I would really appreciate some guidance how to achieve this!

Thank you <3

**Comment by sayakpaul** [comment]
Hi the code snippet doesn't look minimal to me. Could you be a little more specific in helping us find out where exactly does it stem from and preferably provide a Colab Notebook?

**Comment by alexisrolland** [comment]
Hi @sayakpaul and thank you for the prompt answer! 

I have simplified the code a bit in my post above. Here is a Colab to reproduce (with the error displayed at the end): https://colab.research.google.com/gist/alexisrolland/64b20e68742cd796b86a3e4ca76ae5af/untitled0.ipynb

Also here is a log showing the issue:

```
# python
Python 3.10.13 (main, Sep 20 2023, 11:17:48) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import random
>>> import torch
>>> from compel import Compel, ReturnedEmbeddingsType
>>> from diffusers import StableDiffusionXLPipeline, StableDiffusionXLImg2ImgPipeline, StableDiffusionXLControlNetPipeline, ControlNetModel
>>> 
>>> MODEL_PATH = os.getenv('MODEL_PATH')
>>> pipeline = StableDiffusionXLPipeline.from_pretrained(MODEL_PATH, torch_dtype=torch.float16, variant='fp16', use_safetensors=True)
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:50<00:00,  7.26s/it]
>>> pipeline.enable_model_cpu_offload()
>>> 
>>> MODEL_PATH_CONTROLNET = os.getenv('MODEL_PATH_CONTROLNET_DEPTH')
>>> controlnet = ControlNetModel.from_pretrained(MODEL_PATH_CONTROLNET, torch_dtype=torch.float16)
>>> pipeline_controlnet = StableDiffusionXLControlNetPipeline(controlnet=controlnet, **pipeline.components)
>>> pipeline_img2img = StableDiffusionXLImg2ImgPipeline(**pipeline.components)
>>> compel = Compel(
...     tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2],
...     text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2],
...     returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
...     requires_pooled=[False, True]
... )
>>> 
>>> prompts = ["a cat playing with a (ball)++++ in the forest"]
>>> negative_prompts = [""]
>>> prompt_embeds, pooled_prompt_embeds = compel(prompts)
>>> negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)
>>> seed = 123456
>>> generators = torch.Generator(device='cuda').manual_seed(seed)
>>> image = pipeline(
...     prompt_embeds=prompt_embeds,
...     pooled_prompt_embeds=pooled_prompt_embeds,
...     negative_prompt_embeds=negative_prompt_embeds,
...     negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
...     num_inference_steps=30,
...     num_images_per_prompt=1,
...     generator=generators
... ).images[0]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.47it/s]
>>> 
>>> torch.cuda.empty_cache()
>>> torch.cuda.ipc_collect()
>>> image = pipeline_controlnet(
...     prompt_embeds=prompt_embeds,
...     pooled_prompt_embeds=pooled_prompt_embeds,
...     negative_prompt_embeds=negative_prompt_embeds,
...     negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
...     image=image,
...     controlnet_conditioning_scale=0.5,
...     num_inference_steps=30,
...     num_images_per_prompt=1,
...     generator=generators
... ).images[0]
  0%|                                                                                                                                                                                                                   | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 1100, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/controlnet.py", line 730, in forward
    emb = self.time_embedding(t_emb, timestep_cond)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/models/embeddings.py", line 192, in forward
    sample = self.linear_1(sample)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
>>> 
```

Thanks a lot once again for looking into this... I guess I am just misunderstanding how to use `enable_model_cpu_offload()` when working with multiple pipelines in the same application.

**Comment by CesarERamosMedina** [comment]
Getting the same error when running inference of the GLIGEN pipeline with enable_model_cpu_offload

**Comment by patrickvonplaten** [comment]
cc @dhruvrnaik @yiyixuxu here as well

**Comment by alexisrolland** [comment]
After spending hours testing, here is what I *think* is happening...

After instantiating `pipeline_controlnet = StableDiffusionXLControlNetPipeline(controlnet=controlnet, **pipeline.components)`, I verified what is the pipeline state. It says it is on CPU and to be executed on GPU. I assume because it inherits the state from the previous call `pipeline.enable_model_cpu_offload()`...

```py
>>> pipeline_controlnet.device
device(type='cpu')
>>> pipeline_controlnet._execution_device
device(type='cuda', index=0)
```

I think this is partially correct... since `StableDiffusionXLControlNetPipeline` is instantiated after `enable_model_cpu_offload()`, the ControlNet model itself is not set to execute on the GPU. It remains on the CPU and this is what triggers the first error *Expected all tensors to be on the same device*

**Comment by alexisrolland** [comment]
I have done some more tests and made some progess. What I did:

- Load `ControlNetModel`
- Instantiate pipeline `StableDiffusionXLControlNetPipeline` to load model weights
- Enable model CPU offload on `StableDiffusionXLControlNetPipeline`
- Instantiate pipeline `StableDiffusionXLPipeline` from the ControlNet pipeline **components**
- Call `StableDiffusionXLControlNetPipeline` -> OK, ControlNet model is offloaded from the GPU
- Call `StableDiffusionXLPipeline` -> OK, model is offloaded from the GPU

## Problem

- Load new/different `ControlNetModel`
- Instantiate pipeline `StableDiffusionXLControlNetPipeline` from the previous ControlNet pipeline **components**
- Call the new `StableDiffusionXLControlNetPipeline` -> **KO, the pipeline runs fine but it seems the new ControlNet model is not offloaded to the CPU after the inference**

## Question

How to update the instance of a ControlNet pipeline with different ControlNet models without breaking the CPU offloading?

Code to reproduce:

```py
import torch
from compel import Compel, ReturnedEmbeddingsType
from diffusers import ControlNetModel
from diffusers import StableDiffusionXLPipeline, StableDiffusionXLControlNetPipeline
from diffusers.utils import load_image

MODEL_PATH = 'stabilityai/stable-diffusion-xl-base-1.0'
MODEL_PATH_CONTROLNET_DEPTH = 'diffusers/controlnet-depth-sdxl-1.0'
MODEL_PATH_CONTROLNET_CANNY = 'diffusers/controlnet-canny-sdxl-1.0'

# Load ControlNet model and instantiate pipeline 
controlnet = ControlNetModel.from_pretrained(MODEL_PATH_CONTROLNET_DEPTH, torch_dtype=torch.float16)
pipeline_controlnet = StableDiffusionXLControlNetPipeline.from_pretrained(MODEL_PATH, controlnet=controlnet, torch_dtype=torch.float16)
pipeline_controlnet.enable_model_cpu_offload()

# Instantiate text to image pipeline from components
pipeline = StableDiffusionXLPipeline(
    scheduler=pipeline_controlnet.components['scheduler'],
    text_encoder=pipeline_controlnet.components['text_encoder'],
    text_encoder_2=pipeline_controlnet.components['text_encoder_2'],
    tokenizer=pipeline_controlnet.components['tokenizer'],
    tokenizer_2=pipeline_controlnet.components['tokenizer_2'],
    unet=pipeline_controlnet.components['unet'],
    vae=pipeline_controlnet.components['vae']
)

prompts = ["hello world"]
negative_prompts = ["ugly"]
seed = 123456
generators = torch.Generator(device='cuda').manual_seed(seed)
image = load_image("https://hf.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png")

# Convert prompt to embeddings for ControlNet pipeline
compel = Compel(
    tokenizer=[pipeline_controlnet.tokenizer, pipeline_controlnet.tokenizer_2],
    text_encoder=[pipeline_controlnet.text_encoder, pipeline_controlnet.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)
prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)

# Call ControlNet pipeline
image = pipeline_controlnet(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    image=image,
    controlnet_conditioning_scale=0.5,
    num_inference_steps=20,
    num_images_per_prompt=1,
    generator=generators
).images[0]

torch.cuda.empty_cache()

# Convert prompt to embeddings for text to image pipeline
compel = Compel(
    tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2],
    text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)
prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)

# Call text to image pipeline
image = pipeline(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    width=768,
    height=768,
    num_inference_steps=20,
    num_images_per_prompt=1,
    generator=generators
).images[0]

torch.cuda.empty_cache()

# Load second ControlNet model and instantiate pipeline from components
controlnet2 = ControlNetModel.from_pretrained(MODEL_PATH_CONTROLNET_CANNY, torch_dtype=torch.float16)
pipeline_controlnet.components['controlnet'] = controlnet2
pipeline_controlnet2 = StableDiffusionXLControlNetPipeline(**pipeline_controlnet.components)

# Convert prompt to embeddings for second ControlNet pipeline
compel = Compel(
    tokenizer=[pipeline_controlnet2.tokenizer, pipeline_controlnet2.tokenizer_2],
    text_encoder=[pipeline_controlnet2.text_encoder, pipeline_controlnet2.text_encoder_2],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[False, True]
)
prompt_embeds, pooled_prompt_embeds = compel(prompts)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompts)

# Call second ControlNet pipeline
image = pipeline_controlnet2(
    prompt_embeds=prompt_embeds,
    pooled_prompt_embeds=pooled_prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,
    image=image,
    controlnet_conditioning_scale=0.5,
    num_inference_steps=20,
    num_images_per_prompt=1,
    generator=generators
).images[0]

torch.cuda.empty_cache()
```

**Comment by DN6** [comment]
@alexisrolland Since you're instantiating a new pipeline class `pipeline_controlnet_2`, you would need to call `enable_model_cpu_offload` on that new pipeline object to ensure offloading is done properly on all components. Could you check to see if that solves your issue.

**Comment by alexisrolland** [comment]
Hello @DN6 I have tried your suggestion

```
[...]
pipeline_controlnet2 = StableDiffusionXLControlNetPipeline(**pipeline_controlnet.components)
pipeline_controlnet2.enable_model_cpu_offload()
[..]
```

When calling the inference it triggers the error **"ValueError: Cannot generate a cpu tensor from a generator of type cuda."**

I think the reason is because `enable_model_cpu_offload()` is a stateful operation, so my understanding is that it should **not** be called more than one time in a single Python session / application

See documentation: [Model offloading for fast inference and memory savings](https://huggingface.co/docs/diffusers/optimization/fp16#model-offloading-for-fast-inference-and-memory-savings)

> Note: `enable_model_cpu_offload()` is a stateful operation that installs hooks on the models and state on the pipeline. In order to properly offload models after they are called, it is required that the entire pipeline is run and models are called in the order the pipeline expects them to be. Exercise caution if models are re-used outside the context of the pipeline after hooks have been installed. See [accelerate](https://huggingface.co/docs/accelerate/v0.18.0/en/package_reference/big_modeling#accelerate.hooks.remove_hook_from_module) for further docs on removing hooks.
