### ISSUE TITLE
how to deploy locally as chinese gov has block huggingface?

### ISSUE THREAD

**Issue by Louis24** [huggingface/diffusers#5335]
### Describe the bug

got all the models ckpt safetensor, it still try to connect the /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-infer

### Reproduction

pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,)

### System Info

Platform: Win10
Python version: 3.10.11
PyTorch version (GPU?): 2.0.1+cu118
diffusers version: 0.16.1
Transformers version: 4.26.0
Accelerate version: 0.15.0
xFormers version: not installed
Using GPU in script?: 3070
Using distributed or parallel set-up in script?: No

### Who can help?

@yiyixuxu @DN6 @patrickvonplaten @sayakpaul @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can you pass local_files_only=True?

**Comment by Louis24** [comment]
pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False,
                                                              local_files_only=True)
                                                              
 

> Can you pass local_files_only=True?

Ok, if I load .safetensor, do I need the v1-inference.yaml?

**Comment by DN6** [comment]
@Louis24 Yes. You will need to point to a local `v1-inference.yaml` otherwise diffusers will attempt to download it.

**Comment by Louis24** [comment]
> @Louis24 Yes. You will need to point to a local `v1-inference.yaml` otherwise diffusers will attempt to download it.

I have point that what else should i do

**Comment by DN6** [comment]
Are you still experiencing this issue after setting `local_files_only=True` and pointing to the locally saved files on your machine? If that's the case, can you share the full error traceback and a the code you are running?

**Comment by Louis24** [comment]
> Are you still experiencing this issue after setting `local_files_only=True` and pointing to the locally saved files on your machine? If that's the case, can you share the full error traceback and a the code you are running?
yes

**Comment by Louis24** [comment]
pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
                                                              torch_dtype=torch.float16,
                                                              use_safetensors=True,
                                                              safety_checker=None,
                                                              load_safety_checker=False,
                                                              requires_safety_checker=False,
                                                              local_files_only=True)
                                                              
the base_model I use absolute path, 

【Error】

Microsoft Windows [版本 10.0.18363.592]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Zero\Python>cd "c:/Zero/Python/AIGC/Stable Diffusion WebUI Q"

c:\Zero\Python\AIGC\Stable Diffusion WebUI Q>"c:/Zero/Python/AIGC/Stable Diffusion WebUI Q/python/python.exe" "c:/Zero/Python/AIGC/Stable Diffusion WebUI Q/test.py"
2.0.1+cu118
0.21.4
Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000012EC8578D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012EC8578D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\test.py", line 60, in <module>
    infer(base_model="C:/Zero/Python/AIGC/Stable Diffusion WebUI Q/models/Stable-diffusion/realisticVision.safetensors",
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\test.py", line 23, in infer
    pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\diffusers\loaders.py", line 2308, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1289, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "c:\Zero\Python\AIGC\Stable Diffusion WebUI Q\python\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000012EC8578D00>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by sayakpaul** [comment]
Cc: @patrickvonplaten how should we deal with this

**Comment by Louis24** [comment]
`pipe = diffusers.StableDiffusionPipeline.from_single_file(base_model,
torch_dtype=torch.float16,
use_safetensors=True,
# safety_checker=None,
# load_safety_checker=False,
local_files_only=True,
requires_safety_checker=False,
# cache_dir=True
)`

**Comment by patrickvonplaten** [comment]
I don't think that this is an issue for `diffusers` but rather: https://github.com/huggingface/huggingface_hub
