### ISSUE TITLE
Unittest Discovery in VScode

### ISSUE THREAD

**Issue by FrsECM** [huggingface/diffusers#5346]
### Describe the bug

In vscode, the test are not correctly discovered by default, there is an error due to relative imports in some tests.
![image](https://github.com/huggingface/diffusers/assets/26071804/5d3d6a00-8591-4c89-8de6-a2742d623a42)

It seems that the issue is linked with this line : 
```python
from ..others.test_utils import TOKEN, USER, is_staging_test
```

It's the _43rd_ line of file _model/test_modeling_common.py_

### Reproduction

I cloned the repository from github : 
```bash
git clone https://github.com/huggingface/diffusers.git
cd diffusers
```

Then i installed all dependancies : 
```bash
conda create -n diffusers_dev python=3.8
pip install -e .[dev] 
```

Then i configured unittest in vscode with this configuration : 
```json
{
    "python.testing.unittestArgs": [
        "-v",
        "-s",
        "./tests",
        "-p",
        "test_*.py"
    ],
    "python.testing.pytestEnabled": false,
    "python.testing.unittestEnabled": true
}
```

### Logs

```shell
2023-10-09 18:11:41.838 [info] Discover tests for workspace name: diffusers - uri: /mnt/c/BUSCODE/packages/diffusers
2023-10-09 18:11:41.838 [info] Running discovery for unittest using the new test adapter.
2023-10-09 18:11:41.847 [info] > conda run -n diffusers_dev --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/printEnvVariables.py
2023-10-09 18:11:41.847 [info] shell: bash
2023-10-09 18:11:42.992 [info] Discovering unittest tests with arguments: /home/f296849/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/unittestadapter/discovery.py,--port,40129,--uuid,a7ff09e1-176f-46f9-bc53-291bf7c07f94,--udiscovery,-v,-s,./tests,-p,test_*.py

2023-10-09 18:11:42.992 [info] > conda run -n diffusers_dev --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.18.0/pythonFiles/unittestadapter/discovery.py --port 40129 --uuid a7ff09e1-176f-46f9-bc53-291bf7c07f94 --udiscovery -v -s ./tests -p test_*.py
2023-10-09 18:11:42.992 [info] cwd: .
2023-10-09 18:12:04.640 [info] > conda info --json
2023-10-09 18:12:06.705 [info] Send text to terminal: conda activate diffusers_dev
2023-10-09 18:12:08.981 [info] Test server connected to a client.
2023-10-09 18:12:08.981 [info] Test server connected to a client.
2023-10-09 18:12:08.992 [info] ResultResolver EOT received for discovery.
2023-10-09 18:12:09.022 [error] Unittest test discovery error 
 Failed to import test module: models.test_modeling_common
Traceback (most recent call last):
  File "/home/f296849/miniconda3/Bib/envs/diffusers_dev/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/f296849/miniconda3/Bib/envs/diffusers_dev/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/BUSCODE/packages/diffusers/tests/models/test_modeling_common.py", line 43, in <module>
    from ..others.test_utils import TOKEN, USER, is_staging_test
ValueError: attempted relative import beyond top-level package


Failed to import test module: models.test_models_prior
Traceback (most recent call last):
  File "/home/f296849/miniconda3/Bib/envs/diffusers_dev/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/f296849/miniconda3/Bib/envs/diffusers_dev/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/BUSCODE/packages/diffusers/tests/models/test_models_prior.py", line 26, in <module>
    from .test_modeling_common import ModelTesterMixin
  File "/mnt/c/BUSCODE/packages/diffusers/tests/models/test_modeling_common.py", line 43, in <module>
    from ..others.test_utils import TOKEN, USER, is_staging_test
ValueError: attempted relative import beyond top-level package
```

### System Info

Windows 10 - WSL 2 

=== /etc/os-release ===
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

Python 3.8.17

### Who can help?

@DN6 @sayakpaul @yiyixuxu

**Comment by sayakpaul** [comment]
Seems to be very IDE specific to me.

**Comment by FrsECM** [comment]
> Seems to be very IDE specific to me.

Do you have any idea about how to fix it ?
Thanks !

**Comment by sayakpaul** [comment]
We don't run tests that way. 

We usually do:

```bash
pytest tests/models/...
```

I think it might be better to post a minimally reproducible version of this issue on VSCode's repository.
