### ISSUE TITLE
Getting error got an unexpected keyword argument 'checkpoint_path'

### ISSUE THREAD

**Issue by LemonsRobert** [huggingface/diffusers#5374]
### Describe the bug

I been trying to convert .safetenor to .diffusers in Colab. After running .py file getting error as got an unexpected keyword argument 'checkpoint_path'

### Reproduction

Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 130, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'checkpoint_path'

### System Info

latest versions of diffusers, transformers, omegaconf on Google colab

### Who can help?

@patrickvonplaten @sayakpaul or @anyone

**Comment by LemonsRobert** [comment]
Colab Notebook Link- 
https://colab.research.google.com/drive/1n67Jejzs4UlhK85AsSfMvXf7RFnrEBwT?usp=sharing

**Comment by DN6** [comment]
@LemonsRobert When I tried running your notebook I get the following error. I think you need to download the yaml file as well for the model in the notebook. 

```
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
2023-10-12 12:30:24.700908: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 160, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1291, in download_from_original_stable_diffusion_ckpt
    original_config = OmegaConf.load(original_config_file)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/diffusers/v1-inpainting-inference.yaml'
```

**Comment by LemonsRobert** [comment]
Hey @DN6 Thanks for the reply,

I am new to this. So idk how to get yaml file for the model? Can you guide me !

**Comment by DN6** [comment]
There is a mismatch is the UNet channels in your checkpoint and the configuration file being used. Can you verify if the checkpoint you're downloading for inpainting is the right one?
