### ISSUE TITLE
Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.

### ISSUE THREAD

**Issue by Damarcreative** [huggingface/diffusers#5423]
How to solve this??
text to img
Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.

![Screenshot (15)](https://github.com/huggingface/diffusers/assets/106896172/c3da9b47-71a5-426d-b850-fcfa98d9ca0e)

**Comment by patrickvonplaten** [comment]
Can you send the link to the model on the Hub?

**Comment by Damarcreative** [comment]
> Can you send the link to the model on the Hub?

I just checked all the files on this model, it looks like this is due to the diffusers version
https://huggingface.co/tensor-diffusion/Ether-Blu-Mix-V5

**Comment by jojkaart** [comment]
I'm getting this exact error when trying to run https://huggingface.co/SimianLuo/LCM_Dreamshaper_v7 with the code sample in that project's readme.

Here's a copy&paste from my terminal:
```
$ python3 test.py
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
Downloading (…)ain/model_index.json: 100%|████████████████████████████████████████████████████████████████████████| 536/536 [00:00<00:00, 1.45MB/s]
/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:649: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Downloading (…)nsistency_txt2img.py: 33.2kB [00:00, 21.1MB/s]                                                                                      
Downloading (…)_encoder/config.json: 100%|████████████████████████████████████████████████████████████████████████| 610/610 [00:00<00:00, 2.62MB/s]
Downloading (…)cheduler_config.json: 100%|████████████████████████████████████████████████████████████████████████| 504/504 [00:00<00:00, 2.82MB/s]
Downloading (…)_checker/config.json: 100%|████████████████████████████████████████████████████████████████████████| 726/726 [00:00<00:00, 7.23MB/s]
Downloading (…)rocessor_config.json: 100%|████████████████████████████████████████████████████████████████████████| 518/518 [00:00<00:00, 5.64MB/s]
Downloading (…)er/added_tokens.json: 100%|███████████████████████████████████████████████████████████████████████| 57.0/57.0 [00:00<00:00, 569kB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████| 133/133 [00:00<00:00, 1.62MB/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████████████████████████| 765/765 [00:00<00:00, 8.58MB/s]
Downloading (…)eb8/unet/config.json: 100%|████████████████████████████████████████████████████████████████████| 1.73k/1.73k [00:00<00:00, 20.0MB/s]
Downloading (…)tokenizer/merges.txt: 100%|██████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.22MB/s]
Downloading (…)6eb8/vae/config.json: 100%|████████████████████████████████████████████████████████████████████████| 651/651 [00:00<00:00, 4.85MB/s]
Downloading (…)tokenizer/vocab.json: 100%|████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 2.61MB/s]
Downloading (…)ch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████| 335M/335M [00:06<00:00, 50.0MB/s]
Downloading model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████| 492M/492M [00:30<00:00, 16.2MB/s]
Downloading model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████| 1.22G/1.22G [00:36<00:00, 32.9MB/s]
Downloading (…)ch_model.safetensors: 100%|████████████████████████████████████████████████████████████████████| 3.44G/3.44G [00:52<00:00, 65.6MB/s]
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:53<00:00,  3.33s/it]
/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:649: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'                | 1.47G/3.44G [00:29<01:12, 27.3MB/s]
  warnings.warn(h_model.safetensors:  50%|██████████████████████████████████                                  | 1.72G/3.44G [00:36<00:40, 42.2MB/s]
Loading pipeline components...:  17%|█████████████▎                                                                  | 1/6 [00:00<00:01,  4.40it/s]Some weights of StableDiffusionSafetyChecker were not initialized from the model checkpoint at /home/joel/.cache/huggingface/hub/models--SimianLuo--LCM_Dreamshaper_v7/snapshots/c7f9b672c65a664af57d1de926819fd79cb26eb8/safety_checker and are newly initialized: ['vision_model.vision_model.embeddings.position_ids']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading pipeline components...:  67%|█████████████████████████████████████████████████████▎                          | 4/6 [00:00<00:00,  7.09it/s]
Traceback (most recent call last):
  File "/home/joel/AI/LCM_Dreamshaper_v7/test.py", line 9, in <module>
    pipe = DiffusionPipeline.from_pretrained("SimianLuo/LCM_Dreamshaper_v7", custom_pipeline="latent_consistency_txt2img", custom_revision="main")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 472, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/AI/stable-diffusion-webui/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2044, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.
```
