### ISSUE TITLE
WuerstchenPrior no attn_processors in diffusers/examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py

### ISSUE THREAD

**Issue by zdxpan** [huggingface/diffusers#5441]
### Describe the bug

~/workspace/diffusers/examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py

`  File "/home/dell/workspace/wuerstchen/text_to_image/train_text_to_image_lora_prior.py", line 907, in <module>
    main()
  File "/home/dell/workspace/wuerstchen/text_to_image/train_text_to_image_lora_prior.py", line 549, in main
    for name in prior.attn_processors.keys():
  File "/home/dell/.conda/envs/sd/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 210, in __getattr__
    return super().__getattr__(name)
  File "/home/dell/.conda/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'WuerstchenPrior' object has no attribute 'attn_processors'
(base) [dell@bogondx]~/workspace% ls ~/workspace/diffusers/examples/wuerstchen/text_to_image/train_text_to_image_lora_prior.py `

### Reproduction

diffusion_pytorch_model.safetensors ==   https://huggingface.co/warp-ai/wuerstchen-prior/resolve/main/prior/diffusion_pytorch_model.safetensors
`  
from diffusers.pipelines.wuerstchen import DEFAULT_STAGE_C_TIMESTEPS, WuerstchenPrior 
 # load prior model, cast to weight_dtype and move to device
    # prior = WuerstchenPrior.from_pretrained(args.pretrained_prior_model_name_or_path, subfolder="prior")
    config = {    "_class_name": "WuerstchenPrior",    "_diffusers_version": "0.21.0.dev0",
            "c": 1536,    "c_cond": 1280,    "c_in": 16,    "c_r": 64,    "depth": 32,    "dropout": 0.1,    "nhead": 24
        }

    prior = WuerstchenPrior(**config)
    state_dict = load_file("/home/dell/workspace/wuerstchen/prior/prior/diffusion_pytorch_model.safetensors", device="cpu")
    prior.load_state_dict(state_dict)
    prior.to(accelerator.device, dtype=weight_dtype)

    # lora attn processor
    lora_attn_procs = {}
    for name in prior.attn_processors.keys():
        lora_attn_procs[name] = LoRAAttnProcessor(hidden_size=prior.config["c"], rank=args.rank)
    prior.set_attn_processor(lora_attn_procs)
    lora_layers = AttnProcsLayers(prior.attn_processors)
`

### System Info

same ldm requirement`s dependes

**Comment by patrickvonplaten** [comment]
Hey @zdxpan, 

Sorry I'm not able to reproduce this code snippet, could you make sure that your code example can be run?

**Comment by zdxpan** [comment]
cd dictory 
`diffusers/examples/wuerstchen/text_to_image
and run python run train_text_to_image_lora_prior.py 
`

> Hey @zdxpan,
> 
> Sorry I'm not able to reproduce this code snippet, could you make sure that your code example can be run?

**Comment by kamwoh** [comment]
I have a similar bug, `unet.attn_processors` was there, but after a forward pass, `unet.attn_processors` cannot be accessed.

**Comment by bitcoinvsalts** [comment]
> I have a similar bug, `unet.attn_processors` was there, but after a forward pass, `unet.attn_processors` cannot be accessed. `hasattr(unet, 'attn_processors')` is false
> 
> ```
> Traceback (most recent call last):
>    ...
>     unet.save_attn_procs(args.output_dir)
>   File "/home/kamwoh/anaconda3/envs/pt310/lib/python3.10/site-packages/diffusers/loaders.py", line 642, in save_attn_procs
>     for (_, x) in self.attn_processors.items()
>   File "/home/kamwoh/anaconda3/envs/pt310/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 213, in __getattr__
>     return super().__getattr__(name)
>   File "/home/kamwoh/anaconda3/envs/pt310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?
> ```

any solution for this issue?

**Comment by aihao2000** [comment]
I also had this problem, I used 0.21.0 example training script and 0.21.0 diffusers, how did I solve it? In a hurry

**Comment by patrickvonplaten** [comment]
cc @kashif could you check here?

**Comment by kashif** [comment]
sure @patrickvonplaten checking!

**Comment by kashif** [comment]
whenever you get a chance @zdxpan can you try out PR #5959
