### ISSUE TITLE
LoraLoaderMixin.lora_state_dict does not respect argument local_files_only

### ISSUE THREAD

**Issue by Teriks** [huggingface/diffusers#5458]
### Describe the bug

I assume Lora loading is going to be subject to a lot of changes but on 0.21.4 I am unable to load cached weights
without a network connection at least for the model 'sayakpaul/sd-model-finetuned-lora-t4'

When attempting to use the forwarded argument: local_files_only=True

There is a network connection attempted in: diffusers/loader.py

line 1239, in lora_state_dict
    weight_name = cls._best_guess_weight_name

### Reproduction

pipeline.load_lora_weights('sayakpaul/sd-model-finetuned-lora-t4')

On a pipeline while having a network connection so that it enters the cache.

disconnect network.

load again:

pipeline.load_lora_weights('sayakpaul/sd-model-finetuned-lora-t4', local_files_only=True)

### System Info

diffusers 0.21.4, Windows 10

**Comment by patrickvonplaten** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for reporting! Could you provide a fully reproducible snippet?

**Comment by Teriks** [comment]
**test.py**

```
import sys
import torch
from diffusers import StableDiffusionPipeline

local_files_only = sys.argv[1].lower() == 'true'


print('local_files_only =', local_files_only)

pipe = StableDiffusionPipeline.from_pretrained('CompVis/stable-diffusion-v1-4',
                                               torch_dtype=torch.float16,
                                               local_files_only=local_files_only)

pipe.load_lora_weights('sayakpaul/sd-model-finetuned-lora-t4',
                       local_files_only=local_files_only)
```


While connected to the internet run this to download and cache mentioned models:

``python test.py false``

After running that, disable any network connectivity on your system and run this:

``python test.py true``

Result:

```
python test.py true  
local_files_only = True
Loading pipeline components...:
text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...:
Traceback (most recent call last):
  File "REDACT\venv\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACT\venv\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "REDACT\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "REDACT\venv\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "REDACT\venv\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000023CC12A9B50>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACT\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sayakpaul/sd-model-finetuned-lora-t4 (Caused by NameResolutionError("<ur
llib3.connection.HTTPSConnection object at 0x0000023CC12A9B50>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "REDACT\test.py", line 14, in <module>
    pipe.load_lora_weights('sayakpaul/sd-model-finetuned-lora-t4',
  File "REDACT\venv\Lib\site-packages\diffusers\loaders.py", line 1092, in load_lora_weights
    state_dict, network_alphas = self.lora_state_dict(pretrained_model_name_or_path_or_dict, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\loaders.py", line 1239, in lora_state_dict
    weight_name = cls._best_guess_weight_name(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\loaders.py", line 1288, in _best_guess_weight_name
    files_in_repo = model_info(pretrained_model_name_or_path_or_dict).siblings
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\huggingface_hub\hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/sayakpaul/sd-model-finetuned-lora-t4 (Caused by Nam
eResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000023CC12A9B50>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 5f4a7d69-0f78-4ebe-9643-4a
2234d32e3e)')
```

**Comment by sayakpaul** [comment]
Thanks for providing the snippet. 

You can resolve the issue by downloading those checkpoints locally and passing their local paths. have you tried that?

**Comment by Teriks** [comment]
I have not tried pointing it directly at a checkpoint folder yet.

I suppose another work around would be to try to find it in the cache manually with ``huggingface_hub.try_to_load_from_cache``
using a probable LoRA weights filename and then give it the snapshot base folder if it exists.

**Comment by sayakpaul** [comment]
Thanks for providing your suggestion.

> I have not tried pointing it directly at a checkpoint folder yet.

Is easier and does the work without introducing any complexity.
