### ISSUE TITLE
DiffEdit pipeline does not support “inpaint_strength” values other than 0.8

### ISSUE THREAD

**Issue by exx8** [huggingface/diffusers#5465]
### Describe the bug

The diff Edit throws an exception when passed inpaint_strength different from 0.8.
It does however function with strength of 0.8.

### Reproduction

```
import PIL
import requests
import torch
from io import BytesIO
import numpy as np
from diffusers import StableDiffusionDiffEditPipeline,DDIMScheduler,DDIMInverseScheduler

def download_image(url):
    response = requests.get(url)
    return PIL.Image.open(BytesIO(response.content)).convert("RGB")


img_url = "https://i.ibb.co/SsbT3By/Hyen9lkzp-0-0-3000-2248-0-x-large.jpg"

init_image = download_image(img_url).resize((512, 512))

pipeline = StableDiffusionDiffEditPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1", torch_dtype=torch.float16
)
pipeline = pipeline.to("cuda")

pipeline.scheduler = DDIMScheduler.from_config(pipeline.scheduler.config)
pipeline.inverse_scheduler = DDIMInverseScheduler.from_config(pipeline.scheduler.config)
pipeline.enable_model_cpu_offload()

mask_prompt = "boat"
prompt = "pirate ship"

mask_image = pipeline.generate_mask(image=init_image, source_prompt=prompt, target_prompt=mask_prompt)
image_latents = pipeline.invert(image=init_image, prompt=mask_prompt).latents
image = pipeline(prompt=prompt, mask_image=mask_image, image_latents=image_latents,inpaint_strength=0.75).images[0]
image.save("diffedit.png")

```

### Logs

```shell
Loading pipeline components...: 100%|██████████| 6/6 [00:01<00:00,  4.75it/s]
The config attributes {'skip_prk_steps': True} were passed to DDIMInverseScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
100%|██████████| 40/40 [00:02<00:00, 17.36it/s]
Traceback (most recent call last):
  File "/mnt/raid/home/user/project/diffedit.py", line 31, in <module>
    image = pipeline(prompt=prompt, mask_image=mask_image, image_latents=image_latents,inpaint_strength=0.75).images[0]
  File "/mnt/raid/home/user/project/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/raid/home/user/project/venv/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_diffedit.py", line 1442, in __call__
    raise ValueError(
ValueError: `image_latents` must have batch size 1 with latent images from 37 timesteps, but has batch size 1 with latent images from 40 timesteps.
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @exx8, 

I'm not sure we're planning on adding this feature at the moment. Would you like to give it a try to add it? cc @sayakpaul

**Comment by clarencechen** [comment]
@exx8 Please provide the same value for the `inpaint_strength` argument when calling `StableDiffusionDiffEditPipeline.invert()`. Maybe the docs should be updated to clarify this.

**Comment by exx8** [comment]
@patrickvonplaten Currently, I'm focused on my paper (hopefully one day it will be supported by diffusers!). So maybe in the future I'll give it a try?
@clarencechen To be honest, I don't understand why the user is asked to give two parameters that should have the same value; otherwise the pipeline just doesn't work. I believe that both parameters should be unified instead (for this pipeline).
