### ISSUE TITLE
the demo code  generate one image is not work

### ISSUE THREAD

**Issue by diaojunxian** [huggingface/diffusers#5488]
### Describe the bug

my diffusers version is 
```
diffusers                0.21.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-ml-py             11.525.131
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.52
nvidia-nvtx-cu12         12.1.105
```

when run the demo code:
```
from diffusers import StableDiffusionPipeline, LMSDiscreteScheduler

pipe = StableDiffusionPipeline.from_pretrained("stable-diffusion-v1-5")
pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]

image.save("astronaut_rides_horse.png")
```

### Reproduction

run the demo code

### Logs

```shell
the console log

Loading pipeline components...:   0%|                                 | 0/7 [00:00<?, ?it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Loading pipeline components...:  14%|███▌                     | 1/7 [00:02<00:14,  2.36s/it]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading pipeline components...: 100%|█████████████████████████| 7/7 [00:09<00:00,  1.30s/it]
Traceback (most recent call last):
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 717, in convert_to_tensors
    tensor = as_tensor(value)
RuntimeError: Could not infer dtype of NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/sd/test.py", line 11, in <module>
    image = pipe(prompt).images[0]
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 635, in __call__
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
  File "/home/m1l03053/.conda/envs/3.10/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 312, in encode_prompt
    text_inputs = self.tokenizer(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2530, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2636, in _call_one
    return self.encode_plus(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2709, in encode_plus
    return self._encode_plus(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 652, in _encode_plus
    return self.prepare_for_model(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3199, in prepare_for_model
    batch_outputs = BatchEncoding(
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 210, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/m1l03053/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 733, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```
```


### System Info

python == 3.10



### Who can help?

_No response_

**Comment by DN6** [comment]
@diaojunxian  I'm unable to reproduce this based on your example. Can you tell me what version of `transformers` you have installed?

**Comment by diaojunxian** [comment]
> @diaojunxian I'm unable to reproduce this based on your example. Can you tell me what version of `transformers` you have installed?

the latest version. 4.31.0

**Comment by standardAI** [comment]
Hi @diaojunxian. Is your problem still continuing? If so, could you share the output of this command from your terminal:
```sh
diffusers-cli env && python -c "import numpy; print(numpy.__version__)"
```
