### ISSUE TITLE
Using np.ndarray or cv2 image as image doesn't work: image batch size must be same as prompt batch size

### ISSUE THREAD

**Issue by geroldmeisinger** [huggingface/diffusers#5509]
### Describe the bug

image parameter accepts np.ndarray but doesn't work with images loaded from `cv2.imread()` or PIL images converted with `np.array(image)`

https://huggingface.co/docs/diffusers/v0.21.0/en/api/pipelines/controlnet#diffusers.StableDiffusionControlNetPipeline

> image (torch.FloatTensor, PIL.Image.Image, np.ndarray, List[torch.FloatTensor], List[PIL.Image.Image], List[np.ndarray], — List[List[torch.FloatTensor]], List[List[np.ndarray]] or List[List[PIL.Image.Image]]): The ControlNet input condition to provide guidance to the unet for generation. If the type is specified as torch.FloatTensor, it is passed to ControlNet as is. PIL.Image.Image can also be accepted as an image. The dimensions of the output image defaults to image’s dimensions. If height and/or width are passed, image is resized accordingly. If multiple ControlNets are specified in init, images must be passed as a list such that each element of the list can be correctly batched for input to a single ControlNet.

### Reproduction

```
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from diffusers.utils import load_image
import torch
import numpy as np
import cv2

image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/input_image_vermeer.png")
#image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/vermeer_canny_edged.png")

canny_image = np.array(image)
canny_image = cv2.Canny(canny_image, 100, 200)
canny_image = canny_image[:, :, None]
canny_image = np.concatenate([canny_image, canny_image, canny_image], axis=2)

controlnet = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16, use_safetensors=True)
pipe = StableDiffusionControlNetPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16, use_safetensors=True, safety_checker=None).to("cuda")

#print(f"input type: {type(image)}")
#output = pipe("statue", num_inference_steps=10, image=[image]).images[0]

print(f"input type: {type(canny_image)}")
output = pipe("statue", num_inference_steps=10, image=canny_image).images[0]
#output = pipe("statue", num_inference_steps=10, image=[canny_image]).images[0]

print(f"output type: {type(output)}")
output.save("output.webp")
#output.imwrite("output.webp")
```

### Logs

```shell
input type: <class 'numpy.ndarray'>
Traceback (most recent call last):
  File "~/diffusers/examples/controlnet/test.py", line 22, in <module>
    output = pipe("statue", num_inference_steps=10, image=canny_image).images[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/diffusers/examples/controlnet/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "~/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 816, in __call__
    self.check_inputs(
  File "~/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 530, in check_inputs
    self.check_image(image, prompt, prompt_embeds)
  File "~/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet.py", line 639, in check_image
    raise ValueError(
ValueError: If image batch size is not 1, image batch size must be same as prompt batch size. image batch size: 512, prompt batch size: 1
```
```


### System Info

diffusers 0.21


### Who can help?

_No response_

**Comment by DN6** [comment]
@geroldmeisinger I think the issue here is that if you're passing in a numpy array from PIL, you need to provide an array which has a batch dimension. e.g. the array shape has to be `(1, 512, 512, 3)`. 

Using `cv2.imread()` or PIL images converted with `np.array(image)` do not add this batch dimension.

**Comment by wesleywu** [comment]
I think the code in pipeline_controlnet_img2img.py
```
        if image_is_pil:
            image_batch_size = 1
        else:
            image_batch_size = len(image)
```
shoud be 
```
        if image_is_pil or image_is_tensor or image_is_np:
            image_batch_size = 1
        else:
            image_batch_size = len(image)
```
