### ISSUE TITLE
I have a problem when using StableDiffusionInpaintPipeline()

### ISSUE THREAD

**Issue by bent1e** [huggingface/diffusers#5545]
### Describe the bug

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "stable-diffusion-inpainting"
)
Loading pipeline components...:  29%|██▊       | 2/7 [02:26<06:06, 73.22s/it]
Traceback (most recent call last):
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 106, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/torch/serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/e/insect/Grounded-Segment-Anything/SD.py", line 10, in <module>
    pipeline = StableDiffusionInpaintPipeline.from_pretrained(
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 472, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 641, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/home/bentle/anaconda3/envs/aigc/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 112, in load_state_dict
    if f.read().startswith("version"):
OSError: [Errno 5] Input/output error
ERROR conda.cli.main_run:execute(47): `conda run python /mnt/e/insect/Grounded-Segment-Anything/SD.py` failed. (See above for error)

### Reproduction

pipeline = StableDiffusionInpaintPipeline.from_pretrained(
    "stable-diffusion-inpainting"
)
pipeline = pipeline.to("cuda")

### System Info

diffusers version: 0.22.0.dev0
Platform: Linux
Python version: 3.8.0
PyTorch version (GPU): cu116
Using GPU in script?: YES

### Who can help?

 @yiyixuxu @DN6 @patrickvonplaten @sayakpaul @patrickvonplaten

**Comment by DN6** [comment]
Hi @bent1e could you please provide a code snippet we can use to reproduce this issue. The checkpoint you have set doesn't appear to be a valid one.
