### ISSUE TITLE
ValueError: Unexpected keyword arguments: use_reentrant

### ISSUE THREAD

**Issue by unrue** [huggingface/diffusers#5557]
Hi,

I'm training Dreambooth  with dog dataset test, (Prior-reservation loss case) using HPC machine having Tesla V100 card, pytorch 1.10.1,diffusers 0.22.0.dev0, accelerate 0.20.3. The following is the launch command as the manual suggest:

```
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800 
```
having the error:

```
10/27/2023 13:47:54 - INFO - __main__ -   Total optimization steps = 800
Steps:   0%|          | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 1422, in <module>
    main(args)
  File "train_dreambooth.py", line 1253, in main
    model_pred = unet(
  File "*/image2image_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "*/image2image_env/diffusers/src/diffusers/models/unet_2d_condition.py", line 1066, in forward
    sample, res_samples = downsample_block(
  File "*/image2image_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "*/image2image_env/diffusers/src/diffusers/models/unet_2d_blocks.py", line 1150, in forward
    hidden_states = attn(
  File "*/image2image_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "*/image2image_env/diffusers/src/diffusers/models/transformer_2d.py", line 322, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "*/image2image_env/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 209, in checkpoint
    raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwargs))
ValueError: Unexpected keyword arguments: use_reentrant
```

What does such error means? Wrong accelerate version? Which version should I use? Thanks.

**Comment by unrue** [comment]
Ok, I solved disabling gradient checkpoint

**Comment by YuMJie** [comment]
> disabling gradient chec

could you provide some details about the  disabling gradient checkpoint? :)

**Comment by unrue** [comment]
Simply not using --gradient_checkpointing flag.

**Comment by YuMJie** [comment]
> Simply not using --gradient_checkpointing flag.

Thank you for your help, it works for me!
