### ISSUE TITLE
SDXL DreamBooth LoRA training throws errors

### ISSUE THREAD

**Issue by unalkalkan** [huggingface/diffusers#5563]
### Describe the bug

SDXL DreamBooth LoRA training colab notebook doesn't work properly. It throws an error at the `!accelerate launch train_dreambooth_lora_sdxl.py` section.

### Reproduction

You can just ran the [notebook](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb) without changing anything.

### Logs

```shell
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
10/27/2023 21:54:14 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

Downloading (…)okenizer_config.json: 100% 737/737 [00:00<00:00, 3.45MB/s]
Downloading (…)tokenizer/vocab.json: 100% 1.06M/1.06M [00:00<00:00, 1.54MB/s]
Downloading (…)tokenizer/merges.txt: 100% 525k/525k [00:00<00:00, 140MB/s]
Downloading (…)cial_tokens_map.json: 100% 472/472 [00:00<00:00, 2.58MB/s]
Downloading (…)okenizer_config.json: 100% 725/725 [00:00<00:00, 4.20MB/s]
Downloading (…)cial_tokens_map.json: 100% 460/460 [00:00<00:00, 2.61MB/s]
Downloading (…)_encoder/config.json: 100% 565/565 [00:00<00:00, 3.24MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading (…)ncoder_2/config.json: 100% 575/575 [00:00<00:00, 3.37MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading (…)cheduler_config.json: 100% 479/479 [00:00<00:00, 2.71MB/s]
{'thresholding', 'dynamic_thresholding_ratio', 'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
Downloading model.safetensors: 100% 492M/492M [00:04<00:00, 107MB/s]
Downloading model.safetensors: 100% 2.78G/2.78G [00:10<00:00, 253MB/s]
Downloading (…)lve/main/config.json: 100% 631/631 [00:00<00:00, 3.21MB/s]
Downloading (…)ch_model.safetensors: 100% 335M/335M [00:00<00:00, 391MB/s]
Downloading (…)ain/unet/config.json: 100% 1.68k/1.68k [00:00<00:00, 7.79MB/s]
Downloading (…)ch_model.safetensors: 100% 10.3G/10.3G [00:52<00:00, 195MB/s]
{'attention_type', 'dropout', 'reverse_transformer_layers_per_block'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/content/train_dreambooth_lora_sdxl.py", line 1372, in <module>
    main(args)
  File "/content/train_dreambooth_lora_sdxl.py", line 737, in main
    unet.enable_xformers_memory_efficient_attention()
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 290, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 254, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 254, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 250, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 247, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 268, in set_use_memory_efficient_attention_xformers
    raise e
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 262, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py", line 337, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 120, in _dispatch_fw
    return _run_priority_list(
  File "/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/dispatch.py", line 63, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    xFormers wasn't build with CUDA support
    attn_bias type is <class 'NoneType'>
    operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
    xFormers wasn't build with CUDA support
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
    requires GPU with sm80 minimum compute capacity, e.g., A100/H100/L4
    Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    xFormers wasn't build with CUDA support
    operator wasn't built - see `python -m xformers.info` for more info
    unsupported embed per head: 40
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--instance_data_dir=dog', '--output_dir=lora-trained-xl-colab', '--mixed_precision=fp16', '--instance_prompt=a photo of sks dog', '--resolution=1024', '--train_batch_size=2', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--enable_xformers_memory_efficient_attention', '--mixed_precision=fp16', '--use_8bit_adam', '--max_train_steps=500', '--checkpointing_steps=717', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Accelerate version: 0.24.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: not that I know of

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Run without `xformers`:

```bash
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
```

If you're on PT 2.0 or above, we use SDPA by default, so training should still be memory-efficient. 

See more here: https://github.com/huggingface/diffusers/issues/5004, especially this: https://github.com/huggingface/diffusers/issues/5004#issuecomment-1780909598

**Comment by unalkalkan** [comment]
Thanks! It worked when I removed `--enable_xformers_memory_efficient_attention` flag as well, which one should.

Should I open a PR to modify the colab notebook in the repo as well?

**Comment by sayakpaul** [comment]
For now, let's maybe not since it could help the xformers team to figure out the compatibility problems, and so on. 

However, it would make sense to fix the versions of PyTorch 2.0.1 and xformers (0.21) in the Colab Notebook. WDYT? 

Cc: @patrickvonplaten

**Comment by unalkalkan** [comment]
didn't seem to work with applying the following cell, which indicates the versions you give.

```bash
!pip uninstall torch -y
!pip install torch==2.0.1
!pip install xformers==0.0.21 bitsandbytes transformers accelerate
```

By the way, when I haven't used the xformers, train time increased to nearly 2 hours from 1 hour.  It did worked tho so I guess it's something

**Comment by sayakpaul** [comment]
You probably need to specify the exact CUDA wheels during the installation process too. Something like:

```bash
pip install torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cu118
```

I'd recommend doing that as soon as you start the Colab Runtime. 

Your Colab Runtime might need a restart too after that.

**Comment by alireza18878** [comment]
I am having the same issue, has there been a solution for this problem (without disabling memory_efficient_attention_forward)?
