### ISSUE TITLE
AttributeError: 'FrozenDict' object has no attribute 'scaling_factor'

### ISSUE THREAD

**Issue by hosnasn1987** [huggingface/diffusers#5572]
### Describe the bug

@thedarkzeno
in line 715 of the file i get this error:
vae.config has no attribute scaling-factor
what should i do?

### Reproduction

latents = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist.sample()
                latents = latents * vae.config.scaling_factor

### Logs

```shell
env: MODEL_NAME=runwayml/stable-diffusion-inpainting
env: INSTANCE_DIR=/content/images/
env: OUTPUT_DIR=content/outputs/1000
env: CLASS_DIR=/content/class_chair/
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1698588447.260774   22204 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
2023-10-29 14:07:32.941937: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-29 14:07:32.942003: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-29 14:07:32.942042: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-29 14:07:35.500834: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Steps:   0% 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/diffusers/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py", line 825, in <module>
    main()
  File "/content/gdrive/MyDrive/diffusers/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py", line 715, in main
    latents = latents * vae.config.scaling_factor
AttributeError: 'FrozenDict' object has no attribute 'scaling_factor'
Steps:   0% 0/800 [00:04<?, ?it/s]
I0000 00:00:1698588487.737730   22204 tfrt_cpu_pjrt_client.cc:352] TfrtCpuClient destroyed.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_inpaint.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-inpainting', '--instance_data_dir=/content/images/', '--class_data_dir=/content/class_chair/', '--output_dir=content/outputs/1000', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of snapp_chair', '--class_prompt=a photo of chair', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800']' returned non-zero exit status 1
```

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.34.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

I0000 00:00:1698588873.535338   23948 tfrt_cpu_pjrt_client.cc:352] TfrtCpuClient destroyed.

### Who can help?

@thedarkzeno

**Comment by DN6** [comment]
@hosnasn1987 Could you please provide a code snippet showing the arguments that your are passing to the training script

**Comment by hosnasn1987** [comment]
now i get this error

env: MODEL_NAME=runwayml/stable-diffusion-inpainting
env: INSTANCE_DIR=/content/images/
env: OUTPUT_DIR=content/outputs/1000
env: CLASS_DIR=/content/class_chair/
2023-10-31 07:04:20.320721: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-31 07:04:20.320784: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-31 07:04:20.320828: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-31 07:04:23.771200: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Steps:   0% 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/gdrive/MyDrive/diffusers/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py", line 825, in <module>
    main()
  File "/content/gdrive/MyDrive/diffusers/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py", line 785, in main
    optimizer.step()
  File "/usr/local/lib/python3.10/dist-packages/accelerate/optimizer.py", line 145, in step
    self.optimizer.step(closure)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 173, in step
    self._init_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/adamw.py", line 121, in _init_group
    state["exp_avg"] = torch.zeros_like(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB. GPU 0 has a total capacty of 14.75 GiB of which 40.81 MiB is free. Process 517494 has 14.71 GiB memory in use. Of the allocated memory 13.22 GiB is allocated by PyTorch, and 148.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0% 0/800 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 994, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth_inpaint.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-inpainting', '--instance_data_dir=/content/images/', '--class_data_dir=/content/class_chair/', '--output_dir=content/outputs/1000', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of snapp_chair', '--class_prompt=a photo of chair', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800']' returned non-zero exit status 1.

**Comment by hosnasn1987** [comment]
it is all of my code:

from google.colab import drive
drive.mount('/content/gdrive')

%cd gdrive/

%cd MyDrive/

!git clone https://github.com/ShivamShrirao/diffusers

%cd diffusers/
!pip install -e .

# For GPU efficiency
!pip install bitsandbytes

# Install dreambooth requirements
%cd examples/research_projects/dreambooth_inpaint/
!pip install --no-cache-dir -r requirements.txt

# Accelerate environment
!accelerate config default

! pip install --upgrade diffusers

import torch

from diffusers import StableDiffusionInpaintPipeline
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    revision="fp16",
    torch_dtype=torch.float16,
)

! pip install --upgrade accelerate

%env MODEL_NAME=runwayml/stable-diffusion-inpainting
%env INSTANCE_DIR=/content/images/
%env OUTPUT_DIR=content/outputs/1000
%env CLASS_DIR=/content/class_chair/


# !accelerate launch train_dreambooth_inpaint.py \

!accelerate launch train_dreambooth_inpaint.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of snapp_chair" \
  --class_prompt="a photo of chair" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=800

! diffusers-cli env

**Comment by nickkolok** [comment]
Have you tried to use memory optimization techniques: `xformers`, `bitsandbytes` etc? Also, you may want to specify the mixed precision in the parameters, smth like
```
  --mixed_precision="fp16" \
  --use_8bit_adam \
```

**Comment by yiyixuxu** [comment]
cc @sayakpaul here

**Comment by sayakpaul** [comment]
The code you mentioned seems to be using a fork of diffusers which we don't maintain. Could you use our training scripts from https://github.com/huggingface/diffusers/tree/main/examples?

Also, in your commands, it's hard to hard what are you passing as a value for the `pretrained_model_name_or_path`.
