### ISSUE TITLE
KeyError: 'time_embed.0.weight' when using `ControlNetModel.from_single_file`

### ISSUE THREAD

**Issue by xuyxu** [huggingface/diffusers#5577]
### Describe the bug

Hi, I had one problem on loading SXDL ControlNet from local files, using the `from_single_file` method.

The model in safetensors format and the config file are downloaded from https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-small/tree/main .

When calling `ControlNetModel.from_single_file` to load the control net, diffusers throws the following error: 

```bash
Traceback (most recent call last):
  File "/home/admin/xuyixuan.xyx/test_diffusers_sdxl_dual_controlnet.py", line 21, in <module>
    controlnet = ControlNetModel.from_single_file(
  File "/home/xuyixuan.xyx/miniconda3/lib/python3.10/site-packages/diffusers/loaders.py", line 2653, in from_single_file
    controlnet = download_controlnet_from_original_ckpt(
  File "/home/xuyixuan.xyx/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1719, in download_controlnet_from_original_ckpt
    controlnet = convert_controlnet_checkpoint(
  File "/home/xuyixuan.xyx/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1095, in convert_controlnet_checkpoint
    converted_ctrl_checkpoint = convert_ldm_unet_checkpoint(
  File "/home/xuyixuan.xyx/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 422, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```

Will appreciate help from the community very much, thanks ! 

### Reproduction

```python
import torch
from diffusers import ControlNetModel

controlnet = ControlNetModel.from_single_file(
    "diffusion_pytorch_model.safetensors",
    config_file="./config.json",
    torch_dtype=torch.float16,
    local_files_only=True
)
```

`diffusion_pytorch_model.safetensors"` and `config.json` are local files downloaded from https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-small/tree/main

### System Info

- `diffusers` version: 0.21.4
- Platform: Linux-4.19.91-009.ali4000.alios7.x86_64-x86_64-with-glibc2.32
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.18.0
- Transformers version: 4.30.2
- Accelerate version: 0.19.0
- xFormers version: 0.0.21
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu @DN6 @patrickvonplaten

**Comment by sayakpaul** [comment]
The model is not supposed to be used using `from_single_file` method. It's a checkpoint thay is already compatible with diffusers. So, please do

```
ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0-small")
```
