### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'convert'   When are building pokemon-blip-captions

### ISSUE THREAD

**Issue by Jiancong** [huggingface/diffusers#5596]
### Describe the bug

@sayakpaul @patrickvonplaten

I follow this tutorial(https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/README_sdxl.md) to build SDXL LoRA based on Pokemon, but failed. 
 If anyone met smiliar issue when building. 

Thanks,
Jiancong

### Reproduction

!cd diffusers/examples/text_to_image && accelerate launch train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="lambdalabs/pokemon-blip-captions" \
  --resolution=512 --center_crop --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=10000 \
  --use_8bit_adam \
  --learning_rate=1e-06 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --report_to="wandb" \
  --validation_prompt="a cute Sundar Pichai creature" --validation_epochs 5 \
  --checkpointing_steps=5000 \
  --output_dir="sdxl-pokemon-model" \
  --push_to_hub

### Logs

```shell
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Downloading (…)okenizer_config.json: 100%|█████| 737/737 [00:00<00:00, 4.09MB/s]
Downloading (…)tokenizer/vocab.json: 100%|█| 1.06M/1.06M [00:00<00:00, 14.3MB/s]
Downloading (…)tokenizer/merges.txt: 100%|███| 525k/525k [00:00<00:00, 11.1MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████| 472/472 [00:00<00:00, 2.27MB/s]
Downloading (…)okenizer_config.json: 100%|█████| 725/725 [00:00<00:00, 4.21MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████| 460/460 [00:00<00:00, 3.32MB/s]
Downloading (…)_encoder/config.json: 100%|█████| 565/565 [00:00<00:00, 3.82MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading (…)ncoder_2/config.json: 100%|█████| 575/575 [00:00<00:00, 4.11MB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Downloading (…)cheduler_config.json: 100%|█████| 479/479 [00:00<00:00, 4.03MB/s]
{'thresholding', 'clip_sample_range', 'dynamic_thresholding_ratio', 'variance_type'} was not found in config. Values will be initialized to default values.
Downloading model.safetensors: 100%|██████████| 492M/492M [00:02<00:00, 219MB/s]
Downloading model.safetensors: 100%|████████| 2.78G/2.78G [00:12<00:00, 229MB/s]
Downloading (…)lve/main/config.json: 100%|█████| 631/631 [00:00<00:00, 4.99MB/s]
Downloading (…)ch_model.safetensors: 100%|███| 335M/335M [00:11<00:00, 30.3MB/s]
Downloading (…)ain/unet/config.json: 100%|█| 1.68k/1.68k [00:00<00:00, 12.2MB/s]
Downloading (…)ch_model.safetensors: 100%|██| 10.3G/10.3G [00:46<00:00, 221MB/s]
{'dropout', 'attention_type', 'reverse_transformer_layers_per_block'} was not found in config. Values will be initialized to default values.
/opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Downloading: 100%|██████████████████████████████| 731/731 [00:00<00:00, 803kB/s]
Downloading and preparing dataset imagefolder/pokemon (download: 95.05 MiB, generated: 113.89 MiB, post-processed: Unknown size, total: 208.94 MiB) to /root/.cache/huggingface/datasets/parquet/lambdalabs--pokemon-blip-captions-10e3527a764857bd/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901...
Downloading data files:   0%|                             | 0/1 [00:00<?, ?it/s]
Downloading data:   0%|                             | 0.00/99.7M [00:00<?, ?B/s]
Downloading data:   2%|▍                   | 2.19M/99.7M [00:00<00:04, 21.9MB/s]
Downloading data:   9%|█▊                  | 9.08M/99.7M [00:00<00:01, 49.6MB/s]
Downloading data:  16%|███▏                | 16.1M/99.7M [00:00<00:01, 58.8MB/s]
Downloading data:  23%|████▌               | 22.9M/99.7M [00:00<00:01, 62.5MB/s]
Downloading data:  29%|█████▊              | 29.1M/99.7M [00:00<00:03, 23.0MB/s]
Downloading data:  36%|███████▏            | 36.1M/99.7M [00:01<00:02, 30.5MB/s]
Downloading data:  43%|████████▋           | 43.1M/99.7M [00:01<00:01, 37.7MB/s]
Downloading data:  50%|██████████          | 50.2M/99.7M [00:01<00:01, 44.7MB/s]
Downloading data:  57%|███████████▎        | 56.6M/99.7M [00:01<00:01, 25.0MB/s]
Downloading data:  64%|████████████▊       | 63.5M/99.7M [00:01<00:01, 31.4MB/s]
Downloading data:  71%|██████████████▏     | 70.5M/99.7M [00:01<00:00, 37.9MB/s]
Downloading data:  78%|███████████████▌    | 77.4M/99.7M [00:02<00:00, 44.0MB/s]
Downloading data:  85%|████████████████▉   | 84.5M/99.7M [00:02<00:00, 49.9MB/s]
Downloading data:  91%|██████████████████▎ | 91.0M/99.7M [00:02<00:00, 25.8MB/s]
Downloading data: 100%|████████████████████| 99.7M/99.7M [00:03<00:00, 28.1MB/s]
Downloading data files: 100%|█████████████████████| 1/1 [00:04<00:00,  4.24s/it]
Extracting data files: 100%|████████████████████| 1/1 [00:00<00:00, 1084.92it/s]
Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/parquet/lambdalabs--pokemon-blip-captions-10e3527a764857bd/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 173.70it/s]
  0%|                                                     | 0/1 [00:00<?, ?ba/s]
Traceback (most recent call last):
  File "/kaggle/working/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1258, in <module>
    main(args)
  File "/kaggle/working/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 876, in main
    train_dataset = train_dataset.map(compute_embeddings_fn, batched=True, new_fingerprint=new_fingerprint)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1955, in map
    return self._map_single(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 520, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 487, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2331, in _map_single
    batch = input_dataset._getitem(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1749, in _getitem
    formatted_output = format_table(
  File "/opt/conda/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 532, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/opt/conda/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 285, in __call__
    return self.format_batch(pa_table)
  File "/opt/conda/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 418, in format_batch
    return self.transform(batch)
  File "/kaggle/working/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 822, in preprocess_train
    images = [image.convert("RGB") for image in examples[image_column]]
  File "/kaggle/working/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 822, in <listcomp>
    images = [image.convert("RGB") for image in examples[image_column]]
AttributeError: 'dict' object has no attribute 'convert'
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3.10', 'train_text_to_image_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--dataset_name=lambdalabs/pokemon-blip-captions', '--resolution=512', '--center_crop', '--random_flip', '--proportion_empty_prompts=0.2', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--max_train_steps=10000', '--use_8bit_adam', '--learning_rate=1e-06', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--mixed_precision=fp16', '--report_to=wandb', '--validation_prompt=a cute Sundar Pichai creature', '--validation_epochs', '5', '--checkpointing_steps=5000', '--output_dir=sdxl-pokemon-model', '--push_to_hub']' returned non-zero exit status 1.
```

### System Info

/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.15.133+-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu121 (False)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.33.0
- Accelerate version: 0.22.0
- xFormers version: 0.0.22.post7
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
It looks like a data loading bug if you carefully skim through the logs.

**Comment by Jiancong** [comment]
> It looks like a data loading bug if you carefully skim through the logs.

And what can I do next?

**Comment by ariG23498** [comment]
> ```shell
> images = [image.convert("RGB") for image in examples[image_column]]
> ```

`images = [image.convert("RGB") for image in examples[image_column]]` could you check whether `image` is a `dict` of a PIL tensor. The logs seem to suggest that they are a dictionary which should be further indexed into and then coverted to RGB.

Does that help?

**Comment by intersoulest** [comment]
我也是同一个问题，不知道什么原因

**Comment by huangxu-data** [comment]
there is no convert function for dict.

Try change this line 
`images = [image.convert("RGB") for image in examples[image_column]]`

to

```
from io import BytesIO
from PIL import Image

def convert(image_col):
    bytes_io = BytesIO(image_col['bytes'])
    with Image.open(bytes_io) as img:
        rgb = img.convert("RGB")
    return rgb


images = [convert(image) for image in examples[image_column]]
```
