### ISSUE TITLE
load vae with error

### ISSUE THREAD

**Issue by garychan22** [huggingface/diffusers#5693]
### Describe the bug

I am trying to load the vae model from https://huggingface.co/runwayml/stable-diffusion-inpainting using the code
```
from diffusers import AutoencoderKL
model_path = "huggingface_cache/models--runwayml--stable-diffusion-inpainting"
vae = AutoencoderKL.from_pretrained(model_path, subfolder="vae")
```

with error 
```
ValueError: cross_attention_dim must be specified for CrossAttnDownBlock2D
```

I am confused with this error since that vae has no CrossAttnDownBlock2D in its config.json

### Reproduction

as described above

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/models/modeling_utils.py", line 873, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 254, in from_config
    model = cls(**init_dict)
  File inn"/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 644, in inner_init
    init(self, *args, **init_kwargs)
  File "/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/models/autoencoder_kl.py", line 102, in __init__
    self.encoder = Encoder(
  File "/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/models/vae.py", line 97, in __init__
    down_block = get_down_block(
  File "/home/xxx/miniconda3/envs/InST/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 119, in get_down_block
    raise ValueError("cross_attention_dim must be specified for CrossAttnDownBlock2D")
ValueError: cross_attention_dim must be specified for CrossAttnDownBlock2D
```

### System Info

ubuntu 22.04 
python 3.8
diffusers 0.22.2
transformers 4.18

### Who can help?

@sayakpaul @DN6 @yiyixuxu @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Can't reproduce the error, see here: https://colab.research.google.com/drive/1IQB7b-Ly3gr5STLDHadCUaMlxj4fwi-d?usp=sharing

**Comment by garychan22** [comment]
The issue is raised by the `config.json` existing in the model dir `huggingface_cache/models--runwayml--stable-diffusion-inpainting`,  the model is successfully loaded by removing the `config.json`.
