### ISSUE TITLE
TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'text_encoder'

### ISSUE THREAD

**Issue by LYR-GH** [huggingface/diffusers#5781]
### Describe the bug

It happened when I'm using Stable-Diffusion to draw a picture(I'm using a script [Accelerate with OpenVINO] to make it can use Intel GPU[Xe] to make it faster). But I don't know why it can't work normally, and show me the error info：TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'text_encoder'. It can run normal without that script. I think maybe some extentions not support that script[some extentions need CUDA], but I don't know which extention lead to this problem. Or my script is incomplete, but it did not report any problem(except for the error: without an Nvidia graphics card)when it's in the loading phase.

### Reproduction

Accelerate with OpenVINO：I followed this page to install that script：https://github.com/huggingface/blog/blob/main/openvino.md

Stable Diffusion：I'm using an modpack that many people on the web recommend：https://space.bilibili.com/12566101

(I think it's a very small chance that it's an anomaly in the modpack)

### Logs

```shell
Loading phase:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Installing requirements for Batch Face Swap
Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...
Installing requirements for scikit_learn
current transparent-background 1.2.4
Installing fastai==1.0.60 for DeOldify extension
Installing ffmpeg-python for DeOldify extension
Installing yt-dlp for DeOldify extension
Installing opencv-python for DeOldify extension
Installing Pillow for DeOldify extension
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.009547999999995227
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing pyqt5 requirement for depthmap script
Launching Web UI with arguments: --use-cpu all --skip-torch-cuda-test --theme dark --precision full --no-half --no-half-vae --api --autolaunch
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
[-] ADetailer initialized. version: 23.11.0, num models: 9
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
Using sqlite file: C:\AI-Tools\AI-Painting\extensions\sd-webui-agent-scheduler\task_scheduler.sqlite3
dirname:  C:\AI-Tools\AI-Painting\localizations
localizations:  {'zh_CN': 'C:\\AI-Tools\\AI-Painting\\extensions\\stable-diffusion-webui-localization-zh_CN\\localizations\\zh_CN.json', 'zh-Hans (Stable) [vladmandic]': 'C:\\AI-Tools\\AI-Painting\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable) [vladmandic].json', 'zh-Hans (Stable)': 'C:\\AI-Tools\\AI-Painting\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing) [vladmandic]': 'C:\\AI-Tools\\AI-Painting\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing) [vladmandic].json', 'zh-Hans (Testing)': 'C:\\AI-Tools\\AI-Painting\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
2023-11-13 21:02:04,308 - ControlNet - INFO - ControlNet v1.1.416
ControlNet preprocessor location: C:\AI-Tools\AI-Painting\extensions\sd-webui-controlnet\annotator\downloads
2023-11-13 21:02:04,543 - ControlNet - INFO - ControlNet v1.1.416
Hypernetwork-MonkeyPatch-Extension found!
sd-webui-prompt-all-in-one background API service started successfully.
2023-11-13 21:02:07,866 - roop - INFO - roop v0.0.2
2023-11-13 21:02:07,918 - roop - INFO - roop v0.0.2
Default key/cert pair was already generated by webui
Certificate trust store ready
Loading weights [7f96a1a9ca] from C:\AI-Tools\AI-Painting\models\Stable-diffusion\anything-v5-PrtRE.safetensors
Creating model from config: C:\AI-Tools\AI-Painting\configs\v1-inference.yaml
Applying attention optimization: InvokeAI... done.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
No Image data blocks found.
Model loaded in 44.0s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 41.3s, apply float(): 0.6s, load textual inversion embeddings: 1.0s, calculate empty prompt: 0.2s).
2023-11-13 21:02:57,939 - AnimateDiff - INFO - Hacking i2i-batch.
*Deforum ControlNet support: enabled*
[AddNet] Updating model hashes...
[AddNet] Updating model hashes...
2023-11-13 21:03:20,099 - ControlNetFastload - INFO - Load Controlnet Fastload Filter on isRemote=None and accessLevel=2
Running on local URL:  https://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[AgentScheduler] Task queue is empty
INFO:sd:[AgentScheduler] Task queue is empty
INFO:sd:[AgentScheduler] Registering APIs
[AgentScheduler] Registering APIs
Startup time: 173.3s (prepare environment: 72.9s, import torch: 12.8s, import gradio: 2.8s, setup paths: 1.8s, initialize shared: 0.8s, other imports: 0.9s, setup codeformer: 0.8s, list SD models: 0.5s, load scripts: 14.3s, create ui: 70.7s, gradio launch: 1.2s, app_started_callback: 0.7s).


Error report:
Starting job task(arx9r68ctdpyg9h)
INFO:modules.shared_state:Starting job task(arx9r68ctdpyg9h)
purged
*** Error completing request
*** Arguments: ('task(arx9r68ctdpyg9h)', '1girl,', 'low_quality,worst_quality,', [], 20, 'Euler a', 1, 1, 16, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002947BD84A30>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, {'ad_model': 'mediapipe_face_full', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'txt2img', False, '', '', False, 'Euler a', False, 'anything-v5-PrtRE.safetensors [7f96a1a9ca]', True, 0.5, True, 4, True, 32, True, False, 30, False, 6, False, 512, 512, '', False, 1, 'Both ▦', False, '', False, True, True, False, False, False, False, 100, 100, False, '', '', '', 'generateMasksTab', 4, 4, 2.5, 30, 1.03, 1, 1, 5, 0.5, 5, False, True, False, 20, False, 1024, 0, 15, 'R-ESRGAN 4x+', 'R-ESRGAN 4x+', 0.3, 0.1, '', '', 2, 'Noise sync (sharp)', 0, 0.05, 0, 'DPM++ 2M SDE', False, 0, True, 'keyword prompt', 'keyword1, keyword2', 'None', 'textual inversion first', 'None', 0.7, 'None', False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, False, '', 0, None, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.animatediff_ui.AnimateDiffProcess object at 0x000002947BD87490>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000293CB948D30>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000294740E77C0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000294739E44F0>, False, 'Load Only', None, '', 'Send to txt2img', 'Send to img2img', 'Run', None, [], None, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, None, '', None, True, False, False, False, False, False, 0, 0, '0', 0, False, True, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'None', 1, 1, '', False, False, False, 1, 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, 'CodeFormer', 1, 1, 'None', 1, 1, ['After Upscaling/Before Restore Face'], 0, 'Portrait of a [gender]', 'blurry', 20, ['DPM++ 2M Karras'], '', 0, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, True, False, '', '', '🔄', False, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', [False], '0', '0', '0.4', None, '0', '0', False, None, False, '0', 'C:\\AI-Tools\\AI-Painting\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'Denoised', 5.0, 0.0, 0.0, 'Standard operation', 'mp4', 'h264', 2.0, 0.0, 0.0, False, 0.0, True, True, False, False, False, 1, False, False, False, False, False, False, False, False, False, False, 'control_v1p_sd15_qrcode_monster.yaml', 'GPU', True, 'Euler a', True, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', 0, '', None, True, None, None, False, None, None, False, None, None, False, None, None, False, 50, [], 30, '', 4, [], 1, '', '', '', '', True, False, 0, 'Range', 1, 'GPU', True, False, False, False, False, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 2, 0, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation', 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False) {}
    Traceback (most recent call last):
      File "C:\AI-Tools\AI-Painting\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\AI-Tools\AI-Painting\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\AI-Tools\AI-Painting\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "C:\AI-Tools\AI-Painting\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "C:\AI-Tools\AI-Painting\scripts\openvino_accelerate.py", line 769, in run
        processed = process_images_openvino(p, model_config, p.sampler_name, enable_caching, openvino_device, mode)
      File "C:\AI-Tools\AI-Painting\scripts\openvino_accelerate.py", line 518, in process_images_openvino
        shared.sd_diffusers_model = get_diffusers_sd_model(model_config, sampler_name, enable_caching, openvino_device, mode)
      File "C:\AI-Tools\AI-Painting\scripts\openvino_accelerate.py", line 323, in get_diffusers_sd_model
        sd_model = StableDiffusionPipeline.from_single_file(checkpoint_path, local_config_file=local_config_file, load_safety_checker=False)
      File "C:\AI-Tools\AI-Painting\scripts\openvino_accelerate.py", line 248, in from_single_file
        pipe = download_from_original_stable_diffusion_ckpt(
    TypeError: download_from_original_stable_diffusion_ckpt() got an unexpected keyword argument 'text_encoder'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
```

### System Info

Software:
        Stable Diffusion Webui ：v1.6.0-2-g4afaaf8a  [4afaaf8a020c1df457bcf7250cb1c7f609699fa7  (link：https://gitcode.net/overbill1683/stable-diffusion-webui/commit/4afaaf8a020c1df457bcf7250cb1c7f609699fa7)]
        System：                          Windows11
        Python：                          3.10.6

Hardware:
        RAM：64GB
        Disk： SSD-1T
        CPU： Intel-i5-11th
        GPU： Intel Xe

**Comment by patrickvonplaten** [comment]
Can you please provide a diffusers-only fully reproducible code snippet?
