### ISSUE TITLE
[May be a bug] Train dreambooth with prior reservation and snr gamma two parameters together

### ISSUE THREAD

**Issue by Pursue26** [huggingface/diffusers#5791]
### Describe the bug

[May be a bug] Train dream with prior reservation and snr gamma **two parameters together.**

Check the shape of the Tensor:
```python
loss = F.mse_loss(model_pred.float(), target.float(), reduction="none")
logger.info(f"2: {loss.shape}, {mse_loss_weights.shape}")
logger.info(f"3: {snr.shape}, {timesteps.shape}")
loss = loss.mean(dim=list(range(1, len(loss.shape)))) * mse_loss_weights
loss = loss.mean()
```

Maybe it can be fixed like this, at least this way it can run:
```python
if args.with_prior_preservation:
    # Chunk the noise and model_pred into two parts and compute the loss on each part separately.
    model_pred, model_pred_prior = torch.chunk(model_pred, 2, dim=0)
    target, target_prior = torch.chunk(target, 2, dim=0)
    # add to fix BUG in the shape `mse_loss_weights`
    timesteps, _ = torch.chunk(timesteps, 2, dim=0)
    # Compute prior loss
    prior_loss = F.mse_loss(model_pred_prior.float(), target_prior.float(), reduction="mean")
```

### Reproduction

Train dreambooth with prior reservation and snr gamma **two parameters together.** (train_batch_size > 1)

```bash
export MODEL_NAME="/path/to/stabilityai/stable-diffusion-2"
export INSTANCE_DIR="/path/to/dog"
export CLASS_DIR="/path/to/classdog"

accelerate launch --main_process_port 21992 --config_file ./default_config.yaml --multi_gpu train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --prior_loss_weight=1.0 \
  --output_dir="sd-model-db-train" \
  --instance_prompt="xxxxxxxx" \
  --class_prompt="xxxxxxxx" \
  --validation_prompt="xxxxxxxx" \
  --resolution=768 --center_crop \
  --train_batch_size=16 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=800 \
  --num_class_images=200 \
  --checkpointing_steps=200 \
  --checkpoints_total_limit=3 \
  --mixed_precision="fp16" \
  --report_to="tensorboard" \
  --learning_rate=5e-6 \
  --max_grad_norm=1 \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=0 \
  --snr_gamma=5.0 \
  --with_prior_preservation
```

### Logs

```shell
11/14/2023 17:27:57 - INFO - __main__ - ***** Running training *****
11/14/2023 17:27:57 - INFO - __main__ -   Num examples = 200
11/14/2023 17:27:57 - INFO - __main__ -   Num batches each epoch = 2
11/14/2023 17:27:57 - INFO - __main__ -   Num Epochs = 800
11/14/2023 17:27:57 - INFO - __main__ -   Instantaneous batch size per device = 16
11/14/2023 17:27:57 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 256
11/14/2023 17:27:57 - INFO - __main__ -   Gradient Accumulation steps = 2
11/14/2023 17:27:57 - INFO - __main__ -   Total optimization steps = 800
Steps:   0%|                                                                                                        | 0/800 [00:00<?, ?it/s]
11/14/2023 17:28:24 - INFO - __main__ - 2: torch.Size([16, 4, 96, 96]), torch.Size([32])
11/14/2023 17:28:24 - INFO - __main__ - 3: torch.Size([32]), torch.Size([32])
Traceback (most recent call last):
  File "diffusers/examples/dreambooth/train_dreambooth.py", line 1498, in <module>
    main(args)
  File "diffusers/examples/dreambooth/train_dreambooth.py", line 1370, in main
    loss = loss.mean(dim=list(range(1, len(loss.shape)))) * mse_loss_weights
RuntimeError: The size of tensor a (16) must match the size of tensor b (32) at non-singleton dimension 0
```

### System Info

```
diffusers-cli env
[2023-11-14 19:48:49,554] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.10.0-60.72.0.96.hl202.x86_64-x86_64-with-glibc2.34
- Python version: 3.10.0
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.31.0
- Accelerate version: 0.21.0
- xFormers version: 0.0.22
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
Thanks for reporting! I wonder what does the chunked timesteps would represent here though.

**Comment by sayakpaul** [comment]
Alright this then should have been:

```python
# add to fix BUG in the shape `mse_loss_weights`
timesteps, timesteps_prior = torch.chunk(timesteps, 2, dim=0)
```

in case of a total training batch size of > 1. `timesteps_prior` should accordingly be passed to `compute_snr()` when computing for the prior predictions. @patil-suraj WDYT?

**Comment by sayakpaul** [comment]
@linoytsaban since we were discussing something similar.

**Comment by linoytsaban** [comment]
```

# add to fix BUG in the shape `mse_loss_weights`
timesteps, timesteps_prior = torch.chunk(timesteps, 2, dim=0)

```
right! I think what you suggested here ^ is equivalent to the fix we put in place for the advanced lora script here - [#6356](https://github.com/huggingface/diffusers/pull/6356)

**Comment by sayakpaul** [comment]
Is this still a problem?
