### ISSUE TITLE
conver sd_xl_base_1.0 to ONNXT model prompt error 

### ISSUE THREAD

**Issue by mikeduoxin** [huggingface/diffusers#5875]
### Describe the bug

i want to conver sd_xl_base_1.0 to ONNXT model use conv_sd_to_onnx.py but prompt error :
global_step key not found in model
Traceback (most recent call last):
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\conv_sd_to_onnx.py", line 602, in <module>
    pl = load_pipeline_from_original_stable_diffusion_ckpt(
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1141, in load_pipeline_from_original_stable_diffusion_ckpt
    unet.load_state_dict(converted_unet_checkpoint)
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\lib\site-packages\torch\nn\modules\module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

### Reproduction

global_step key not found in model
Traceback (most recent call last):
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\conv_sd_to_onnx.py", line 602, in <module>
    pl = load_pipeline_from_original_stable_diffusion_ckpt(
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1141, in load_pipeline_from_original_stable_diffusion_ckpt
    unet.load_state_dict(converted_unet_checkpoint)
  File "J:\download\StableDiffusionONNX\Stable-Diffusion-ONNX-FP16ver1.3\lib\site-packages\torch\nn\modules\module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

### System Info

Diffusers version :sd_xl_base_1.0
platform: windows 11
Python version:3.10.6
use AMD 6800 VIDEO CARD

**Comment by echarlaix** [comment]
@mikeduoxin you can find more examples for export and inference in the [documentation](https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/models), and feel free to open an issue in [optimum](https://github.com/huggingface/optimum) directly in case you're facing any issue.

Also might make sense to start adding deprecation warnings in diffusers @patrickvonplaten wdyt ?
