### ISSUE TITLE
Error RuntimeError: Invalid buffer size 

### ISSUE THREAD

**Issue by misteral** [huggingface/diffusers#5894]
### Describe the bug

I got the error `RuntimeError: Invalid buffer size: 11.25 GB` while create simple gif with `AnimateDiffPipeline`, code is bellow. 

Please  help me. I use Mac M1 Pro, 16GB

### Reproduction

```
import torch
from diffusers import MotionAdapter, AnimateDiffPipeline, EulerAncestralDiscreteScheduler
from diffusers.utils import export_to_gif

# Load the motion adapter
adapter = MotionAdapter.from_pretrained("guoyww/animatediff-motion-adapter-v1-5-2")
# load SD 1.5 based finetuned model
adapter = adapter.to('mps')
model_id = "DiffCivit/epiCPhotoGasm_X_v2"
pipe = AnimateDiffPipeline.from_pretrained(model_id, motion_adapter=adapter,
                                           variant="fp16",
                                           torch_dtype=torch.float16,
                                           safety_checker=None,
                                           use_safetensors=True,
                                           cache_dir="./models_cache")
scheduler = EulerAncestralDiscreteScheduler.from_pretrained(
    model_id, subfolder="scheduler", clip_sample=False, timestep_spacing="linspace", steps_offset=1
)
pipe.scheduler = scheduler
# Check if CUDA is available and set the appropriate device
# device = "cuda" if torch.cuda.is_available() else "cpu"
# Ensure all parts of the pipeline and related components are using the correct device
pipe = pipe.to('mps')

# This line is removed because DDIMScheduler does not have a 'to' method
# print(f"Pipeline components are using device: {device}")

# enable memory savings
# pipe.unet.enable_forward_chunking(chunk_size=4, dim=4)
pipe.enable_vae_slicing()

pipe.enable_attention_slicing()
# pipe.enable_model_cpu_offload()

prompt = (
        "beautiful young looking woman, "
        "smiling, white teeth, deep blue eyes, dress, (looking at the camera:1.4), "
        "(highest quality), (best shadow), intricate details, interior, blonde hair:1.3, "
        "dark studio, muted colors, jewelry"
    )
negative_prompt = "cartoon, cgi, render, illustration, painting, drawing"

generator = torch.Generator(device="mps").manual_seed(3358854173)

output = pipe(prompt=prompt,
    negative_prompt=negative_prompt,
    width=512,
    height=768,
    num_frames=10,
    guidance_scale=5,
    num_inference_steps=15,
    generator=generator
)
frames = output.frames[0]
export_to_gif(frames, "animation.gif")

```

### Logs

```shell
This is my console report 

The config attributes {'motion_activation_fn': 'geglu', 'motion_attention_bias': False, 'motion_cross_attention_dim': None} were passed to MotionAdapter, but are not expected and will be ignored. Please verify your config.json configuration file.
/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py:1695: FutureWarning: You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.The default model files: {'unet/diffusion_pytorch_model.safetensors', 'vae/diffusion_pytorch_model.safetensors', 'safety_checker/model.safetensors', 'text_encoder/model.safetensors'} will be loaded instead. Make sure to not load from `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error in v0.24.0 as defaulting to non-variantmodeling files is deprecated.
  deprecate("no variant default", "0.24.0", deprecation_message, standard_warn=False)
Keyword arguments {'safety_checker': None} are not expected by AnimateDiffPipeline and will be ignored.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  1.49it/s]
The config attributes {'center_input_sample': False, 'flip_sin_to_cos': True, 'freq_shift': 0, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'only_cross_attention': False, 'dropout': 0.0, 'transformer_layers_per_block': 1, 'encoder_hid_dim': None, 'encoder_hid_dim_type': None, 'attention_head_dim': 8, 'dual_cross_attention': False, 'class_embed_type': None, 'addition_embed_type': None, 'addition_time_embed_dim': None, 'num_class_embeds': None, 'upcast_attention': False, 'resnet_time_scale_shift': 'default', 'resnet_skip_time_act': False, 'resnet_out_scale_factor': 1.0, 'time_embedding_type': 'positional', 'time_embedding_dim': None, 'time_embedding_act_fn': None, 'timestep_post_act': None, 'time_cond_proj_dim': None, 'conv_in_kernel': 3, 'conv_out_kernel': 3, 'projection_class_embeddings_input_dim': None, 'attention_type': 'default', 'class_embeddings_concat': False, 'mid_block_only_cross_attention': None, 'cross_attention_norm': None, 'addition_embed_type_num_heads': 64} were passed to UNetMotionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
  0%|                                                                                                                                                                                       | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/aleksandrbobrov/data/sd/sd-local/anima.py", line 45, in <module>
    output = pipe(prompt=prompt,
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/pipelines/animatediff/pipeline_animatediff.py", line 661, in __call__
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/unet_motion_model.py", line 781, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/unet_3d_blocks.py", line 1083, in forward
    hidden_states = attn(
                    ^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/transformer_2d.py", line 375, in forward
    hidden_states = block(
                    ^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/attention.py", line 258, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/Users/aleksandrbobrov/data/sd/sd-local/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 1231, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Invalid buffer size: 11.25 GB
```
```


### System Info

```
- `diffusers` version: 0.23.1
- Platform: macOS-14.1.1-arm64-arm-64bit
- Python version: 3.11.6
- PyTorch version (GPU?): 2.2.0.dev20231121 (False)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Who can help?

@DN6 @sayakpaul

**Comment by DN6** [comment]
@pcuenca This looks like an OOM error on an M1 right?

**Comment by pcuenca** [comment]
@DN6 Yes, looks like that. Memory consumption in my system was huge (> 80 GB peak). There are operations not supported by the MPS backend (incompatible shapes), it could be the case that they run on CPU and that causes additional overhead (just guessing here).

**Comment by misteral** [comment]
@pcuenca Yes, I run it on my Mac Pro w/o GPU ... it not supported currently?

**Comment by ballenvironment** [comment]
I got the same error think AnimateDiff uses a huge amount of memory and not usable if you only have 16GB. Can the memory usage be brought down?

**Comment by EricBintner** [comment]
Same thing here with an M1 Ultra 128GB running Python 3.10.13:   `RuntimeError: Invalid buffer size: 104.25 GB`

It seems to be something besides memory limit. And and others say it's probably trying to run something for CUDA on the CPU. I'm still hoping someone can get this running on for ARM gpu.

**Comment by adrianrrrrr** [comment]
Same problem here. `RuntimeError: Invalid buffer size: 4.00 GB` in a M3 using MPS in Pytorch for a VERY simple uNET implementation. I would track the error reaching ASM directives but the zero support Apple gives to developers in this matter makes it unpractical. No way my network needs 4GB of VRAM, it is something to do with Pytorch and/or Python structures implementation. I may give a try with C / Swift, in which case I'd upload news.

**Comment by archcra** [comment]
Same problem: 
__call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Invalid buffer size: 56.50 GB

**Comment by artur-nur** [comment]
Same problem here. RuntimeError: Invalid buffer size: 39.58 GB in an M1 Max using MPS in Pytorch for a simple uNET implementation on a dataset of 347 MB.

**Comment by archcra** [comment]
您的邮件已被接收，我将努力找时间处理。

**Comment by Mathijs-Sentigrate** [comment]
Identical problem. RuntimeError: Invalid buffer size: 24.58 GB for a simple CNN implementation. The error seems to be happening very late in the network, on a simple nn.Linear layer:
--> [317] nn.Linear(in_features, out_features)

**Comment by pascal-maker** [comment]
same pronlem here any solution

**Comment by archcra** [comment]
您的邮件已被接收，我将努力找时间处理。

**Comment by DN6** [comment]
I'm guessing the problem is MPS related with FP16 dtype. Currently don't have bandwidth to dig deeper. cc'ing: @bghira incase they have any insights.

**Comment by bghira** [comment]
you might need unet slicing enabled for sd1.5 or 2.x but in general the earlier sd models dont work at all on MPS due to enormous allocations

**Comment by bghira** [comment]
try disabling attention slicing since it is enabled. if it doesnt work try DrawThings which uses Metal insted of Pytorch.

**Comment by karolina-sowinska** [comment]
Same problem here. It fails at the same function (scaled_dot_product_attention) when I set pipe = pipe.to('mps').

Has anyone solved it?

**Comment by adhimmulia** [comment]
Same phenomenon while using M1 chip

**Comment by surak** [comment]
It's still happening on a m4 pro max with 36gb

**Comment by archcra** [comment]
您的邮件已被接收，我将努力找时间处理。

**Comment by bghira** [comment]
as mentioned above it just wont work, ever. MPS doesnt allow the allocations to succeed. use DrawThings or get a CUDA device.

**Comment by surak** [comment]
Then we should remove the text saying that mps is supported, right?

**Comment by bghira** [comment]
Nope.

**Comment by bghira** [comment]
you could open a PR to block the download etc of AnimateDiff on MPS, but there's no precedent for this. @yiyixuxu or @pcuenca maybe you have ideas?

**Comment by asomoza** [comment]
just to have more context, what do usually mac owners do when there's a new model? they expect it to work on macs every time? What about other libraries? for example when they use ComfyUI they expect it to work with everything?

I know people that use ROCm usually don't expect this because of the poor support it has.

I don't have a mac to test this, but taking into account all the models that diffusers supports, this is the only one that doesn't work or there's more?

if this is the only one we can just make a note on top of the model doc page saying that this model doesn't work on MPS, if there's more models that don't work, maybe we can add a tag for the models that DO work.

**Comment by bghira** [comment]
i'm not sure if Cascade works anymore. but for example, Wan Video takes 600 seconds for 1 step on M3 Max 128G. why? because Pytorch doesn't support 3D convolutions in MPS yet.

SD 1.5 and 2.x both do this particular issue. AnimateDiff is an extension of SD 1.5, so, it also falls apart in the same way. I'm not sure which allocation exactly fails, but this is an issue **in pytorch** and a couple other issues have been resolved there; but at a certain point, there is no more chunking and slicing that can be done to reduce the size of the allocation any further.

SDXL, Flux, SD3, LTX Video (surprisingly, very quickly) all work on MPS.

it's not easy to find the ones that do not work, because they are probably making use of invisible CPU fallback mode inside of Pytorch instead of straight-up erroring when it hits something unsupported.

in general, there is a specific page for MPS optimised inference in the Diffusers docs. it's probably there that some mention should be made about NDArray size limits of `2**32` and that any issues like this need to be opened for the team to investigate whether the model should be officially disabled for MPS or whether there's a way to chunk the allocation into smaller pieces. but this is something pytorch should be doing. it is an implementation detail of MPS that leaks.

**Comment by asomoza** [comment]
I think that's a good approach, WDYT @stevhliu? We can just mark the ones that we know for sure that work and are fast, the others that are slow or don't work, probably it should suffice to say that they're not supported or with limited support (for me too slow is the same as not working) but maybe there's some people that are willing to wait hours for a 5 sec video though.

**Comment by bghira** [comment]
right, blocking those slow models keeps people from doing simple end-to-end testing that would otherwise work. for my use case i created a tiny Wan model that I could run to do simple testing of encoding and predicting without hitting that crazy 600 second time, even with the 1.3B model.

that's really, for my use case, all i expect MPS to be capable of. but it's unfair for me to expect others to also treat MPS like it's solely a development platform.

**Comment by bghira** [comment]
- SDXL
- SD3.x
- Flux (especially distilled, or pruned models) and LoRA/Lycoris
- LTX Video
- Sana
- Kwai Kolors
- DeepFloyd

these all work great on MPS now as of pytorch 2.5.1. it's not an exhaustive list, but if we wanted to make a note of models that definitely can be expected to work even for fine-tuning, these are the ones I know of. (DeepFloyd and some others did not work on 2.4.1 or earlier)

**Comment by bghira** [comment]
if we're adding the badge let's mention its meaning on the MPS page, like "you can be sure this model will work (albeit at possibly reduced performance) when this is available on a page. if any working pipelines are missing the badge, blah blah pull request link etc" 😄

**Comment by fzngagan** [comment]
Same issue when trying to run `Wan-AI/Wan2.1-I2V-14B-480P-Diffusers` on my Macbook Air M4 10cpu 10gpu 32 GB ram
`RuntimeError: Invalid buffer size: 76.92 GB`

**Comment by archcra** [comment]
您的邮件已被接收，我将努力找时间处理。

**Comment by the-brute-force** [comment]
I can confirm that with this code sample, I get a similar issue.
```python3
from transformers import AutoModelForCausalLM
import torch

model = AutoModelForCausalLM.from_pretrained("./QwQ-32B/", dtype=torch.bfloat16, device_map="auto")
```
`RuntimeError: Invalid buffer size: 45.95 GiB`
My machine has 64 GB of RAM and shouldn't have an issue with this

**Comment by archcra** [comment]
您的邮件已被接收，我将努力找时间处理。
