### ISSUE TITLE
Error when using torch.compile

### ISSUE THREAD

**Issue by saeedkhanehgir** [huggingface/diffusers#5934]
Hi,

With torch.compel I get  below error. without torch.compile everything is OK.

```
/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_prims/__init__.py:256: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:31.)
  return torch.empty_strided(shape, strides, dtype=dtype, device=device)

  0%|                                                                                                                                                         | 0/22 [00:53<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 670, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 1055, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/__init__.py", line 1390, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 455, in compile_fx
    return aot_autograd(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 48, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2822, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2515, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1715, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1328, in aot_dispatch_base
    compiled_fw = aot_config.fw_compiler(fw_module, flat_args_with_views_handled)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 430, in fw_compiler
    return inner_compile(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 177, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 586, in compile_to_fn
    return self.compile_to_module().call
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 571, in compile_to_module
    code = self.codegen()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 522, in codegen
    self.scheduler.codegen()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 1167, in codegen
    self.get_backend(device).codegen_nodes(node.get_nodes())
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 1495, in codegen_nodes
    return self.codegen_node_schedule(node_schedule, numel, rnumel)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 1551, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 1216, in codegen_kernel
    "signature": dict(enumerate(map(signature_of, signature))),
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 48, in signature_of
    tye = JITFunction._type_of(arg.dtype)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/triton/runtime/jit.py", line 166, in _type_of
    ty = {
KeyError: torch.complex32

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1039, in __call__
    noise_pred = self.unet(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/mnt/saeed.khanehgir/txt2image/menv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised KeyError: torch.complex32

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

I use torch.compile as below

`model.unet = torch.compile(model.unet, mode="reduce-overhead", fullgraph=True)`

my python version is 3.10 and environment is : 

```
Package                  Version
------------------------ ----------
accelerate               0.24.1
arrow                    1.3.0
astroid                  3.0.1
asttokens                2.4.1
beautifulsoup4           4.12.2
black                    23.11.0
boltons                  23.1.1
certifi                  2023.7.22
charset-normalizer       3.3.2
click                    8.1.7
cmake                    3.27.7
comm                     0.2.0
compel                   2.0.2
coverage                 7.3.2
debugpy                  1.8.0
decorator                5.1.1
deep-translator          1.11.4
diffusers                0.23.0
dill                     0.3.7
exceptiongroup           1.1.3
executing                2.0.1
filelock                 3.13.1
fsspec                   2023.10.0
huggingface-hub          0.17.3
idna                     3.4
importlib-metadata       6.8.0
iniconfig                2.0.0
ipykernel                6.26.0
ipython                  8.17.2
isort                    5.12.0
jedi                     0.19.1
Jinja2                   3.1.2
jupyter_client           8.6.0
jupyter_core             5.5.0
lit                      17.0.5
MarkupSafe               2.1.3
matplotlib-inline        0.1.6
mccabe                   0.7.0
mpmath                   1.3.0
mypy-extensions          1.0.0
nest-asyncio             1.5.8
networkx                 3.2.1
numpy                    1.26.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu11        10.9.0.58
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu11       10.2.10.91
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu11     11.7.4.91
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu11         2.14.3
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.52
nvidia-nvtx-cu11         11.7.91
nvidia-nvtx-cu12         12.1.105
packaging                23.2
parso                    0.8.3
pathspec                 0.11.2
pexpect                  4.8.0
pika                     1.3.2
Pillow                   10.1.0
pip                      23.3.1
platformdirs             4.0.0
pluggy                   1.3.0
prettytable              3.9.0
prompt-toolkit           3.0.40
psutil                   5.9.6
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.16.1
pylint                   3.0.2
pyparsing                3.1.1
pytest                   7.4.3
pytest-cov               4.1.0
python-dateutil          2.8.2
PyYAML                   6.0.1
pyzmq                    25.1.1
regex                    2023.10.3
requests                 2.31.0
safetensors              0.4.0
scipy                    1.11.3
setuptools               65.5.0
six                      1.16.0
soupsieve                2.5
stack-data               0.6.3
sympy                    1.12
tabulate                 0.9.0
tokenizers               0.14.1
tomli                    2.0.1
tomlkit                  0.12.3
torch                    2.0.1
torchdynamo              1.13.0
torchsde                 0.2.5
torchvision              0.16.1
tornado                  6.3.3
tqdm                     4.66.1
traitlets                5.13.0
trampoline               0.1.2
transformers             4.35.0
triton                   2.0.0
types-python-dateutil    2.8.19.14
typing_extensions        4.8.0
urllib3                  2.1.0
wcwidth                  0.2.9
wheel                    0.41.3
zipp                     3.17.0
```

my system is RTX8000 and cuda version is 12.1 and cudnn is 8.9.5 .

**Comment by patrickvonplaten** [comment]
Could you please post a fully reproducible code snippet?

**Comment by bgonzalezfractal** [comment]
Sure @patrickvonplaten:
```
# Init
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
MAX_SEED = np.iinfo(np.int32).max
#CACHE_EXAMPLES = torch.cuda.is_available() and os.getenv("CACHE_EXAMPLES", "1") == "1"
MAX_IMAGE_SIZE = "1024"
USE_TORCH_COMPILE = None #"0"
ENABLE_CPU_OFFLOAD = "1"
ENABLE_REFINER = "1"
# Compile model
if torch.cuda.is_available():
    vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
    pipe = StableDiffusionXLPipeline.from_pretrained(
        "segmind/SSD-1B",
        vae=vae,
        torch_dtype=torch.float16,
        use_safetensors=True,
        variant="fp16",
        num_images_per_prompt=4,
    )
    if ENABLE_REFINER:
        refiner = DiffusionPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-refiner-1.0",
            vae=vae,
            torch_dtype=torch.float16,
            use_safetensors=True,
            variant="fp16",
        )

    if ENABLE_CPU_OFFLOAD:
        pipe.enable_model_cpu_offload()
        if ENABLE_REFINER:
            refiner.enable_model_cpu_offload()
    else:
        pipe.to(device)
        if ENABLE_REFINER:
            refiner.to(device)
        print("Loaded on Device!")

    if USE_TORCH_COMPILE:
        pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
        if ENABLE_REFINER:
            refiner.unet = torch.compile(refiner.unet, mode="reduce-overhead", fullgraph=True)
        print("Model Compiled!")

# Generation
image = pipe(
            prompt=prompt,
            negative_prompt=negative_prompt,
            prompt_2=prompt_2,
            negative_prompt_2=negative_prompt_2,
            width=width,
            height=height,
            guidance_scale=guidance_scale_base,
            num_inference_steps=num_inference_steps_base,
            generator=generator,
            output_type="pil",
            num_images_per_prompt=num_images_per_prompt
        ).images[0]
```
The model is failing at the compiling step (no print for "Model Compiled"), as @saeedkhanehgir pointed out, the does not happen if compile is not executed (temporal solution for now).


Watermark:
```
Last updated: 2023-11-27T15:40:33.300962+00:00

Python implementation: CPython
Python version       : 3.8.10
IPython version      : 8.12.3

Compiler    : GCC 9.4.0
OS          : Linux
Release     : 5.15.0-1050-aws
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

```

**Comment by patrickvonplaten** [comment]
cc @sayakpaul could you maybe check here?

**Comment by kaan-aytekin** [comment]
Having a similar problem, I think the error is caused by the use of `enable_model_cpu_offload` with `torch.compile`. 
When I don't use one of them pipeline runs without any errors.

[This issue](https://github.com/huggingface/diffusers/issues/4399#issue-1830002356) also states a similar problem

**Comment by sayakpaul** [comment]
@saeedkhanehgir a reproducible code snippet please.

**Comment by jkyl** [comment]
> This issue goes away with torch nightly: https://gist.github.com/sayakpaul/4da273d2b81a57974385582bc60439fa. I 

Can you please specify the build that you used? The issue persists with `pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime`.

**Comment by standardAI** [comment]
PyTorch 2.2.2 seems OK in [Colab](https://gist.github.com/standardAI/92e886bfdb3d0d42bff5cbe6d2acf6f2).
