### ISSUE TITLE
StableDiffusionControlNetImg2ImgPipeline will crash when image and control_image sizes are inconsistent

### ISSUE THREAD

**Issue by Moskize91** [huggingface/diffusers#5953]
### Describe the bug

you can see error message `"RuntimeError: The size of tensor a (96) must match the size of tensor b (64) at non-singleton"` after run the code as follows.

I think the reason for this is that the `control_image` and `image` sizes are inconsistent. we can see the source code as follows:

https://github.com/huggingface/diffusers/blob/50a749e90990932d49556ee54a333278559722f3/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1056-L1058

https://github.com/huggingface/diffusers/blob/50a749e90990932d49556ee54a333278559722f3/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1061-L1071

https://github.com/huggingface/diffusers/blob/50a749e90990932d49556ee54a333278559722f3/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1076-L1085

we will see that both preprocessing of `image` and prepareing of `control_image` are passed `width` and `height` as parameters.

but if I never pass `width` or `height`(when I call `pipe(...)`), they will match the default size of model. this will cause their size to be inconsistent, and they cannot always generate tensors that can be matched.

### Reproduction

```python
import torch
import numpy as np

from diffusers import StableDiffusionControlNetImg2ImgPipeline, ControlNetModel, UniPCMultistepScheduler
from transformers import pipeline
from diffusers.utils import load_image

def get_depth_map(image, depth_estimator):
    image = depth_estimator(image)["depth"]
    image = np.array(image)
    image = image[:, :, None]
    image = np.concatenate([image, image, image], axis=2)
    detected_map = torch.from_numpy(image).float() / 255.0
    depth_map = detected_map.permute(2, 0, 1)
    return depth_map

if __name__ == "__main__":
    url = "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/controlnet-img2img.jpg"
    image = load_image(url).resize((768, 768))
    control_image = load_image(url).resize((512, 512))
    depth_estimator = pipeline("depth-estimation")
    depth_map = get_depth_map(control_image, depth_estimator).unsqueeze(0).half().to("cuda")
    controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11f1p_sd15_depth", torch_dtype=torch.float16, use_safetensors=True)
    pipe = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
        "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16, use_safetensors=True
    ).to("cuda")

    pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
    pipe.enable_model_cpu_offload()
    output = pipe(
        "lego batman and robin", image=image, control_image=depth_map,
    ).images[0]
    output.save("./output.png")
```

### Logs

```shell
No model was supplied, defaulted to Intel/dpt-large and revision e93beec (https://huggingface.co/Intel/dpt-large).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of DPTForDepthEstimation were not initialized from the model checkpoint at Intel/dpt-large and are newly initialized: ['neck.fusion_stage.layers.0.residual_layer1.convolution1.weight', 'neck.fusion_stage.layers.0.residual_layer1.convolution1.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.bias', 'neck.fusion_stage.layers.0.residual_layer1.convolution2.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Loading pipeline components...:  14%|██████████████▋                                                                                        | 1/7 [00:00<00:03,  1.55it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.47it/s]
  0%|                                                                                                                                              | 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\oomol\codes\diffusers-plugin\src\test.py", line 30, in <module>
    output = pipe(
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet_img2img.py", line 1090, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\oomol\codes\diffusers-plugin\env\lib\site-packages\diffusers\models\controlnet.py", line 777, in forward
    sample = sample + controlnet_cond
RuntimeError: The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 3
```

### System Info

WIndows 11
CUDA Version: 12.3
Python 3.9.18

**Comment by yiyixuxu** [comment]
ohh sorry actually probably a bug already fixed a while ago .... 
https://github.com/huggingface/diffusers/pull/5665/files

are you using the latest version?

**Comment by Moskize91** [comment]
yes, i'm using the latest version.

```shell
$ pip show diffusers 
Name: diffusers
Version: 0.24.0
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: patrick@huggingface.co
License: Apache
Location: /Users/taozeyu/codes/github.com/oomol/diffusers-plugin/env/lib/python3.9/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by: 
```

you can see this line today.

https://github.com/huggingface/diffusers/blob/1d686bac8146037e97f3fd8c56e4063230f71751/src/diffusers/pipelines/controlnet/pipeline_controlnet_img2img.py#L1091
