### ISSUE TITLE
SVD Pipeline IndexError in scheduling_euler_discrete

### ISSUE THREAD

**Issue by akshetpandey** [huggingface/diffusers#6095]
### Describe the bug

I can consistently reproduce a crash on a asset when generating a video.
The crash happens across a bunch of different random seeds. Asset is attached.

Pipeline is running on an A100 40GB

![drshiba_6](https://github.com/huggingface/diffusers/assets/1213060/a1707082-91cf-4b34-8198-8f64f4af5a93)

### Reproduction

```python
import torch

from diffusers import StableVideoDiffusionPipeline
from diffusers.utils.loading_utils import load_image

image = load_image(filename)
image = image.resize((1024, 576))

pipe = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid-xt",
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)
pipe.to("cuda")

generator = torch.Generator()
seed = generator.seed()

frames = pipe(
    image,
    decode_chunk_size=25,
    generator=generator,
    num_frames=25,
    motion_bucket_id=25,
    noise_aug_strength=0.05,
).frames[0]
```

### Logs

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 126, in _wrap_callback_errors
    callback(message)
  File "/home/root/svd.py", line 164, in process_callback
    for _ in generate_svd_batch(pipe, filename, output_dir):
  File "/home/root/svd.py", line 102, in generate_svd_batch
    frames = pipe(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 513, in __call__
    latents = self.scheduler.step(noise_pred, t, latents).prev_sample
  File "/opt/conda/lib/python3.10/site-packages/diffusers/schedulers/scheduling_euler_discrete.py", line 454, in step
    dt = self.sigmas[self.step_index + 1] - sigma_hat
IndexError: index 26 is out of bounds for dimension 0 with size 26
```

### System Info

```
- `diffusers` version: 0.24.0
- Platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no
```

### Who can help?

@patil-suraj @patrickvonplaten

**Comment by sayakpaul** [comment]
Do you have a sense of which generator seeds tend to lead to this error? We need to be able to reproduce the error.

**Comment by sayakpaul** [comment]
@patil-suraj could you take a look here?

**Comment by akshetpandey** [comment]
@sayakpaul This crashed pretty consistently on random seeds.

**Comment by yiyixuxu** [comment]
can you try with latest diffusers?

**Comment by akshetpandey** [comment]
Yes, will try soon-ish!

**Comment by yurkovak** [comment]
Still getting it with diffusers from a few days ago (after #7447) with various seeds (e.g. 0, 1, 2, 42) 
```
    frames = pipeline(image, decode_chunk_size=4, generator=generator, motion_bucket_id=0, noise_aug_strength=0.05).frames[0]
  File "/home/projects/talide/kateryna/.conda/envs/studio-a40/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/projects/talide/kateryna/diffusers/src/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 537, in __call__
    latents = self.scheduler.step(noise_pred, t, latents).prev_sample
  File "/home/projects/talide/kateryna/diffusers/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 965, in step
    prev_sample = self.multistep_dpm_solver_second_order_update(self.model_outputs, sample=sample, noise=noise)
  File "/home/projects/talide/kateryna/diffusers/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 698, in multistep_dpm_solver_second_order_update
    self.sigmas[self.step_index + 1],
```

**Comment by sayakpaul** [comment]
You're using the same code from [here](https://github.com/huggingface/diffusers/issues/6095#issue-2031342583)?

**Comment by yurkovak** [comment]
Resolved, I was accidentally overriding a scheduler

**Comment by sayakpaul** [comment]
Closing the issue then.
