### ISSUE TITLE
How to use the models from sd_control_collection hf repo in diffusers

### ISSUE THREAD

**Issue by anilsathyan7** [huggingface/diffusers#6113]
How to load/convert the models at https://huggingface.co/lllyasviel/sd_control_collection/tree/main with diffusers?

```
>>> pipe = diffusers.StableDiffusionPipeline.from_single_file("diffusers_xl_canny_full.safetensors")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 261, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1436, in download_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 426, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'
```
Also not able to convert it via hf script: https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_controlnet_to_diffusers.py

How can it be used with diffusers?

**Comment by sayakpaul** [comment]
You are using a wrong class to load the checkpoint. It should be `ControlNetModel`. 

Cc: @DN6

**Comment by anilsathyan7** [comment]
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
model = ControlNetModel.from_pretrained("diffusers_xl_canny_mid.safetensors") # did not work


>>> model = ControlNetModel.from_single_file("diffusers_xl_canny_mid.safetensors")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/git/diffusers/src/diffusers/loaders.py", line 2271, in from_single_file
    controlnet = download_controlnet_from_original_ckpt(
  File "/home/ubuntu/git/diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1678, in download_controlnet_from_original_ckpt
    controlnet = convert_controlnet_checkpoint(
  File "/home/ubuntu/git/diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1095, in convert_controlnet_checkpoint
    converted_ctrl_checkpoint = convert_ldm_unet_checkpoint(
  File "/home/ubuntu/git/diffusers/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 422, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'

**Comment by anilsathyan7** [comment]
Is it not yet supported?

**Comment by anilsathyan7** [comment]
Still getting the same error @sayakpaul 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-2-704636ffa40a>](https://localhost:8080/#) in <cell line: 3>()
      1 from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
      2 
----> 3 controlnet = ControlNetModel.from_single_file('/content/diffusers_xl_canny_full.safetensors')
      4 #model = ControlNetModel.from_pretrained("diffusers_xl_canny_mid.safetensors") # did not work

4 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py](https://localhost:8080/#) in convert_ldm_unet_checkpoint(checkpoint, config, path, extract_ema, controlnet, skip_extract_state_dict)
    424     new_checkpoint = {}
    425 
--> 426     new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
    427     new_checkpoint["time_embedding.linear_1.bias"] = unet_state_dict["time_embed.0.bias"]
    428     new_checkpoint["time_embedding.linear_2.weight"] = unet_state_dict["time_embed.2.weight"]

KeyError: 'time_embed.0.weight'

**Comment by anilsathyan7** [comment]
Same error for 'diffusers_xl_depth_full.safetensors' model...

**Comment by DN6** [comment]
@anilsathyan7 Could you link me to the single file checkpoints on the hub?

**Comment by anilsathyan7** [comment]
All models are in the hf repo only at : https://huggingface.co/lllyasviel/sd_control_collection/tree/main as shared previously. @DN6 (eppol sheriyakkum?😉)

**Comment by yiyixuxu** [comment]
gentle pin @DN6

**Comment by anilsathyan7** [comment]
```
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL

controlnet = ControlNetModel.from_single_file('diffusers_xl_canny_mid.safetensors')
```

Getting the following after installing diffusers from source: pip install git+https://github.com/huggingface/diffusers


```
KeyError                                  Traceback (most recent call last)
[<ipython-input-2-e853ecb37187>](https://localhost:8080/#) in <cell line: 3>()
      1 from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
      2 
----> 3 controlnet = ControlNetModel.from_single_file('diffusers_xl_canny_mid.safetensors')

3 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/loaders/single_file_utils.py](https://localhost:8080/#) in convert_controlnet_checkpoint(checkpoint, config)
    824 
    825     # mid block
--> 826     new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
    827     new_checkpoint["controlnet_mid_block.bias"] = controlnet_state_dict.pop("middle_block_out.0.bias")
    828 

KeyError: 'middle_block_out.0.weight'
```

model url: https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_mid.safetensors?download=true

**Comment by asomoza** [comment]
Just to let you know, that model you're trying to load is not an original controlnet format, they just grabbed the diffusers one, changed the name and put it there, that's why in its name it says `diffusers` and why you can't convert it.

You have two ways of doing this, one is to just use the diffusers one directly which is the same model:

https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-mid

```python
controlnet_model = ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0-mid")
```

Or if you insist on using that specific one, you can put it in its own directory, rename it to `diffusion_pytorch_model.safetensors`, download the [config file](https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0-mid/resolve/main/config.json?download=true) and save it in the same directory with the model. Then load it the same way, for example if you put them in a directory named `canny`:

```python
controlnet_model = ControlNetModel.from_pretrained("canny")
```

**Comment by YoucanBaby** [comment]
> ```
> from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
> 
> controlnet = ControlNetModel.from_single_file('diffusers_xl_canny_mid.safetensors')
> ```
> 
> Getting the following after installing diffusers from source: pip install git+https://github.com/huggingface/diffusers
> 
> ```
> KeyError                                  Traceback (most recent call last)
> [<ipython-input-2-e853ecb37187>](https://localhost:8080/#) in <cell line: 3>()
>       1 from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
>       2 
> ----> 3 controlnet = ControlNetModel.from_single_file('diffusers_xl_canny_mid.safetensors')
> 
> 3 frames
> [/usr/local/lib/python3.10/dist-packages/diffusers/loaders/single_file_utils.py](https://localhost:8080/#) in convert_controlnet_checkpoint(checkpoint, config)
>     824 
>     825     # mid block
> --> 826     new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
>     827     new_checkpoint["controlnet_mid_block.bias"] = controlnet_state_dict.pop("middle_block_out.0.bias")
>     828 
> 
> KeyError: 'middle_block_out.0.weight'
> ```
> 
> model url: https://huggingface.co/lllyasviel/sd_control_collection/resolve/main/diffusers_xl_canny_mid.safetensors?download=true

Same error. How to solve this problem?

**Comment by asomoza** [comment]
as I wrote before, that is a diffusers controlnet model, just load it in the usual way and not as a single file:

```py
controlnet_model = ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0-mid")
```

**Comment by YoucanBaby** [comment]
> as I wrote before, that is a diffusers controlnet model, just load it in the usual way and not as a single file:
> 
> ```python
> controlnet_model = ControlNetModel.from_pretrained("diffusers/controlnet-canny-sdxl-1.0-mid")
> ```

Thanks a lot! It works for me!

**Comment by CallmeZhangChenchen** [comment]
sai_xl_recolor_128lora.safetensors

**Comment by CallmeZhangChenchen** [comment]
以及得到作者恢复 ，不支持

**Comment by asomoza** [comment]
I don't understand the japanese? part but those controlnets are control loras and they're not supported in diffusers.
