### ISSUE TITLE
AttributeError: 'unet2dconditionmodel' object has no attribute 'attn_processors'.

### ISSUE THREAD

**Issue by kamwoh** [huggingface/diffusers#6139]
### Describe the bug

This error happens with a custom attention processor after setting lora layers 

### Reproduction

```
from diffusers import UNet2DConditionModel
from diffusers.models.lora import LoRALinearLayer


class AttnProcessorCustom:
    def __call__(
            self,
            attn,
            hidden_states,
            encoder_hidden_states=None,
            attention_mask=None,
            temb=None,
            scale=1.0,
    ):
        print('nothing')


def setup_attn_processors(unet):
    attn_procs = {}
    for name in unet.attn_processors.keys():
        attn_procs[name] = AttnProcessorCustom()
    unet.set_attn_processor(attn_procs)
    print(unet.attn_processors)   # AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?


unet = UNet2DConditionModel.from_pretrained(
    "stabilityai/sdxl-turbo", subfolder="unet"
)

for attn_processor_name, attn_processor in unet.attn_processors.items():
    # Parse the attention module.
    attn_module = unet
    for n in attn_processor_name.split(".")[:-1]:
        attn_module = getattr(attn_module, n)

    # Set the `lora_layer` attribute of the attention-related matrices.
    attn_module.to_q.set_lora_layer(
        LoRALinearLayer(
            in_features=attn_module.to_q.in_features, out_features=attn_module.to_q.out_features, rank=4
        )
    )
    attn_module.to_k.set_lora_layer(
        LoRALinearLayer(
            in_features=attn_module.to_k.in_features, out_features=attn_module.to_k.out_features, rank=4
        )
    )
    attn_module.to_v.set_lora_layer(
        LoRALinearLayer(
            in_features=attn_module.to_v.in_features, out_features=attn_module.to_v.out_features, rank=4
        )
    )
    attn_module.to_out[0].set_lora_layer(
        LoRALinearLayer(
            in_features=attn_module.to_out[0].in_features,
            out_features=attn_module.to_out[0].out_features,
            rank=4,
        )
    )

setup_attn_processors(unet)

```

### Logs

```shell
/home/kamwoh/anaconda3/envs/pt310/bin/python /home/kamwoh/projects/diffusers/scatch.py 
Traceback (most recent call last):
  File "/home/kamwoh/projects/diffusers/scatch.py", line 60, in <module>
    setup_attn_processors(unet)
  File "/home/kamwoh/projects/diffusers/scatch.py", line 23, in setup_attn_processors
    print(unet.attn_processors)
  File "/home/kamwoh/projects/diffusers/src/diffusers/models/modeling_utils.py", line 222, in __getattr__
    return super().__getattr__(name)
  File "/home/kamwoh/anaconda3/envs/pt310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'. Did you mean: 'set_attn_processor'?
```

### System Info

Python 3.10
torch==2.0.1+cu117
diffusers==0.25.0.dev0  # pulled from main branch & pip install

### Who can help?

@DN6 @yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by kamwoh** [comment]
```

def attn_processors(self):
    r"""
    Returns:
        `dict` of attention processors: A dictionary containing all attention processors used in the model with
        indexed by its weight name.
    """
    # set recursively
    processors = {}

    def fn_recursive_add_processors(name: str, module, processors):
        if hasattr(module, "get_processor"):
            processors[f"{name}.processor"] = module.get_processor(return_deprecated_lora=True)

        for sub_name, child in module.named_children():
            fn_recursive_add_processors(f"{name}.{sub_name}", child, processors)

        return processors

    for name, module in self.named_children():
        fn_recursive_add_processors(name, module, processors)

    return processors
def setup_attn_processors(unet):
    attn_procs = {}
    for name in unet.attn_processors.keys():
        attn_procs[name] = AttnProcessorCustom()
    unet.set_attn_processor(attn_procs)
    # print(unet.attn_processors)
    print(attn_processors(unet))
```

tried trace back what happened inside `.attn_processors`, see the error log below:

```
/home/kamwoh/anaconda3/envs/pt310/bin/python /home/kamwoh/projects/diffusers/scatch.py 
Traceback (most recent call last):
  File "/home/kamwoh/projects/diffusers/scatch.py", line 81, in <module>
    setup_attn_processors(unet)
  File "/home/kamwoh/projects/diffusers/scatch.py", line 45, in setup_attn_processors
    print(attn_processors(unet))
  File "/home/kamwoh/projects/diffusers/scatch.py", line 36, in attn_processors
    fn_recursive_add_processors(name, module, processors)
  File "/home/kamwoh/projects/diffusers/scatch.py", line 31, in fn_recursive_add_processors
    fn_recursive_add_processors(f"{name}.{sub_name}", child, processors)
  File "/home/kamwoh/projects/diffusers/scatch.py", line 31, in fn_recursive_add_processors
    fn_recursive_add_processors(f"{name}.{sub_name}", child, processors)
  File "/home/kamwoh/projects/diffusers/scatch.py", line 31, in fn_recursive_add_processors
    fn_recursive_add_processors(f"{name}.{sub_name}", child, processors)
  [Previous line repeated 3 more times]
  File "/home/kamwoh/projects/diffusers/scatch.py", line 28, in fn_recursive_add_processors
    processors[f"{name}.processor"] = module.get_processor(return_deprecated_lora=True)
  File "/home/kamwoh/projects/diffusers/src/diffusers/models/attention_processor.py", line 449, in get_processor
    lora_processor_cls = getattr(import_module(__name__), "LoRA" + non_lora_processor_cls_name)
AttributeError: module 'diffusers.models.attention_processor' has no attribute 'LoRAAttnProcessorCustom'.
```

seems like the following two lines are having problems when using a custom attention processor?
```
non_lora_processor_cls_name = self.processor.__class__.__name__
lora_processor_cls = getattr(import_module(__name__), "LoRA" + non_lora_processor_cls_name)
```

**Comment by kamwoh** [comment]
Hi, thanks for replying

please see the reproduction of the bug

https://colab.research.google.com/gist/kamwoh/17d3dfc9da039cd51817d222caba2e87/scratchpad.ipynb

**Comment by sayakpaul** [comment]
Well it might be happening because your custom attention processor is basically just printing stuff. 

I suggest you take a look at a custom attention processor:
https://github.com/huggingface/diffusers/blob/c46711e895bcec849fdcce69a7bc6864f023b6d1/src/diffusers/models/attention_processor.py#L1495

and then try to debug your way through.

**Comment by kamwoh** [comment]
my temporary solution is bypassing this bug manually

```
def get_processor(self, return_deprecated_lora: bool = False):
    r"""
    Get the attention processor in use.

    Args:
        return_deprecated_lora (`bool`, *optional*, defaults to `False`):
            Set to `True` to return the deprecated LoRA attention processor.

    Returns:
        "AttentionProcessor": The attention processor in use.
    """
    if not return_deprecated_lora:
        return self.processor

    # TODO(Sayak, Patrick). The rest of the function is needed to ensure backwards compatible
    # serialization format for LoRA Attention Processors. It should be deleted once the integration
    # with PEFT is completed.
    is_lora_activated = {
        name: module.lora_layer is not None
        for name, module in self.named_modules()
        if hasattr(module, "lora_layer")
    }

    # 1. if no layer has a LoRA activated we can return the processor as usual
    if not any(is_lora_activated.values()):
        return self.processor

    # If doesn't apply LoRA do `add_k_proj` or `add_v_proj`
    is_lora_activated.pop("add_k_proj", None)
    is_lora_activated.pop("add_v_proj", None)
    # 2. else it is not posssible that only some layers have LoRA activated
    if not all(is_lora_activated.values()):
        raise ValueError(
            f"Make sure that either all layers or no layers have LoRA activated, but have {is_lora_activated}"
        )

    # 3. And we need to merge the current LoRA layers into the corresponding LoRA attention processor
    # non_lora_processor_cls_name = self.processor.__class__.__name__
    # lora_processor_cls = getattr(import_module(__name__), "LoRA" + non_lora_processor_cls_name)   
    ##### the bug happens when the code tries to use the name of my custom processor to import a LoRA processor,
    ##### as my use case is still using LoRAAttnProcessor but with some custom codes happened inside 
    ##### so I just hard coded the lora_processor_cls and removed all if else use cases in the original code

    hidden_size = self.inner_dim

    # now create a LoRA attention processor from the LoRA layers
    kwargs = {
        "cross_attention_dim": self.cross_attention_dim,
        "rank": self.to_q.lora_layer.rank,
        "network_alpha": self.to_q.lora_layer.network_alpha,
        "q_rank": self.to_q.lora_layer.rank,
        "q_hidden_size": self.to_q.lora_layer.out_features,
        "k_rank": self.to_k.lora_layer.rank,
        "k_hidden_size": self.to_k.lora_layer.out_features,
        "v_rank": self.to_v.lora_layer.rank,
        "v_hidden_size": self.to_v.lora_layer.out_features,
        "out_rank": self.to_out[0].lora_layer.rank,
        "out_hidden_size": self.to_out[0].lora_layer.out_features,
    }

    if hasattr(self.processor, "attention_op"):
        kwargs["attention_op"] = self.processor.attention_op

    lora_processor = LoRAAttnProcessor(hidden_size, **kwargs)
    lora_processor.to_q_lora.load_state_dict(self.to_q.lora_layer.state_dict())
    lora_processor.to_k_lora.load_state_dict(self.to_k.lora_layer.state_dict())
    lora_processor.to_v_lora.load_state_dict(self.to_v.lora_layer.state_dict())
    lora_processor.to_out_lora.load_state_dict(self.to_out[0].lora_layer.state_dict())

    return lora_processor


def get_attn_processors(self):
    r"""
    Returns:
        `dict` of attention processors: A dictionary containing all attention processors used in the model with
        indexed by its weight name.
    """
    # set recursively
    processors = {}

    def fn_recursive_add_processors(name: str, module: torch.nn.Module, processors):
        if hasattr(module, "get_processor"):
            processors[f"{name}.processor"] = get_processor(module, return_deprecated_lora=True)  # using the function i defined above instead of module.get_processor to bypass this error

        for sub_name, child in module.named_children():
            fn_recursive_add_processors(f"{name}.{sub_name}", child, processors)

        return processors

    for name, module in self.named_children():
        fn_recursive_add_processors(name, module, processors)

    return processors
```

instead of:
```
for key in unet.attn_processors.keys():
   ...
```

what i did is
```
for key in get_attn_processors(unet):
  ...
```
