### ISSUE TITLE
Error loading ControlNetXS Depth SDXL 

### ISSUE THREAD

**Issue by aaronsantiago** [huggingface/diffusers#6196]
### Describe the bug

```
Traceback (most recent call last):
  File "/mnt/d/OpenPrograms/daedalus/perf_tests/sdxl_controlnet-depth_test.py", line 18, in <module>
    controlnet = ControlNetXSModel.from_pretrained(
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn    
    return fn(*args, **kwargs)
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 795, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 259, in from_config
    model = cls(**init_dict)
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 649, in inner_init
    init(self, *args, **init_kwargs)
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/diffusers/models/controlnetxs.py", line 307, in __init__
    increase_block_input_in_encoder_resnet(
  File "/mnt/d/OpenPrograms/daedalus/wsl_venv/lib/python3.9/site-packages/diffusers/models/controlnetxs.py", line 824, in increase_block_input_in_encoder_resnet
    assert hasattr(old_conv1, a)
AssertionError
```

### Reproduction

```
import torch
import numpy as np
from PIL import Image

from transformers import DPTFeatureExtractor, DPTForDepthEstimation
from diffusers import ControlNetModel, ControlNetXSModel, StableDiffusionXLControlNetPipeline, AutoencoderKL
from diffusers.utils import load_image


depth_estimator = DPTForDepthEstimation.from_pretrained("Intel/dpt-hybrid-midas").to("cuda")
feature_extractor = DPTFeatureExtractor.from_pretrained("Intel/dpt-hybrid-midas")
# controlnet = ControlNetModel.from_pretrained(
#     "diffusers/controlnet-depth-sdxl-1.0",
#     variant="fp16",
#     use_safetensors=True,
#     torch_dtype=torch.float16,
# ).to("cuda")
controlnet = ControlNetXSModel.from_pretrained(
            "UmerHA/ConrolNetXS-SDXL-depth",
            torch_dtype=torch.float16).to("cuda")
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16).to("cuda")
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16,
).to("cuda")
pipe.enable_model_cpu_offload()

def get_depth_map(image):
    image = feature_extractor(images=image, return_tensors="pt").pixel_values.to("cuda")
    with torch.no_grad(), torch.autocast("cuda"):
        depth_map = depth_estimator(image).predicted_depth

    depth_map = torch.nn.functional.interpolate(
        depth_map.unsqueeze(1),
        size=(1024, 1024),
        mode="bicubic",
        align_corners=False,
    )
    depth_min = torch.amin(depth_map, dim=[1, 2, 3], keepdim=True)
    depth_max = torch.amax(depth_map, dim=[1, 2, 3], keepdim=True)
    depth_map = (depth_map - depth_min) / (depth_max - depth_min)
    image = torch.cat([depth_map] * 3, dim=1)

    image = image.permute(0, 2, 3, 1).cpu().numpy()[0]
    image = Image.fromarray((image * 255.0).clip(0, 255).astype(np.uint8))
    return image


prompt = "stormtrooper lecture, photorealistic"
image = load_image("https://huggingface.co/lllyasviel/sd-controlnet-depth/resolve/main/images/stormtrooper.png")
controlnet_conditioning_scale = 0.5  # recommended for good generalization

depth_image = get_depth_map(image)

images = pipe(
    prompt, image=depth_image, num_inference_steps=30, controlnet_conditioning_scale=controlnet_conditioning_scale,
).images
images[0]

images[0].save(f"sdxl_controlnet-depth.png")
```

### System Info

- `diffusers` version: 0.25.0.dev0
- Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.9.16
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

This is using the most recent commit in main at time of writing: https://github.com/huggingface/diffusers/commit/2d94c7838e273c40920ffd6d24d724357add7f2d

### Who can help?

@patrickvonplaten @sayakpaul

**Comment by sayakpaul** [comment]
Cc: @UmerHA

**Comment by UmerHA** [comment]
Will look into it!

**Comment by vladmandic** [comment]
seems to be fine with latest commit [3e71a206502994d6de0b908e36254df2d09b172c](https://github.com/huggingface/diffusers/commit/32ff4773d4b6662ddbb35c4a75f7178eb2b70cf0)
