### ISSUE TITLE
Allow VAE encode(inp).latent_dist.sample() function to be better supported by torch FX

### ISSUE THREAD

**Issue by aviator19941** [huggingface/diffusers#6239]
### Describe the bug

Torch randn, which is used in the `vae.encode(inp).latent_dist.sample()` function, cannot take symbol shapes as shape argument. However, using randn_like works since it can get the symbolic shape of the tensor. If the sample function could use torch.randn_like instead of torch.rand, it would be able to use make_fx with symbolic tracing.

### Reproduction

```
import numpy as np
import torch
from torch.fx.experimental.proxy_tensor import make_fx
from diffusers import AutoencoderKL

hf_model_name = "CompVis/stable-diffusion-v1-4"

class VaeModel(torch.nn.Module):
    def __init__(self, hf_model_name):
        super().__init__()
        self.vae = AutoencoderKL.from_pretrained(
            hf_model_name,
            subfolder="vae",
        )

    def forward(self, inp):
        latents = self.vae.encode(inp).latent_dist.sample()
        return 0.18215 * latents

vae_model = VaeModel(hf_model_name)

inputs = (torch.randn(1, 3, 512, 512),)

fx_g = make_fx(
    vae_model,
    decomposition_table={},
    tracing_mode="symbolic",
    _allow_non_fake_inputs=True,
    _allow_fake_constant=False,
)(*inputs)

print(fx_g)
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/avinash/nod/SHARK-Turbine/python/turbine_models/custom_models/sd_inference/vae_encode.py", line 31, in <module>
    fx_g = make_fx(
           ^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 468, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 817, in trace
    (self.create_arg(fn(*args)),),
                     ^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 485, in wrapped
    out = f(*tensors)
          ^^^^^^^^^^^
  File "<string>", line 1, in <lambda>
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 795, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 425, in call_module
    return forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/_symbolic_trace.py", line 788, in forward
    return _orig_module_call(mod, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/python/turbine_models/custom_models/sd_inference/vae_encode.py", line 24, in forward
    latents = self.vae.encode(inp).latent_dist.sample()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/diffusers/models/vae.py", line 780, in sample
    sample = randn_tensor(
             ^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/diffusers/utils/torch_utils.py", line 80, in randn_tensor
    latents = torch.randn(shape, generator=generator, device=rand_device, dtype=dtype, layout=layout).to(device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 555, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 580, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/fx/experimental/proxy_tensor.py", line 361, in proxy_call
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_subclasses/fake_tensor.py", line 1487, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_subclasses/fake_tensor.py", line 422, in constructors
    r = func(*args, **new_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avinash/nod/SHARK-Turbine/turbine/lib/python3.11/site-packages/torch/_ops.py", line 448, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: aten/src/ATen/RegisterCompositeExplicitAutograd.cpp:3404: SymIntArrayRef expected to contain only concrete integers
```

### System Info

- `diffusers` version: 0.24.0
- Platform: Linux-6.2.0-1019-gcp-x86_64-with-glibc2.35
- Python version: 3.11.6
- PyTorch version (GPU?): 2.1.0+cu121 (False)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.36.1
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sayakpaul @DN6

**Comment by sayakpaul** [comment]
This is quite specific and I don't think we should change anything here.

**Comment by aviator19941** [comment]
Would it be possible to update the randn_tensor function with some sort of check like https://github.com/aviator19941/diffusers/commit/d3fdb443166bbb053f0c624f24210e430d50747f?

**Comment by aviator19941** [comment]
> This is quite specific and I don't think we should change anything here.

I see, so there's no other solution on the diffusers side that can fix this issue?

**Comment by stellaraccident** [comment]
> This is quite specific and I don't think we should change anything here.

FYI - This is rooted in a known PyTorch bug: https://github.com/pytorch/pytorch/issues/107170. The core maintainers are working towards getting all of this better supported, but we find that most projects these days are considering it a priority to make their codebases work with fx.

If I look at other HF projects, they do consider FX support to be important and accept patches to get things moving while the future catches up. What about a patch [like the above](https://github.com/aviator19941/diffusers/commit/d3fdb443166bbb053f0c624f24210e430d50747f) that explicitly noted that this is being done to unblock better FX support while https://github.com/pytorch/pytorch/issues/107170 is still being fixed?

While full/robust generality in PyTorch is an ultimate goal, I know that locally, when we have a pragmatic approach. If there is something simple we can do today that works and is a toss-up, we take it. Bird in the hand vs two in the bush, etc. Having clear workaround like this can also be helpful to the PyTorch team to roll a fix and undo it.
