### ISSUE TITLE
Prompt not equal, tends to cut in half, i have no negative prompts though.

### ISSUE THREAD

**Issue by Truebob** [huggingface/diffusers#6312]
### Describe the bug

 Basically did a prompt, with 77 words. Uh it doesn't seem to work, since the torch size is cut in half and not equal to positive or negative prompt. Not sure how to fix it, I've read people on github with similar issues but do not know how they solved them or if the compel solution works. I do not know where to put the code or edit it. I am also using open vino so it could just be old. 

### Reproduction

        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).'

### Logs

```shell
venv "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 44006297e03a07f28505d54d6ba5fd55e0c1292d
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
Creating model from config: D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 62.4s (prepare environment: 1.9s, import torch: 27.0s, import gradio: 5.1s, setup paths: 6.0s, initialize shared: 0.7s, other imports: 7.6s, setup codeformer: 1.2s, setup gfpgan: 0.2s, list SD models: 0.2s, load scripts: 7.0s, load upscalers: 0.1s, initialize extra networks: 0.3s, create ui: 3.7s, gradio launch: 2.2s).
Applying attention optimization: InvokeAI... done.
Model loaded in 77.6s (load weights from disk: 5.8s, create model: 0.7s, apply weights to model: 65.8s, apply float(): 2.8s, hijack: 0.1s, load textual inversion embeddings: 0.8s, calculate empty prompt: 1.3s).
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(ldadtwfrkczvhlb)', '(Voyeuristic), (Peeking in the bedroom) of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC24D3B1F0>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).

---
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(6m278bukf1xvut0)', 'Voyeuristic, Peeking in the bedroom of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC26849150>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).

---
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(zltbqx313j0qxar)', 'Voyeuristic, Peeking in the bedroom of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC24D1B670>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).

---
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(5relqpw3y07zd5d)', 'Voyeuristic, Peeking in the bedroom of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'Euler a', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC2685FBE0>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).

---
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(d8ilb65ejoukfhn)', 'Voyeuristic, Peeking in the bedroom of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'Euler a', 1, 1, 7, 776, 768, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC26849D80>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).

---
{}
Loading weights [876b4c7ba5] from D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\models\Stable-diffusion\cetusMix_Whalefall2.safetensors
OpenVINO Script:  created model from config : D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\configs\v1-inference.yaml
In this conversion only the non-EMA weights are extracted. If you want to instead extract the EMA weights (usually better for inference), please make sure to add the `--extract_ema` flag.
*** Error completing request
*** Arguments: ('task(mwi32jzi54nt0l1)', 'Voyeuristic, Peeking in the bedroom of a very sexy goth 20 year old female with enormous boobs changing clothes, she is looking away, lavish lace lingerie, black stockings, black garter belt, hair between eyes, high-cut short hair, side-locks, black eye-shadow, narrow waist, wide hips, misty, foggy, gloomy, overcast, cloudy', '', [], 20, 'Euler a', 1, 1, 7, 768, 768, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FC26E93BB0>, 1, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'gelbooru', True, 100, False, False, True, '', False, 0.75, False, "Don't Change", "Don't Change", True, '', False, 2, 'None', 'None', 0.5, 1, 100, 'Random', 'All', '', 1, -1, 1, False, '', False, False, False, False, '', '', 'None', 'None', 'GPU', True, 'Euler a', True, False, 'None', 0.8, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 1228, in run
        processed = process_images_openvino(p, model_config, vae_ckpt, p.sampler_name, enable_caching, openvino_device, mode, is_xl_ckpt, refiner_ckpt, refiner_frac)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\scripts\openvino_accelerate.py", line 979, in process_images_openvino
        output = shared.sd_diffusers_model(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 754, in __call__
        self.check_inputs(
      File "D:\Stable Diffusion Open Vino Version\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 530, in check_inputs
        raise ValueError(
    ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 768]) != `negative_prompt_embeds` torch.Size([1, 77, 768]).
```

### System Info

don't know how to run the command.

**Comment by sayakpaul** [comment]
Need to see some reproducible code here to understand what you exactly mean.

**Comment by Truebob** [comment]
I am using open vino to accelerate stable diffusion i cannot use any other gpu.

**Comment by sayakpaul** [comment]
OpenVINO is not a part core `diffusers`.
