### ISSUE TITLE
get assert error when following controlnet_xs example

### ISSUE THREAD

**Issue by universewill** [huggingface/diffusers#6371]
I followed the controlnet xs example (https://github.com/UmerHA/diffusers/tree/cnxs-training/examples/controlnet_xs) and get assert error.

```
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
12/28/2023 14:49:42 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

tokenizer/tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████| 737/737 [00:00<00:00, 113kB/s]
tokenizer/vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 57.8MB/s]
tokenizer/merges.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 120MB/s]
tokenizer/special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████| 472/472 [00:00<00:00, 436kB/s]
tokenizer_2/tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████| 725/725 [00:00<00:00, 234kB/s]
tokenizer_2/special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████| 460/460 [00:00<00:00, 352kB/s]
text_encoder/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████| 565/565 [00:00<00:00, 189kB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
text_encoder_2/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 575/575 [00:00<00:00, 674kB/s]
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
scheduler/scheduler_config.json: 100%|███████████████████████████████████████████████████████████████████████████████| 479/479 [00:00<00:00, 120kB/s]
{'clip_sample_range', 'dynamic_thresholding_ratio', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 492M/492M [00:01<00:00, 295MB/s]
model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 2.78G/2.78G [00:08<00:00, 330MB/s]
vae/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 642/642 [00:00<00:00, 102kB/s]
diffusion_pytorch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████| 335M/335M [00:01<00:00, 321MB/s]
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 1.68k/1.68k [00:00<00:00, 1.79MB/s]
diffusion_pytorch_model.safetensors: 100%|███████████████████████████████████████████████████████████████████████| 10.3G/10.3G [00:32<00:00, 316MB/s]
{'reverse_transformer_layers_per_block', 'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
12/28/2023 14:50:34 - INFO - __main__ - Initializing controlnet weights from unet, with dimensions & config as in original paper
/root/miniconda3/lib/python3.8/site-packages/datasets/load.py:1429: FutureWarning: The repository for fusing/fill50k contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/fusing/fill50k
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Downloading builder script: 100%|███████████████████████████████████████████████████████████████████████████████| 2.88k/2.88k [00:00<00:00, 7.61MB/s]
HF google storage unreachable. Downloading and preparing it from source
12/28/2023 14:50:50 - WARNING - datasets.builder - HF google storage unreachable. Downloading and preparing it from source
Downloading data: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7.00M/7.00M [00:00<00:00, 71.9MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 109M/109M [00:01<00:00, 69.4MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 123M/123M [00:01<00:00, 74.2MB/s]
Generating train split: 50000 examples [00:15, 3134.62 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 50000/50000 [03:27<00:00, 241.15 examples/s]
12/28/2023 14:55:04 - INFO - __main__ - ***** Running training *****
12/28/2023 14:55:04 - INFO - __main__ -   Num examples = 50000
12/28/2023 14:55:04 - INFO - __main__ -   Num batches each epoch = 50000
12/28/2023 14:55:04 - INFO - __main__ -   Num Epochs = 2
12/28/2023 14:55:04 - INFO - __main__ -   Instantaneous batch size per device = 1
12/28/2023 14:55:04 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
12/28/2023 14:55:04 - INFO - __main__ -   Gradient Accumulation steps = 4
12/28/2023 14:55:04 - INFO - __main__ -   Total optimization steps = 15000
Steps:   1%|▌                                                                             | 100/15000 [03:58<9:51:15,  2.38s/it, loss=0.122, lr=1e-5]12/28/2023 14:59:02 - INFO - __main__ - Running validation...
model_index.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<00:00, 135kB/s]
diffusion_pytorch_model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████| 335M/335M [00:01<00:00, 246MB/s]
Fetching 15 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.36it/s]
{'controlnet', 'feature_extractor', 'image_encoder'} was not found in config. Values will be initialized to default values.5 [00:03<00:00,  4.36it/s]
                                                                                                                                                    Loaded tokenizer as CLIPTokenizer from `tokenizer` subfolder of stabilityai/stable-diffusion-xl-base-1.0.                       | 0/7 [00:00<?, ?it/s]
Loaded text_encoder as CLIPTextModel from `text_encoder` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
                                                                                                                                                    Loaded text_encoder_2 as CLIPTextModelWithProjection from `text_encoder_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.:00<00:01,  2.75it/s]
                                                                                                                                                    {'timestep_type', 'sigma_min', 'rescale_betas_zero_snr', 'sigma_max'} was not found in config. Values will be initialized to default values. 1.28it/s]
Loaded scheduler as EulerDiscreteScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loaded tokenizer_2 as CLIPTokenizer from `tokenizer_2` subfolder of stabilityai/stable-diffusion-xl-base-1.0.
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.23it/s]
{'solver_order', 'solver_type', 'solver_p', 'disable_corrector', 'thresholding', 'lower_order_final', 'predict_x0', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "train_controlnetxs_sdxl.py", line 1245, in <module>
    main(args)
  File "train_controlnetxs_sdxl.py", line 1209, in main
    image_logs = log_validation(
  File "train_controlnetxs_sdxl.py", line 116, in log_validation
    image = pipeline(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/turing/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 1115, in __call__
    self.check_inputs(
  File "/root/autodl-tmp/turing/diffusers/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 651, in check_inputs
    assert False
AssertionError
Steps:   1%|▌                                                                            | 100/15000 [04:05<10:09:39,  2.45s/it, loss=0.122, lr=1e-5]
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', 'train_controlnetxs_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--output_dir=.', '--init_original', '--dataset_name=fusing/fill50k', '--mixed_precision=fp16', '--resolution=512', '--learning_rate=1e-5', '--max_train_steps=15000', '--validation_image', './conditioning_image_1.png', './conditioning_image_2.png', '--validation_prompt', 'red circle with blue background', 'cyan circle with brown floral background', '--validation_steps=100', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--seed=42']' returned non-zero exit status 1.
```

**Comment by universewill** [comment]
@UmerHA  Can you help here?

**Comment by sayakpaul** [comment]
This comes from a different repository altogether and should not reside here. Hence, I am closing it.
