### ISSUE TITLE
Abnormally high VRAM required when using StableVideoDiffusionPipeline

### ISSUE THREAD

**Issue by feiyangsuo** [huggingface/diffusers#6385]
### Describe the bug

Accordingto the doc https://huggingface.co/docs/diffusers/v0.24.0/en/using-diffusers/svd#low-memory it says applying all the low-memory tricks shall make the VRAM needed no more than 8-GB. Yet I still met CUDA OOM problem with an abnormal VRAM requirement of about 40 GB. I have the code almost totally copied from the doc, so I cannot figure out what's wrong.

The strange thing is that whether do I apply those low-memory tricks or not, the 40 GB VRAM requirement amount never change, seems they have not a bit effect at all.

Also at first there's a strange warning saying "Could not find cuda drivers on your machine, GPU will not be used". But `pipe.to("cuda")` works fine and `torch.cuda.is_available()` returns True.

### Reproduction

my code:
```
import torch

from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video

pipe = StableVideoDiffusionPipeline.from_pretrained(
    "/mnt/aigc/sd_weights/modelscope/hub/AI-ModelScope/stable-video-diffusion-img2vid-xt",
    torch_dtype=torch.float16, variant="fp16"
)
pipe.enable_model_cpu_offload()
pipe.unet.enable_forward_chunking()

# Load the conditioning image
image = load_image("./test_data/rocket.png")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
frames = pipe(image, decode_chunk_size=1, generator=generator).frames[0]

export_to_video(frames, "generated.mp4", fps=7)
```

### Logs

```shell
error info:

2023-12-29 15:56:37.408528: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-29 15:56:37.456843: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-29 15:56:37.456898: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-29 15:56:37.458745: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-29 15:56:37.467283: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-29 15:56:37.467535: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-29 15:56:42.427277: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.93it/s]
  0%|                                                                                                              | 0/25 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/workspace/lcm/test4_img2video.py", line 20, in <module>
    frames = pipe(image, decode_chunk_size=1, generator=generator).frames[0]
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 499, in __call__
    noise_pred = self.unet(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/unet_spatio_temporal_condition.py", line 434, in forward
    sample, res_samples = downsample_block(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/unet_3d_blocks.py", line 2173, in forward
    hidden_states = attn(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/transformer_temporal.py", line 351, in forward
    hidden_states = block(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/attention.py", line 288, in forward
    attn_output = self.attn1(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 743, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/mnt/workspace/conda_venvs/torch/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 590, in get_attention_scores
    baddbmm_input = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 39.55 GiB (GPU 0; 31.75 GiB total capacity; 5.01 GiB already allocated; 25.05 GiB free; 5.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
```


### System Info

- `diffusers` version: 0.24.0
- Platform: Linux-4.19.91-009.ali4000.alios7.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.36.0
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

_No response_

**Comment by sayakpaul** [comment]
Can you try this PyTorch 2.x? Is it possible to try this on a free-tier Colab Notebook?

Cc: @DN6 here.

**Comment by feiyangsuo** [comment]
> Can you try this PyTorch 2.x? Is it possible to try this on a free-tier Colab Notebook?
> 
> Cc: @DN6 here.

sry for late reply. pytorch 2.x works fine. it's astonishing such a big efficiency gap between 1.x and 2.x

**Comment by patrickvonplaten** [comment]
PyTorch 2.0 makes use of SDPA: https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html - a more memory efficient attention function.
