### ISSUE TITLE
ValueError: --caption_column' value 'text' needs to be one of: image, label

### ISSUE THREAD

**Issue by loboere** [huggingface/diffusers#6445]
I am trying to train lora sdxl in kaggle but it gives me this error  ValueError: --caption_column' value 'text' needs to be one of: image, label

```
!python /kaggle/working/train_text_to_image_lora_sdxl.py  \
--pretrained_model_name_or_path "stabilityai/stable-diffusion-xl-base-1.0" \
--train_data_dir data/ \
--resolution 1024 \
--train_batch_size 1 \
--num_train_epochs 50 \
--gradient_accumulation 4 \
--checkpointing_steps 50 \
--mixed_precision "fp16" \
--resume_from_checkpoint "latest" \
--caption_column 'text'
​
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'variance_type', 'dynamic_thresholding_ratio', 'rescale_betas_zero_snr', 'thresholding', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'reverse_transformer_layers_per_block', 'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
Downloading and preparing dataset image_folder/default to /root/.cache/huggingface/datasets/image_folder/default-b9560c2d865259dc/0.0.0/ee92df8e96c6907f3c851a987be3fd03d4b93b247e727b69a8e23ac94392a091...
Downloading data files: 100%|██████████████████| 4/4 [00:00<00:00, 20020.54it/s]
Downloading data files: 100%|███████████████████| 1/1 [00:00<00:00, 7928.74it/s]
Extracting data files: 100%|████████████████████| 1/1 [00:00<00:00, 1337.90it/s]
Dataset image_folder downloaded and prepared to /root/.cache/huggingface/datasets/image_folder/default-b9560c2d865259dc/0.0.0/ee92df8e96c6907f3c851a987be3fd03d4b93b247e727b69a8e23ac94392a091. Subsequent calls will reuse this data.
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 676.06it/s]
['image', 'label']
Traceback (most recent call last):
  File "/kaggle/working/train_text_to_image_lora_sdxl.py", line 1265, in <module>
    main(args)
  File "/kaggle/working/train_text_to_image_lora_sdxl.py", line 799, in main
    raise ValueError(
ValueError: --caption_column' value 'text' needs to be one of: image, label
```

i use this script
https://raw.githubusercontent.com/huggingface/diffusers/main/examples/text_to_image/train_text_to_image_lora_sdxl.py

 
![image](https://github.com/huggingface/diffusers/assets/15265895/2f5c486d-9ac3-4902-b891-52dd6ca4e4fe)

metadata.jsonl
{"file_name": "image/1.jpg", "text": "toy"}
{"file_name": "image/2.jpg", "text": "toyb"}

**Comment by maliozer** [comment]
your dataset has columns named as "image", "label"
it does not read the the metadata you provided

**Comment by XiangjiBU** [comment]
I meet the same problem when train controlnet ( example/controlnet ). I spent a lot time on the dataset form, still can't find how to range dataset. it's too hard to use!

**Comment by 27182812** [comment]
pip install datasets==2.4.0
