### ISSUE TITLE
Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl_img2img because of the following error (look up to see its traceback):

### ISSUE THREAD

**Issue by nihilisticneuralnet** [huggingface/diffusers#6517]
### Describe the bug

Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl_img2img because of the following error (look up to see its traceback):

### Reproduction

from diffusers import AutoPipelineForText2Image

### Logs

```shell
'Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl_img2img.py", line 52, in <module>
    from ..stable_diffusion_xl.watermark import StableDiffusionXLWatermarker
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/watermark.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
  File "/usr/local/lib/python3.10/site-packages/imwatermark/__init__.py", line 1, in <module>
    from .watermark import WatermarkEncoder, WatermarkDecoder
  File "/usr/local/lib/python3.10/site-packages/imwatermark/watermark.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 21, in <module>
    from .controlnet import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl_img2img because of the following error (look up to see its traceback):
libGL.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/cog/server/http.py", line 361, in <module>
    app = create_app(
  File "/usr/local/lib/python3.10/site-packages/cog/server/http.py", line 72, in create_app
    predictor = load_predictor_from_ref(predictor_ref)
  File "/usr/local/lib/python3.10/site-packages/cog/predictor.py", line 172, in load_predictor_from_ref
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/predict.py", line 6, in <module>
    from diffusers import AutoPipelineForText2Image
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.auto_pipeline because of the following error (look up to see its traceback):
Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl_img2img because of the following error (look up to see its traceback):
libGL.so.1: cannot open shared object file: No such file or directory'
```

### System Info

- `diffusers` version: 0.25.0
- Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.12
- PyTorch version (GPU?): 2.1.0+cu121 (False)
- Huggingface_hub version: 0.20.1
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo
