### ISSUE TITLE
Unable to convert DreamShaper v8 Inpaint model → Diffusers

### ISSUE THREAD

**Issue by nosferatu500** [huggingface/diffusers#6584]
### Describe the bug

Hi! I'm trying to convert dream shaper v8 inpaint model ([link](https://civitai.com/models/4384?modelVersionId=131004)) from SafeTensors to Diffusers using next script:

`python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path dreamshaper_8Inpainting.safetensors --from_safetensors --device cpu --extract_ema --dump_path dreamshaper_8Inpainting_diffusers`

but the next error appears:
`ValueError: Trying to set a tensor of shape torch.Size([320, 9, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.`

Is the any special config for inpaint model conversion?

### Reproduction

python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path dreamshaper_8Inpainting.safetensors --from_safetensors --device cpu --extract_ema --dump_path dreamshaper_8Inpainting_diffusers

### Logs

```shell
Traceback (most recent call last):
  File "convert_script.py", line 188, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/Users/user_name/miniforge3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1442, in download_from_original_stable_diffusion_ckpt
    set_module_tensor_to_device(unet, param_name, "cpu", value=param)
  File "/Users/user_name/miniforge3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 285, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([320, 9, 3, 3]) in "weight" (which has shape torch.Size([320, 4, 3, 3])), this look incorrect.
```

### System Info

macOS 14.2.1 (m2 pro), diffusers 0.23 (from python_coreml_stable_diffusion=1.1.0)

**Comment by nosferatu500** [comment]
I just successfully converted it by passing `--num_in_channels 9`
