### ISSUE TITLE
Request: Let StableDiffusionXLImg2ImgPipeline use: load_lora_weights

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#6593]
### Describe the bug

I don't know if this is a bug or a feature request, but I tried to load a LoRA into StableDiffusionXLImg2ImgPipeline, but it doesn't seem to work?

### Reproduction

```
import torch
from diffusers import StableDiffusionXLImg2ImgPipeline
from diffusers.utils import load_image

from diffusers import StableDiffusionXLImg2ImgPipeline, AutoencoderKL
from diffusers import LCMScheduler

vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16,
)
pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    vae=vae,
    torch_dtype=torch.float16,
    variant="fp16",
)

pipe.scheduler = LCMScheduler.from_config(pipe.scheduler.config)
pipe.load_lora_weights("latent-consistency/lcm-lora-sdxl")

pipe = pipe.to("cuda")
url = "https://huggingface.co/datasets/patrickvonplaten/images/resolve/main/aa_xl/000000009.png"

init_image = load_image(url).convert("RGB")
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt, image=init_image).images[0]
```

### Logs

```shell
Error: Python: Traceback (most recent call last):
  File "C:\Users\XXXX\Documents\lora_bug.blend\Text.002", line 20, in <module>
  File "C:\Users\XXXX\Documents\blender-4.1.0-alpha\blender-4.1.0\4.1\python\Lib\site-packages\diffusers\loaders\lora.py", line 1450, in load_lora_weights
    self.load_lora_into_unet(
  File "C:\Users\XXXX\Documents\blender-4.1.0-alpha\blender-4.1.0\4.1\python\Lib\site-packages\diffusers\loaders\lora.py", line 461, in load_lora_into_unet
    incompatible_keys = set_peft_model_state_dict(unet, state_dict, adapter_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\Documents\blender-4.1.0-alpha\blender-4.1.0\4.1\python\Lib\site-packages\peft\utils\save_and_load.py", line 201, in set_peft_model_state_dict
    load_result = model.load_state_dict(peft_model_state_dict, strict=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for down_blocks.0.resnets.0.conv1.lora_A.default_0.weight: copying a param with shape torch.Size([64, 320, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 384, 3, 3]).
        size mismatch for down_blocks.0.resnets.0.conv1.lora_B.default_0.weight: copying a param with shape torch.Size([320, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([384, 64, 1, 1]).
        size mismatch for down_blocks.0.resnets.0.time_emb_proj.lora_A.default_0.weight: copying a param with shape torch.Size([64, 1280]) from checkpoint, the shape in current model is torch.Size([64, 1536]).
```

### System Info

Windows 11
Diffusers 0.25.0

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

**Comment by tin2tin** [comment]
Ok, sorry. This is in the feature request category, then. 

If it was possible to load LoRAs on top of SDXLimg2imgpipe, then it would be possible to make faces "act", keeping character consistency, using the slider LoRAs Ex. https://civitai.com/models/227077?modelVersionId=256155

The reason for img2img is locking the Seed will only keep the character consistency for small LoRA value changes. 

Ex. of acting LoRAs: 
![GD4JJQlWAAAiNxV](https://github.com/huggingface/diffusers/assets/1322593/ab00bb2e-10ca-4fe8-b35e-9409d6836847)
![GD4JT7vXwAAIryc](https://github.com/huggingface/diffusers/assets/1322593/5ab2c3fc-0b6e-47df-b175-044e9cbe9e6d)

**Comment by tin2tin** [comment]
@sayakpaul Is it now possible to use LoRAs in img2img processing? If not could you reopen this and tag is as a feature request(as mentioned above)?

**Comment by yiyixuxu** [comment]
Hi @tin2tin 
I don't think it is a feature we can support - as @sayakpaul points out, it is just not possible to load a lora trained on base unet into the refiner checkpoint,

you can load lora with img2img processing if you use the base unet with it
