### ISSUE TITLE
Unable to convert SSD-1B.safetensors → Diffusers

### ISSUE THREAD

**Issue by nosferatu500** [huggingface/diffusers#6689]
### Describe the bug

Hi! I'm trying to convert SSD-1B model ([link](https://huggingface.co/segmind/SSD-1B/tree/main)) from SafeTensors to Diffusers 

### Reproduction

`python convert_original_stable_diffusion_to_diffusers.py --checkpoint_path ./models/ssd_1b.safetensors --from_safetensors --device cpu --extract_ema --dump_path ./converted/ssd_1b_diffusers --pipeline_class_name StableDiffusionXLPipeline`

### Logs

```shell
Traceback (most recent call last):
  File "convert_original_stable_diffusion_to_diffusers.py", line 191, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "/Users/user/miniforge3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1445, in download_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "/Users/user/miniforge3/envs/coreml_stable_diffusion/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 515, in convert_ldm_unet_checkpoint
    attentions = middle_blocks[1]
KeyError: 1
```
```


### System Info

diffusers==0.25.1

python 3.8

macOS 14.3 (M2 Pro)

**Comment by sayakpaul** [comment]
The model already comes in the `diffusers` format. So, not sure if this is still relevant.
