### ISSUE TITLE
 CUDA out of memory when training SDXL Lora

### ISSUE THREAD

**Issue by noskill** [huggingface/diffusers#6697]
### Describe the bug

SDXL Lora can't be trained on 24 GB gpu

### Reproduction

for reproduction

```
export MODEL_NAME=/home/imgen/models/SDXL/juggernautXL_v8Rundiffusion/
export OUTPUT_DIR=`pwd`/poke11-lora
export DATASET_NAME="lambdalabs/pokemon-blip-captions"

python3 -m pdb examples/text_to_image/train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
            --dataset_name=$DATASET_NAME \
              --dataloader_num_workers=8 \
                --resolution=512 \
                  --center_crop \
                    --random_flip \
                      --train_batch_size=1 \
                        --gradient_accumulation_steps=4 \
                          --max_train_steps=15000 \
                            --learning_rate=1e-04 \
                              --max_grad_norm=1 \
                                --lr_scheduler="cosine" \
                                  --lr_warmup_steps=0 \
                                    --output_dir=${OUTPUT_DIR} \
                                    --mixed_precision=fp16 \
                                    --gradient_checkpointing \
                                    --enable_xformers_memory_efficient_attention \
                                    --use_8bit_adam \
                                            --checkpointing_steps=500 \
                                              --validation_prompt="A poke11 with red nose." \
                                                --seed=1337
```

### Logs

I added debug logs to monitor the memory consumption
```shell

@@ -894,9 +912,12 @@ def main(args):
             new_fingerprint=new_fingerprint_for_vae,
         )
 
+    logging.warning('gpu utilisation before vae and encoders deleted %s', str(print_gpu_utilization(0)))
+    del compute_vae_encodings_fn, compute_embeddings_fn, text_encoder_one, text_encoder_two
     del text_encoders, tokenizers, vae
     gc.collect()
     torch.cuda.empty_cache()
+    logging.warning('gpu utilisation after vae and encoders deleted %s', str(print_gpu_utilization(0)))
 
     def collate_fn(examples):
         model_input = torch.stack([torch.tensor(example["model_input"]) for example in examples])
@@ -912,7 +933,6 @@ def main(args):
```

some more changes:
```
@@ -1057,6 +1077,7 @@ def main(args):
                 prompt_embeds = batch["prompt_embeds"].to(accelerator.device)
                 pooled_prompt_embeds = batch["pooled_prompt_embeds"].to(accelerator.device)
                 unet_added_conditions.update({"text_embeds": pooled_prompt_embeds})
+                logger.warning('gpu utilisation before model_pred %s', str(print_gpu_utilization(0)))
                 model_pred = unet(
                     noisy_model_input,
                     timesteps,
@@ -1065,6 +1086,7 @@ def main(args):
                     return_dict=False,
                 )[0]
 
+                logger.warning('gpu utilisation after model_pred %s', str(print_gpu_utilization(0)))
                 # Get the target for loss depending on the prediction type
                 if args.prediction_type is not None:
                     # set prediction_type of scheduler if defined
@@ -1104,14 +1126,20 @@ def main(args):
                 avg_loss = accelerator.gather(loss.repeat(args.train_batch_size)).mean()
                 train_loss += avg_loss.item() / args.gradient_accumulation_steps
 
+                logger.warning('gpu utilisation before loss.backward %s', str(print_gpu_utilization(0)))
                 # Backpropagate
                 accelerator.backward(loss)
+                logger.warning('gpu utilisation after loss.backward %s', str(print_gpu_utilization(0)))
                 if accelerator.sync_gradients:
                     params_to_clip = unet.parameters()
                     accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
                 optimizer.step()
                 lr_scheduler.step()
                 optimizer.zero_grad()
+                unet.zero_grad(set_to_none=True)
+                import time
+                time.sleep(2)
+                logger.warning('gpu utilisation after zero_grad %s', str(print_gpu_utilization(0)))
```

without sleep and  unet.zero_grad(set_to_none=True) the out of memory error is thrown on the first iteration. With these changes it does 3 iterations.

```
/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/huggingface_hub/utils/_runtime.py:184: UserWarning: Pydantic is installed
 but cannot be imported. Please check your installation. `huggingface_hub` will default to not using Pydantic. Error message: '{e}'
  warnings.warn(                                                                                                              
2024-01-24 10:55:40.849515: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attemptin
g to register factory for plugin cuDNN when one has already been registered                        
2024-01-24 10:55:40.849551: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting
 to register factory for plugin cuFFT when one has already been registered                                     
2024-01-24 10:55:40.850397: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempt
ing to register factory for plugin cuBLAS when one has already been registered                                 
2024-01-24 10:55:41.518549: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT   
01/24/2024 10:55:43 - INFO - __main__ - Distributed environment: NO                                             
Num processes: 1                                                                                                              
Process index: 0                                                                                                              
Local process index: 0                                                                                                
Device: cuda                                                                                       
                                                       
Mixed precision type: fp16                                                                         
                                                       
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models a
nd can yield errors.                             
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models a
nd can yield errors.                                                                                                  
{'thresholding', 'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range'} was not found in config. Values will be initialize
d to default values.           
01/24/2024 10:55:47 - WARNING - root - gpu utilisation before vae and encoders created 319                                     
01/24/2024 10:55:49 - WARNING - root - gpu utilisation after vae and encoders created 3271
01/24/2024 10:55:52 - WARNING - root - gpu utilisation before vae and encoders deleted 3271
01/24/2024 10:55:52 - WARNING - root - gpu utilisation after vae and encoders deleted 1251
01/24/2024 10:55:54 - INFO - __main__ - ***** Running training *****
01/24/2024 10:55:54 - INFO - __main__ -   Num examples = 833
01/24/2024 10:55:54 - INFO - __main__ -   Num Epochs = 72
01/24/2024 10:55:54 - INFO - __main__ -   Instantaneous batch size per device = 1
01/24/2024 10:55:54 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4                         
01/24/2024 10:55:54 - INFO - __main__ -   Gradient Accumulation steps = 4
01/24/2024 10:55:54 - INFO - __main__ -   Total optimization steps = 15000
Steps:   0%|                                                                                                 | 0/15000 [00:00<?, ?it/s]
01/24/2024 10:55:55 - WARNING - __main__ - gpu utilisation before model_pred 11333                                                     
/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Applied workaround for CuDNN i
ssue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)                                         
  return F.conv2d(input, weight, bias, self.stride,
01/24/2024 10:55:57 - WARNING - __main__ - gpu utilisation after model_pred 17387
01/24/2024 10:55:57 - WARNING - __main__ - gpu utilisation before loss.backward 17387
01/24/2024 10:55:57 - WARNING - __main__ - gpu utilisation after loss.backward 22559
01/24/2024 10:56:00 - WARNING - __main__ - gpu utilisation after zero_grad 12077
Steps:   0%|                                                                     | 0/15000 [00:05<?, ?it/s, lr=0.0001, step_loss=0.141]
01/24/2024 10:56:00 - WARNING - __main__ - gpu utilisation before model_pred 12077                                                     
01/24/2024 10:56:00 - WARNING - __main__ - gpu utilisation after model_pred 17465
01/24/2024 10:56:00 - WARNING - __main__ - gpu utilisation before loss.backward 17465
01/24/2024 10:56:00 - WARNING - __main__ - gpu utilisation after loss.backward 22575
01/24/2024 10:56:03 - WARNING - __main__ - gpu utilisation after zero_grad 12079
Steps:   0%|                                                                    | 0/15000 [00:08<?, ?it/s, lr=0.0001, step_loss=0.0175]
01/24/2024 10:56:03 - WARNING - __main__ - gpu utilisation before model_pred 12079                                                     
01/24/2024 10:56:03 - WARNING - __main__ - gpu utilisation after model_pred 17465
01/24/2024 10:56:03 - WARNING - __main__ - gpu utilisation before loss.backward 17465
01/24/2024 10:56:04 - WARNING - __main__ - gpu utilisation after loss.backward 22575
01/24/2024 10:56:06 - WARNING - __main__ - gpu utilisation after zero_grad 12075
Steps:   0%|                                                                    | 0/15000 [00:11<?, ?it/s, lr=0.0001, step_loss=0.0323]
01/24/2024 10:56:06 - WARNING - __main__ - gpu utilisation before model_pred 12075                                                     
01/24/2024 10:56:06 - WARNING - __main__ - gpu utilisation after model_pred 17465
01/24/2024 10:56:06 - WARNING - __main__ - gpu utilisation before loss.backward 17465
01/24/2024 10:56:07 - WARNING - __main__ - gpu utilisation after loss.backward 22575
Traceback (most recent call last):                                                                                             [7/1989]
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/pdb.py", line 1723, in main                                                    
    pdb._runscript(mainpyfile)                                                                                                         
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/pdb.py", line 1583, in _runscript                                              
    self.run(statement)                                                                                                                
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/bdb.py", line 598, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/imgen/projects/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1319, in <module>                     
    main(args)
  File "/home/imgen/projects/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1136, in main                         
    optimizer.step()
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/accelerate/optimizer.py", line 133, in step                      
    self.scaler.step(self.optimizer, closure)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 416, in step                
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 315, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper                
    return wrapped(*args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/optim/optimizer.py", line 373, in wrapper                  
    out = func(*args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 266, in step              
    self.init_state(group, p, gindex, pindex)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 417, in init_state
    state["state2"] = self.get_state_buffer(p, dtype=torch.uint8)
  File "/home/imgen/miniconda3/envs/py31/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 306, in get_state_buffer
    return torch.zeros_like(p, dtype=dtype, device=p.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 20.94 MiB
 is free. Including non-PyTorch memory, this process has 23.67 GiB memory in use. Of the allocated memory 21.65 GiB is allocated by PyT
orch, and 419.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb 
to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF                                           
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

### System Info

diffusers version 0.26.0.dev0
torch version 2.1.2+cu118

### Who can help?

@patrickvonplaten @say

**Comment by noskill** [comment]
also the function i use for memory logging:
```python
def print_gpu_utilization(idx=0):
    from pynvml import *
    nvmlInit()
    handle = nvmlDeviceGetHandleByIndex(idx)
    info = nvmlDeviceGetMemoryInfo(handle)
    print(f"GPU memory occupied: {info.used//1024**2} MB.")
    return info.used//(1024**2
