### ISSUE TITLE
ValueError: Unhandled pipeline class: SDXLLongPromptWeightingPipeline

### ISSUE THREAD

**Issue by calmiLovesAI** [huggingface/diffusers#6731]
### Describe the bug

When running such code:
```python
pipeline = SDXLLongPromptWeightingPipeline.from_single_file(pretrained_model,
                                                                    use_safetensors=True,
                                                                    load_safety_checker=requires_safety_checker).to(
            device)
```
An ERROR occurred: 
```
Traceback (most recent call last):
  File "D:\AI\OpenSource\AIGC\scripts\text2image.py", line 100, in <module>
    main()
  File "D:\AI\OpenSource\AIGC\scripts\text2image.py", line 75, in main
    pipeline = Text2ImagePipeline(prompt=prompt,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\OpenSource\AIGC\src\diffusion\txt2img_pipeline.py", line 84, in __init__
    self.pipeline = build_stable_diffusion_xl_pipeline(model_name, loras,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\OpenSource\AIGC\src\diffusion\stable_diffusion.py", line 107, in build_stable_diffusion_xl_pipeline
    pipeline = SDXLLongPromptWeightingPipeline.from_single_file(pretrained_model,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Lib\site-packages\diffusers\loaders\single_file.py", line 223, in from_single_file
    raise ValueError(f"Unhandled pipeline class: {pipeline_name}")
ValueError: Unhandled pipeline class: SDXLLongPromptWeightingPipeline
```

### Reproduction

```python
pipeline = SDXLLongPromptWeightingPipeline.from_single_file(pretrained_model,
                                                                    use_safetensors=True,
                                                                    load_safety_checker=requires_safety_checker).to(
            device)
```

### System Info

diffusers:                  0.25.1
python:    3.11.2

**Comment by calmiLovesAI** [comment]
One of the solution is to rename the **SDXLLongPromptWeightingPipeline** in `lpw_stable_diffusion_xl.py` to **StableDiffusionXLLongPromptWeightingPipeline**

**Comment by yiyixuxu** [comment]
cc @DN6

**Comment by DN6** [comment]
I think this PR: #7496  should help with the issue

**Comment by sayakpaul** [comment]
Seems like fixed with https://github.com/huggingface/diffusers/pull/7496. Closing hence.
