### ISSUE TITLE
When trying to do inference using StableDiffusionPipeline, I get Transformers error : 'tokenizers.AddedToken' object has no attribute 'special'

### ISSUE THREAD

**Issue by Saumya-Gupta-26** [huggingface/diffusers#6955]
Hi! I get an error when trying to load the pretrained weights for Stable Diffusion (same issue with ControlNet). Below is my code:

```
from diffusers import StableDiffusionPipeline
import os

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe.to("cuda")
```

And I get an error from the Transformers library:

```
Traceback (most recent call last):
  File "/data/saumgupta/diffusion-repositories/diffusers/inference-sd-saum.py", line 27, in <module>
    pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1286, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/transformers/models/clip/tokenization_clip.py", line 343, in __init__
    super().__init__(
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/home/saumgupta/.conda/envs/diffusers/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 489, in _add_tokens
    if not token.special and token.normalized and getattr(self, "do_lower_case", False):
           ^^^^^^^^^^^^^
AttributeError: 'tokenizers.AddedToken' object has no attribute 'special'
```

I would really appreciate any and all help! Thank you!

**Comment by Saumya-Gupta-26** [comment]
Looks like it was an issue with the library version. I created a fresh environment and reinstalled the libraries, and the issue was solved.
