### ISSUE TITLE
Import error HF_HOME

### ISSUE THREAD

**Issue by Will-Zhao0** [huggingface/diffusers#7021]
### Describe the bug

ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants'

### Reproduction

from diffusers import (
    AutoencoderKL,
    DDPMScheduler,
    PNDMScheduler,
    StableDiffusionPipeline,
    UNet2DConditionModel,
)

### Logs

```shell
/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/wz1937/learn/finetune.py", line 18, in <module>
    from diffusers import (
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants'
```

### System Info

Traceback (most recent call last):
  File "/home/wz1937/miniconda3/envs/learn/bin/diffusers-cli", line 7, in <module>
    from diffusers.commands.diffusers_cli import main
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .constants import (
  File "/home/wz1937/miniconda3/envs/learn/lib/python3.9/site-packages/diffusers/utils/constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants'

(which is just the exact same error of this issue)

**Comment by leemomo0617** [comment]
I meet the same trouble.Could you please to tell me how you resolve the problem?

**Comment by Will-Zhao0** [comment]
updated the package I think, nothing special I can remember
