### ISSUE TITLE
sdxl text to image lora fine tuning with train_text_encoder parameter got me an error.

### ISSUE THREAD

**Issue by haandol** [huggingface/diffusers#7056]
### Describe the bug

Hi, I'm trying to fine-tune the SDXL 1.0 model using diffusers 0.26.2 with ` train_text_encoder` parameter. But it got me an error.

However, training without the parameter, it works fine.

I forked 0.26.2 [training file](https://github.com/huggingface/diffusers/blob/v0.26.2/examples/text_to_image/train_text_to_image_lora_sdxl.py) and tweak some code for Sagemaker training job, but I'm pretty sure the entire training code is just same as the original one. Because training job works just fine without the parameter.

Here is my command, running on g5.16xlarge with single GPU instance.
```
Command "/opt/conda/bin/python3.10 -m accelerate.commands.launch --multi_gpu sdxl-lora-sagemaker.py --checkpointing_steps 500 --checkpoints_total_limit 5 --enable_xformers_memory_efficient_attention --gradient_accumulation_steps 4 --gradient_checkpointing --learning_rate 1e-05 --lr_scheduler constant --lr_warmup_steps 0 --max_train_steps 15000 --pretrained_model_name_or_path stabilityai/stable-diffusion-xl-base-1.0 --pretrained_vae_model_name_or_path madebyollin/sdxl-vae-fp16-fix --rank 16 --report_to wandb --resolution 1024 --train_batch_size 1 --train_text_encoder --use_8bit_adam"
```

### Reproduction

run [train_text_to_image_lora_sdxl.py](https://github.com/huggingface/diffusers/blob/v0.26.3/examples/text_to_image/train_text_to_image_lora_sdxl.py) with `train_text_encoder` parameter.

### Logs

```shell
ErrorMessage "RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
 Parameter at index 255 with name text_model.encoder.layers.31.self_attn.out_proj.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
 wandb: - 0.008 MB of 0.008 MB uploaded
 wandb: \ 0.008 MB of 0.034 MB uploaded
 wandb: 🚀 View run sdxl-txt2img-lora-2024-02-22-04-04-59-615-4sn178-algo-1 at: https://wandb.ai/haandol/sdxl-txt2img-lora/runs/sdxl-txt2img-lora-2024-02-22-04-04-59-615-4sn178-algo-1
 wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
 wandb: Find logs at: ./wandb/run-20240222_041347-sdxl-txt2img-lora-2024-02-22-04-04-59-615-4sn178-algo-1/logs
 [2024-02-22 04:14:06,387] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 125) of binary: /opt/conda/bin/python3.10
 Traceback (most recent call last)
 File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 return _run_code(code, main_globals, None,
 File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
 exec(code, run_globals)
 File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 996, in <module>
 main()
 File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 992, in main
 launch_command(args)
 File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
 multi_gpu_launcher(args)
 File "/opt/conda/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
 distrib_run.run(args)
 File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
 elastic_launch(
 File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
 return launch_agent(self._config, self._entrypoint, list(args))
 File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
 raise ChildFailedError(
 torch.distributed.elastic.multiprocessing.errors.ChildFailedError
 ============================================================
 sdxl-lora-sagemaker.py FAILED
 ------------------------------------------------------------
 Failures
 <NO_OTHER_FAILURES>
 Root Cause (first observed failure)
 [0]
 time      : 2024-02-22_04:14:06
 host      : algo-1
 rank      : 0 (local_rank: 0)
 exitcode  : 1 (pid: 125)
 error_file: <N/A>
 traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html"
```

### System Info

python 3.10
torch 2.1.0
cuda 12.1
diffusers 0.26.2

**Comment by haandol** [comment]
maybe I use run the container without accelerate for single GPU.
