### ISSUE TITLE
train_text_to_image_sdxl.py error:CUDA out of memory

### ISSUE THREAD

**Issue by Siannodel** [huggingface/diffusers#7114]
### Describe the bug

I tried to run the following script to train the sdxl_model, but encountered a CUDA out of memory error. After debugging, I found that during training: unet.dtype=torch.float32. I tried adding [unet.to](http://unet.to/)(accelerator.device, dtype=weight_dtype), but encountered another error: Attempting to unscale FP16 gradients.

### Reproduction

`CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --mixed_precision="fp16" /workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --dataset_name=$DATASET_NAME \
  --output_dir=$OUTPUT_DIR \
  --enable_xformers_memory_efficient_attention \
  --resolution=1024 \
  --center_crop \
  --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=4 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --num_train_epochs=20 \
  --use_8bit_adam \
  --learning_rate=1e-06 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --validation_prompt="a cute Sundar Pichai creature" \
  --validation_epochs 1 \
  --checkpointing_steps=5000`

### Logs

```shell
CUDA out of memory:
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1056, in main
    model_pred = unet(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/unet_2d_condition.py", line 1075, in forward
    sample, res_samples = downsample_block(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/unet_2d_blocks.py", line 1150, in forward
    hidden_states = attn(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/transformer_2d.py", line 380, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 251, in checkpoint
    return _checkpoint_without_reentrant(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 432, in _checkpoint_without_reentrant
    output = function(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/transformer_2d.py", line 375, in custom_forward
    return module(*inputs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/attention.py", line 348, in forward
    ff_output = self.ff(norm_hidden_states, scale=lora_scale)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/attention.py", line 544, in forward
    hidden_states = module(hidden_states, scale)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/activations.py", line 100, in forward
    hidden_states, gate = self.proj(hidden_states, *args).chunk(2, dim=-1)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/src/diffusers/models/lora.py", line 430, in forward
    out = super().forward(hidden_states)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 1; 39.59 GiB total capacity; 37.63 GiB already allocated; 20.19 MiB free; 38.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


Attempting to unscale FP16 gradients:
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1281, in <module>
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    main(args)
  File "/workspace/user_code/workplace/ai_draw/controlnet/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1103, in main
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    self.unscale_gradients()
      File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
        self.unscale_gradients()self.unscale_gradients()

  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.unscale_gradients()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    self.unscale_gradients()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
    self.unscale_gradients()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.unscale_gradients()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.unscale_gradients()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    self.scaler.unscale_(opt)
      File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
      File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)    
optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_

  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
    ValueErroroptimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False):         
Attempting to unscale FP16 gradients.self.scaler.unscale_(opt)raise ValueError("Attempting to unscale FP16 gradients.")      File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_



raise ValueError("Attempting to unscale FP16 gradients.")  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
ValueError
: Attempting to unscale FP16 gradients.ValueError
: Attempting to unscale FP16 gradients.
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    self.scaler.unscale_(opt)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)ValueError
:   File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
Attempting to unscale FP16 gradients.
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
```

### System Info
8*A100 40GB
diffusers: 0.25.0 0.26.3 0.24.0 (I tried these three versions and encountered the same error.)
torch: 2.0.0+cu118
accelerate: 0.23.0
transformers: 4.32.1
### Who can help?

@sayakpaul
@DN6 
@yiyixuxu

**Comment by sayakpaul** [comment]
What is your GPU memory? 

Also, we prepare the UNet with `accelerate` and it should be kept in fp32 so that accelerate can handle autocasting with the provided `mixed_precision`.

**Comment by Siannodel** [comment]
> What is your GPU memory?
> 
> Also, we prepare the UNet with `accelerate` and it should be kept in fp32 so that accelerate can handle autocasting with the provided `mixed_precision`.

40GB

**Comment by sayakpaul** [comment]
Does lowering resolution help? So each GPU is 40 GB?

**Comment by Siannodel** [comment]
> Does lowering resolution help? So each GPU is 40 GB?
I tried with resolution=512 and batch_size=1, but I still encountered a CUDA out of memory error. 
Yes, each graphics card has 40GB.

**Comment by sayakpaul** [comment]
Okay will give this a look tomorrow.

**Comment by sayakpaul** [comment]
I attempted training on a 80GB card and it seems to work:

```bash
export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export VAE_NAME="madebyollin/sdxl-vae-fp16-fix"
export DATASET_NAME="lambdalabs/pokemon-blip-captions"

CUDA_VISIBLE_DEVICES=1 accelerate launch train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --dataset_name=$DATASET_NAME \
  --use_8bit_adam \
  --resolution=512 --center_crop --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=10000 \
  --use_8bit_adam \
  --learning_rate=1e-06 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --report_to="wandb" \
  --validation_prompt="a cute Sundar Pichai creature" --validation_epochs 5 \
  --checkpointing_steps=5000 \
  --output_dir="sdxl-pokemon-model" 
```

**Comment by Siannodel** [comment]
> I attempted training on a 80GB card and it seems to work (https://wandb.ai/sayakpaul/text2image-fine-tune-sdxl/runs/mzgfjcad):
> 
> ```shell
> export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
> export VAE_NAME="madebyollin/sdxl-vae-fp16-fix"
> export DATASET_NAME="lambdalabs/pokemon-blip-captions"
> 
> CUDA_VISIBLE_DEVICES=1 accelerate launch train_text_to_image_sdxl.py \
>   --pretrained_model_name_or_path=$MODEL_NAME \
>   --pretrained_vae_model_name_or_path=$VAE_NAME \
>   --dataset_name=$DATASET_NAME \
>   --use_8bit_adam \
>   --resolution=512 --center_crop --random_flip \
>   --proportion_empty_prompts=0.2 \
>   --train_batch_size=1 \
>   --gradient_accumulation_steps=4 --gradient_checkpointing \
>   --max_train_steps=10000 \
>   --use_8bit_adam \
>   --learning_rate=1e-06 --lr_scheduler="constant" --lr_warmup_steps=0 \
>   --mixed_precision="fp16" \
>   --report_to="wandb" \
>   --validation_prompt="a cute Sundar Pichai creature" --validation_epochs 5 \
>   --checkpointing_steps=5000 \
>   --output_dir="sdxl-pokemon-model" 
> ```

resolution=512 and train_batch_size=1 need 80GB card, I don't think this is normal.

**Comment by sayakpaul** [comment]
Works with 1024 as well.

**Comment by sayakpaul** [comment]
Closing the issue due to inactivity. Feel free to reopen.

**Comment by DuShunpeng** [comment]
hi, @Siannodel 
i'm not sure that "35GB when setting --train_batch_size=1 and --resolution=1024." is true or not,
but pls try as below:
1、make sure that --use_8bit_adam --enable_xformers_memory_efficient_attention --set_grads_to_none
2、find "optimizer_class = bnb.optim.AdamW8bit" => "bnb.optim.PagedAdamW8bit " . train_controlnet_sdxl.py or whatever you are using

Good luck!
