### ISSUE TITLE
CUDA OOM Error when fine tuning SDXL using train_text_to_image_sdxl.py

### ISSUE THREAD

**Issue by DarshSamyak** [huggingface/diffusers#7146]
### Describe the bug

Hello, I'm trying to fine tune SDXL using the train_text_to_image_sdxl.py file with the following parameters and I'm getting a CUDA Out of Memory error even before any training begins. I've also tried to train it on a custom dataset of 70 images (with captions) and I'm facing the same error.
I'm fairly new to this and I'm not sure what to do next.
Any help is appreciated :)

### Reproduction

!CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --mixed_precision="fp16"  diffusers/examples/text_to_image/train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="lambdalabs/pokemon-blip-captions" \
  --use_ema \
  --resolution=1024 \
  --train_batch_size=1 \
  --use_8bit_adam \
  --enable_xformers_memory_efficient_attention \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=100 \
  --learning_rate=2e-6 \
  --max_grad_norm=1 \
  --enable_xformers_memory_efficient_attention \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --output_dir="sd-pokemon-model" \
  --num_train_epochs=1

### Logs

```shell
/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/accelerate/accelerator.py:394: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
02/29/2024 09:32:50 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'variance_type', 'dynamic_thresholding_ratio', 'clip_sample_range', 'thresholding', 'rescale_betas_zero_snr'} was not found in config. Values will be initialized to default values.
{'latents_mean', 'latents_std'} was not found in config. Values will be initialized to default values.
/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/diffusers/models/lora.py:300: FutureWarning: `LoRACompatibleConv` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleConv` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleConv", "1.0.0", deprecation_message)
/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/diffusers/models/lora.py:387: FutureWarning: `LoRACompatibleLinear` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleLinear` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleLinear", "1.0.0", deprecation_message)
{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.
{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/home/root_samyak/Desktop/Darsh/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 1305, in <module>
    main(args)
  File "/home/root_samyak/Desktop/Darsh/diffusers/examples/text_to_image/train_text_to_image_sdxl.py", line 955, in main
    ema_unet.to(accelerator.device)
  File "/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/diffusers/training_utils.py", line 350, in to
    self.shadow_params = [
  File "/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/diffusers/training_utils.py", line 351, in <listcomp>
    p.to(device=device, dtype=dtype) if p.is_floating_point() else p.to(device=device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 31.73 GiB of which 10.38 MiB is free. Process 13024 has 11.02 GiB memory in use. Including non-PyTorch memory, this process has 20.65 GiB memory in use. Of the allocated memory 19.87 GiB is allocated by PyTorch, and 453.62 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/root_samyak/Desktop/Darsh/myenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/home/root_samyak/Desktop/Darsh/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/root_samyak/Desktop/Darsh/myenv/bin/python', 'diffusers/examples/text_to_image/train_text_to_image_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--dataset_name=lambdalabs/pokemon-blip-captions', '--use_ema', '--resolution=1024', '--train_batch_size=1', '--use_8bit_adam', '--enable_xformers_memory_efficient_attention', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=100', '--learning_rate=2e-6', '--max_grad_norm=1', '--enable_xformers_memory_efficient_attention', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--mixed_precision=fp16', '--output_dir=sd-pokemon-model', '--num_train_epochs=1']' returned non-zero exit status 1.
```

### System Info

GPU VRAM: 32 GB

`diffusers` version: 0.27.0.dev0
- Platform: Linux-5.15.0-97-generic-x86_64-with-glibc2.35
- Python version: 3.9.18
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Huggingface_hub version: 0.21.1
- Transformers version: 4.38.1
- Accelerate version: 0.27.2
- xFormers version: 0.0.24
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sayakpaul

**Comment by standardAI** [comment]
Hi @DarshSamyak!
Could you please try lowering `--resolution` and/or increasing `gradient_accumulation_steps`?

**Comment by DarshSamyak** [comment]
Hello, I tried with `gradient_accumulation_steps` of 4 and 10 with `resolution ` of 512 and 256 but I'm still facing the same issue, even before any training begins.

Here's the code I ran,

```
!CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --mixed_precision="fp16"  diffusers/examples/text_to_image/train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="lambdalabs/pokemon-blip-captions" \
  --use_ema \
  --resolution=256 \
  --train_batch_size=1 \
  --use_8bit_adam \
  --enable_xformers_memory_efficient_attention \
  --gradient_accumulation_steps=10 \
  --gradient_checkpointing \
  --max_train_steps=100 \
  --learning_rate=2e-6 \
  --max_grad_norm=1 \
  --enable_xformers_memory_efficient_attention \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="fp16" \
  --output_dir="sd-pokemon-model" \
  --num_train_epochs=1
```

Error,

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 31.73 GiB of which 46.00 MiB is free. Including non-PyTorch memory, this process has 31.63 GiB memory in use. Of the allocated memory 29.90 GiB is allocated by PyTorch, and 1.33 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Steps:   0%|                                            | 0/100 [00:01<?, ?it/s]
```

**Comment by sayakpaul** [comment]
I am able to run on an 80GB GPU. The script is not memory-optimized.

**Comment by sayakpaul** [comment]
Maybe but I don't have bandwidth to figure that out now.

**Comment by DarshSamyak** [comment]
Ok no problem thanks for the help!
