### ISSUE TITLE
[LoRA] torch compile is failing even when LoRA is fused.

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#7159]
Code to reproduce:

```python
from diffusers import LCMScheduler, StableDiffusionXLPipeline
import torch

pipeline = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("latent-consistency/lcm-lora-sdxl")
pipeline.fuse_lora()
pipeline.scheduler = LCMScheduler.from_config(pipeline.scheduler.config)

pipeline.unet.to(memory_format=torch.channels_last)
pipeline.unet = torch.compile(pipeline.unet, mode="reduce-overhead", fullgraph=True)

_ = pipeline(
    prompt="a dog",
    num_inference_steps=4,
    guidance_scale=1.0,
)
```

Leads to:

```bash
Traceback (most recent call last):
  File "/home/sayak/diffusers/benchmarks/benchmark_t2i_lcm_lora.py", line 23, in <module>
    benchmark_pipe.benchmark(args)
  File "/home/sayak/diffusers/benchmarks/base_classes.py", line 170, in benchmark
    time = benchmark_fn(self.run_inference, self.pipe, args)  # in seconds.
  File "/home/sayak/diffusers/benchmarks/utils.py", line 58, in benchmark_fn
    return f"{(t0.blocked_autorange().mean):.3f}"
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 372, in blocked_autorange
    number = self._estimate_block_size(min_run_time)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 319, in _estimate_block_size
    time_taken = self._timeit(number)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/benchmark/utils/timer.py", line 264, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/home/sayak/.pyenv/versions/3.10.12/lib/python3.10/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/sayak/diffusers/benchmarks/base_classes.py", line 158, in run_inference
    _ = pipe(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sayak/diffusers/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1167, in __call__
    noise_pred = self.unet(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 248, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2261, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2376, in inline_call_
    tracer.run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 470, in wrapper
    return inner_fn(self, inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1213, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 652, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 294, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 248, in call_function
    return super().call_function(tx, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 81, in call_function
    return tx.inline_user_function_return(
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2261, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2376, in inline_call_
    tracer.run()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1642, in CONTAINS_OP
    self.push(right.call_method(self, "__contains__", [left], {}))
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/variables/base.py", line 330, in call_method
    raise unimplemented(f"call_method {self} {name} {args} {kwargs}")
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/torch/_dynamo/exc.py", line 193, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: call_method ListIteratorVariable() __contains__ [ConstantVariable(str)] {}

from user code:
   File "/home/sayak/diffusers/src/diffusers/models/unets/unet_2d_condition.py", line 1311, in forward
    unscale_lora_layers(self, lora_scale)
  File "/home/sayak/diffusers/src/diffusers/utils/peft_utils.py", line 134, in unscale_lora_layers
    module.unscale_layer(weight)
  File "/home/sayak/.pyenv/versions/diffusers/lib/python3.10/site-packages/peft/tuners/lora/layer.py", line 249, in unscale_layer
    if active_adapter not in self.lora_A.keys():

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

I am on latest `peft` and `torch` (stable versions). 

After `fuse_lora()` has been called the code path shown in the logs should never be hit IIUC. Related thread: https://github.com/huggingface/peft/issues/1199. 

Cc: @younesbelkada @pacman100 @BenjaminBossan

**Comment by sayakpaul** [comment]
I think one way to solve this could be to disable the active adapters since their weights would have already been merged into the base model weights so that the code path never gets hit. But I am not sure about the consequences.

**Comment by sayakpaul** [comment]
Okay can confirm this goes away with:

```python
from diffusers import LCMScheduler, StableDiffusionXLPipeline
import torch

pipeline = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16).to("cuda")
pipeline.load_lora_weights("latent-consistency/lcm-lora-sdxl")
pipeline.fuse_lora()
pipeline.unload_lora_weights()
pipeline.scheduler = LCMScheduler.from_config(pipeline.scheduler.config)

pipeline.unet.to(memory_format=torch.channels_last)
pipeline.unet = torch.compile(pipeline.unet, mode="reduce-overhead", fullgraph=True)

_ = pipeline(
    prompt="a dog",
    num_inference_steps=4,
    guidance_scale=1.0,
)
```

Sorry for the false alarm.

**Comment by okaris** [comment]
@sayakpaul Thanks for sharing this. If unloading after fusing has no effect on generation results wouldn’t it make sense to make this behaviour default?
