### ISSUE TITLE
Advanced training has an issue when saving checkpoints

### ISSUE THREAD

**Issue by landmann** [huggingface/diffusers#7229]
### Describe the bug

I'm running both 

https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py

and 

https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py

and they both have issues around saving the checkpoint -different issues, but issues nonetheless.

### Reproduction

Just train it

### Logs

```shell
For sdxl:


Traceback (most recent call last):
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 2234, in <module>
    main(args)
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 2007, in main
    accelerator.save_state(save_path)
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2767, in save_state
    hook(self._models, weights, output_dir)
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 1420, in save_model_hook
    embedding_handler.save_embeddings(f"{output_dir}/{args.output_dir}_emb.safetensors")
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 787, in save_embeddings
    save_file(tensors, file_path)
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/safetensors/torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

For 1.5:

```
Traceback (most recent call last):
  File "/home/ubuntu/myenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1023, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/myenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 643, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/myenv/bin/python3', '../scripts/train_lora_sd_15.py', '--pretrained_model_name_or_path=/home/ubuntu/models/sd15/fml', '--dataset_name=/home/ubuntu/nate_pics_768/', '--output_dir=/home/ubuntu/nate_models/lora_fml', "--instance_prompt='a TOK man'", '--gradient_accumulation_steps=1', '--caption_column=prompt', '--train_batch_size=4', '--repeats=1', '--mixed_precision=bf16', '--resolution=768', '--gradient_checkpointing', '--learning_rate=1.0', '--text_encoder_lr=1.0', '--adam_beta2=0.99', '--optimizer=prodigy', '--train_text_encoder_ti', '--train_text_encoder_ti_frac=0.5', '--token_abstraction=TOK', '--snr_gamma=5.0', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--rank=32', '--max_train_steps=2160', '--checkpointing_steps=10', '--seed=0', '--with_prior_preservation', '--prior_generation_precision=bf16', '--sample_batch_size=1', "--class_prompt='a man'", '--class_data_dir=/home/ubuntu/notebooks/man_4321_imgs_768x768px', '--report_to=wandb', '--validation_prompt=a TOK man, professional headshot, hyperdetailed photography, soft light, head and shoulders portrait, cover', '--num_validation_images=3', '--validation_epochs=200']' returned non-zero exit status 1.
```
```


### System Info

linux distro - nothing special.

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
What training commands are you using? 

Cc: @linoytsaban

**Comment by landmann** [comment]
Very simple


```
process = [
    "accelerate", 
    "launch",
    f"{dreambooth_filename}",
    f"--pretrained_model_name_or_path=SG161222/RealVisXL_V4.0",
    f"--dataset_name={img_folder_path}",
    # f"--instance_data_dir={img_folder_path}",
    f"--output_dir={output_dir}",
    f"--instance_prompt='{class_prompt}'",
    f"--gradient_accumulation_steps=1",
    f"--caption_column=prompt",
    "--train_batch_size=4",
    "--repeats=1",
    "--mixed_precision=bf16",
    f"--resolution={IMG_SIZE}",
    "--gradient_checkpointing",
    "--learning_rate=1.0",
    "--text_encoder_lr=1.0",
    "--adam_beta2=0.99",
    f"--optimizer=prodigy",
    "--train_text_encoder_ti",
    "--train_text_encoder_ti_frac=0.5",
    "--token_abstraction=TOK",
    "--snr_gamma=5.0", # Default 0. SNR weighting gamma to be used if rebalancing the loss. Recommended value is 5.0. 
    f"--lr_scheduler=constant",
    f"--lr_warmup_steps=0",
    f"--rank={rank}",
    f"--max_train_steps={TRAINING_STEPS}",
    "--checkpointing_steps=10",
    "--seed=0"
]

process.extend(
    [
        f"--with_prior_preservation",
        f"--prior_generation_precision=bf16",
        f"--sample_batch_size=1",
        f"--class_prompt='a man'",
        # f"--num_class_images=100", # Not necessary - we have too many class_data_dir images so they will be taken straight from there.
        f"--class_data_dir={class_data_dir}",
    ]
)

process.extend(
    [
        f"--report_to=wandb",
        f'--validation_prompt={validation_prompt}',
        f"--num_validation_images=3",
        f"--validation_epochs=200",
    ]
)

try:
    # Run the subprocess and capture stdout and stderr
    print("Running Subprocess...")
    subprocess.run(process)
    print("Finished!")
except subprocess.CalledProcessError as e:
    # Print more detailed error information
    print(f"Command failed with exit status {e.returncode}")
    print(f"Command: {' '.join(e.cmd)}")
    print(f"Stdout: {e.stdout.decode('utf-8')}")
    print(f"Stderr: {e.stderr.decode('utf-8')}")
    traceback.print_exc()
except Exception as e:
    # Catch-all for other exceptions
    print("An unexpected error occurred.")
    traceback.print_exc()
```

**Comment by landmann** [comment]
Ah found the issue in the XL file - I'll make a pr.

Seems like `save_embeddings` only worked if the model was in the current directory. If the model was in another directory it added the path multiple times. Pushing now.

**Comment by landmann** [comment]
Oof I love you guys but I found another bug in the sdxl training script...

```
Traceback (most recent call last):
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 2242, in <module>
    main(args)
  File "/home/ubuntu/notebooks/../scripts/train_lora_sdxl.py", line 2176, in main
    state_dict["clip_l"],
KeyError: 'clip_l'
```

**Comment by linoytsaban** [comment]
Hi! can you share your environment please?

**Comment by landmann** [comment]
simple ec2 instance in ubuntu. Here's my pip packages

```
accelerate==0.27.2
appdirs==1.4.4
asttokens==2.4.1
bitsandbytes==0.43.0
boto3==1.34.59
botocore==1.34.59
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
comm==0.2.1
contourpy==1.2.0
cycler==0.12.1
dadaptation==3.2
debugpy==1.8.1
decorator==5.1.1
diffusers @ git+https://github.com/huggingface/diffusers.git@ec64f371b1ef52b1c2c0c146acea979c48b4a6db
dlib==19.24.2
docker-pycreds==0.4.0
einops==0.7.0
exceptiongroup==1.2.0
executing==2.0.1
face-recognition==1.3.0
face-recognition-models==0.3.0
filelock==3.13.1
fonttools==4.49.0
fsspec==2024.2.0
ftfy==6.1.3
gitdb==4.0.11
GitPython==3.1.42
huggingface-hub==0.21.4
idna==3.6
importlib_metadata==7.0.2
ipykernel==6.29.3
ipython==8.22.2
jedi==0.19.1
Jinja2==3.1.3
jmespath==1.0.1
jupyter_client==8.6.0
jupyter_core==5.7.1
kiwisolver==1.4.5
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
mpmath==1.3.0
nest-asyncio==1.6.0
networkx==3.2.1
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
open-clip-torch==2.24.0
opencv-python==4.9.0.80
packaging==23.2
parso==0.8.3
peft==0.9.0
pexpect==4.9.0
piexif==1.1.3
pillow==10.2.0
platformdirs==4.2.0
prodigyopt==1.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.17.2
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
PyYAML==6.0.1
pyzmq==25.1.2
regex==2023.12.25
requests==2.31.0
s3transfer==0.10.0
safetensors==0.4.2
sentencepiece==0.2.0
sentry-sdk==1.41.0
setproctitle==1.3.3
six==1.16.0
smmap==5.0.1
stack-data==0.6.3
sympy==1.12
timm==0.9.16
tokenizers==0.15.2
torch==2.2.1
torchvision==0.17.1
tornado==6.4
tqdm==4.66.2
traitlets==5.14.1
transformers==4.38.2
triton==2.2.0
typing_extensions==4.10.0
urllib3==2.0.7
wandb==0.16.4
wcwidth==0.2.13
xformers==0.0.24
zipp==3.17.0
```

**Comment by chideraidabor** [comment]
> Ah found the issue in the XL file - I'll make a pr.
> 
> Seems like `save_embeddings` only worked if the model was in the current directory. If the model was in another directory it added the path multiple times. Pushing now.

hi what was the solution to this?
