### ISSUE TITLE
train_controlnet.py broken local data loading

### ISSUE THREAD

**Issue by morrisalp** [huggingface/diffusers#7267]
### Describe the bug

The script `examples/controlnet/train_controlnet.py` is designed to either take a HF dataset with `--dataset_name` (as illustrated [here](https://huggingface.co/blog/train-your-controlnet)) or local data `--train_data_dir`, but the latter case fails out-of-the-box.

### Reproduction

Running script with flags `--train_data_dir`, `--image_column`, `--conditioning_image_column`, `--caption_column` referring to dataset in standard HF format with `metadata.csv` file in the data dir. Fails for two reasons:
1. `metadata.csv` must have column named `file_name` containing the filename of the target image files, but flag must be set to `--image_column=image` and not `--image_column=file_name`, which is an undocumented bug.
2. The script fails to load the images from the conditioning image column and instead treats the strings as PIL Images causing an error. I had to change the current line 702 from:
`conditioning_images = [image.convert("RGB") for image in examples[conditioning_image_column]]`
to:
`conditioning_images = [Image.open(image).convert("RGB") for image in examples[conditioning_image_column]]`
for the script to run.

### System Info

- `diffusers` version: 0.27.0.dev0
- Platform: Linux-5.15.0-82-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Huggingface_hub version: 0.21.3
- Transformers version: 4.38.0.dev0
- Accelerate version: 0.25.0
- xFormers version: 0.0.24
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@sayakpaul @yiyixuxu @DN6

**Comment by sayakpaul** [comment]
Feel free to send over a PR to fix :)

**Comment by crapthings** [comment]
--train_data_dir

doesn't work

how do u make it work?

@morrisalp 

```
DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 2
    })
})
Traceback (most recent call last):
  File "/home/zznet/workspace/diffusers/examples/controlnet/train_controlnet.py", line 1190, in <module>
    main(args)
  File "/home/zznet/workspace/diffusers/examples/controlnet/train_controlnet.py", line 924, in main
    train_dataset = make_train_dataset(args, tokenizer, accelerator)
  File "/home/zznet/workspace/diffusers/examples/controlnet/train_controlnet.py", line 640, in make_train_dataset
    raise ValueError(
ValueError: `--image_column` value 'image' not found in dataset columns. Dataset columns are: text
Traceback (most recent call last):
  File "/home/zznet/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zznet/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/zznet/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/home/zznet/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 703, in simple_launcher
  ```

**Comment by crapthings** [comment]
Use this and modify the path as needed

```
export MODEL_DIR="stable-diffusion-v1-5/stable-diffusion-v1-5"
export DATA_DIR="/home/zznet/workspace/dataset/train.py"
export OUTPUT_DIR="tdq_new_controlnet_20241027"

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --train_data_dir=$DATA_DIR \
 --resolution=512 \
 --learning_rate=1e-5 \
 --train_batch_size=4
```


```
import pandas as pd
from huggingface_hub import hf_hub_url
import datasets
import os

print(111222333)

_VERSION = datasets.Version("0.0.2")

_DESCRIPTION = "TODO"
_HOMEPAGE = "TODO"
_LICENSE = "TODO"
_CITATION = "TODO"

_FEATURES = datasets.Features(
    {
        "image": datasets.Image(),
        "conditioning_image": datasets.Image(),
        "text": datasets.Value("string"),
    },
)

_DEFAULT_CONFIG = datasets.BuilderConfig(name="default", version=_VERSION)


class Fill50k(datasets.GeneratorBasedBuilder):
    BUILDER_CONFIGS = [_DEFAULT_CONFIG]
    DEFAULT_CONFIG_NAME = "default"

    def _info(self):
        return datasets.DatasetInfo(
            description=_DESCRIPTION,
            features=_FEATURES,
            supervised_keys=None,
            homepage=_HOMEPAGE,
            license=_LICENSE,
            citation=_CITATION,
        )

    def _split_generators(self, dl_manager):
        metadata_path = r"/home/zznet/workspace/dataset/metadata.jsonl"
        images_dir = r"/home/zznet/workspace/dataset/images"
        conditioning_images_dir = r"/home/zznet/workspace/dataset/conditioning_images"

        return [
            datasets.SplitGenerator(
                name=datasets.Split.TRAIN,
                # These kwargs will be passed to _generate_examples
                gen_kwargs={
                    "metadata_path": metadata_path,
                    "images_dir": images_dir,
                    "conditioning_images_dir": conditioning_images_dir,
                },
            ),
        ]

    def _generate_examples(self, metadata_path, images_dir, conditioning_images_dir):
        metadata = pd.read_json(metadata_path, lines=True)

        for _, row in metadata.iterrows():
            text = row["text"]

            image_path = row["image"]
            image_path = os.path.join(images_dir, image_path)
            image = open(image_path, "rb").read()

            conditioning_image_path = row["conditioning_image"]
            conditioning_image_path = os.path.join(
                conditioning_images_dir, row["conditioning_image"]
            )
            conditioning_image = open(conditioning_image_path, "rb").read()

            yield row["image"], {
                "text": text,
                "image": {
                    "path": image_path,
                    "bytes": image,
                },
                "conditioning_image": {
                    "path": conditioning_image_path,
                    "bytes": conditioning_image,
                },
            }

```

**Comment by sayakpaul** [comment]
@crapthings thanks for your answer. I am going to close due to lack of activity.
