### ISSUE TITLE
AutoencoderKL will mess up with bfloat16 when running on TPU v4 devices

### ISSUE THREAD

**Issue by PikaCat-OuO** [huggingface/diffusers#7415]
### Describe the bug

AutoencoderKL will mess up with bfloat16 when running on TPU v4 devices.

Another issue I found is that, settings `mixed_precision: 'bf16'` in the yaml file has no effect at all, so that's why the `mixed_precision='bf16'` is still needed in the code when initializing Accelerator

### Reproduction

my_test.py:
```python
import torch
from accelerate import Accelerator
from diffusers import AutoencoderKL

def main():
  acc = Accelerator(mixed_precision='bf16')
  weight_dtype = torch.bfloat16
  vae = AutoencoderKL.from_pretrained("ckpts", subfolder="vae")
  vae.to(acc.device, dtype=weight_dtype)
  vae.encode(torch.ones(1, 3, 256, 256).to(acc.device, dtype=weight_dtype))

if __name__ == '__main__':
  main()
```

config:
```
~/.cache/huggingface/accelerate# cat default_config.yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: TPU
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

run with `accelerate launch my_test.py`

### Logs

```shell
WARNING:root:XRT configuration not detected. Defaulting to preview PJRT runtime. To silence this warning and continue using PJRT, explicitly set PJRT_DEVICE to a supported device or configure XRT. To disable default device selection, set PJRT_SELECT_DEFAULT_DEVICE=0
WARNING:root:For more information about the status of PJRT, see https://github.com/pytorch/xla/blob/master/docs/pjrt.md
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
WARNING:root:Unsupported nprocs (8), ignoring...
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 92, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 245, in _run_thread_per_device
    replica_results = list(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 238, in _thread_fn
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 341, in __call__
    self.fn(global_ordinal(), *self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/launch.py", line 554, in __call__
    self.launcher(*args)
  File "/root/Wonder3D/my_test.py", line 10, in main
    vae.encode(torch.ones(1, 3, 256, 256).to(acc.device, dtype=weight_dtype))
  File "/usr/local/lib/python3.8/dist-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/autoencoder_kl.py", line 242, in encode
    h = self.encoder(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/vae.py", line 139, in forward
    sample = down_block(sample)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_blocks.py", line 1157, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/resnet.py", line 612, in forward
    hidden_states = self.conv1(hidden_states)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/lora.py", line 102, in forward
    return F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 990, in launch_command
    tpu_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 733, in tpu_launcher
    xmp.spawn(PrepareForLaunch(main_function), args=(), nprocs=args.num_processes)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 386, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 365, in spawn
    _run_multiprocess(spawn_fn, start_method=start_method)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 92, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 322, in _run_multiprocess
    replica_results = list(
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/experimental/pjrt.py", line 323, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.13.0-1023-gcp-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- Huggingface_hub version: 0.21.4
- Transformers version: 4.38.2
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?: NO

### Who can help?

@sayakpaul @DN6 @yiyixuxu

**Comment by PikaCat-OuO** [comment]
VAE from `https://huggingface.co/flamehaze1115/wonder3d-v1.0/tree/main/vae`

**Comment by sayakpaul** [comment]
Maybe the bfloat16 precision isn't well suited for the given VAE. In any case, I don't think the is a bug of the library per se and is better off as a [Discussion](https://github.com/huggingface/diffusers/discussions). 

> Another issue I found is that, settings mixed_precision: 'bf16' in the yaml file has no effect at all, so that's why the mixed_precision='bf16' is still needed in the code when initializing Accelerator

It is probably an issue better off in the `accelerate` repository.

**Comment by PikaCat-OuO** [comment]
> Maybe the bfloat16 precision isn't well suited for the given VAE. In any case, I don't think the is a bug of the library per se and is better off as a [Discussion](https://github.com/huggingface/diffusers/discussions).
>
Ok, thanks for your rapid reply, after examining the config.yaml, I found that the config has `force_upcast=true`. But I'm still wondering why it works fine with float16 on GPU.

> > Another issue I found is that, settings mixed_precision: 'bf16' in the yaml file has no effect at all, so that's why the mixed_precision='bf16' is still needed in the code when initializing Accelerator
> 
> It is probably an issue better off in the `accelerate` repository.
Sorry for the wrong place, I will set an issue up in the `accelerate` repository later.

**Comment by PikaCat-OuO** [comment]
Setting `force_upcast=False` in scripts still does not help. Never mind, since it's not regarded as a bug, I'll close it now.

**Comment by sayakpaul** [comment]
> Never mind, since it's not regarded as a bug, I'll close it now.

I am not saying it's not a bug. I am saying it's better off in the `accelerate` repository because the configuration you're referring to belongs to `accelerate`. I hope it makes sense why this is probably not suited for this repository. Let me know if you need further clarification.

**Comment by PikaCat-OuO** [comment]
> I am not saying it's not a bug.

I mean the VAE one only, not the accelerate one.

**Comment by sayakpaul** [comment]
Ah then you're referring to `config.json` and not `config.yaml` ([example](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/vae/config.json)). This is important to note because `diffusers` model configs are always in JSON whereas `accelerate` configs are in YAML. This is why I was confused. 

Some VAEs are known to mess up when exposed to reduced precisions actually. This VAE, for example: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/vae.

**Comment by PikaCat-OuO** [comment]
I identified the issue in:
https://github.com/huggingface/diffusers/blob/3e1097cb63c724f5f063704df5ede8a18f472f29/src/diffusers/models/resnet.py#L332

The hidden_states before this line is with torch.bfloat16, after this line, hidden_states is torch.float32.
@sayakpaul
Any clue?

**Comment by PikaCat-OuO** [comment]
seems `self.nonlinearity` also has this behavior, I explicitly setting the input to bfloat16 but it still outputs float32

**Comment by sayakpaul** [comment]
Does this happen when using float16 too?

**Comment by PikaCat-OuO** [comment]
This does not happen with float16, may be a Pytorch issue.

**Comment by sayakpaul** [comment]
Thanks for providing the information. If you reproduce this with a smaller snippet, I think it might worth opening an issue on the PyTorch repository.
