### ISSUE TITLE
Issue running SDXL Lora dreambooth on Nvidia 3060 12 GB RAM

### ISSUE THREAD

**Issue by sagargulabani** [huggingface/diffusers#7513]
### Describe the bug

I am trying to run train_dreambooth_lora_sdxl on ubuntu WSL.
I have an Nvidia card with 3060.
I have about 19.5 GB of RAM allocated to ubuntu WSL.
I am running into the following error.

```
 Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
```

I get this error when adding these flags

```
  --mixed_precision="fp16" \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --use_8bit_adam \
```

what could be the issue ?

### Reproduction

```
export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="lora-trained-xl"
export VAE_PATH="madebyollin/sdxl-vae-fp16-fix"

 accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --pretrained_vae_model_name_or_path=$VAE_PATH \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --use_8bit_adam \
  --instance_prompt="a photo of sks dog" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="0" \
  --push_to_hub
```

### Logs

```shell
Full stack trace with command. 

export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="lora-trained-xl"
export VAE_PATH="madebyollin/sdxl-vae-fp16-fix"

 accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --pretrained_vae_model_name_or_path=$VAE_PATH \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --enable_xformers_memory_efficient_attention \
  --gradient_checkpointing \
  --use_8bit_adam \
  --instance_prompt="a photo of sks dog" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="0" \
  --push_to_hub
03/29/2024 11:19:14 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'clip_sample_range', 'thresholding', 'dynamic_thresholding_ratio', 'variance_type', 'rescale_betas_zero_snr'} was not found in config. Values will be initialized to default values.
{'latents_mean', 'latents_std'} was not found in config. Values will be initialized to default values.
{'attention_type', 'reverse_transformer_layers_per_block', 'dropout'} was not found in config. Values will be initialized to default values.
03/29/2024 11:21:15 - INFO - __main__ - ***** Running training *****
03/29/2024 11:21:15 - INFO - __main__ -   Num examples = 5
03/29/2024 11:21:15 - INFO - __main__ -   Num batches each epoch = 5
03/29/2024 11:21:15 - INFO - __main__ -   Num Epochs = 250
03/29/2024 11:21:15 - INFO - __main__ -   Instantaneous batch size per device = 1
03/29/2024 11:21:15 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
03/29/2024 11:21:15 - INFO - __main__ -   Gradient Accumulation steps = 4
03/29/2024 11:21:15 - INFO - __main__ -   Total optimization steps = 500
Steps:   0%|                                                                                                                                                                                  | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/sagargulabani/dev/huggingface/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1985, in <module>
    main(args)
  File "/home/sagargulabani/dev/huggingface/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1697, in main
    model_pred = unet(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/accelerate/utils/operations.py", line 822, in forward
    return model_forward(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/accelerate/utils/operations.py", line 810, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/unets/unet_2d_condition.py", line 1216, in forward
    sample, res_samples = downsample_block(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/unets/unet_2d_blocks.py", line 1269, in forward
    hidden_states = attn(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/transformers/transformer_2d.py", line 385, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 489, in checkpoint
    ret = function(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/transformers/transformer_2d.py", line 380, in custom_forward
    return module(*inputs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/attention.py", line 366, in forward
    attn_output = self.attn2(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/home/sagargulabani/dev/huggingface/diffusers/src/diffusers/models/attention_processor.py", line 1191, in __call__
    hidden_states = xformers.ops.memory_efficient_attention(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 247, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 370, in _memory_efficient_attention
    return _fMHA.apply(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 61, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 392, in _memory_efficient_attention_forward_requires_grad
    inp.validate_inputs()
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/xformers/ops/fmha/common.py", line 123, in validate_inputs
    raise ValueError(
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
Steps:   0%|                                                                                                                                                                                  | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/sagargulabani/miniconda3/envs/hf/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/home/sagargulabani/miniconda3/envs/hf/lib/python3.10/site-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/sagargulabani/miniconda3/envs/hf/bin/python', 'train_dreambooth_lora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--instance_data_dir=dog', '--pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix', '--output_dir=lora-trained-xl', '--mixed_precision=fp16', '--enable_xformers_memory_efficient_attention', '--gradient_checkpointing', '--use_8bit_adam', '--instance_prompt=a photo of sks dog', '--resolution=1024', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--learning_rate=1e-4', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=500', '--validation_prompt=A photo of sks dog in a bucket', '--validation_epochs=25', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.
```

### System Info

Windows with Ubuntu WSL 2.
Nvidia 3060
20 GB Ram
intel i7  8thGen

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Don't use enable_xformers_memory_efficient_attention. It's a known issue with xformers and PyTorch 2.0.

**Comment by sagargulabani** [comment]
ok
it was part of the docs here. https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/README_sdxl.md

Will remove it and try.

**Comment by sayakpaul** [comment]
Yeah will update the docs. Keep us posted on how it goes. Our Colab [here](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/SDXL_DreamBooth_LoRA_.ipynb) runs on a 16GB GPU (free-tier Colab).

**Comment by sagargulabani** [comment]
Ok, it took very long to run. It took about 2 hours to run. 
is 2 hours reasonable and does it also take others also this much time ?
Any suggestions on how I can make it faster ?

I was able to train and get  the inferences.

**Comment by sayakpaul** [comment]
Since training gets running successfully I am going to close the issue.
