### ISSUE TITLE
AttributeError: module diffusers has no attribute DepthNormalEstimationPipeline

### ISSUE THREAD

**Issue by csyhping** [huggingface/diffusers#7516]
### Describe the bug

Hi, I'm trying to use the [GeoWizzard](https://huggingface.co/lemonaddie/Geowizard) model from the Huggingface Page, I just copied the codes from 'Use in Diffusers' as described on the webpage, but it raised the error `AttributeError: module diffusers has no attribute DepthNormalEstimationPipeline`. 

### Reproduction

I reinstalled my diffusers from source as some of other issues did but it didn't work, I also tried the pip package, it also failed.

### Logs

```shell
Traceback (most recent call last):
  File "/userhome/cs/csyhping/Proj/SceneGeneration/test.py", line 15, in <module>
    pipeline = DiffusionPipeline.from_pretrained("lemonaddie/Geowizard")
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1096, in from_pretrained
    cached_folder = cls.download(
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1768, in download
    pipeline_class = _get_pipeline_class(
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 395, in _get_pipeline_class
    pipeline_cls = getattr(diffusers_module, class_name)
  File "/userhome/cs/csyhping/anaconda3/envs/SceneGen/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 703, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module diffusers has no attribute DepthNormalEstimationPipeline
```

### System Info

Diffusers: tried `0.25.0` / `latest pip package` / `from source`
Python: `3.10.13`

### Who can help?

@yiyixuxu @DN6

**Comment by sayakpaul** [comment]
I think they are using a custom form of `diffusers`. You might want to open an issue here: https://huggingface.co/lemonaddie/Geowizard/discussions.

**Comment by sayakpaul** [comment]
Someone has already: https://huggingface.co/lemonaddie/Geowizard/discussions/2.
