### ISSUE TITLE
KeyError: 'middle_block_out.0.weight'

### ISSUE THREAD

**Issue by nick8592** [huggingface/diffusers#7574]
### Describe the bug

I'm encountering a `KeyError: 'middle_block_out.0.weight'` while attempting to utilize the **ControlNet** for an image colorization task. I have followed most of the guidelines outlined in the  [tutorial](https://huggingface.co/docs/diffusers/training/controlnet?installation=PyTorch&gpu-select=16GB#controlnet) for training the model. However, during testing, the error arises, pointing to the issue with 'middle_block_out.0.weight'. 

I adapted the `train_controlnet.py` script slightly to suit the colorization task and load COCO images. The complete code can be found [here](https://github.com/nick8592/ColorNet.git). Specifically, modifications were only made at line [691](https://github.com/huggingface/diffusers/blob/71f49a5d2a00ccf5417b923b424177bd617e80a9/examples/controlnet/train_controlnet.py#L691)
```
    conditioning_image_transforms = transforms.Compose(
        [
            transforms.Grayscale(num_output_channels=3), # added this line
            transforms.Resize(args.resolution, interpolation=transforms.InterpolationMode.BILINEAR),
            transforms.CenterCrop(args.resolution),
            transforms.ToTensor(),
        ]
    )
```
and line [700](https://github.com/huggingface/diffusers/blob/71f49a5d2a00ccf5417b923b424177bd617e80a9/examples/controlnet/train_controlnet.py#L700), [703](https://github.com/huggingface/diffusers/blob/71f49a5d2a00ccf5417b923b424177bd617e80a9/examples/controlnet/train_controlnet.py#L703).
```
    def preprocess_train(examples):
        images = [Image.open(image).convert("RGB") for image in examples[image_column]] # modified this line
        images = [image_transforms(image) for image in images]

        conditioning_images = [Image.open(image).convert("RGB") for image in examples[conditioning_image_column]] # modified this line
        conditioning_images = [conditioning_image_transforms(image) for image in conditioning_images]
```
Here's the training command:
```
export MODEL_DIR="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="output"

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --dataset_name=phiyodr/coco2017 \
 --image_column="file_name" \
 --conditioning_image_column="file_name" \
 --caption_column="captions" \
 --max_train_samples=1000 \
 --resolution=512 \
 --num_train_epochs=5 \
 --dataloader_num_workers=8 \
 --learning_rate=1e-5 \
 --validation_image "./000000295478.jpg" "./000000122962.jpg" \
 --validation_prompt "Woman walking a small white dog behind her." "A group of children sitting at a long table eating pizza." \
 --train_batch_size=5 \
 --gradient_accumulation_steps=4 \
 --mixed_precision="fp16" \
 --gradient_checkpointing \
 --use_8bit_adam
```
Pre-trained weight can download from [here](https://drive.google.com/drive/folders/1ADLcsjaaA0jLfWzTL6jYxEU6eMAF2cJd?usp=sharing).

### Reproduction

```
# Test for Image Colorization 
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel
from diffusers.utils import load_image
import torch

# own training model
url = "/home/nick/Documents/code/control-color/output/checkpoint-500/controlnet/diffusion_pytorch_model.safetensors"

controlnet = ControlNetModel.from_single_file(url, torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16
).to("cuda")

control_image = load_image("./000000295478.jpg")
prompt = "Woman walking a small white dog behind her."

generator = torch.manual_seed(0)
image = pipe(prompt, num_inference_steps=20, generator=generator, image=control_image).images[0]
image.save("./output.png")
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/nick/Documents/code/control-color/test_controlnet.py", line 8, in <module>
    controlnet = ControlNetModel.from_single_file(url, torch_dtype=torch.float16)
  File "/home/nick/miniconda3/envs/control-color/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/nick/miniconda3/envs/control-color/lib/python3.9/site-packages/diffusers/loaders/controlnet.py", line 124, in from_single_file
    component = create_diffusers_controlnet_model_from_ldm(
  File "/home/nick/miniconda3/envs/control-color/lib/python3.9/site-packages/diffusers/loaders/single_file_utils.py", line 975, in create_diffusers_controlnet_model_from_ldm
    diffusers_format_controlnet_checkpoint = convert_controlnet_checkpoint(checkpoint, diffusers_config)
  File "/home/nick/miniconda3/envs/control-color/lib/python3.9/site-packages/diffusers/loaders/single_file_utils.py", line 939, in convert_controlnet_checkpoint
    new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
KeyError: 'middle_block_out.0.weight'
```

### System Info

- `diffusers` version: 0.28.0.dev0
- Platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.9.19
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.39.3
- Accelerate version: 0.28.0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@sayakpaul @yiyixuxu @DN6

Any insights or guidance on resolving this issue would be greatly appreciated. Thank you!

**Comment by sayakpaul** [comment]
```
controlnet = ControlNetModel.from_single_file(url, torch_dtype=torch.float16)
```

You are not supposed from use `from_single_file` when using the `diffusers` format. 

Just do:

```python
controlnet = ControlNetModel.from_pretrained("path-to-checkpoint")
```
