### ISSUE TITLE
StableDiffusionXL from_single_file get RuntimeError with dimensions smaller

### ISSUE THREAD

**Issue by DeJoker** [huggingface/diffusers#7640]
### Describe the bug

I'm using StableDiffusionXLPipeline From safetensor predict, got RuntimeError
very sure safetensor is OK, use [sd_scripts](https://github.com/kohya-ss/sd-scripts)  with ckpt infer get Expected result

### Reproduction

```python
tokenizer = CLIPTokenizer.from_pretrained(
        "/aigc-nas02/sd_models/stable_diffusion/stable-diffusion-xl-base-1.0/tokenizer",
        local_files_only=True,
    )
tokenizer_2 = CLIPTokenizer.from_pretrained(
    "/aigc-nas02/sd_models/stable_diffusion/stable-diffusion-xl-base-1.0/tokenizer_2/",
    local_files_only=True,
)
text_encoder = CLIPTextModel.from_pretrained(
    "/aigc-nas02/sd_models/stable_diffusion/stable-diffusion-xl-base-1.0/text_encoder",
    # variant="fp16", torch_dtype=torch.float16,
    local_files_only=True,
)
text_encoder_2 = CLIPTextModelWithProjection.from_pretrained(
    "/aigc-nas02/sd_models/stable_diffusion/stable-diffusion-xl-base-1.0/text_encoder_2",
    # variant="fp16", torch_dtype=torch.float16,
    local_files_only=True,
)

pipe = StableDiffusionXLPipeline.from_single_file(
        "/aigc-nas02/sd_models/stable_diffusion/sdxl1_0/AnythingXL_xl.safetensors",
        load_safety_checker=False, safety_checker=None, 
        text_encoder=text_encoder,
        text_encoder_2=text_encoder,
        tokenizer=tokenizer,
        tokenizer_2=tokenizer_2,
        local_files_only=True, cache_dir="/aigc-nas02/sd_models/cache/openai/hub",
        use_safetensors=True,
        # torch_dtype=torch.float16, variant="fp16",
    )
pipe.scheduler = DPMSolverSinglestepScheduler.from_config(
    pipe.scheduler.config, use_karras_sigmas="yes"
)
pipe.to("cuda")
img_list = pipe(
      prompt="A cat is playing in the flower field under the moonlight.",
      negative_prompt="((nsfw)), EasyNegative, grayscale, verybadimagenegative_v1.3",
      num_images_per_prompt=4,
      output_type="np",
      num_inference_steps=8,
      height=1024,
      width=1024,
      guidance_scale=0,
  ).images
```

### Logs

```shell
pipe init cost: 126.013s

Traceback (most recent call last):
  File "/aigc-nas02/workspace/code/tmp/ZyMultiRoundTrain/sd_infer/diff_safetensor.py", line 98, in <module>
    img_list = pipe(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1054, in __call__
    ) = self.encode_prompt(
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 475, in encode_prompt
    pooled_prompt_embeds = pooled_prompt_embeds.repeat(1, num_images_per_prompt).view(
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor
```

### System Info

- `diffusers` version: 0.27.2
- Platform: Linux-5.10.134-13.1.al8.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.39.3
- Accelerate version: 0.23.0
- xFormers version: 0.0.25.post1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@yiyixuxu

**Comment by standardAI** [comment]
`text_encoder_2=text_encoder`

**Comment by asomoza** [comment]
Nicely spotted.

Also, there's a discussion about this: https://github.com/huggingface/diffusers/discussions/6836 if you encounter more problems.

**Comment by yiyixuxu** [comment]
can we close this one now?

**Comment by DeJoker** [comment]
thx. my mistake

> `text_encoder_2=text_encoder`

**Comment by omrastogi** [comment]
```
    # Load the tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        pretrained_model_name_or_path,
        subfolder="tokenizer",
        revision=revision,
        use_fast=False,
    )
    tokenizer_two = AutoTokenizer.from_pretrained(
        pretrained_model_name_or_path,
        subfolder="tokenizer_2",
        revision=revision,
        use_fast=False,
    )


    # Load scheduler and models
    noise_scheduler = DDPMScheduler.from_pretrained(pretrained_model_name_or_path, subfolder="scheduler")

    text_encoder_one = CLIPTextModel.from_pretrained(
        pretrained_model_name_or_path, subfolder="text_encoder", revision=revision
    )
    text_encoder_two = CLIPTextModel.from_pretrained(
        pretrained_model_name_or_path, subfolder="text_encoder_2", revision=revision
    )

    vae = AutoencoderKL.from_pretrained(pretrained_model_name_or_path, subfolder="vae", revision=revision)
    unet = UNet2DConditionModel.from_pretrained(
        pretrained_model_name_or_path, subfolder="unet", revision=revision
    )

    config = LoraConfig(
        r=lora_rank,
        lora_alpha=lora_alpha,
        target_modules=["to_k", "to_q", "to_v", "to_out.0"],
        lora_dropout=lora_dropout,
        bias=lora_bias,
    )

    unet = get_peft_model(unet, config)

    config = LoraConfig(
        r=lora_rank,
        lora_alpha=lora_alpha,
        target_modules=["k_proj", "q_proj", "v_proj"],
        lora_dropout=lora_dropout,
        bias=lora_bias,
    )

    # text_encoder_one = get_peft_model(text_encoder_one, config)
    # text_encoder_two = get_peft_model(text_encoder_two, config)


    vae.requires_grad_(False)

    pipeline = StableDiffusionXLPipeline.from_pretrained(
    pretrained_model_name_or_path,
    vae=vae,
    text_encoder=text_encoder_one,
    text_encoder_2=text_encoder_two,
    unet=unet,
    revision=revision,
    )

    results = pipeline (
        batch_prompts,  # Repeat the prompt for each image in the batch
        image=batch_images,
        mask_image=batch_masks,
        num_inference_steps=50,
        height=h,
        width=w,
        guidance_scale=1,
        generator=generator,
    ).images

```

Now I have been cautious with the text_encoders, yet I am getting the same error here:
`/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 475, in encode_prompt
    pooled_prompt_embeds = pooled_prompt_embeds.repeat(1, num_images_per_prompt).view(
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor`

After a inspection in the diffusers code: [diffusers](https://github.com/huggingface/diffusers/tree/main)/[src](https://github.com/huggingface/diffusers/tree/main/src)/[diffusers](https://github.com/huggingface/diffusers/tree/main/src/diffusers)/[pipelines](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines)/[stable_diffusion_xl](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/stable_diffusion_xl)/pipeline_stable_diffusion_xl.py

1. On line number 475, 

```
pooled_prompt_embeds = pooled_prompt_embeds.repeat(1, num_images_per_prompt).view(
            bs_embed * num_images_per_prompt, -1
        )
```
The shape of pooled_prompt_embeds  is [4, 77, 2048] due to which I am getting an error. 

2.  Which we get on line number 368, 
`pooled_prompt_embeds = prompt_embeds[0]
`
where prompt_embeds is a (sorta) list. 

I am not really sure what can be the error here. 
1. Should I add an dimension to 'repeat'
2. Or is there some issue with prompt_embeds itself
3. Or is there some error in m code only

System Info:
diffuser version: 0.27.1
python:3.10.14
pytorch version: 2.2.1

**Comment by standardAI** [comment]
I think you need to use [`StableDiffusionXLInpaintPipeline`](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLInpaintPipeline.__call__.example). It seems that you defined tokenizers but didn't pass them to the pipeline. [Lastly, `text_encoder_two` should be `CLIPTextModelWithProjection`.](https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/stable_diffusion_xl#diffusers.StableDiffusionXLInpaintPipeline.text_encoder_2)
