### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load /home/sh0006yi/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so.

### ISSUE THREAD

**Issue by crystal-kur** [huggingface/diffusers#7641]
### Describe the bug

![d1a3a225abc2e65c071c10277c1920e](https://github.com/huggingface/diffusers/assets/56252135/00933ce6-da4d-4186-82b6-cd289bb55556)
![128128b305234f349ee0f720a424b67](https://github.com/huggingface/diffusers/assets/56252135/ec0974fd-2def-4f6a-8bf3-c40c745848d9)

### Reproduction

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR='/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_inn6_dtdugai_sec0.1_per1_lf1_tvae0.0001_vaerecon0.0001_epoch=0_step=3000/cover'
#"/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_dtdugai_sec0.1_per1_lf1_tclip0.01_vaerecon0.0001_epoch=4_step=44500/stego"
#"/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/1pertur0_inn6_dtdugai_sec0.1_per1_lf1_vaerecon0.0001_epoch=2_step=30000/stego"
#"/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_dtdugai_sec0.1_per1_lf1_tclip0.01_vaerecon0.0001_epoch=3_step=40000/"
#/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_inn6_dtdugai_sec0.1_per1_lf1_tvae0.0001_vaerecon0.0001_epoch=2_step=30000/
#/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_dtdugai_sec0.1_per1_lf1_tvae0.0001_tclip0.01_vaerecon0.0001_epoch=2_step=30000/
export OUTPUT_DIR='/home/sh0006yi/idea/Unlearn_GAI_code/vango_old/van_gogh/pertur0_inn6_dtdugai_sec0.1_per1_lf1_tvae0.0001_vaerecon0.0001_epoch=0_step=3000/train_db_ori'
accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="A painting in the style of sks" \
  --resolution=512 \
  --train_batch_size=5 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --checkpointing_steps=100 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A painting in the style of sks" \
  --validation_epochs=100 \
  --mixed_precision=fp16 \
  --seed="0"
  
  bash train_db.sh

### System Info

(pytorch) sh0006yi@sh0006yi-U3018:~/diffusers-main/examples/dreambooth$ diffusers-cli env
Traceback (most recent call last):
  File "/home/sh0006yi/miniconda3/envs/pytorch/bin/diffusers-cli", line 5, in <module>
    from diffusers.commands.diffusers_cli import main
  File "/home/sh0006yi/miniconda3/envs/pytorch/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/sh0006yi/miniconda3/envs/pytorch/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 91, in <module>
    from .peft_utils import (
  File "/home/sh0006yi/miniconda3/envs/pytorch/lib/python3.9/site-packages/diffusers/utils/peft_utils.py", line 28, in <module>
    import torch
  File "/home/sh0006yi/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### Who can help?

@sayakpaul

**Comment by standardAI** [comment]
Firstly, could you please be sure that you installed PyTorch properly, or upgrade it to newer versions if it is old?

**Comment by crystal-kur** [comment]
> Firstly, could you please be sure that you installed PyTorch properly; or upgrade it to newer versions if it is old and try again?

I use the version 2.0.1+11.8 and could run the relevant code previously, while when I upgated to 2.2.2, the error occurs

**Comment by DN6** [comment]
@crystal-kur The traceback seems to indicate an issue with the torch install. Can you try installing torch 2.2. in a fresh virtualenv and run again? Once you have created this fresh environment can you also run `diffusers-cli env` and share the output

**Comment by sayakpaul** [comment]
Closing this issue because of inactivity. Feel free to reopen.
