### ISSUE TITLE
Trace example does not work

### ISSUE THREAD

**Issue by AbhinavGopal** [huggingface/diffusers#7660]
### Describe the bug

The example of the trace for memory efficiency in the docs errors

### Reproduction
```
import time
import torch
from diffusers import StableDiffusionPipeline
import functools

torch.set_grad_enabled(False)

n_experiments = 2
unet_runs_per_experiment = 50


def generate_inputs():
    sample = torch.randn((2, 4, 64, 64), device="cuda", dtype=torch.float16)
    timestep = torch.rand(1, device="cuda", dtype=torch.float16) * 999
    encoder_hidden_states = torch.randn((2, 77, 768), device="cuda", dtype=torch.float16)
    return sample, timestep, encoder_hidden_states


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")
unet = pipe.unet
unet.eval()
unet.to(memory_format=torch.channels_last)  # use channels_last memory format
unet.forward = functools.partial(unet.forward, return_dict=False)  # set return_dict=False as default

for _ in range(3):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet(*inputs)

print("tracing..")
unet_traced = torch.jit.trace(unet, inputs)
unet_traced.eval()
print("done tracing")


for _ in range(5):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet_traced(*inputs)


with torch.inference_mode():
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet_traced(*inputs)
        torch.cuda.synchronize()
        print(f"unet traced inference took {time.time() - start_time:.2f} seconds")
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet(*inputs)
        torch.cuda.synchronize()
        print(f"unet inference took {time.time() - start_time:.2f} seconds")

unet_traced.save("unet_traced.pt")


from diffusers import StableDiffusionPipeline
import torch
from dataclasses import dataclass


@dataclass
class UNet2DConditionOutput:
    sample: torch.FloatTensor


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")


unet_traced = torch.jit.load("unet_traced.pt")


class TracedUNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.in_channels = pipe.unet.config.in_channels
        self.device = pipe.unet.device

    def forward(self, latent_model_input, t, encoder_hidden_states):
        sample = unet_traced(latent_model_input, t, encoder_hidden_states)[0]
        return UNet2DConditionOutput(sample=sample)


pipe.unet = TracedUNet()

with torch.inference_mode():
    image = pipe('dog', num_inference_steps=50).images[0]
```

### Logs

```shell
Traceback (most recent call last):
  File "/app/temp.py", line 108, in <module>
    image = pipe('dog', num_inference_steps=50).images[0]
  File "/opt/conda/envs/a/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/a/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 860, in __call__
    height = height or self.unet.config.sample_size * self.vae_scale_factor
  File "/opt/conda/envs/a/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TracedUNet' object has no attribute 'config'
```

### System Info

- `diffusers` version: 0.28.0.dev0
- Platform: Linux-5.10.213-201.855.amzn2.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.39.3
- Accelerate version: 0.29.2
- xFormers version: 0.0.25.post1
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@DN6 @yiyixuxu @sayakpaul @stevhliu

**Comment by sayakpaul** [comment]
Can you try register a config to the `TracedUnet` class? 

`setattr(self, "config", pipeline.unet.config)`

**Comment by DN6** [comment]
@AbhinavGopal The `UNet2DConditionModel` inherits from the `ConfigMixin` class and has it's init arguments registered to a config attribute. If you're setting an `nn.Module` as the UNet in the pipeline, the rest of the pipeline inference code cannot access an expected attribute of the model. 

As @sayakpaul mentioned, you can set a `config` attribute in your TraceUNet that is the same as the original UNets and it should work.

**Comment by AbhinavGopal** [comment]
Thanks for the help! With the new code (I'm putting it below), I'm getting a new year
```
import time
import torch
from diffusers import StableDiffusionPipeline
import functools

torch.set_grad_enabled(False)

n_experiments = 2
unet_runs_per_experiment = 50


def generate_inputs():
    sample = torch.randn((2, 4, 64, 64), device="cuda", dtype=torch.float16)
    timestep = torch.rand(1, device="cuda", dtype=torch.float16) * 999
    encoder_hidden_states = torch.randn((2, 77, 768), device="cuda", dtype=torch.float16)
    return sample, timestep, encoder_hidden_states


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")
unet = pipe.unet
unet.eval()
unet.to(memory_format=torch.channels_last)  # use channels_last memory format
unet.forward = functools.partial(unet.forward, return_dict=False)  # set return_dict=False as default

for _ in range(3):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet(*inputs)

print("tracing..")
unet_traced = torch.jit.trace(unet, inputs)
unet_traced.eval()
print("done tracing")


for _ in range(5):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet_traced(*inputs)


with torch.inference_mode():
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet_traced(*inputs)
        torch.cuda.synchronize()
        print(f"unet traced inference took {time.time() - start_time:.2f} seconds")
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet(*inputs)
        torch.cuda.synchronize()
        print(f"unet inference took {time.time() - start_time:.2f} seconds")

unet_traced.save("unet_traced.pt")


from diffusers import StableDiffusionPipeline
import torch
from dataclasses import dataclass


@dataclass
class UNet2DConditionOutput:
    sample: torch.FloatTensor


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")


unet_traced = torch.jit.load("unet_traced.pt")


class TracedUNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.in_channels = pipe.unet.config.in_channels
        setattr(self, "config", pipe.unet.config)
        self.device = pipe.unet.device

    def forward(self, latent_model_input, t, encoder_hidden_states, **kwargs):
        sample = unet_traced(latent_model_input, t, encoder_hidden_states)[0]
        return UNet2DConditionOutput(sample=sample).sample


pipe.unet = TracedUNet()

with torch.inference_mode():
    image = pipe('dog', num_inference_steps=50).images[0]
```


Error:


```
Traceback (most recent call last):
  File "/app/temp.py", line 100, in <module>
    image = pipe('dog', num_inference_steps=50).images[0]
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 993, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 257, in step
    return self.step_plms(model_output=model_output, timestep=timestep, sample=sample, return_dict=return_dict)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 382, in step_plms
    prev_sample = self._get_prev_sample(sample, timestep, prev_timestep, model_output)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 443, in _get_prev_sample
    sample_coeff * sample - (alpha_prod_t_prev - alpha_prod_t) * model_output / model_output_denom_coeff
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1
```

**Comment by sayakpaul** [comment]
What happens without "inference_mode" context?

**Comment by AbhinavGopal** [comment]
Same thing :/

```
Traceback (most recent call last):
  File "/app/temp.py", line 99, in <module>
    image = pipe('dog', num_inference_steps=50).images[0]
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 993, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs, return_dict=False)[0]
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 257, in step
    return self.step_plms(model_output=model_output, timestep=timestep, sample=sample, return_dict=return_dict)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 382, in step_plms
    prev_sample = self._get_prev_sample(sample, timestep, prev_timestep, model_output)
  File "/opt/conda/envs/kong/lib/python3.10/site-packages/diffusers/schedulers/scheduling_pndm.py", line 443, in _get_prev_sample
    sample_coeff * sample - (alpha_prod_t_prev - alpha_prod_t) * model_output / model_output_denom_coeff
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1
```

**Comment by sayakpaul** [comment]
Okay this should work:

```python
import time
import torch
from diffusers import StableDiffusionPipeline
from dataclasses import dataclass
import functools

torch.set_grad_enabled(False)

n_experiments = 2
unet_runs_per_experiment = 50

@dataclass
class UNet2DConditionOutput:
    sample: torch.FloatTensor


def generate_inputs():
    sample = torch.randn((2, 4, 64, 64), device="cuda", dtype=torch.float16)
    timestep = torch.rand(1, device="cuda", dtype=torch.float16) * 999
    encoder_hidden_states = torch.randn((2, 77, 768), device="cuda", dtype=torch.float16)
    return sample, timestep, encoder_hidden_states


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")
unet = pipe.unet
unet.eval()
unet.to(memory_format=torch.channels_last)  # use channels_last memory format
unet.forward = functools.partial(unet.forward, return_dict=False)  # set return_dict=False as default

for _ in range(3):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet(*inputs)

print("tracing..")
unet_traced = torch.jit.trace(unet, inputs)
unet_traced.eval()
print("done tracing")


for _ in range(5):
    with torch.inference_mode():
        inputs = generate_inputs()
        orig_output = unet_traced(*inputs)


with torch.inference_mode():
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet_traced(*inputs)
        torch.cuda.synchronize()
        print(f"unet traced inference took {time.time() - start_time:.2f} seconds")
    for _ in range(n_experiments):
        torch.cuda.synchronize()
        start_time = time.time()
        for _ in range(unet_runs_per_experiment):
            orig_output = unet(*inputs)
        torch.cuda.synchronize()
        print(f"unet inference took {time.time() - start_time:.2f} seconds")

unet_traced.save("unet_traced.pt")


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")


unet_traced = torch.jit.load("unet_traced.pt")


class TracedUNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.in_channels = pipe.unet.config.in_channels
        setattr(self, "config", pipe.unet.config)
        self.device = pipe.unet.device

    def forward(self, latent_model_input, t, encoder_hidden_states, **kwargs):
        sample = unet_traced(latent_model_input, t, encoder_hidden_states)
        return UNet2DConditionOutput(sample=sample).sample


pipe.unet = TracedUNet()

with torch.inference_mode():
    image = pipe('dog', num_inference_steps=50).images[0]
```

Try it out and let us know?

**Comment by AbhinavGopal** [comment]
Works! One question though, if I modify the last lines to be:
```
with torch.inference_mode():
    image = pipe('dog', num_inference_steps=50).images[0]
    image = pipe('cat', num_inference_steps=50).images[0]
```

The first inference line is stuck at 0/50 for some time, and then quickly gets to 50/50 (3.35it/s).
The second inference line doesn't get stuck and takes (17.71it/s).

What is the reason for this? Is there a way i can separate the time-blocking step from the inference?

**Comment by AbhinavGopal** [comment]
Are there also similar docs for the SDXL version of trace? Running a u-net pass requires added_cond_kwargs, which I'm not completely sure on how to mock.

**Comment by sayakpaul** [comment]
You are asking non-library-related questions now. Discussions are preferred for those. 

So, I am going to close the issue.

**Comment by sayakpaul** [comment]
> The first inference line is stuck at 0/50 for some time, and then quickly gets to 50/50 (3.35it/s).
The second inference line doesn't get stuck and takes (17.71it/s).

For compiled models, usually, the first inference call takes time as it figures out the most optimal code path to perform the execution. At least that's the case for `torch.compile()`. 

> Are there also similar docs for the SDXL version of trace? Running a u-net pass requires added_cond_kwargs, which I'm not completely sure on how to mock.

I recommend going through the [SDXL pipeline code](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py) and adding print statements to understand how `added_cond_kwargs` should be crafted.
