### ISSUE TITLE
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback): Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback): module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by vedant123454** [huggingface/diffusers#7681]
### Describe the bug

Getting error while importing DiffusionPipeline from Diffusers 

```
Traceback (most recent call last):
  File "/nfs/Vision/DataRW/anushka/prompt_yml/stable_cascade2.py", line 18, in <module>
    from diffusers import DiffusionPipeline
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/diffusers/utils/import_utils.py", line 709, in __getattr__
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/diffusers/utils/import_utils.py", line 708, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/diffusers/utils/import_utils.py", line 720, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

### Reproduction

Install latest version of Diffusers :- `pip install --upgrade diffusers[torch]`
`from diffusers import DiffusionPipeline`

### System Info

Python :- 3.8.10
diffusers==0.27.2

### Who can help?

 @yiyixuxu @DN6

**Comment by vedant123454** [comment]
Issue with pyopenssl 
solved by upgrading `pip install pyopenssl --upgrade`

**Comment by vedant123454** [comment]
Issue with pyopenssl
solved by upgrading pip install pyopenssl --upgrade
