### ISSUE TITLE
fail to load modal from same folder 

### ISSUE THREAD

**Issue by neonarc4** [huggingface/diffusers#7939]
### Describe the bug

it cant load model just loading it from link not from disk 

### Reproduction
```py

from diffusers import OnnxRuntimeModel, DiffusionPipeline
import torch
pipeline = DiffusionPipeline.from_pretrained(
    "anything-v3-fp16-pruned.safetensors",
    use_safetensors=True,
    revision="fp16",
    torch_dtype=torch.float16,
    safety_checker=None,
    requires_safety_checker=False,
)

```
### Logs

```shell
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "X:\sad\neo.py", line 264, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
                    ^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "Z:\software\python11\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1454, in download
    raise EnvironmentError(
OSError: Cannot load model anything-v3-fp16-pruned.safetensors: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.


OSError: Cannot load model anything-v3-fp16-pruned.safetensors: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
```

### System Info

3.11 window 11

**Comment by missionfloyd** [comment]
Try this.
```python

from diffusers import StableDiffusionPipeline
import torch
pipeline = StableDiffusionPipeline.from_single_file(
    "anything-v3-fp16-pruned.safetensors",
    torch_dtype=torch.float16,
    safety_checker=None,
    requires_safety_checker=False,
    local_files_only=False
)
```
https://huggingface.co/docs/diffusers/main/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.from_single_file

It'll still have to download `v1-inference.yaml`. To load it locally, [download it](https://github.com/CompVis/stable-diffusion/blob/main/configs/stable-diffusion/v1-inference.yaml) and add `original_config_file="v1-inference.yaml"`

**Comment by neonarc4** [comment]
@missionfloyd  come here https://discord.com/channels/879548962464493619/1239779807403704371

**Comment by neonarc4** [comment]
@missionfloyd how do u know what is the base model of any model from civiai
