### ISSUE TITLE
controlNet training for dstilled models

### ISSUE THREAD

**Issue by kmpartner** [huggingface/diffusers#8424]
Is it possible to run distilled model (Block-removed Knowledge-distilled Stable Diffusion, https://github.com/Nota-NetsPresso/BK-SDM)?

When I used scripts in example folder for distilled model for controlNet training, it returns error, similar to "unknown mid_block_type ...." , probably because of unet structure changed. Are there any ways to train controlNet for distilled model?

**Comment by sayakpaul** [comment]
Can you provide more details into how you're approaching the training? Maybe provide some code snippets, etc.?

**Comment by kmpartner** [comment]
Thank you for response. I just followed code in controlnet folder using distilled models (mid block deleted models, such as "nota-ai/bk-sdm-tiny")

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path="nota-ai/bk-sdm-tiny" \
 --dataset_name=fusing/fill50k \
 --resolution=512 \
 --learning_rate=1e-5 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --train_batch_size=4

Before starting training iteration error was displayed probably because mid block is removed from unet.

"
Traceback (most recent call last):
  File "/content/diffusers/examples/controlnet/train_controlnet.py", line 1187, in <module>
    main(args)
  File "/content/diffusers/examples/controlnet/train_controlnet.py", line 818, in main
    controlnet = ControlNetModel.from_unet(unet)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 471, in from_unet
    controlnet = cls(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 658, in inner_init
    init(self, *args, **init_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 442, in __init__
    raise ValueError(f"unknown mid_block_type : {mid_block_type}")
ValueError: unknown mid_block_type : None
...
"


I will try to find ways to train using distilled model.
