### ISSUE TITLE
controlnet++

### ISSUE THREAD

**Issue by crapthings** [huggingface/diffusers#8509]
### Model/Pipeline/Scheduler description

https://huggingface.co/huchenlei/ControlNet_plus_plus_collection_fp16/tree/main

https://huggingface.co/huchenlei/ControlNet_plus_plus_collection_fp16/discussions/1

```
Traceback (most recent call last):
  File "/home/zznet/workspace/ai-pipe/prod-ai-pipe-replace-model/runpod_app.py", line 14, in <module>
    from pipe import text2img, getText2imgPipe, set_sampler, compel
  File "/home/zznet/workspace/ai-pipe/prod-ai-pipe-replace-model/pipe.py", line 17, in <module>
    canny_control = ControlNetModel.from_single_file('/home/zznet/workspace/ControlNet/models/controlnet_canny_tudaqian.pth', torch_dtype = torch.float16)
  File "/home/zznet/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/zznet/.local/lib/python3.10/site-packages/diffusers/loaders/controlnet.py", line 124, in from_single_file
    component = create_diffusers_controlnet_model_from_ldm(
  File "/home/zznet/.local/lib/python3.10/site-packages/diffusers/loaders/single_file_utils.py", line 973, in create_diffusers_controlnet_model_from_ldm
    diffusers_format_controlnet_checkpoint = convert_controlnet_checkpoint(checkpoint, diffusers_config)
  File "/home/zznet/.local/lib/python3.10/site-packages/diffusers/loaders/single_file_utils.py", line 937, in convert_controlnet_checkpoint
    new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
KeyError: 'middle_block_out.0.weight'
```

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

https://huggingface.co/huchenlei/ControlNet_plus_plus_collection_fp16/discussions/1#666894a2e6266af8e7445eba

**Comment by a-r-r-o-w** [comment]
@yiyixuxu @asomoza Are there any plans to support [ControlNet++](https://liming-ai.github.io/ControlNet_Plus_Plus/)? If yes, can open this for community contributions unless one of us has the bandwidth. If not, can mark as unplanned and close for the moment

**Comment by asomoza** [comment]
IMO this controlnet didn't grab that much traction because we can't really see that much of a difference, also it's only for SD 1.5. I'm closing it as not planned but if someone can provide some good examples that shows the difference with the current ones we can re-open and see if someone wants to contribute a community pipeline.

**Comment by asomoza** [comment]
IMO this controlnet didn't grab that much traction because we can't really see that much of a difference, also it's only for SD 1.5. I'm closing it as not planned but if someone can provide some good examples that shows the difference with the current ones we can re-open and see if someone wants to contribute a community pipeline.
