### ISSUE TITLE
if use 8gb vram train seting convert, Should ckpt conversion also be modified?

### ISSUE THREAD

**Issue by A-Polyana** [huggingface/diffusers#853]
hi there, Thanks to you, I finished my 8gb vram training well
but I have one problem that Web UI is can`t load My train Model ckpt

I use this ckpt convert py
`https://gist.github.com/jachiam/8a5c0b607e38fcc585168b90c686eb05`

if use my train model Web UI I'm sending out a log like this
```
To create a public link, set `share=True` in `launch()`.
Loading weights [722e0036] from E:\AI\stable-diffusion-webui\models\Stable-diffusion\fumitest.ckpt
Error verifying pickled file from E:\AI\stable-diffusion-webui\models\Stable-diffusion\fumitest.ckpt:
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\modules\safe.py", line 97, in load
    check_pt(filename)
  File "E:\AI\stable-diffusion-webui\modules\safe.py", line 81, in check_pt
    unpickler.load()
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 138, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 134, in _rebuild_tensor
    return t.set_(storage._untyped(), storage_offset, size, stride)
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1668787200 bytes.


The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 785, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 694, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\stable-diffusion-webui\modules\ui.py", line 1457, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "E:\AI\stable-diffusion-webui\modules\ui.py", line 1324, in run_settings_single
    opts.data_labels[key].onchange()
  File "E:\AI\stable-diffusion-webui\webui.py", line 41, in f
    res = func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\webui.py", line 86, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights(shared.sd_model)))
  File "E:\AI\stable-diffusion-webui\modules\sd_models.py", line 215, in reload_model_weights
    load_model_weights(sd_model, checkpoint_info)
  File "E:\AI\stable-diffusion-webui\modules\sd_models.py", line 138, in load_model_weights
    if "global_step" in pl_sd:
TypeError: argument of type 'NoneType' is not iterable
```

if I can load ckpt Change diffusers Setting? or Use other diffuers to ckpt script?
 
My train setting with Window 22H2 WSL2 with RTX 3070ti
```
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="training"
export CLASS_DIR="classes"
export OUTPUT_DIR="model"
 
accelerate launch train_dreambooth.py \
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="training"
export CLASS_DIR="classes"
export OUTPUT_DIR="model"
 
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of a fumika" \
  --class_prompt="a photo of a fumika" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=20 \
  --mixed_precision=fp16

```

**Comment by DonStroganotti** [comment]
This one works https://github.com/ratwithacompiler/diffusers_stablediff_conversion

**Comment by A-Polyana** [comment]
> This one works https://github.com/ratwithacompiler/diffusers_stablediff_conversion
> 
> to run it:
> python ./convert_diffusers_to_sd.py ./model ./sd-v1-4.ckpt ./model.ckpt

ty! that can load on webui
