### ISSUE TITLE
Running stable diffusion 3 medium : fused_layer_norm_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by zagglez** [huggingface/diffusers#8624]
### Describe the bug

Running diffusers version 0.29

```import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)
```

immediately throws error:
ImportError: /usr/local/lib/python3.10/dist-packages/fused_layer_norm_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE

torch: '2.3.1+cu121'
diffusers: 0.29

### Reproduction

import torch
from diffusers import StableDiffusion3Pipeline

pipe = StableDiffusion3Pipeline.from_pretrained("stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16)

### Logs

```shell
Loading pipeline components...:  56%|█████████████████████████████████████████████████▍                                       | 5/9 [00:00<00:00, 18.81it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 881, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_loading_utils.py", line 703, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3626, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py", line 1881, in __init__
    self.encoder = T5Stack(encoder_config, self.shared)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py", line 908, in __init__
    [T5Block(config, has_relative_attention_bias=bool(i == 0)) for i in range(config.num_layers)]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py", line 908, in <listcomp>
    [T5Block(config, has_relative_attention_bias=bool(i == 0)) for i in range(config.num_layers)]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py", line 649, in __init__
    self.layer.append(T5LayerSelfAttention(config, has_relative_attention_bias=has_relative_attention_bias))
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/t5/modeling_t5.py", line 580, in __init__
    self.layer_norm = T5LayerNorm(config.d_model, eps=config.layer_norm_epsilon)
  File "/usr/local/lib/python3.10/dist-packages/apex/normalization/fused_layer_norm.py", line 364, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.10/dist-packages/fused_layer_norm_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
```

### System Info

Running in a Docker container built on Ubuntu 22.04.4 
- Diffusers version: 0.29.0
- Platform: Linux-6.8.0-35-generic-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.41.2
- Accelerate version: 0.31.0
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.27+133d7f1.d20240618
- Accelerator: NVIDIA GeForce RTX 3060, 12288 MiB VRAM
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

Accelerate env
- `Accelerate` version: 0.31.0
- Platform: Linux-6.8.0-35-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /usr/local/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 31.26 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: NO
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- enable_cpu_affinity: True
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []

**Comment by doctorpangloss** [comment]
your copy of apex does not have fused_layer_norm compiled in it, which is optional

**Comment by zagglez** [comment]
I  am running pytorch 2.x which provides much of what apex did for pytorch 1, so I resolved the issue by just uninstalling apex.
