### ISSUE TITLE
StableDiffusionXLPipeline.from_single_file can't use in offline server

### ISSUE THREAD

**Issue by 631068264** [huggingface/diffusers#8752]
### Describe the bug

error
```
`local_files_only` is True but no local configs were found for this checkpoint.
Attempting to download the necessary config files for this pipeline.

Traceback (most recent call last):
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f86e852ce50>, 'Connection to huggingface.co timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/stabilityai/stable-diffusion-xl-base-1.0/revision/main (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnec


```
I don't know why this function is called `from_single_file` , but it need other files to run.

### Reproduction

```
from diffusers import StableDiffusionXLPipeline
import torch

# pipe = StableDiffusionXLPipeline.from_pretrained(
#     "hf_models/stable-diffusion-xl-base-1.0",
#     torch_dtype=torch.float16, variant="fp16", use_safetensors=True,
# ).to("cuda")

pipe = StableDiffusionXLPipeline.from_single_file(
    "hf_models/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors",
    torch_dtype=torch.float16
).to("cuda")

# if using torch < 2.0
# pipe.enable_xformers_memory_efficient_attention()

prompt = "An astronaut riding a green horse"

images = pipe(prompt=prompt).images[0]
```
the sd_xl_base_1.0.safetensors   is exist in this path.
```
ll hf_models/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors
-rw-r--r-- 1 root root 6938078334 Aug 30  2023 hf_models/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors
```

### System Info

python 3.11
diffusers                0.29.2

**Comment by DN6** [comment]
Hi @631068264 Is it possible for you to run `StableDiffusionXLPipeline.from_single_file(...)` with `local_files_only=False` once? 

We infer the appropriate model configs for the pipeline from the single file checkpoint and attempt to download them if they are not present locally. Once they're available locally, you can run `from_single_file` with `local_files_only=True`  

This section in our docs explains how to download the configs locally to your machine
https://huggingface.co/docs/diffusers/en/using-diffusers/other-formats?local=specific+local+directory#local-files

**Comment by 631068264** [comment]
```
local_config_path = snapshot_download(
    repo_id="stabilityai/stable-diffusion-xl-base-1.0",
    allowed_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"],
    local_dir="hf_models/stable-diffusion-xl-base-1.0",
)

print(local_config_path)

pipe = StableDiffusionXLPipeline.from_single_file(
    "hf_models/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors",
    config=local_config_path,
    local_files_only=True,
    torch_dtype=torch.float16).to("cuda")

prompt = "An astronaut riding a green horse"
# pipe.enable_xformers_memory_efficient_attention()
# pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
pipe.enable_vae_slicing()
pipe.enable_model_cpu_offload()
images = pipe(prompt=[prompt] * 5).images
```

Get error  https://github.com/huggingface/transformers/issues/15393#issuecomment-2201639115 ,  I even don't know why almost same code can run https://github.com/huggingface/diffusers/blob/4e57aeff1f184663177358492a03ecbefae89556/src/diffusers/loaders/single_file.py#L239   

Finally  I have to let the config to save in cache dir @DN6 



**Comment by DN6** [comment]
Ah appears there is a mistake in the docs. It should be `allow_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"]`. I will update that. This should work 

```python
local_config_path = snapshot_download(
    repo_id="stabilityai/stable-diffusion-xl-base-1.0",
    allow_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"],
    local_dir="hf_models/stable-diffusion-xl-base-1.0",
)

print(local_config_path)

pipe = StableDiffusionXLPipeline.from_single_file(
    "hf_models/stable-diffusion-xl-base-1.0/sd_xl_base_1.0.safetensors",
    config=local_config_path,
    local_files_only=True,
    torch_dtype=torch.float16).to("cuda")

prompt = "An astronaut riding a green horse"
# pipe.enable_xformers_memory_efficient_attention()
# pipe.unet = torch.compile(pipe.unet, mode="reduce-overhead", fullgraph=True)
pipe.enable_vae_slicing()
pipe.enable_model_cpu_offload()
images = pipe(prompt=[prompt] * 5).images
```

But if the config is saved in the cache that can work as well.

**Comment by whisky-12** [comment]
The same problem, when I want to load an SD local model using StableDiffusion 3Pipeline.from_stngle file, follow the above configuration:
local_config_path = snapshot_download(
repo_id="stabilityai/stable-diffusion-xl-base-1.0",
allow_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"],
local_dir="hf_models/stable-diffusion-xl-base-1.0",
)
How do I want to design the repo_id? I have tried "stabilizability/table diffusion-3-medium" but it seems that there is no related config. json or other configuration. It doesn't seem like this repo_id? I hope you can help confirm, as there are a large number of requirements loading local SD3 files

**Comment by asomoza** [comment]
for sd3 with diffusers you need to use this repo: [stabilityai/stable-diffusion-3-medium-diffusers](https://huggingface.co/stabilityai/stable-diffusion-3-medium-diffusers)

**Comment by whisky-12** [comment]
> for sd3 with diffusers you need to use this repo: [stabilityai/stable-diffusion-3-medium-diffusers](https://huggingface.co/stabilityai/stable-diffusion-3-medium-diffusers)

Thank you very much ！
