### ISSUE TITLE
How to make custom datasets for instruct-pix2pix?

### ISSUE THREAD

**Issue by jeonga0303** [huggingface/diffusers#8824]
### Describe the bug

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/venv/lib/python3.10/site-packages/datasets/builder.py", line 1750, in _prepare_split_single
[rank0]:     for key, record in generator:
[rank0]:   File "/opt/venv/lib/python3.10/site-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 315, in _generate_examples
[rank0]:     raise ValueError(
[rank0]: ValueError: image at [image name].jpg doesn't have metadata in [my_metadata_path]metadata.jsonl.
```

### Reproduction

I want to make custom datasets for local.

### dataset
- datasets
    - input_images
        - image.jpg
        - image.jpg
        - ...
    - edited_images
        - edited_image.jpg
        - edited_image.jpg
        - ...
    - metadata.jsonl

### metadata.jsonl
```
{"file_name": "input_images/image.jpg", "edited_images/edited_image": "edited_image.jpg", "edit_prompt": "sample"}
```

### train script
```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export TRAIN_DIR="datasets/"
export OUTPUT_DIR="weights/"


accelerate launch --mixed_precision="fp16" --multi_gpu train_instruct_pix2pix.py \
 --pretrained_model_name_or_path=$MODEL_NAME \
 --train_data_dir=$TRAIN_DIR \
 --use_ema \
 --resolution=512 --random_flip \
 --train_batch_size=2 --gradient_accumulation_steps=4 --gradient_checkpointing \
 --max_train_steps=15000 \
 --checkpointing_steps=5000 --checkpoints_total_limit=1 \
 --learning_rate=5e-05 --lr_warmup_steps=0 \
 --conditioning_dropout_prob=0.05 \
 --mixed_precision=fp16 \
 --seed=42 \
 --output_dir=${OUTPUT_DIR}
```

### error log

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/venv/lib/python3.10/site-packages/datasets/builder.py", line 1750, in _prepare_split_single
[rank0]:     for key, record in generator:
[rank0]:   File "/opt/venv/lib/python3.10/site-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 315, in _generate_examples
[rank0]:     raise ValueError(
[rank0]: ValueError: image at [image name].jpg doesn't have metadata in [my_metadata_path]metadata.jsonl.
```

how to make custom datasets for local?
I didn't find any solution.

### System Info

diffusers                 0.30.0.dev0

**Comment by jeonga0303** [comment]
i got this solution.

```
datasets
   - edited_images
       - images.jpg
       - images.jpg
       - ...
   - original_images
       - images.jpg
       - images.jpg
       - ...
   - metadata.jsol
```

If you don't have metadata.jsonl, run the following code

```
# make_metadata.py
import os
import json

normal_apple_dir = 'original_images/'
abnormal_apple_dir = 'edited_images/'

normal_apples = sorted(os.listdir(normal_apple_dir))
abnormal_apples = sorted(os.listdir(abnormal_apple_dir))

dataset = []

for normal, abnormal in zip(normal_apples[:min(len(normal_apples), len(abnormal_apples))], abnormal_apples):
    data_entry = {
        "original_image": "input_images/" + normal,
        "edited_image":  "edited_images/" + abnormal,
        "edit_prompt": "Converting Normal Image to Abnormal"
    }
    dataset.append(data_entry)

with open('metadata.jsonl', 'w', encoding='utf-8') as f:
    for entry in dataset:
        f.write(json.dumps(entry, ensure_ascii=False) + '\n')

print(f"Dataset creation complete! Total pairs: {len(dataset)}")
```

(optional)
Also, if the number of files in original_images is not the same as the number of files in edited_images, run the following code 

```
# remove_not_meta.py
import os
import json

edited_image_dir = 'original_images/'

metadata_file = 'metadata.jsonl'

used_images = set()
with open(metadata_file, 'r') as f:
    for line in f:
        data_entry = json.loads(line.strip())
        edited_image_path = data_entry["original_image"]
        used_images.add(os.path.basename(edited_image_path))

all_images = set(os.listdir(edited_image_dir))

print(f"Total edited images: {len(all_images)}")
print(f"Used images in metadata: {len(used_images)}")
unused_images = all_images - used_images

print(f"Unused images: {len(unused_images)}")

for image_path in unused_images:
    os.remove(os.path.join(edited_image_dir, image_path))
    print(f"Deleted unused image: {image_path}")

print("Unused images deletion complete!")

```
---
The file you need to modify is as follows.
# train_instruct_pix2pix.py
Modify the following fuction
## Just, Convert load_dataset("imageFolder" ...) to load_dataset("json", data_files=json_path) !
```
    if args.dataset_name is not None:
        # Downloading and loading a dataset from the hub.
        dataset = load_dataset(
            args.dataset_name,
            args.dataset_config_name,
            cache_dir=args.cache_dir,
        )
    else:
        data_files = {}
        if args.train_data_dir is not None:
            data_files["train"] = os.path.join(args.train_data_dir, "**")
        # dataset = load_dataset(
        #     "imagefolder",
        #     data_files=data_files,
        #     cache_dir=args.cache_dir,
        # )
        dataset = load_dataset('json', data_files='datasets/metadata.jsonl')
```
```
def convert_to_np(image_path, resolution):
    image_path = os.path.join('datasets', image_path)
    with Image.open(image_path) as img:
        img = img.convert("RGB").resize((resolution, resolution))
        np_img = np.array(img).transpose(2, 0, 1)
        return np_img
```
---
# fine_tuning.sh
add "--original_image_column"
```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export DATASET_ID="datasets/"

accelerate launch --mixed_precision="fp16" --multi_gpu train_instruct_pix2pix.py \
 --pretrained_model_name_or_path=$MODEL_NAME \
 --train_data_dir=$DATASET_ID \
 --use_ema \
 --resolution=512 --random_flip \
 --original_image_column="input_image" \
 --train_batch_size=4 --gradient_accumulation_steps=4 --gradient_checkpointing \
 --max_train_steps=15000 \
 --checkpointing_steps=5000 --checkpoints_total_limit=1 \
 --learning_rate=5e-05 --lr_warmup_steps=0 \
 --conditioning_dropout_prob=0.05 \
 --mixed_precision=fp16 \
 --seed=42 \
 --push_to_hub
```
