### ISSUE TITLE
Bug still Found during Lora Training: ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by dibbla** [huggingface/diffusers#8871]
### Describe the bug

I was using the example code for lora training on SDXL model. However, as I launch the training, I get error `ValueError: Attempting to unscale FP16 gradients.`, which seems like training something fp16. 

The error message is shown as follows:
```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `3`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
07/16/2024 15:22:06 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 3
Process index: 1
Local process index: 1
Device: cuda:1

Mixed precision type: fp16

Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
07/16/2024 15:22:06 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 3
Process index: 2
Local process index: 2
Device: cuda:2

Mixed precision type: fp16

07/16/2024 15:22:06 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 3
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'dynamic_thresholding_ratio', 'thresholding', 'rescale_betas_zero_snr', 'clip_sample_range', 'variance_type'} was not found in config. Values will be initialized to default values.
{'shift_factor', 'latents_mean', 'use_quant_conv', 'use_post_quant_conv', 'latents_std'} was not found in config. Values will be initialized to default values.
{'reverse_transformer_layers_per_block', 'attention_type', 'dropout'} was not found in config. Values will be initialized to default values.
Resolving data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 2291.61it/s]
Resolving data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 2228.01it/s]
Resolving data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 4531.09it/s]
07/16/2024 15:23:28 - INFO - __main__ - ***** Running training *****
07/16/2024 15:23:28 - INFO - __main__ -   Num examples = 72
07/16/2024 15:23:28 - INFO - __main__ -   Num Epochs = 100
07/16/2024 15:23:28 - INFO - __main__ -   Instantaneous batch size per device = 1
07/16/2024 15:23:28 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 3
07/16/2024 15:23:28 - INFO - __main__ -   Gradient Accumulation steps = 1
07/16/2024 15:23:28 - INFO - __main__ -   Total optimization steps = 2400
Steps:   0%|                                                                                                                                                                    | 0/2400 [00:00<?, ?it/s][W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Traceback (most recent call last):
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1327, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1327, in <module>
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1327, in <module>
    main(args)
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1191, in main
    main(args)
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1191, in main
    main(args)
  File "/root/picasso/xyg1/style/style_transfer_ws_Chibi/scripts/ref.py", line 1191, in main
    accelerator.clip_grad_norm_(params_to_optimize, args.max_grad_norm)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2295, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_optimize, args.max_grad_norm)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2295, in clip_grad_norm_
    accelerator.clip_grad_norm_(params_to_optimize, args.max_grad_norm)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2295, in clip_grad_norm_
    self.unscale_gradients()
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2245, in unscale_gradients
    self.unscale_gradients()
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2245, in unscale_gradients
    self.unscale_gradients()
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 2245, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_
    self.scaler.unscale_(opt)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_
        optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)self.scaler.unscale_(opt)

  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
Steps:   0%|                                                                                                                                                                    | 0/2400 [00:02<?, ?it/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 97570 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 97571 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 97569) of binary: /opt/conda/envs/lora/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/lora/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1088, in launch_command
    multi_gpu_launcher(args)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/accelerate/commands/launch.py", line 733, in multi_gpu_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/ref.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-16_15:23:33
  host      : xyg1-desktop-7ywkj5f-f845497f5-k98m6
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 97569)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### Reproduction

I am using the latest [example](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py). My training command is:
```bash
accelerate launch --multi_gpu --mixed_precision="fp16" scripts/train_text_to_image_lora_sdxl.py --dataset_name data/hf_datasets --pretrained_model_na
me_or_path /root/stable-diffusion-xl-base-1.0/ --train_batch_size 1 --resolution 512
```

I am using a local model weight and 3 RTX3090 GPUs. The code is moved else where but remains the same. The dataset is private, but it can replicate the issue if using the naruto-blip-captions.

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.27
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.9
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.4
- Accelerate version: 0.32.1
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.16
- Accelerator: NVIDIA GeForce RTX 3090, 24576 MiB
NVIDIA GeForce RTX 3090, 24576 MiB
NVIDIA GeForce RTX 3090, 24576 MiB VRAM
- Using GPU in script?: Yes, 3 RTX3090
- Using distributed or parallel set-up in script?: Yes

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Does this happen on a single GPU?

**Comment by dibbla** [comment]
> Does this happen on a single GPU?

Yes, I cancelled the --multi_gpu and set process number to 1, the error is the same. I am investigating into the data type of the returned `LoraModel`

**Comment by dibbla** [comment]
> Does this happen on a single GPU?

Update: I modified the https://github.com/huggingface/diffusers/blob/3b37fefee99425286984a9d5fa4f1850064d01eb/src/diffusers/loaders/peft.py#L104-L108

to 
```python
        for name, module in self.named_modules():
            if isinstance(module, BaseTunerLayer):
                print(name, type(module))
                print(module.weight.dtype, module.bias.dtype)

                if hasattr(module, "set_adapter"):
                    module.set_adapter(adapter_name)
```

Seems like everything is in fp16 instead of fp32. According to my understanding of previous similar issues, this is not gonna train well?

**Comment by tolgacangoz** [comment]
[Duplicate?](https://github.com/huggingface/diffusers/issues/6363)

**Comment by dibbla** [comment]
Not really a duplicate of #6363, given the commits after it should have already resolved the issue. However, given I am using a docker image remotely, I testes on other images and things goes fine. Maybe it is just something wrong with the system.

Closing this issue as solved. Thanks for the help.
