### ISSUE TITLE
How to load sd_xl_refiner_1.0.safetensors  use from_single_file

### ISSUE THREAD

**Issue by 631068264** [huggingface/diffusers#8900]
### Describe the bug

```
Traceback (most recent call last):
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 300, in <module>
    A1111(local_dir, 'sd_xl_base_1.0.safetensors', steps=50, cfs_scale=8)
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 235, in A1111
    refiner = StableDiffusionXLPipeline.from_single_file(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/loaders/single_file.py", line 503, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/loaders/single_file.py", line 113, in load_single_file_sub_model
    loaded_sub_model = create_diffusers_clip_model_from_ldm(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/loaders/single_file_utils.py", line 1411, in create_diffusers_clip_model_from_ldm
    unexpected_keys = load_model_dict_into_meta(model, diffusers_format_checkpoint, dtype=torch_dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/models/model_loading_utils.py", line 154, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load because text_model.embeddings.position_embedding.weight expected shape tensor(..., device='meta', size=(77, 768)), but got torch.Size([77, 1280]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.
```

### Reproduction

I have add   `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`  but not work
```
def download_config(local_dir):
    # 检查是否存在指定的子目录
    sub_dir = '.huggingface'
    path = os.path.join(local_dir, sub_dir)

    # 判断目录是否存在
    if not os.path.isdir(path):
        if 'base' in path:
            local_config_path = snapshot_download(
                repo_id="stabilityai/stable-diffusion-xl-base-1.0",
                allow_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"],
                local_dir=local_dir,
            )
        elif 'refiner' in path:
            local_config_path = snapshot_download(
                repo_id="stabilityai/stable-diffusion-xl-refiner-1.0",
                allow_patterns=["*.json", "**/*.json", "*.txt", "**/*.txt"],
                local_dir=local_dir,
            )

    return local_dir


def A1111(local_dir, model_name, steps, cfs_scale, dir=''):
    pipe = StableDiffusionXLPipeline.from_single_file(
        f'{local_dir}/{model_name}',
        config=download_config(local_dir),
        local_files_only=True,
        torch_dtype=torch.float16,
    ).to("cuda")
    # refiner model
    refiner_path = '/workspace/work/private/hf_models/stable-diffusion-xl-refiner-1.0'
    refiner = StableDiffusionXLPipeline.from_single_file(
        f'{refiner_path}/sd_xl_refiner_1.0.safetensors',
        text_encoder_2=pipe.text_encoder_2,
        vae=pipe.vae,
        config=download_config(local_dir),
        local_files_only=True,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=False,
        ignore_mismatched_sizes=True,
    ).to("cuda")

    # lora
    lora_dir = '/data/modeldata/aigc-fg-gen/v1.9/Lora'
    # adapter name 不能有点
    pipe.load_lora_weights(lora_dir, weight_name="fix_hands.pt", adapter_name="fix_hands")
    pipe.load_lora_weights(lora_dir, weight_name="sdxl_lora_fg_v1.2_colorv2_shirt_mp.safetensors",
                           adapter_name="sdxl_lora_fg_v1_2_colorv2_shirt_mp")
    pipe.set_adapters(["fix_hands", "sdxl_lora_fg_v1_2_colorv2_shirt_mp"], adapter_weights=[1.5, 0.8])
    # sample name https://huggingface.co/docs/diffusers/v0.26.2/en/api/schedulers/overview#schedulers
    scheduler = DPMSolverSinglestepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)
    pipe.scheduler = scheduler

    # 提示参数
    prompt = "xxxxx"
    negative_prompt = "xxxxx"
    generator = torch.Generator(device="cuda").manual_seed(1227346489)
    num_images = 4
    width, height = 1024, 1024
    steps = steps
    cfg_scale = cfs_scale
    # if 'step' in model_name:
    normal_optimization(pipe, infer=False)

    params = {
        'prompt': prompt,
        'height': height,
        'width': width,
        'num_inference_steps': steps,
        'guidance_scale': cfg_scale,
        'negative_prompt': negative_prompt,
        'num_images_per_prompt': num_images,
        'generator': generator,
        'denoising_end': 0.8,
    }

    # 生成图像
    images = pipe(output_type="latent", **params).images
    images = refiner(image=images, **params).images

    save_image(images, f'output/{dir}')

```

local_dir = "/workspace/work/private/hf_models/stable-diffusion-xl-base-1.0"
A1111(local_dir, 'sd_xl_base_1.0.safetensors', steps=50, cfs_scale=8)

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.10.134-16.1.al8.x86_64-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.11.9
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.3
- Accelerate version: 0.31.0
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.26.post1
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?
@yiyixuxu @sayakpaul @DN6
_No response_

**Comment by DN6** [comment]
Hi @631068264 It looks like your `local_dir` when loading the config for the refiner model is actually set to the base model? You will have to point it to the path of the refiner model in order to load it.

**Comment by 631068264** [comment]
@DN6  Thanks your reply. I have fix the error but  still get error  when get refiner output

```
Loading pipeline components...:   0%|                                                                                                                           | 0/7 [00:00<?, ?it/s]Some weights of the model checkpoint were not used when initializing CLIPTextModel: 
 ['text_model.embeddings.position_ids']
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 13.02it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 19.81it/s]
 `last_sigmas_type='zero'` is not supported for `lower_order_final=False`. Changing scheduler {self.config} to have `lower_order_final` set to True.
  0%|                                                                                                                                                          | 0/50 [00:00<?, ?it/s]/opt/conda/envs/tensorrt/lib/python3.11/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:08<00:00,  5.93it/s]
Traceback (most recent call last):
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 349, in <module>
    A1111(local_dir, 'sd_xl_base_1.0.safetensors', steps=50, cfs_scale=8)
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 318, in A1111
    images = refiner(image=image, **params).images
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 1131, in __call__
    add_time_ids = self._get_add_time_ids(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 736, in _get_add_time_ids
    raise ValueError(
ValueError: Model expects an added time embedding vector of length 2560, but a vector of 2816 was created. The model has an incorrect config. Please check `unet.config.time_embedding_type` and `text_encoder_2.config.projection_dim`.
```

**Comment by 631068264** [comment]
When I use StableDiffusionXLImg2ImgPipeline  instead ,  it can run well.
```
    refiner = StableDiffusionXLImg2ImgPipeline.from_single_file(
        f'{refiner_path}/{refiner_model}',
        config=download_config(refiner_path),
        local_files_only=True,
        torch_dtype=torch.float16,
        text_encoder_2=pipe.text_encoder_2,
        vae=pipe.vae,
    ).to("cuda")
```

**Comment by DN6** [comment]
Hi @631068264 that is correct. Refiner is meant to be used with Img2Img.

**Comment by yiyixuxu** [comment]
can we close this issue now?
