### ISSUE TITLE
OVStableDiffusionXLPipeline can't load model

### ISSUE THREAD

**Issue by 631068264** [huggingface/diffusers#8956]
### Describe the bug

```
Framework not specified. Using pt to export the model.
Keyword arguments {'subfolder': '', 'trust_remote_code': False} are not expected by StableDiffusionXLImg2ImgPipeline and will be ignored.
Loading pipeline components...:  29%|████████████████████████████████▊                                                                                  | 2/7 [00:00<00:00, 21.49it/s]
Loading TensorFlow model in PyTorch before exporting.
Keyword arguments {'subfolder': '', 'trust_remote_code': False, 'from_tf': True} are not expected by StableDiffusionXLImg2ImgPipeline and will be ignored.
Loading pipeline components...:  29%|████████████████████████████████▊                                                                                  | 2/7 [00:00<00:00, 30.50it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/optimum/exporters/tasks.py", line 1990, in get_model_from_task
    model = model_class.from_pretrained(model_name_or_path, **kwargs).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 881, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 703, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3371, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin found in directory /workspace/work/private/hf_models/stable-diffusion-xl-base-1.0/text_encoder_2 but there is a file for Flax weights. Use `from_flax=True` to load this model from those weights.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 401, in <module>
    pipe = load_onnx(local_dir, model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/work/private/TensorRT/demo/Diffusion/st_base.py", line 390, in load_onnx
    pipeline = OVStableDiffusionXLPipeline.from_pretrained(local_dir, export=True,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/optimum/modeling_base.py", line 427, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/optimum/intel/openvino/modeling_diffusion.py", line 381, in _from_transformers
    main_export(
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/optimum/exporters/openvino/__main__.py", line 290, in main_export
    model = TasksManager.get_model_from_task(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/optimum/exporters/tasks.py", line 1997, in get_model_from_task
    model = model_class.from_pretrained(model_name_or_path, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 881, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 703, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/tensorrt/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3371, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin found in directory /workspace/work/private/hf_models/stable-diffusion-xl-base-1.0/text_encoder_2 but there is a file for Flax weights. Use `from_flax=True` to load this model from those weights.
```

### Reproduction

I have download the files from hf
```
local_config_path = snapshot_download(
    repo_id="stabilityai/stable-diffusion-xl-base-1.0",
    allow_patterns=["openvino_model.*", "**/openvino_model.*", "**/flax_model.msgpack",
                    "**/diffusion_pytorch_model.safetensors"],
    local_dir=local_dir,
)
```

load the file
```
def load_onnx(local_dir, model_name):
    from optimum.intel import OVStableDiffusionXLPipeline

    pipeline = OVStableDiffusionXLPipeline.from_pretrained(local_dir, export=True,
                                                           # torch_dtype=torch.float16,
                                                           # use_safetensors=True, variant="fp16"
                                                           )
    pipeline.save_pretrained("/workspace/work/private/hf_models/openvino-sdxl-base")
    return pipeline
```

model path
```
.
├── model_index.json
├── scheduler
│   └── scheduler_config.json
├── sd_xl_base_1.0.safetensors -> /data/modeldata/aigc-fg-gen/v1.9/Stable-diffusion/sd_xl_base_1.0.safetensors
├── sdxl_lightning_8step.safetensors
├── text_encoder
│   ├── config.json
│   ├── flax_model.msgpack
│   ├── openvino_model.bin
│   └── openvino_model.xml
├── text_encoder_2
│   ├── config.json
│   ├── flax_model.msgpack
│   ├── openvino_model.bin
│   └── openvino_model.xml
├── tokenizer
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── tokenizer_2
│   ├── merges.txt
│   ├── special_tokens_map.json
│   ├── tokenizer_config.json
│   └── vocab.json
├── unet
│   ├── config.json
│   ├── diffusion_pytorch_model.safetensors
│   ├── openvino_model.bin
│   └── openvino_model.xml
├── vae
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
├── vae_1_0
│   ├── config.json
│   └── diffusion_pytorch_model.safetensors
├── vae_decoder
│   ├── config.json
│   ├── openvino_model.bin
│   └── openvino_model.xml
└── vae_encoder
    ├── config.json
    ├── openvino_model.bin
    └── openvino_model.xml

```

### System Info

- 🤗 Diffusers version: 0.29.2
- Platform: Linux-5.10.134-16.1.al8.x86_64-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.11.9
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.42.3
- Accelerate version: 0.31.0
- PEFT version: 0.11.1
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: 0.0.26.post1
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@DN6

**Comment by tolgacangoz** [comment]
It might be more appropriate to open this issue in the `optimum-intel` library.
Isn't it proper to use as explained on [the docs page](https://huggingface.co/docs/diffusers/main/en/optimization/open_vino) for you?
