### ISSUE TITLE
Script to export Flux to diffusers.

### ISSUE THREAD

**Issue by mrrfr** [huggingface/diffusers#9088]
### Describe the bug

Hello, 

I am trying to cast Flux model on FP8, as the original version of Flux need to be converted in order to be used by diffusers i tried to use the script provided but i have an error. It's all good with the transformer, i succeeded to export it, but i have an issue with VAE. Tried sevral things on the script but nothing, i tried to look at the previous issue and i wasn't able to solve my problem !

When i try to use the script to export the VAE for FluxPipeline from Black forest sft file i have a Missing keys in state_dict: error. 

Thank you for the help :))

### Reproduction

```bash
python scripts/convert_flux_to_diffusers.py  \
--original_state_dict_repo_id "black-forest-labs/FLUX.1-schnell" \
--filename "ae.sft"
--output_path "flux-schnell" \
--vae
```

### Logs

```shell
root@R:~$ python convert_flux_to_diffusers.py --original_state_dict_repo_id "black-forest-labs/FLUX.1-schnell" --filename "flux1-schnell.sft" --output_path "flux-schnell" --vae
vae/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 739/739 [00:00<00:00, 7.28MB/s]
Traceback (most recent call last):
  File "/root/convert.py", line 310, in <module>
    main(args)
  File "/root/convert.py", line 305, in main
    vae.load_state_dict(converted_vae_state_dict, strict=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.conv_in.weight", "encoder.conv_in.bias", "encoder.down_blocks.0.resnets.0.norm1.weight", "encoder.down_blocks.0.resnets.0.norm1.bias", "encoder.down_blocks.0.resnets.0.conv1.weight", "encoder.down_blocks.0.resnets.0.conv1.bias", "encoder.down_blocks.0.resnets.0.norm2.weight", "encoder.down_blocks.0.resnets.0.norm2.bias", "encoder.down_blocks.0.resnets.0.conv2.weight", "encoder.down_blocks.0.resnets.0.conv2.bias", "encoder.down_blocks.0.resnets.1.norm1.weight", "encoder.down_blocks.0.resnets.1.norm1.bias", "encoder.down_blocks.0.resnets.1.conv1.weight", "encoder.down_blocks.0.resnets.1.conv1.bias", "encoder.down_blocks.0.resnets.1.norm2.weight", "encoder.down_blocks.0.resnets.1.norm2.bias", "encoder.down_blocks.0.resnets.1.conv2.weight", "encoder.down_blocks.0.resnets.1.conv2.bias", "encoder.down_blocks.0.downsamplers.0.conv.weight", "encoder.down_blocks.0.downsamplers.0.conv.bias", "encoder.down_blocks.1.resnets.0.norm1.weight", "encoder.down_blocks.1.resnets.0.norm1.bias", "encoder.down_blocks.1.resnets.0.conv1.weight", "encoder.down_blocks.1.resnets.0.conv1.bias", "encoder.down_blocks.1.resnets.0.norm2.weight", "encoder.down_blocks.1.resnets.0.norm2.bias", "encoder.down_blocks.1.resnets.0.conv2.weight", "encoder.down_blocks.1.resnets.0.conv2.bias", "encoder.down_blocks.1.resnets.0.conv_shortcut.weight", "encoder.down_blocks.1.resnets.0.conv_shortcut.bias", "encoder.down_blocks.1.resnets.1.norm1.weight", "encoder.down_blocks.1.resnets.1.norm1.bias", "encoder.down_blocks.1.resnets.1.conv1.weight", "encoder.down_blocks.1.resnets.1.conv1.bias", "encoder.down_blocks.1.resnets.1.norm2.weight", "encoder.down_blocks.1.resnets.1.norm2.bias", "encoder.down_blocks.1.resnets.1.conv2.weight", "encoder.down_blocks.1.resnets.1.conv2.bias", "encoder.down_blocks.1.downsamplers.0.conv.weight", "encoder.down_blocks.1.downsamplers.0.conv.bias", "encoder.down_blocks.2.resnets.0.norm1.weight", "encoder.down_blocks.2.resnets.0.norm1.bias", "encoder.down_blocks.2.resnets.0.conv1.weight", "encoder.down_blocks.2.resnets.0.conv1.bias", "encoder.down_blocks.2.resnets.0.norm2.weight", "encoder.down_blocks.2.resnets.0.norm2.bias", "encoder.down_blocks.2.resnets.0.conv2.weight", "encoder.down_blocks.2.resnets.0.conv2.bias", "encoder.down_blocks.2.resnets.0.conv_shortcut.weight", "encoder.down_blocks.2.resnets.0.conv_shortcut.bias", "encoder.down_blocks.2.resnets.1.norm1.weight", "encoder.down_blocks.2.resnets.1.norm1.bias", "encoder.down_blocks.2.resnets.1.conv1.weight", "encoder.down_blocks.2.resnets.1.conv1.bias", "encoder.down_blocks.2.resnets.1.norm2.weight", "encoder.down_blocks.2.resnets.1.norm2.bias", "encoder.down_blocks.2.resnets.1.conv2.weight", "encoder.down_blocks.2.resnets.1.conv2.bias", "encoder.down_blocks.2.downsamplers.0.conv.weight", "encoder.down_blocks.2.downsamplers.0.conv.bias", "encoder.down_blocks.3.resnets.0.norm1.weight", "encoder.down_blocks.3.resnets.0.norm1.bias", "encoder.down_blocks.3.resnets.0.conv1.weight", "encoder.down_blocks.3.resnets.0.conv1.bias", "encoder.down_blocks.3.resnets.0.norm2.weight", "encoder.down_blocks.3.resnets.0.norm2.bias", "encoder.down_blocks.3.resnets.0.conv2.weight", "encoder.down_blocks.3.resnets.0.conv2.bias", "encoder.down_blocks.3.resnets.1.norm1.weight", "encoder.down_blocks.3.resnets.1.norm1.bias", "encoder.down_blocks.3.resnets.1.conv1.weight", "encoder.down_blocks.3.resnets.1.conv1.bias", "encoder.down_blocks.3.resnets.1.norm2.weight", "encoder.down_blocks.3.resnets.1.norm2.bias", "encoder.down_blocks.3.resnets.1.conv2.weight", "encoder.down_blocks.3.resnets.1.conv2.bias", "encoder.mid_block.attentions.0.group_norm.weight", "encoder.mid_block.attentions.0.group_norm.bias", "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight", "encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "encoder.mid_block.resnets.0.norm1.weight", "encoder.mid_block.resnets.0.norm1.bias", "encoder.mid_block.resnets.0.conv1.weight", "encoder.mid_block.resnets.0.conv1.bias", "encoder.mid_block.resnets.0.norm2.weight", "encoder.mid_block.resnets.0.norm2.bias", "encoder.mid_block.resnets.0.conv2.weight", "encoder.mid_block.resnets.0.conv2.bias", "encoder.mid_block.resnets.1.norm1.weight", "encoder.mid_block.resnets.1.norm1.bias", "encoder.mid_block.resnets.1.conv1.weight", "encoder.mid_block.resnets.1.conv1.bias", "encoder.mid_block.resnets.1.norm2.weight", "encoder.mid_block.resnets.1.norm2.bias", "encoder.mid_block.resnets.1.conv2.weight", "encoder.mid_block.resnets.1.conv2.bias", "encoder.conv_norm_out.weight", "encoder.conv_norm_out.bias", "encoder.conv_out.weight", "encoder.conv_out.bias", "decoder.conv_in.weight", "decoder.conv_in.bias", "decoder.up_blocks.0.resnets.0.norm1.weight", "decoder.up_blocks.0.resnets.0.norm1.bias", "decoder.up_blocks.0.resnets.0.conv1.weight", "decoder.up_blocks.0.resnets.0.conv1.bias", "decoder.up_blocks.0.resnets.0.norm2.weight", "decoder.up_blocks.0.resnets.0.norm2.bias", "decoder.up_blocks.0.resnets.0.conv2.weight", "decoder.up_blocks.0.resnets.0.conv2.bias", "decoder.up_blocks.0.resnets.1.norm1.weight", "decoder.up_blocks.0.resnets.1.norm1.bias", "decoder.up_blocks.0.resnets.1.conv1.weight", "decoder.up_blocks.0.resnets.1.conv1.bias", "decoder.up_blocks.0.resnets.1.norm2.weight", "decoder.up_blocks.0.resnets.1.norm2.bias", "decoder.up_blocks.0.resnets.1.conv2.weight", "decoder.up_blocks.0.resnets.1.conv2.bias", "decoder.up_blocks.0.resnets.2.norm1.weight", "decoder.up_blocks.0.resnets.2.norm1.bias", "decoder.up_blocks.0.resnets.2.conv1.weight", "decoder.up_blocks.0.resnets.2.conv1.bias", "decoder.up_blocks.0.resnets.2.norm2.weight", "decoder.up_blocks.0.resnets.2.norm2.bias", "decoder.up_blocks.0.resnets.2.conv2.weight", "decoder.up_blocks.0.resnets.2.conv2.bias", "decoder.up_blocks.0.upsamplers.0.conv.weight", "decoder.up_blocks.0.upsamplers.0.conv.bias", "decoder.up_blocks.1.resnets.0.norm1.weight", "decoder.up_blocks.1.resnets.0.norm1.bias", "decoder.up_blocks.1.resnets.0.conv1.weight", "decoder.up_blocks.1.resnets.0.conv1.bias", "decoder.up_blocks.1.resnets.0.norm2.weight", "decoder.up_blocks.1.resnets.0.norm2.bias", "decoder.up_blocks.1.resnets.0.conv2.weight", "decoder.up_blocks.1.resnets.0.conv2.bias", "decoder.up_blocks.1.resnets.1.norm1.weight", "decoder.up_blocks.1.resnets.1.norm1.bias", "decoder.up_blocks.1.resnets.1.conv1.weight", "decoder.up_blocks.1.resnets.1.conv1.bias", "decoder.up_blocks.1.resnets.1.norm2.weight", "decoder.up_blocks.1.resnets.1.norm2.bias", "decoder.up_blocks.1.resnets.1.conv2.weight", "decoder.up_blocks.1.resnets.1.conv2.bias", "decoder.up_blocks.1.resnets.2.norm1.weight", "decoder.up_blocks.1.resnets.2.norm1.bias", "decoder.up_blocks.1.resnets.2.conv1.weight", "decoder.up_blocks.1.resnets.2.conv1.bias", "decoder.up_blocks.1.resnets.2.norm2.weight", "decoder.up_blocks.1.resnets.2.norm2.bias", "decoder.up_blocks.1.resnets.2.conv2.weight", "decoder.up_blocks.1.resnets.2.conv2.bias", "decoder.up_blocks.1.upsamplers.0.conv.weight", "decoder.up_blocks.1.upsamplers.0.conv.bias", "decoder.up_blocks.2.resnets.0.norm1.weight", "decoder.up_blocks.2.resnets.0.norm1.bias", "decoder.up_blocks.2.resnets.0.conv1.weight", "decoder.up_blocks.2.resnets.0.conv1.bias", "decoder.up_blocks.2.resnets.0.norm2.weight", "decoder.up_blocks.2.resnets.0.norm2.bias", "decoder.up_blocks.2.resnets.0.conv2.weight", "decoder.up_blocks.2.resnets.0.conv2.bias", "decoder.up_blocks.2.resnets.0.conv_shortcut.weight", "decoder.up_blocks.2.resnets.0.conv_shortcut.bias", "decoder.up_blocks.2.resnets.1.norm1.weight", "decoder.up_blocks.2.resnets.1.norm1.bias", "decoder.up_blocks.2.resnets.1.conv1.weight", "decoder.up_blocks.2.resnets.1.conv1.bias", "decoder.up_blocks.2.resnets.1.norm2.weight", "decoder.up_blocks.2.resnets.1.norm2.bias", "decoder.up_blocks.2.resnets.1.conv2.weight", "decoder.up_blocks.2.resnets.1.conv2.bias", "decoder.up_blocks.2.resnets.2.norm1.weight", "decoder.up_blocks.2.resnets.2.norm1.bias", "decoder.up_blocks.2.resnets.2.conv1.weight", "decoder.up_blocks.2.resnets.2.conv1.bias", "decoder.up_blocks.2.resnets.2.norm2.weight", "decoder.up_blocks.2.resnets.2.norm2.bias", "decoder.up_blocks.2.resnets.2.conv2.weight", "decoder.up_blocks.2.resnets.2.conv2.bias", "decoder.up_blocks.2.upsamplers.0.conv.weight", "decoder.up_blocks.2.upsamplers.0.conv.bias", "decoder.up_blocks.3.resnets.0.norm1.weight", "decoder.up_blocks.3.resnets.0.norm1.bias", "decoder.up_blocks.3.resnets.0.conv1.weight", "decoder.up_blocks.3.resnets.0.conv1.bias", "decoder.up_blocks.3.resnets.0.norm2.weight", "decoder.up_blocks.3.resnets.0.norm2.bias", "decoder.up_blocks.3.resnets.0.conv2.weight", "decoder.up_blocks.3.resnets.0.conv2.bias", "decoder.up_blocks.3.resnets.0.conv_shortcut.weight", "decoder.up_blocks.3.resnets.0.conv_shortcut.bias", "decoder.up_blocks.3.resnets.1.norm1.weight", "decoder.up_blocks.3.resnets.1.norm1.bias", "decoder.up_blocks.3.resnets.1.conv1.weight", "decoder.up_blocks.3.resnets.1.conv1.bias", "decoder.up_blocks.3.resnets.1.norm2.weight", "decoder.up_blocks.3.resnets.1.norm2.bias", "decoder.up_blocks.3.resnets.1.conv2.weight", "decoder.up_blocks.3.resnets.1.conv2.bias", "decoder.up_blocks.3.resnets.2.norm1.weight", "decoder.up_blocks.3.resnets.2.norm1.bias", "decoder.up_blocks.3.resnets.2.conv1.weight", "decoder.up_blocks.3.resnets.2.conv1.bias", "decoder.up_blocks.3.resnets.2.norm2.weight", "decoder.up_blocks.3.resnets.2.norm2.bias", "decoder.up_blocks.3.resnets.2.conv2.weight", "decoder.up_blocks.3.resnets.2.conv2.bias", "decoder.mid_block.attentions.0.group_norm.weight", "decoder.mid_block.attentions.0.group_norm.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight", "decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.resnets.0.norm1.weight", "decoder.mid_block.resnets.0.norm1.bias", "decoder.mid_block.resnets.0.conv1.weight", "decoder.mid_block.resnets.0.conv1.bias", "decoder.mid_block.resnets.0.norm2.weight", "decoder.mid_block.resnets.0.norm2.bias", "decoder.mid_block.resnets.0.conv2.weight", "decoder.mid_block.resnets.0.conv2.bias", "decoder.mid_block.resnets.1.norm1.weight", "decoder.mid_block.resnets.1.norm1.bias", "decoder.mid_block.resnets.1.conv1.weight", "decoder.mid_block.resnets.1.conv1.bias", "decoder.mid_block.resnets.1.norm2.weight", "decoder.mid_block.resnets.1.norm2.bias", "decoder.mid_block.resnets.1.conv2.weight", "decoder.mid_block.resnets.1.conv2.bias", "decoder.conv_norm_out.weight", "decoder.conv_norm_out.bias", "decoder.conv_out.weight", "decoder.conv_out.bias".
```

### System Info

- Python Version 3.10.13
diffusers                 0.30.0.dev0
accelerate                0.33.0
torch                     2.4.0
torchao                   0.3.1
torchaudio                2.4.0
torchelastic              0.2.2
torchvision               0.19.0
transformers              4.43.4
triton                    3.0.0

### Who can help?

@sayakpaul  (I think u are the most appropriate user to ping as u wrote this script)

**Comment by sayakpaul** [comment]
Cc: @DN6 for the `vae`.

**Comment by mrrfr** [comment]
Hi Guys, sorry for the issue, it wasn't really a case ! 

After a clean installation, I realized the mistake was on my end.

For those looking into this issue, in my case, it wasn't a problem with Diffusers or the export script. I used the wrong file and expected an output. My bad, sorry guys!

Thank u anyway :)
Have nice night!
