### ISSUE TITLE
Auraflow inference error: The size of tensor a (264) must match the size of tensor b (4096) at non-singleton dimension 1

### ISSUE THREAD

**Issue by anushka0415** [huggingface/diffusers#9112]
### Describe the bug

I am using the auraflow piepline and keep getting the same error as described.

### Reproduction

`import os
import torch
from PIL import Image
from diffusers import AuraFlowPipeline

# Set the device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the model
model = AuraFlowPipeline.from_pretrained(
    "fal/AuraFlow-v0.2",
    torch_dtype=torch.float16,
    cache_dir='cache'
).to(device)

# Enable memory-efficient attention and model CPU offload
model.enable_xformers_memory_efficient_attention()
model.enable_model_cpu_offload()

# Define the prompt
prompt = "a beautiful landscape with mountains and a river during sunset"

# Generate the image
generator = torch.Generator().manual_seed(42)
image = model(
    prompt=prompt, 
    width=1024,
    height=1024,
    num_inference_steps=28, 
    generator=generator,
    guidance_scale=5.0
).images[0]`

### Logs

```shell
Traceback (most recent call last):
  File "/new-zpool/Vision/content-creation/anushka/auraflow.py", line 305, in <module>
    image = base(
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/diffusers/pipelines/aura_flow/pipeline_aura_flow.py", line 555, in __call__
    noise_pred = self.transformer(
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py", line 473, in forward
    encoder_hidden_states, hidden_states = block(
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/auraflow/lib/python3.8/site-packages/diffusers/models/transformers/auraflow_transformer_2d.py", line 232, in forward
    encoder_hidden_states = self.norm2_context(residual_context + c_gate_msa.unsqueeze(1) * context_attn_output)
RuntimeError: The size of tensor a (264) must match the size of tensor b (4096) at non-singleton dimension 1
```

### System Info

🤗 Diffusers version: 0.30.0.dev0  
Platform: Linux eaca9a07ef23 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Running on Google Colab?: No
Python version: 3.8
PyTorch version (GPU?):  2.2.0+cu118 
Huggingface_hub version: 0.23.4
Transformers version: 4.42.4
Accelerate version: 0.33.0
PEFT version: 0.7.0
Bitsandbytes version: 0.43.0
Safetensors version: 0.4.2
xFormers version: 0.0.24+cu118
Using GPU in script?: yes

**Comment by bghira** [comment]
it's probably xformers, which is really deprecated these days and could probably be ignored for most use cases

**Comment by anushka0415** [comment]
Thanks removing` model.enable_xformers_memory_efficient_attention()` made it work.
