### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by nannanmath** [huggingface/diffusers#9138]
### Describe the bug

I train controlnet by script `examples/train_controlnet.py` use the commad like:
```bash
export MODEL_DIR="runwayml/stable-diffusion-v1-5"
export DATA_DIR="/home/zhangnan/codes/diffusers/examples/controlnet/fill50k_bak"
export OUTPUT_DIR="./output"

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --train_data_dir=$DATA_DIR \
 --resolution=512 \
 --learning_rate=1e-5 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --train_batch_size=4
```
here, I have downloaded the dataset `fill50k` to local machine. 
When the model need to be saved, has an error:
```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/date1/zhangnan/codes/diffusers/examples/controlnet/train_controlnet.py", line 1192, in <module>
[rank0]:     main(args)
[rank0]:   File "/date1/zhangnan/codes/diffusers/examples/controlnet/train_controlnet.py", line 1128, in main
[rank0]:     accelerator.save_state(save_path)
[rank0]:   File "/date1/zhangnan/miniconda3/envs/diffusers2/lib/python3.9/site-packages/accelerate/accelerator.py", line 2987, in save_state
[rank0]:     hook(self._models, weights, output_dir)
[rank0]:   File "/date1/zhangnan/codes/diffusers/examples/controlnet/train_controlnet.py", line 843, in save_model_hook
[rank0]:     model.save_pretrained(os.path.join(output_dir, sub_dir))
[rank0]:   File "/date1/zhangnan/codes/diffusers/src/diffusers/models/modeling_utils.py", line 344, in save_pretrained
[rank0]:     state_dict_split = split_torch_state_dict_into_shards(
[rank0]:   File "/date1/zhangnan/miniconda3/envs/diffusers2/lib/python3.9/site-packages/huggingface_hub/serialization/_torch.py", line 86, in split_torch_state_dict_into_shards
[rank0]:     return split_state_dict_into_shards_factory(
[rank0]:   File "/date1/zhangnan/miniconda3/envs/diffusers2/lib/python3.9/site-packages/huggingface_hub/serialization/_base.py", line 117, in split_state_dict_into_shards_factory
[rank0]:     if tensor_size > max_shard_size:
[rank0]: TypeError: '>' not supported between instances of 'int' and 'str'
```
and I add some code in `huggingface_hub/serialization/_base.py` like:
line 114
```python
        # If this tensor is bigger than the maximal size, we put it in its own shard
        print(tensor_size)
        print(max_shard_size)
        if tensor_size > max_shard_size:
            total_size += tensor_size
            shard_list.append({key: tensor})
            continue
```
to print the `tensor_size` and `max_shard_size`, the output is:
```bash
46080
10GB
```
if that means an `int` wants to compare with a `str`.

### Reproduction

train controlnet by script `examples/train_controlnet.py` use the commad like:
```bash
export MODEL_DIR="runwayml/stable-diffusion-v1-5"
export DATA_DIR="/home/zhangnan/codes/diffusers/examples/controlnet/fill50k_bak"
export OUTPUT_DIR="./output"

accelerate launch train_controlnet.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --train_data_dir=$DATA_DIR \
 --resolution=512 \
 --learning_rate=1e-5 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --train_batch_size=4
```

### System Info

- 🤗 Diffusers version: 0.30.0.dev0
- Platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.9.19
- PyTorch version (GPU?): 2.3.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.1
- Transformers version: 4.44.0
- Accelerate version: 0.33.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.2
- xFormers version: not installed
- Accelerator: NVIDIA A800 80GB PCIe, 81920 MiB
NVIDIA A800 80GB PCIe, 81920 MiB
NVIDIA A800 80GB PCIe, 81920 MiB
NVIDIA A800 80GB PCIe, 81920 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Thanks for reporting. Could you update your local `huggingface_hub` installation?

**Comment by zyx1213271098** [comment]
i have the same problem

**Comment by BadSeedX** [comment]
> pip install -U transformers fix my problem

Thanks

**Comment by yiyixuxu** [comment]
I think this has been resolved?

**Comment by jiacongfang** [comment]
> pip install -U transformers fix my problem

Thanks!
