### ISSUE TITLE
Loading PT Files for VAE with the AutoEncoder is still broken!!!

### ISSUE THREAD

**Issue by JemiloII** [huggingface/diffusers#9154]
### Describe the bug

Just doesn't load pt files anymore. Really frustrating as it's been broken for a long time now. I keep posting about it, so now I'll just open a issue / bug instead of messaging in update threads. Last working version is 0.27.2

There is not a working safetensors or diffusers version of the VAE I'm using and I shouldn't have to. PT works just fine.

### Reproduction

        pipe = StableDiffusionPipeline.from_single_file(
            "./assets/models/AOM3B4_orangemixs.safetensors",
            safety_checker=None,
            requires_safety_checker=False,
            cache_dir=path.join("./assets/models"),
            local_files_only=True,
            torch_dtype=torch.bfloat16,
        )

        pipe = pipe.to(device, torch.bfloat16)

        pipe.vae = AutoencoderKL.from_single_file(
            path.join("./assets/vae/orangemix.vae.pt"),
            local_files_only=True,
            torch_dtype=torch.bfloat16
        )

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\models\model_loading_utils.py", line 108, in load_state_dict
    return torch.load(
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\torch\serialization.py", line 1024, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported class pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\models\model_loading_utils.py", line 116, in load_state_dict
    if f.read().startswith("version"):
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1681: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-test\main.py", line 89, in <module>
    asyncio.run(main(args.device, args.port))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-test\main.py", line 79, in main
    pipe, clip_layers = shibiko_init(settings, device)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-test\src\generation.py", line 126, in shibiko_init
    pipe.vae = AutoencoderKL.from_single_file(
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\loaders\single_file_model.py", line 209, in from_single_file
    checkpoint = load_single_file_checkpoint(
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 346, in load_single_file_checkpoint
    checkpoint = load_state_dict(pretrained_model_link_or_path)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\models\model_loading_utils.py", line 128, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for './assets/vae/orangemix.vae.pt' at './assets/vae/orangemix.vae.pt'.
```

### System Info

Python 3.10.9

AMD 7950X3D | AMD 5950X
RTX 4090 x2 | RTX 4090
128GB DDR5  | 128GB DDR4
Windows 10  | Windows 10

### Who can help?

@sayakpaul

**Comment by JemiloII** [comment]
Any VAE that's saved in a pt format

Link To VAE I'm Using
https://huggingface.co/WarriorMama777/OrangeMixs/blob/main/VAEs/orangemix.vae.pt

The diffuser version doesn't have VAE worker, nor do I want to use it.

**Comment by DN6** [comment]
Hi @JemiloII the issue here isn't the `pt` format. Rather that the checkpoint contains serialised objects that are not model weights. See attached screenshot below. 
<img width="1558" alt="Screenshot 2024-08-19 at 11 09 18 AM" src="https://github.com/user-attachments/assets/34c3f91d-57f4-4890-a5d0-9d18705bff82">

We switched to not allowing loading arbitrary serialised objects from pickle files after `0.27.2` since this is a potential security risk. Using `torch.load` with `weights_only=False` allows executing code on the users machine. See attached discussions:
https://github.com/pytorch/pytorch/issues/52181
https://github.com/pytorch/pytorch/issues/52596
https://github.com/voicepaw/so-vits-svc-fork/issues/193

You can load the VAE state dict with `weights_only=False` in the following way 
```python
import torch
from huggingface_hub import hf_hub_download
from diffusers import AutoencoderKL

state_dict = torch.load(hf_hub_download("WarriorMama777/OrangeMixs", filename="VAEs/orangemix.vae.pt"), weights_only=False)
vae = AutoencoderKL.from_single_file(state_dict)
```

**Comment by JemiloII** [comment]
That doesn't work.

```log
Traceback (most recent call last):
  File "C:\Users\Shibiko AI\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 138, in run
    return loop.run_until_complete(task)
  File "C:\Users\Shibiko AI\AppData\Roaming\JetBrains\IntelliJIdea2024.2\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 243, in run_until_complete
    return f.result()
  File "C:\Program Files\Python310\lib\asyncio\futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "C:\Program Files\Python310\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\main.py", line 81, in main
    pipe, clip_layers = shibiko_init(settings, device)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\src\generation.py", line 144, in shibiko_init
    pipe.vae = AutoencoderKL.from_single_file(state_dict)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\loaders\autoencoder.py", line 119, in from_single_file
    original_config, checkpoint = fetch_ldm_config_and_checkpoint(
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 314, in fetch_ldm_config_and_checkpoint
    checkpoint = load_single_file_model_checkpoint(
  File "C:\Users\Shibiko AI\Desktop\shibiko ai\diffusion-ai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 339, in load_single_file_model_checkpoint
    if os.path.isfile(pretrained_model_link_or_path):
  File "C:\Program Files\Python310\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not dict
python-BaseException

Process finished with exit code 1
```

I even tried with `pipe.vae.load_state_dict`. No dice there. I even went to try that on 0.27.2...

**Comment by JemiloII** [comment]
Not sure if this is helpful, but the state_dict has these keys.

[state_dict_keys.txt](https://github.com/user-attachments/files/16737986/state_dict_keys.txt)

**Comment by DN6** [comment]
Which version of diffusers are you using? The snippet I shared is meant to be run with the >0.27.2 version. Based on the  traceback it seems like you're using version 0.27.2 to try and load the state dict?

**Comment by JemiloII** [comment]
I tried with 0.27.2 and the latest release. The goal is to update to the latest, but the diffusers keeps making breaking changes. This PT one is crazy as many vsts for sd1.5 are in pt format and many i've found for sdxl are in that format as well.

When an update happens, I don't expect my production app to just break from making zero code changes. I don't use hub, but i even tried with your hub example. I don't like using the hub, just local files so i know nothing ever changes. hub will get updates. hub saves things in mysterious locations where you don't want model files anyways.

**Comment by Eduardishion** [comment]
No si esto te pueda ayudar, a mi me funciono, este nnotebook , convierte el archivo .pt to safetensors, para despues poder usar con normalidad la carga del VAE con la la funcion single_flle:```
 vae = AutoencoderKL.from_single_file(
          vae_name,
          torch_dtype=torch.float16,
         ).to(device)
```
 pipeline.vae = vaehttps://github.com/DiffusionDalmation/pt_to_safetensors_converter_notebook

**Comment by JemiloII** [comment]
I guess I'll have to convert this to not be a notebook and test it out.

**Comment by asomoza** [comment]
oh, I didn't think that would solve your problem since a lot of researchers and model owners still don't publish safetensors files. I can convert the ones you need if you want and helps you.

**Comment by DN6** [comment]
> I tried with 0.27.2 and the latest release. The goal is to update to the latest, but the diffusers keeps making breaking changes. This PT one is crazy as many vsts for sd1.5 are in pt format and many i've found for sdxl are in that format as well.

The issue is not with the `.pt` extension, but due to the fact that the checkpoints you are trying to load contain "non-weight" serialized objects. We do not allow loading pickle files that contain these objects anymore since it is a security risk. 

The snippet I shared is only an example of what to do if you have pickle files with such types of objects. You can replace the hub download part with a path to your local file. 

1. Use torch load to deserialize the checkpoint and then pass the `state_dict` directly to `from_single_file`.    
2. Convert the pickle file to a safetensors file and load it via single file as @Eduardishion suggested

**Comment by a-r-r-o-w** [comment]
Marking as closed due to inactivity, and because I think this was sufficiently addressed with solutions above. Please feel free to re-open if you still need help with this, or a new issue if we can assist with anything else :hugs:

**Comment by JemiloII** [comment]
that wasn't really a solution to convert things just to fit an overly opinionated design choice. but it doesn't really matter anymore, I've moved on from this project that enjoys to consistently make breaking changes.
