### ISSUE TITLE
--train-text-encoder in train_dreambooth.py yields type error 

### ISSUE THREAD

**Issue by MarkRich** [huggingface/diffusers#918]
### Describe the bug

specifying the --train_text_encoder flag in `train_dreambooth.py` yields an error: 

```
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
``` 

Removing the --train_text_encoder flag prevents the issue, so seems related to that? 

### Reproduction

accelerate launch train_dreambooth.py   --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"    --train_text_encoder   --instance_data_dir="<instance dir>"   --class_data_dir="<class_data_dir>"   --output_dir="/home/mark/projects/stable_diffusion/dreambooth/hf_dreambooth/output_model"   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="<instance prompt>"   --class_prompt="<instance prompt>"   --resolution=512   --train_batch_size=1 --train_text_encoder

### Logs

```shell
accelerate launch train_dreambooth.py   --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"    --train_text_encoder   --instance_data_dir="<photos_dir>"   --class_data_dir="<class_data_dir>"   --output_dir="<outdir>"   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="<prompt>"   --class_prompt="<class photo prompt>"   --resolution=512   --train_batch_size=1
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_cpu_threads_per_process` was set to `24` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
/usr/lib/python3/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /usr/lib/python3/dist-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
/usr/lib/python3/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /usr/lib/python3/dist-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
[2022-10-19 20:48:40,585] [INFO] [comm.py:633:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2022-10-19 20:48:51,632] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.7.3, git-hash=unknown, git-branch=unknown
/home/mark/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:418: UserWarning: torch.distributed.distributed_c10d._get_global_rank is deprecated please use torch.distributed.distributed_c10d.get_global_rank instead
  warnings.warn(
/home/mark/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:418: UserWarning: torch.distributed.distributed_c10d._get_global_rank is deprecated please use torch.distributed.distributed_c10d.get_global_rank instead
  warnings.warn(
[2022-10-19 20:48:52,705] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2022-10-19 20:48:52,705] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-10-19 20:48:52,705] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-10-19 20:48:52,725] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = {basic_optimizer.__class__.__name__}
[2022-10-19 20:48:52,725] [INFO] [utils.py:52:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'torch.optim.adamw.AdamW'>
[2022-10-19 20:48:52,725] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2022-10-19 20:48:52,725] [INFO] [stage_1_and_2.py:134:__init__] Reduce bucket size 500000000
[2022-10-19 20:48:52,725] [INFO] [stage_1_and_2.py:135:__init__] Allgather bucket size 500000000
[2022-10-19 20:48:52,725] [INFO] [stage_1_and_2.py:136:__init__] CPU Offload: True
[2022-10-19 20:48:52,725] [INFO] [stage_1_and_2.py:137:__init__] Round robin gradient partitioning: False
Using /home/mark/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Using /home/mark/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Emitting ninja build file /home/mark/.cache/torch_extensions/py38_cu116/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.3905336856842041 seconds
Loading extension module utils...
Time to load utils op: 0.40270566940307617 seconds
Rank: 1 partition count [2] and sizes[(491290722, False)]
Rank: 0 partition count [2] and sizes[(491290722, False)]
[2022-10-19 20:48:56,870] [INFO] [utils.py:827:see_memory_usage] Before initializing optimizer states
[2022-10-19 20:48:56,870] [INFO] [utils.py:828:see_memory_usage] MA 3.8 GB         Max_MA 3.8 GB         CA 4.16 GB         Max_CA 4 GB
[2022-10-19 20:48:56,870] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 16.04 GB, percent = 6.4%
Using /home/mark/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.0003247261047363281 seconds
[2022-10-19 20:49:02,264] [INFO] [utils.py:827:see_memory_usage] After initializing optimizer states
[2022-10-19 20:49:02,264] [INFO] [utils.py:828:see_memory_usage] MA 3.8 GB         Max_MA 3.8 GB         CA 4.16 GB         Max_CA 4 GB
[2022-10-19 20:49:02,264] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 27.16 GB, percent = 10.8%
[2022-10-19 20:49:02,264] [INFO] [stage_1_and_2.py:516:__init__] optimizer state initialized
[2022-10-19 20:49:02,325] [INFO] [utils.py:827:see_memory_usage] After initializing ZeRO optimizer
[2022-10-19 20:49:02,326] [INFO] [utils.py:828:see_memory_usage] MA 3.8 GB         Max_MA 3.8 GB         CA 4.16 GB         Max_CA 4 GB
[2022-10-19 20:49:02,326] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 27.16 GB, percent = 10.8%
[2022-10-19 20:49:02,326] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Final Optimizer = AdamW
[2022-10-19 20:49:02,326] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed using client LR scheduler
[2022-10-19 20:49:02,326] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2022-10-19 20:49:02,326] [INFO] [logging.py:68:log_dist] [Rank 0] step=0, skipped=0, lr=[5e-06], mom=[(0.9, 0.999)]
[2022-10-19 20:49:02,327] [INFO] [config.py:987:print] DeepSpeedEngine configuration:
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   amp_enabled .................. False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   amp_params ................... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": null,
    "exps_dir": null,
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   bfloat16_enabled ............. False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   checkpoint_tag_validation_enabled  True
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   checkpoint_tag_validation_fail  False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7f118c5eb520>
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   communication_data_type ...... None
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   curriculum_enabled ........... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   curriculum_params ............ False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   dataloader_drop_last ......... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   disable_allgather ............ False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   dump_state ................... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   dynamic_loss_scale_args ...... None
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_enabled ........... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_gas_boundary_resolution  1
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_layer_num ......... 0
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_max_iter .......... 100
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_stability ......... 1e-06
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_tol ............... 0.01
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   eigenvalue_verbose ........... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   elasticity_enabled ........... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   flops_profiler_config ........ {
    "enabled": false,
    "profile_step": 1,
    "module_depth": -1,
    "top_modules": 1,
    "detailed": true,
    "output_file": null
}
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   fp16_auto_cast ............... None
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   fp16_enabled ................. False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   fp16_master_weights_and_gradients  False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   global_rank .................. 0
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   gradient_accumulation_steps .. 1
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   gradient_clipping ............ 0.0
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   gradient_predivide_factor .... 1.0
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   initial_dynamic_scale ........ 4294967296
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   load_universal_checkpoint .... False
[2022-10-19 20:49:02,327] [INFO] [config.py:991:print]   loss_scale ................... 0
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   memory_breakdown ............. False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   monitor_config ............... <deepspeed.monitor.config.DeepSpeedMonitorConfig object at 0x7f118c5eb4c0>
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   nebula_config ................ {
    "enabled": false,
    "persistent_storage_path": null,
    "persistent_time_interval": 100,
    "num_of_version_in_retention": 2,
    "enable_nebula_load": true,
    "load_path": null
}
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   optimizer_legacy_fusion ...... False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   optimizer_name ............... None
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   optimizer_params ............. None
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   pld_enabled .................. False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   pld_params ................... False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   prescale_gradients ........... False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   scheduler_name ............... None
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   scheduler_params ............. None
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   sparse_attention ............. None
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   sparse_gradients_enabled ..... False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   steps_per_print .............. inf
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   train_batch_size ............. 2
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   train_micro_batch_size_per_gpu  1
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   wall_clock_breakdown ......... False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   world_size ................... 2
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   zero_allow_untested_optimizer  True
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   zero_config .................. stage=2 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500000000 allgather_partitions=True allgather_bucket_size=500000000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=DeepSpeedZeroOffloadParamConfig(device='cpu', nvme_path=None, buffer_count=5, buffer_size=100000000, max_in_cpu=1000000000, pin_memory=False) offload_optimizer=DeepSpeedZeroOffloadOptimizerConfig(device='cpu', nvme_path=None, buffer_count=4, pin_memory=False, pipeline=False, pipeline_read=False, pipeline_write=False, fast_init=False) sub_group_size=1000000000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50000000 param_persistence_threshold=100000 model_persistence_threshold=9223372036854775807 max_live_parameters=1000000000 max_reuse_distance=1000000000 gather_16bit_weights_on_model_save=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   zero_enabled ................. True
[2022-10-19 20:49:02,328] [INFO] [config.py:991:print]   zero_optimization_stage ...... 2
[2022-10-19 20:49:02,328] [INFO] [config.py:976:print_user_config]   json = {
    "train_batch_size": 2,
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 1,
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu"
        },
        "offload_param": {
            "device": "cpu"
        },
        "stage3_gather_16bit_weights_on_model_save": false
    },
    "steps_per_print": inf,
    "zero_allow_untested_optimizer": true
}
Using /home/mark/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
No modifications detected for re-loaded extension module utils, skipping build step...
Loading extension module utils...
Time to load utils op: 0.000209808349609375 seconds
Steps:   0%|                                                                                                                   | 0/1101 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 623, in <module>
    main()
  File "train_dreambooth.py", line 563, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 733, in forward
    return self.text_model(
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 636, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
Traceback (most recent call last):
  File "train_dreambooth.py", line 623, in <module>
    main()
  File "train_dreambooth.py", line 563, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 733, in forward
    return self.text_model(
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 636, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1357, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/mark/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
Steps:   0%|
```
```


### System Info

diffusers 0.6.0.

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by patil-suraj** [comment]
Hi thanks for the issue!

Seems like you are using `deepspeed` in the example. Note that `deepspeed` support is somewhat experimental and not well tested. At the moment the example doesn't seem to work with `deepspeed` when `--train_text_encoder` is `True`,  but should work fine without it, here's the command I used 


```bash
accelerate launch --use_deepspeed --zero_stage=2 --gradient_accumulation_steps=1 \
  --offload_param_device=cpu --offload_optimizer_device=cpu \
  ../diffusers/examples/dreambooth/train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=4 \
  --with_prior_preservation --num_class_images=400 --sample_batch_size=4 \
```

`--train_text_encoder` should work fine without deepspeed.

**Comment by MarkRich** [comment]
Ah, thank you @patil-suraj, that works!
