### ISSUE TITLE
Pipeline has no attribute '_execution_device'

### ISSUE THREAD

**Issue by choidaedae** [huggingface/diffusers#9180]
### Describe the bug

Hello, I implemented my own custom pipeline referring StableDiffusionPipeline (RepDiffusionPipeline), but there are some issues
I called "accelerator.prepare" properly, and mapped the models on device (with "to.(accelerator.device)")
But when I call pipeline and the '__call__' function is called, sometimes I met the error 
It is not only problem in using multi-gpu, it occurs when I use single gpu. 
For example, I defined my pipeline for my validation in training code like this: 
```python
val_pipe = RepDiffusionPipeline.from_pretrained(
                        "runwayml/stable-diffusion-v1-5",
                        unet=accelerator.unwrap_model(unet),
                        rep_encoder=accelerator.unwrap_model(rep_encoder),
                        vae=accelerator.unwrap_model(vae),
                        revision=None, variant=None, torch_dtype=weight_dtype, safety_checker=None
                    ).to(accelerator.device)
```
 then, when I called 'val_pipe' like this: 
```
model_pred = val_pipe(
                                        image = condition_original_image if args.val_mask_op else data["original_images"],
                                        representation = representation,
                                        prompt = "",
                                        num_inference_steps = 20,
                                        image_guidance_scale = 1.5,
                                        guidance_scale = scale,
                                        generator = generator
                                    ).images[0]
```                                    
                                    
At that time, the error "RepDiffusionPipeline has no attribute '_execution_device'" occurs. (Not always, just randomly)
How can I solve this issue, or what part of my code can be doubted and fixed?
Thank you for reading:)

### Reproduction

It occurs randomly, so there is no option to reproduce... 

But when I call the defined pipeline, it occurs randomly. 

### Logs

```shell
RepDiffusionPipeline has no attribute '_execution_device'
```

### System Info

I tried to test in various diffusers & python versions, but the problem still occurs. 
In now, I am running my code in diffusers 0.27.2, python 3.10.14. 

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.2+cu121 with CUDA 1201 (you have 2.2.2+cu118)
    Python  3.10.14 (you have 3.10.14)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.27.2
- Platform: Linux-5.4.0-132-generic-x86_64-with-glibc2.31
- Python version: 3.10.14
- PyTorch version (GPU?): 2.2.2+cu118 (True)
- Huggingface_hub version: 0.24.3
- Transformers version: 4.43.3
- Accelerate version: 0.33.0
- xFormers version: 0.0.25.post1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @yiyixuxu

**Comment by yiyixuxu** [comment]
hi @choidaedae 

would you be able to provide a minimum reproducible code example? i.e. a script I can run on my end to get the same error that you're getting? 

it would really help us understand the problem :)

**Comment by choidaedae** [comment]
hi @yiyixuxu 
Thanks for replying.
It occurs when I validate with my customized pipeline, in training code of my private repos.
Can I invite you to my private repository and can you run the code? 
If it can, I'll clean the code and data to run it easily and invite you.
Thanks :)

**Comment by LinB203** [comment]
same question.

**Comment by MuQY1818** [comment]
Same question

**Comment by yiyixuxu** [comment]
@LinB203 @MuQY1818 
a minimum reproducible code example to help me understand the problem will be appreciated!

**Comment by luyvlei** [comment]
I had a similar problem, and it happened randomly so it was hard to reproduce, and I have now abandoned this attribute

**Comment by asomoza** [comment]
so can we assume this issue is resolved? OP also didn't provide any code to reproduce the error.

**Comment by choidaedae** [comment]
I am sorry for not providing any code, but it occurs randomly and actually I'm not working with this pipeline now, so I can't provide it. 

If anyone still has this problem, providing the code can be userful for huggingface.
I will let you know if a similar error occurs again later. 

Thank you for your hard work : )

**Comment by yiyixuxu** [comment]
think we can try to catch the exception for that property - so maybe in the future it happens we will have some visibility into the problem

**Comment by Lum1104** [comment]
Same problem. This bug will disappear if I run it again.

**Comment by myendless1** [comment]
Same problem, occurs randomly.

**Comment by Arlaz** [comment]
Same problem, occurs about half of the time with the same script

**Comment by sayakpaul** [comment]
Again, having a minimal reproducible snippet would be really amazing!

**Comment by a-r-r-o-w** [comment]
I am re-opening this due to 3 comments in two weeks because it seems like a legitimate problem now.

Could any of you please provide a minimal script for what you're trying that causes this error? I don't see enough information here to be able to start debugging. If it happens on a single GPU as well, as mentioned above, I think it is safe to rule out race conditions, but maybe not since there is mentions that it happens randomly. It would also be nice if you could check with latest diffusers release

**Comment by yiyixuxu** [comment]
@a-r-r-o-w, see ,my comment here https://github.com/huggingface/diffusers/issues/9180#issuecomment-2383793559
let's catch the exception so that they can report back

**Comment by sayakpaul** [comment]
Thank you so much!

> PS: If you have a tip for constructing pooled_prompt_embeds, I'll happily take it (can also be a zero-weight T5 if need be). :)

You can compute the text embeddings needed to run the `FluxPipeline` like so:

```py
from diffusers import FluxPipeline
import torch 

ckpt_id = "black-forest-labs/FLUX.1-dev"
prompt = "a photo of a dog with cat-like look"

pipeline = FluxPipeline.from_pretrained(
    ckpt_id,
    vae=None,
    torch_type=torch.bfloat16
).to("cuda")

with torch.no_grad():
    print("Encoding prompts.")
    prompt_embeds, pooled_prompt_embeds, text_ids = pipeline.encode_prompt(
        prompt=prompt, prompt_2=None, max_sequence_length=512
    )
```

Does this help?

**Comment by HilaManor** [comment]
for me it happens as well, but even simpler,
```python
pipe = StableDiffusionPipeline.from_pretrained(..)
print(pipe.dtype)
```
sometimes work, and sometimes `AttributeError: 'StableDiffusionPipeline' object has no attribute 'dtype'`.

Only as part of a script and not in iPython, for example. I think it's related maybe to accelerate and offloading?

**Comment by asomoza** [comment]
@HilaManor Hi, that example code is too simple, I can execute that 100 times and all 100 times it will work for me, probably there's something in your env that it's making this to happen.

IMO this should be treated as an issue or bug if it happens with our pipelines and code, if someone is using part of it or doing a custom pipeline, this error probably means that there's something wrong in the code or the environment, but it would be ideal to also properly catch it and give a better explanation of the error.

**Comment by HilaManor** [comment]
It occurs randomly, so I think it's a race condition. When I captured that and tried to debug this it disappeared, that's part of the reason I think it's a race thing..

**Comment by asomoza** [comment]
if that would be the case it should happen at least once for me in a 100 times experiment no? What I mean is that we probably need more data about what you're doing, for example, your environment and hardware.

**Comment by HilaManor** [comment]
@asomoza it happened on 5 different computers, which have 3 different types of GPUs (an A6000 server, an 2080Ti server and on a personal computer, a 3090Ti on a personal computer), with different CPUs and generally different hardware, 

The env is roughly the same (up to the fact that the nvidia drivers is different on each server) (below). Please let me know what more info could help.
```
Package                   Version              Editable project location
------------------------- -------------------- --------------------------------------
absl-py                   2.1.0
accelerate                1.1.1
addict                    2.4.0
aiohappyeyeballs          2.4.3
aiohttp                   3.10.10
aiosignal                 1.3.1
anyio                     4.6.2.post1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
av                        13.1.0
babel                     2.16.0
basicsr                   1.4.2
bcrypt                    4.2.1
beautifulsoup4            4.12.3
bitsandbytes              0.45.0
bleach                    6.2.0
boto3                     1.35.82
botocore                  1.35.82
certifi                   2024.8.30
cffi                      1.17.1
cfgv                      3.4.0
charset-normalizer        3.4.0
click                     8.1.7
cmake                     3.31.2
colorama                  0.4.6
comm                      0.2.2
compressai                1.2.6
contourpy                 1.3.0
cryptography              44.0.0
cycler                    0.12.1
dctorch                   0.1.2
debugpy                   1.8.8
decorator                 5.1.1
defusedxml                0.7.1
diffusers                 0.31.0
distlib                   0.3.9
DISTS-pytorch             0.1
docker-pycreds            0.4.0
einops                    0.8.0
executing                 2.1.0
facexlib                  0.3.0
fastcore                  1.7.19
fastjsonschema            2.21.1
filelock                  3.16.1
filterpy                  1.4.5
fonttools                 4.54.1
fqdn                      1.5.1
frozenlist                1.5.0
fsspec                    2024.10.0
ftfy                      6.3.1
future                    1.0.0
fvcore                    0.1.5.post20221221
gitdb                     4.0.11
GitPython                 3.1.43
grpcio                    1.67.1
h11                       0.14.0
httpcore                  1.0.7
httpx                     0.28.0
huggingface-hub           0.26.2
icecream                  2.1.3
identify                  2.6.4
idna                      3.10
imageio                   2.36.0
importlib_metadata        8.5.0
iniconfig                 2.0.0
inquirerpy                0.3.4
iopath                    0.1.10
ipykernel                 6.29.5
ipython                   8.29.0
isoduration               20.11.0
jedi                      0.19.2
Jinja2                    3.1.4
jmespath                  1.0.1
json5                     0.10.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.3.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
keyboard                  0.13.5
kiwisolver                1.4.7
lazy_loader               0.4
lightning                 2.4.0
lightning-utilities       0.11.8
llvmlite                  0.43.0
lmdb                      1.5.1
lovely-numpy              0.2.13
lovely-tensors            0.1.17
lpips                     0.1.4
Markdown                  3.7
MarkupSafe                3.0.2
matplotlib                3.9.2
matplotlib-inline         0.1.7
mistune                   3.0.2
mpmath                    1.3.0
multidict                 6.1.0
natten                    0.17.3+torch250cu121
nbclient                  0.10.1
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.4.2
neuralcompression         0.3.0
nodeenv                   1.9.1
notebook                  7.3.1
notebook_shim             0.2.4
numba                     0.60.0
numpy                     1.26.4
nvidia-cublas-cu12        12.4.5.8
nvidia-cuda-cupti-cu12    12.4.127
nvidia-cuda-nvrtc-cu12    12.4.127
nvidia-cuda-runtime-cu12  12.4.127
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.2.1.3
nvidia-curand-cu12        10.3.5.147
nvidia-cusolver-cu12      11.6.1.9
nvidia-cusparse-cu12      12.3.1.170
nvidia-nccl-cu12          2.21.5
nvidia-nvjitlink-cu12     12.4.127
nvidia-nvtx-cu12          12.4.127
openai-clip               1.0.1
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
overrides                 7.7.0
packaging                 24.2
pandas                    2.2.3
pandocfilters             1.5.1
parameterized             0.9.0
paramiko                  3.5.0
parso                     0.8.4
pexpect                   4.9.0
pfzy                      0.3.4
pillow                    11.0.0
pip                       24.0
piq                       0.8.0
platformdirs              4.3.6
pluggy                    1.5.0
portalocker               3.0.0
pre_commit                4.0.1
prometheus_client         0.21.1
prompt_toolkit            3.0.48
propcache                 0.2.0
protobuf                  5.28.3
psutil                    6.1.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pycparser                 2.22
Pygments                  2.18.0
pyiqa                     0.1.13
PyNaCl                    1.5.0
pyparsing                 3.2.0
pytest                    8.3.4
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytorch-lightning         2.4.0
pytorch-msssim            1.0.0
pytorchvideo              0.1.5
pytz                      2024.2
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.35.1
regex                     2024.11.6
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.22.3
s3transfer                0.10.4
safetensors               0.4.5
scikit-image              0.24.0
scipy                     1.14.1
seaborn                   0.13.2
Send2Trash                1.8.3
sentencepiece             0.2.0
sentry-sdk                2.18.0
setproctitle              1.3.3
setuptools                75.3.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.6
stack-data                0.6.3
sympy                     1.13.1
tabulate                  0.9.0
tb-nightly                2.19.0a20241112
tensorboard               2.18.0
tensorboard-data-server   0.7.2
termcolor                 2.5.0
terminado                 0.18.1
tifffile                  2024.9.20
timm                      1.0.11
tinycss2                  1.4.0
tokenizers                0.15.2
tomli                     2.1.0
torch                     2.5.1
torch-ema                 0.3
torch_fidelity            0.4.0b0              
torch-geometric           2.6.1
torchmetrics              1.5.2
torchvision               0.20.1
tornado                   6.4.1
tqdm                      4.67.0
traitlets                 5.14.3
transformers              4.37.2
triton                    3.1.0
types-python-dateutil     2.9.0.20241003
typing_extensions         4.12.2
tzdata                    2024.2
uri-template              1.3.0
urllib3                   2.2.3
virtualenv                20.28.1
wandb                     0.18.6
wcwidth                   0.2.13
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.1.3
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.17.1
zipp                      3.21.0
```

**Comment by asomoza** [comment]
thanks for the detailed answer, just to be clear, you are getting `Pipeline has no attribute '_execution_device'`  with just this code:

```python
pipe = StableDiffusionPipeline.from_pretrained(..)
print(pipe.dtype)
```

Ideally we should have a fully reproducible code snipper that gives the error all the time, since you're saying this is random, I'll try to use an AWS instance to test this for a longer time. 

As I told you, I constantly use diffusers (hundreds of times a day) with linux and windows, with a 3090, A100 and a mobile 4090 and never, not once, I had this error, so it seems this is going to be a really hard bug to catch.

**Comment by HilaManor** [comment]
Clarifying - for the code you wrote I get `AttributeError: 'StableDiffusionPipeline' object has no attribute 'dtype'.`, and not an execution device bug.
I found that instead, `pipe.model.dtype` **always** works for me. 
So I think what happens is that for both attributes, there's some race condition from the loading of the model and when the model's attributes are loaded into the pipeline object. I have no idea if this is easily fixable.

**Comment by asomoza** [comment]
oh, I look at a lot of issues so I usually go by the title of the issue, that's why is not a good idea to use another issue to add yours. Probably this should go in a new one since it's totally unrelated to the one from this discussion.

What happens to you it's even more weird, since the `dtype` is just a [property of the pipeline](https://github.com/huggingface/diffusers/blob/1ae9b0595f28df9cc92df87cf49193ec8ca07245/src/diffusers/pipelines/pipeline_utils.py#L500) and it returns `torch.float32` by default, so there's something else happening here. There's no race condition here.

You're using just plain unmodified diffusers for this right?

You seem to have solved it anyway but if you want to keep digging into this, please open a new issue with your problem and also we don't need the full library list of your environment, you can just use `diffusers-cli env` and post the output, that gives us all the information we need.

**Comment by mirix** [comment]
Intriguing. The bug is still present today but, for me, only with LoRAs. And it happens half of the times with exactly the same script.

**Comment by hosjiu1702** [comment]
confirm

**Comment by asomoza** [comment]
Hi, in case this is not that clear yet, we don't need a confirmation or "I have the same problem", what we need to be able to help you is a snippet of code that reproduces the error, also we can't support custom pipelines or custom code because we don't have the bandwidth, so this needs to be with just diffusers code.

Sadly this is something than never happens to us or the majority of the people using diffusers, so we need your help to be able to help you.

**Comment by mashrurmorshed** [comment]
This happened to me when I was trying to trick diffuser's DDIMPipeline into working with a non-diffusers diffusion model (a bit unrelated to OP's original use case, but it may still be useful to someone).

The findings is that the `_execution_device` is available when if whatever model you are passing has a .device attribute (the device is set when `register_modules` is called in `__init__` in the pipeline). Minimal reproducible example:

```python
import torch
import diffusers

class DummyNoDevice(torch.nn.Module):
    def __init__(self):
        super().__init__()
   
    def forward(self, sample, timestep):
        return (sample,)

class DummyWithDevice(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
   
    def forward(self, sample, timestep):
        return (sample,)

noise_scheduler = diffusers.DDPMScheduler(1000)
pipe_no_device = diffusers.DDIMPipeline(unet=DummyNoDevice(), scheduler=noise_scheduler)
pipe_with_device = diffusers.DDIMPipeline(unet=DummyWithDevice(), scheduler=noise_scheduler)

try:
    print(f"Success: W/ device: {pipe_with_device._execution_device}")
except Exception as e:
    print(f"Failed: W/ device: {e}")

try:
    print(f"Success: no device: {pipe_no_device._execution_device}")
except Exception as e:
    print(f"Failed: no device: {e}")
```

Result: (diffusers 0.32.2)
```
Success: W/ device: cuda:0
Failed: no device: 'DDIMPipeline' object has no attribute '_execution_device'
```

**Comment by asomoza** [comment]
thanks a lot @mashrurmorshed 

@yiyixuxu wee have a reproducible snippet of code now

**Comment by SPronav** [comment]
Same problem as @mashrurmorshed when trying to use a non-diffusers diffusion model with DDIMPipeline. Adding a `device` attribute worked for me in the meantime. Thanks!
Then I have to add other attributes like `dtype` to resolve other errors to work with DDIMPipeline.

**Comment by sayakpaul** [comment]
Okay as characterized in https://github.com/huggingface/diffusers/issues/9180#issuecomment-2762289919, this happens when working with custom stuff where we may not have any control so, I would say this is kinda expected. 

When using custom models into a `DiffusionPipeline` class, maybe making the custom model inherit from `ModelMixin` solves the issue?

**Comment by GXYM** [comment]
so， this problem was solved ?

**Comment by jinjianzhao** [comment]
```python
import torch
import diffusers

class DummyNoDevice(torch.nn.Module):
    def __init__(self):
        super().__init__()
   
    def forward(self, sample, timestep):
        return (sample,)

class DummyWithDevice(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
   
    def forward(self, sample, timestep):
        return (sample,)

class RobustDDIMPipeline(diffusers.DDIMPipeline):
    @property
    def device(self) -> torch.device:
        r"""
        Returns:
            `torch.device`: The torch device on which the pipeline is located.
        """
        module_names, _ = self._get_signature_keys(self)
        modules = [getattr(self, n, None) for n in module_names]
        modules = [m for m in modules if isinstance(m, torch.nn.Module)]
        modules = [m for m in modules if hasattr(m, "device")]

        for module in modules:
            return module.device

        return torch.device("cpu")

        
        
noise_scheduler = diffusers.DDPMScheduler(1000)
pipe_no_device = diffusers.DDIMPipeline(unet=DummyNoDevice(), scheduler=noise_scheduler)
pipe_with_device = diffusers.DDIMPipeline(unet=DummyWithDevice(), scheduler=noise_scheduler)
robust_pipe_no_device = RobustDDIMPipeline(unet=DummyNoDevice(), scheduler=noise_scheduler)
robust_pipe_with_device = RobustDDIMPipeline(unet=DummyWithDevice(), scheduler=noise_scheduler)

try:
    print(f"Success: W/ device: {pipe_with_device._execution_device}")
except Exception as e:
    print(f"Failed: W/ device: {e}")

try:
    print(f"Success: no device: {pipe_no_device._execution_device}")
except Exception as e:
    print(f"Failed: no device: {e}")
    
try:
    print(f"Success: Robust W/ device: {robust_pipe_with_device._execution_device}")
except Exception as e:
    print(f"Failed: Robust W/ device: {e}")

try:
    print(f"Success: Robust no device: {robust_pipe_no_device._execution_device}")
except Exception as e:
    print(f"Failed: Robust no device: {e}")
```

follow https://github.com/huggingface/diffusers/issues/9180#issuecomment-2762289919, Another robust solution for cases where you’re unsure which module lacks a defined device is to override the pipeline’s device property with a custom implementation that explicitly resolves the execution device.


```txt
Success: W/ device: cuda:0
Failed: no device: 'DDIMPipeline' object has no attribute '_execution_device'
Success: Robust W/ device: cuda:0
Success: Robust no device: cpu
```

**Comment by ErenAta16** [comment]
The piece that has never been stated in this thread is *why* the message says `_execution_device`. It is not the error that was actually raised. `_execution_device` exists on the class; the AttributeError you see is a second one that erases the first.

The chain, on `main`:

1. `DiffusionPipeline._execution_device` ([pipeline_utils.py#L1144](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pipeline_utils.py#L1144)) ends in `return self.device`.
2. `DiffusionPipeline.device` ([pipeline_utils.py#L601](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pipeline_utils.py#L601)) does `return module.device` on the first `torch.nn.Module` among the signature keys. A bare `nn.Module` has no `device`, so `nn.Module.__getattr__` raises `AttributeError: 'DummyNoDevice' object has no attribute 'device'`.
3. CPython treats an `AttributeError` raised *inside* a property getter as "attribute not found" and falls through to `type(obj).__getattr__`.
4. `ConfigMixin.__getattr__` ([configuration_utils.py#L159-L175](https://github.com/huggingface/diffusers/blob/main/src/diffusers/configuration_utils.py#L159-L175)) ends with `raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")`. Because the interpreter clears the pending exception before calling `__getattr__`, there is no `__context__` and no "During handling of the above exception" section. The real error is gone.

diffusers 0.39.0 / torch 2.13.0, using @mashrurmorshed's model:

```python
import torch, diffusers, traceback
class DummyNoDevice(torch.nn.Module):
    def forward(self, sample, timestep): return (sample,)

pipe = diffusers.DDIMPipeline(unet=DummyNoDevice(), scheduler=diffusers.DDPMScheduler(1000))
try:
    pipe._execution_device
except AttributeError:
    traceback.print_exc()

print(diffusers.DiffusionPipeline.device.fget(pipe))   # bypass __getattr__
```

```
Traceback (most recent call last):
  File "/tmp/df_repro.py", line 11, in <module>
    pipe._execution_device
  File "/tmp/dfenv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 176, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DDIMPipeline' object has no attribute '_execution_device'

--- the error that was actually raised, unmasked ---
AttributeError: 'DummyNoDevice' object has no attribute 'device'
```

Note the traceback frames: the only diffusers frame is `__getattr__`. Nothing points at `pipeline_utils.py`. That is why this thread has run for two years with people guessing at accelerate, multi-GPU, and `from_pretrained`, none of which are involved.

This also explains the reported fixes. `ModelMixin` defines a `device` property, so a custom model that inherits it satisfies step 2 (@sayakpaul's suggestion), as does setting `self.device` manually (@SPronav), as does overriding `device` (@GXYM). And @SPronav's "then I had to add `dtype` too" is the same bug one property over: `DiffusionPipeline.dtype` ([L616](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/pipeline_utils.py#L616)) does `return module.dtype` and gets masked identically.

The masking is not specific to pipelines. `ConfigMixin` is a base of models and schedulers too, so *any* `AttributeError` raised inside *any* property on those classes gets reported as "object has no attribute `<that property>`".

A contained fix is to stop `__getattr__` from swallowing errors raised by descriptors that do exist. Re-invoking the descriptor is enough, since `__getattr__` is only reached after normal lookup already failed:

```python
def __getattr__(self, name: str) -> Any:
    is_in_config = "_internal_dict" in self.__dict__ and hasattr(self.__dict__["_internal_dict"], name)
    is_attribute = name in self.__dict__

    if is_in_config and not is_attribute:
        ...
        return self._internal_dict[name]

    # `name` resolves to a descriptor on the class: the AttributeError came from inside
    # it, not from the attribute being absent. Re-invoke so the real error surfaces.
    for klass in type(self).__mro__:
        if name in klass.__dict__ and hasattr(klass.__dict__[name], "__get__"):
            return klass.__dict__[name].__get__(self, type(self))

    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
```

With that patch applied to the same repro:

```
Traceback (most recent call last):
  File "/tmp/df_fix.py", line 21, in <module>
    pipe._execution_device
  File "/tmp/dfenv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1171, in _execution_device
    return self.device
  File "/tmp/dfenv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 598, in device
    return module.device
  File "/tmp/dfenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1967, in __getattr__
    raise AttributeError(
AttributeError: 'DummyNoDevice' object has no attribute 'device'

missing-attribute path still works -> 'DDIMPipeline' object has no attribute 'not_a_real_attribute'
config passthrough -> 1000
```

Genuinely missing attributes and the deprecated config passthrough both still behave as before.

Orthogonal to that, `DiffusionPipeline.device` and `.dtype` could stop assuming every `nn.Module` component exposes `.device`, e.g. fall back to `next(module.parameters()).device` (which is what `ModelMixin` does) or skip components that do not have one. Either change alone would fix this specific report; the `__getattr__` change is what stops the next one from being this hard to diagnose.

---
*Disclosure: I used Claude Code to help investigate and draft this comment. Both tracebacks above are real output from diffusers 0.39.0 with torch 2.13.0+cpu, and the source references were checked against `main`.*
