### ISSUE TITLE
 We couldn't connect to '"https://hf-mirror.com"' to load this model

### ISSUE THREAD

**Issue by SoumyaMB10** [huggingface/diffusers#9209]
### Describe the bug

env: MODEL_NAME="runwayml/stable-diffusion-v1-5"
env: DATASET_NAME="/content/drive/MyDrive/Newfolder"
env: HF_ENDPOINT="https://hf-mirror.com/"
env: TRANSFORMERS_OFFLINE=0
2024-08-17 19:12:18.804427: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-17 19:12:18.846567: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-17 19:12:18.855525: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-17 19:12:21.306784: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
08/17/2024 19:12:24 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: bf16

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '"runwayml/stable-diffusion-v1-5"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/train_text_to_image_lora.py", line 979, in <module>
    main()
  File "/content/train_text_to_image_lora.py", line 492, in main
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to '"https://hf-mirror.com/"' to load this model, couldn't find it in the cached files and it looks like "runwayml/stable-diffusion-v1-5" is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"', '--dataset_name="/content/drive/MyDrive/Newfolder"', '--dataloader_num_workers=8', '--resolution=512', '--center_crop', '--random_flip', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--max_train_steps=15000', '--learning_rate=1e-04', '--max_grad_norm=1', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--checkpointing_steps=500', '--caption_column=en_text', '--validation_prompt=forward trajectory.', '--seed=1337']' returned non-zero exit status 1.

### Reproduction

%env MODEL_NAME="runwayml/stable-diffusion-v1-5"
%env DATASET_NAME="/content/drive/MyDrive/Newfolder"
%env HF_ENDPOINT="https://hf-mirror.com"
%env TRANSFORMERS_OFFLINE=0

!accelerate launch --mixed_precision="bf16"  train_text_to_image_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME \
  --dataloader_num_workers=8 \
  --resolution=512 \
  --center_crop \
  --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=15000 \
  --learning_rate=1e-04 \
  --max_grad_norm=1 \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=0 \
  --checkpointing_steps=500 \
  --caption_column="en_text" \
  --validation_prompt="forward trajectory." \
  --seed=1337

### System Info

- 🤗 Diffusers version: 0.31.0.dev0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Running on Google Colab?: Yes
- Python version: 3.10.12
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Huggingface_hub version: 0.23.5
- Transformers version: 4.42.4
- Accelerate version: 0.32.1
- PEFT version: 0.7.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.4
- xFormers version: not installed
- Accelerator: Tesla T4, 15360 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul  
1. how to fix the above issue i tried all possible solutions 
2. also there is a package conflicts ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 17.0.0 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 17.0.0 which is incompatible.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 2.21.0 requires pyarrow>=15.0.0, but you have pyarrow 14.0.1 which is incompatible. 
not sure if this is causing the error

**Comment by tolgacangoz** [comment]
Could you try with this env variable:
```sh
%env HF_ENDPOINT=https://hf-mirror.com
```

**Comment by SoumyaMB10** [comment]
same error 

env: MODEL_NAME="runwayml/stable-diffusion-v1-5"
env: INSTANCE_DIR="/content/drive/MyDrive/Newfolder"
env: HF_ENDPOINT=https://hf-mirror.com/
2024-08-18 07:38:39.034668: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-18 07:38:39.054017: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-18 07:38:39.059988: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-18 07:38:40.196960: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
08/18/2024 07:38:41 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '"runwayml/stable-diffusion-v1-5"'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/train_text_to_image_lora.py", line 979, in <module>
    main()
  File "/content/train_text_to_image_lora.py", line 492, in main
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://hf-mirror.com/' to load this model, couldn't find it in the cached files and it looks like "runwayml/stable-diffusion-v1-5" is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 703, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_text_to_image_lora.py', '--pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"', '--dataset_name="/content/drive/MyDrive/Newfolder"', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--checkpointing_steps=100', '--learning_rate=1e-4', '--report_to=wandb', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=500', '--validation_prompt=forward trajectory', '--validation_epochs=50', '--seed=0', '--push_to_hub']' returned non-zero exit status 1.

**Comment by tolgacangoz** [comment]
OK, try this:
```py
%env MODEL_NAME=runwayml/stable-diffusion-v1-5
%env DATASET_NAME=/content/drive/MyDrive/Newfolder
%env HF_ENDPOINT=https://hf-mirror.com
```
`"` is the problem :/

**Comment by tolgacangoz** [comment]
Remove all the `"` from the environment variables. This causes the problem :/

**Comment by SoumyaMB10** [comment]
different error now 

env: MODEL_NAME=runwayml/stable-diffusion-v1-5
env: INSTANCE_DIR=/content/drive/MyDrive/Newfolder
env: HF_ENDPOINT=https://hf-mirror.com/
2024-08-18 08:37:58.361447: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-18 08:37:58.394200: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-18 08:37:58.404395: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-18 08:38:00.068958: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
08/18/2024 08:38:01 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

scheduler/scheduler_config.json: 100% 308/308 [00:00<00:00, 1.99MB/s]
{'rescale_betas_zero_snr', 'dynamic_thresholding_ratio', 'thresholding', 'clip_sample_range', 'variance_type', 'sample_max_value', 'prediction_type', 'timestep_spacing'} was not found in config. Values will be initialized to default values.
tokenizer/tokenizer_config.json: 806B [00:00, 3.98MB/s]       
tokenizer/vocab.json: 1.06MB [00:00, 2.14MB/s]
tokenizer/merges.txt: 525kB [00:00, 1.63MB/s]
tokenizer/special_tokens_map.json: 100% 472/472 [00:00<00:00, 2.81MB/s]
text_encoder/config.json: 617B [00:00, 3.82MB/s]       
model.safetensors: 100% 492M/492M [00:03<00:00, 146MB/s]
vae/config.json: 547B [00:00, 2.55MB/s]       
diffusion_pytorch_model.safetensors: 100% 335M/335M [00:02<00:00, 112MB/s]
{'mid_block_add_attention', 'latents_std', 'scaling_factor', 'force_upcast', 'use_quant_conv', 'latents_mean', 'use_post_quant_conv', 'shift_factor'} was not found in config. Values will be initialized to default values.
unet/config.json: 743B [00:00, 3.76MB/s]       
diffusion_pytorch_model.safetensors: 100% 3.44G/3.44G [00:34<00:00, 99.5MB/s]
{'class_embed_type', 'addition_time_embed_dim', 'num_attention_heads', 'time_cond_proj_dim', 'conv_in_kernel', 'class_embeddings_concat', 'timestep_post_act', 'dual_cross_attention', 'resnet_skip_time_act', 'transformer_layers_per_block', 'mid_block_type', 'attention_type', 'only_cross_attention', 'upcast_attention', 'resnet_out_scale_factor', 'mid_block_only_cross_attention', 'addition_embed_type', 'conv_out_kernel', 'time_embedding_act_fn', 'cross_attention_norm', 'time_embedding_dim', 'dropout', 'projection_class_embeddings_input_dim', 'encoder_hid_dim_type', 'encoder_hid_dim', 'num_class_embeds', 'addition_embed_type_num_heads', 'use_linear_projection', 'resnet_time_scale_shift', 'reverse_transformer_layers_per_block', 'time_embedding_type'} was not found in config. Values will be initialized to default values.
Resolving data files: 100% 18/18 [00:00<00:00, 106184.91it/s]
Generating train split: 9 examples [00:00, 92.24 examples/s]
Traceback (most recent call last):
  File "/content/train_text_to_image_lora.py", line 979, in <module>
    main()
  File "/content/train_text_to_image_lora.py", line 625, in main
    raise ValueError(
ValueError: --image_column' value 'image' needs to be one of: text
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main

**Comment by tolgacangoz** [comment]
OK, now this issue is resolved. Could you open another issue for the last error?

**Comment by SoumyaMB10** [comment]
okay will do

**Comment by SoumyaMB10** [comment]
https://github.com/huggingface/diffusers/issues/9210 new issue
