### ISSUE TITLE
TypeError: couldn't find storage object Float8_e4m3fnStorage

### ISSUE THREAD

**Issue by maxin9966** [huggingface/diffusers#9293]
### Describe the bug

latest version of diffusers
torch Version: 2.4.0+cu124    OR   Version: 2.3.1
transformers Version: 4.44.2
3090 CUDA Version: 12.5

## Error:
Traceback (most recent call last):
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-hyper.py", line 552, in gen
    img_path, image = gen_with_api(prompt, steps, guidance, width, height, seed)
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-hyper.py", line 392, in gen_with_api
    return generate2(prompt, steps, guidance, width, height, seed)
  File "/home/ma/work/flux/demo/TotoroUI/flux-demo-hyper.py", line 513, in generate2
    flux_pipe = FluxPipeline.from_pretrained(bfl_repo, transformer=transformer, torch_dtype=torch.float8_e4m3fn)
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 859, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 698, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3794, in from_pretrained
    dtype_orig = cls._set_default_torch_dtype(torch_dtype)
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1608, in _set_default_torch_dtype
    torch.set_default_dtype(dtype)
  File "/home/ma/miniconda3/envs/flux/lib/python3.10/site-packages/torch/__init__.py", line 1009, in set_default_dtype
    _C._set_default_dtype(d)
TypeError: couldn't find storage object Float8_e4m3fnStorage

### Reproduction

flux_pipe = FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=torch.float8_e4m3fn)

## Another issue:
1. I want to implement flux1-dev-fp8 + t5-fp8 + hyper Lora. How can I achieve this using diffusers? The online resources are confusing, and despite my efforts, I haven't been able to succeed with any of the methods I've tried. Could you provide the implementation code?

2. How do you load a model from a single file?
**like this?**
transformer = FluxTransformer2DModel.from_pretrained(bfl_repo2, subfolder="transformer", torch_dtype=torch.float8_e4m3fn, revision=revision)
flux_pipe = FluxPipeline.from_pretrained(bfl_repo, transformer=transformer, torch_dtype=torch.float8_e4m3fn)

**Hyper-Flux1-dev:**
https://huggingface.co/bdsqlsz/Hyper-Flux1-dev/tree/main

### System Info

1

**Comment by tolgacangoz** [comment]
[Could you examine Flux's documentation page for the float8 recommendation?](https://huggingface.co/docs/diffusers/main/en/api/pipelines/flux#single-file-loading-for-the-fluxtransformer2dmodel)

**Comment by maxin9966** [comment]
@tolgacangoz I tried, but the reasoning performance is much lower than Comfy.
