### ISSUE TITLE
[Flux] FluxControlNetPipeline run on Flux 1. schnell bug

### ISSUE THREAD

**Issue by yinian-lw** [huggingface/diffusers#9309]
### Describe the bug

When I use FluxControlNetPipeline,  
`Loading pipeline components...:   0%|                                                                                                                                   | 0/7 [00:00<?, ?it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  8.51it/s]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.35it/s]
  0%|                                                                                                                                                                  | 0/28 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/dreamcloth_imggen/scripts/flux_demo.py", line 163, in <module>
    controlnet_demo()
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/dreamcloth_imggen/scripts/flux_demo.py", line 85, in controlnet_demo
    image = pipe(
            ^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/diffusers/pipelines/flux/pipeline_flux_controlnet.py", line 851, in __call__
    controlnet_block_samples, controlnet_single_block_samples = self.controlnet(
                                                                ^^^^^^^^^^^^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/diffusers/models/controlnet_flux.py", line 281, in forward
    self.time_text_embed(timestep, pooled_projections)
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/bn/liwen/mlx/users/liwen.8459/playground/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CombinedTimestepGuidanceTextProjEmbeddings.forward() missing 1 required positional argument: 'pooled_projection'`

### Reproduction

```
from diffusers import FluxControlNetModel, FluxControlNetPipeline

controlnet_model = "InstantX/FLUX.1-dev-Controlnet-Union"
controlnet = FluxControlNetModel.from_pretrained(controlnet_model, torch_dtype=torch.bfloat16)
pipe = FluxControlNetPipeline.from_pretrained(
         "black-forest-labs/FLUX.1-schnell", controlnet=controlnet, torch_dtype=torch.bfloat16)
pipe.to("cuda")

control_image = load_image("https://huggingface.co/InstantX/SD3-Controlnet-Canny/resolve/main/canny.jpg")
prompt = "A girl in city, 25 years old, cool, futuristic"
image = pipe(
        prompt,
        control_image=control_image,
        controlnet_conditioning_scale=0.6,
        num_inference_steps=28,
        guidance_scale=3.5,
    ).images[0]
```

### System Info

diffusers==0.31.0.dev0

**Comment by christopher-beckham** [comment]
AFAIK the Schnell model is not meant to be used with a non-zero guidance scale, though even with a guidance scale of 0.0 this error will still pop up. It's related to this line here in the ControlNet:

```
text_time_guidance_cls = (
    CombinedTimestepGuidanceTextProjEmbeddings if guidance_embeds else CombinedTimestepTextProjEmbeddings
)
```

Basically you need to pass `guidance_embeds=False` when you init the ControlNet so that the class sets `text_time_guidance_cls` to be `CombinedTimestepTextProjEmbeddings` instead.

**Comment by yiyixuxu** [comment]
`InstantX/FLUX.1-dev-Controlnet-Union` should work with `flux1-dev`, no? you are using `FLUX.1-schnell` here
