### ISSUE TITLE
add new parameter module of CogVideoXTransformer3DModel, raise error

### ISSUE THREAD

**Issue by trouble-maker007** [huggingface/diffusers#9415]
### Describe the bug

I was add a new nn.Conv2d in the CogVideoXPatchEmbed of CogVideoXTransformer3DModel, and get a new CogVideoXTransformer3DPoseModel, while use from_pretrained method raise error, it is ok while load 2B model, but switch 5B, 

### Reproduction
```python
args.pretrained_model_name_or_path = "/home/local_path/CogVideoX-5b"
transformer = CogVideoXTransformer3DPoseModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="transformer", revision=args.revision, variant=args.variant, low_cpu_mem_usage=False, device_map=None
    )
```

### Logs

```shell
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.05it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 103, in load_state_dict
[rank0]:     file_extension = os.path.basename(checkpoint_file).split(".")[-1]
[rank0]:   File "/home/work/miniconda3/envs/py310/lib/python3.10/posixpath.py", line 142, in basename
[rank0]:     p = os.fspath(p)
[rank0]: TypeError: expected str, bytes or os.PathLike object, not NoneType

[rank0]: During handling of the above exception, another exception occurred:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/work/local_path/train_cogvideox_pose.py", line 1079, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/work/local_path/train_cogvideox_pose.py", line 676, in main
[rank0]:     transformer = CogVideoXTransformer3DImageToVideoModel.from_pretrained(
[rank0]:   File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 828, in from_pretrained
[rank0]:     state_dict = load_state_dict(model_file, variant=variant)
[rank0]:   File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 115, in load_state_dict
[rank0]:     with open(checkpoint_file) as f:
[rank0]: TypeError: expected str, bytes or os.PathLike object, not NoneType
E0911 12:53:34.995000 140254569887552 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 282311) of binary: /home/work/miniconda3/envs/py310/bin/python
Traceback (most recent call last):
  File "/home/work/miniconda3/envs/py310/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    deepspeed_launcher(args)
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 852, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/work/miniconda3/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_cogvideox_image_to_video_inpaint.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-11_12:53:34
  host      : codeserver-293d083f-bfa3-451c-b462-9c65704003b7-6c9c5b4fd4fvhbh
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 282311)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### System Info

accelerate                0.34.2
deepspeed                 0.15.1
diffusers                 0.30.2
transformers              4.44.2

**Comment by trouble-maker007** [comment]
@a-r-r-o-w the same code in THUDM/CogVideoX-2b with local path is ok, I will try another to load the pretrained model

**Comment by Ttttttttyj** [comment]
> [@a-r-r-o-w](https://github.com/a-r-r-o-w) the same code in THUDM/CogVideoX-2b with local path is ok, I will try another way to load the pretrained model
How did you solve it?
