### ISSUE TITLE
Can't add a custom checkpoint model to convert to ONNX

### ISSUE THREAD

**Issue by Yanislar** [huggingface/diffusers#945]
### Describe the bug

I'm using one of the models used here: https://rentry.co/sdmodels

I get hit with an error **It looks like the config file at 'C:\amd_img2img\model.ckpt' is not a valid JSON file.**

### Full error message 
```
(diffusers_venv) PS C:\amd_img2img\diffusers> python .\scripts\convert_stable_diffusion_checkpoint_to_onnx.py --model_path "C:\amd_img2img\model.ckpt" --output_path "C:\amd_img2img\onnx"
Traceback (most recent call last):
  File "C:\amd_img2img\diffusers\src\diffusers\configuration_utils.py", line 277, in get_config_dict
    config_dict = cls._dict_from_json_file(config_file)
  File "C:\amd_img2img\diffusers\src\diffusers\configuration_utils.py", line 329, in _dict_from_json_file
    text = reader.read()
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\amd_img2img\diffusers\scripts\convert_stable_diffusion_checkpoint_to_onnx.py", line 227, in <module>
    convert_models(args.model_path, args.output_path, args.opset)
  File "C:\amd_img2img\diffusers_venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\amd_img2img\diffusers\scripts\convert_stable_diffusion_checkpoint_to_onnx.py", line 73, in convert_models
    pipeline = StableDiffusionPipeline.from_pretrained(model_path)
  File "C:\amd_img2img\diffusers\src\diffusers\pipeline_utils.py", line 367, in from_pretrained
    config_dict = cls.get_config_dict(
  File "C:\amd_img2img\diffusers\src\diffusers\configuration_utils.py", line 279, in get_config_dict
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at 'C:\amd_img2img\model.ckpt' is not a valid JSON file.
```

### Reproduction

I placed the checkpoint file just outside the directory of /diffusers/ and ran 
```
python .\scripts\convert_stable_diffusion_checkpoint_to_onnx.py --model_path "C:\amd_img2img\model.ckpt" --output_path "C:\amd_img2img\onnx"
```

### Logs

```shell
python -m venv diffusers_venv
. ./diffusers/Scripts/activate
git clone https://github.com/huggingface/diffusers
cd diffusers
pip install -e .
pip install transformers scipy ftfy onnx onnxruntime torch
```

### System Info

- `diffusers` version: 0.7.0.dev0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.7
- PyTorch version (GPU?): 1.12.1+cpu (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by SkyTNT** [comment]
You need to convert the ckpt to diffusers first, then use this script to convert the diffusers model to onnx

**Comment by patrickvonplaten** [comment]
Thanks @SkyTNT !
