### ISSUE TITLE
Enable assigning a list of SD3ControlNetModel to StableDiffusion3ControlNetPipeline

### ISSUE THREAD

**Issue by avrech** [huggingface/diffusers#9460]
### Describe the bug

StableDiffusion3ControlNetPipeline seems to lack full support for multiple controlnets like in StableDiffusionXLControlNetPipeline.
When feeding a list of SD3ControlNetModel, it does not converts them to SD3MultiControlNetModel and then crashes with:
AttributeError: 'list' object has no attribute '__module__' 

I suggest a simple fix, adding conversion to SD3MultiControlNetModel like in StableDiffusion3ControlNetPipeline right after the `super().__init__()` call.

### Reproduction

```
from diffusers import StableDiffusion3ControlNetPipeline
from diffusers.models import SD3ControlNetModel
controlnet_depth = SD3ControlNetModel.from_pretrained("InstantX/SD3-Controlnet-Depth")
controlnet_pose = SD3ControlNetModel.from_pretrained("InstantX/SD3-Controlnet-Pose")
pipe = StableDiffusion3ControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-3-medium-diffusers",
    controlnet=[controlnet_depth, controlnet_pose]
)
```

### Logs

```shell
diffusers version: 0.31.0.dev0
Loading pipeline components...:   0%|          | 0/9 [00:00<?, ?it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...:  44%|████▍     | 4/9 [00:00<00:00,  5.79it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.09s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.99s/it]
Loading pipeline components...: 100%|██████████| 9/9 [00:11<00:00,  1.31s/it]
Traceback (most recent call last):
  File "/home/avrech/Downloads/pycharm-professional-2024.1/pycharm-2024.1/plugins/python/helpers/pydev/pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/avrech/Downloads/pycharm-professional-2024.1/pycharm-2024.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/avrech/projects/SyntheticDatasetGenerator/playground/sd3_ctrl_example.py", line 24, in <module>
    pipe = StableDiffusion3ControlNetPipeline.from_pretrained(
  File "/home/avrech/virtualenvs/sd3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/avrech/projects/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 922, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/home/avrech/projects/diffusers/src/diffusers/pipelines/controlnet_sd3/pipeline_stable_diffusion_3_controlnet.py", line 196, in __init__
    self.register_modules(
  File "/home/avrech/projects/diffusers/src/diffusers/pipelines/pipeline_utils.py", line 163, in register_modules
    library, class_name = _fetch_class_library_tuple(module)
  File "/home/avrech/projects/diffusers/src/diffusers/pipelines/pipeline_loading_utils.py", line 729, in _fetch_class_library_tuple
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'list' object has no attribute '__module__'. Did you mean: '__mul__'?
```

### System Info

- 🤗 Diffusers version: 0.31.0.dev0
- Platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.4.1+cu118 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.24.7
- Transformers version: 4.44.2
- Accelerate version: 0.34.2
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: 0.0.28.post1
- Accelerator: NVIDIA GeForce RTX 3090, 24576 MiB
NVIDIA GeForce RTX 3090, 24576 MiB
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

### Who can help?

@yiyixuxu @sayakpaul

**Comment by sayakpaul** [comment]
Sure, would you be willing to open a PR to contribute this feature?

**Comment by sayakpaul** [comment]
@avrech WDYT?

**Comment by asomoza** [comment]
oh, this was added with this [PR](https://github.com/huggingface/diffusers/pull/9652). Closing it now since it wasn't linked to this issue.
