### ISSUE TITLE
Add FLUX image-to-image to `AutoPipelineForImage2Image` 

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#9492]
**Is your feature request related to a problem? Please describe.**
Currently `FluxImg2ImgPipeline` is not mapped to `AutoPipelineForImage2Image`

**Describe the solution you'd like.**

**Additional context.**
Here's the error
```shell
Traceback (most recent call last):
  File "/home/user/app/app.py", line 28, in <module>
    pipe_i2i = AutoPipelineForImage2Image.from_pretrained("black-forest-labs/FLUX.1-dev", torch_dtype=dtype).to(device)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 670, in from_pretrained
    image_2_image_cls = _get_task_class(AUTO_IMAGE2IMAGE_PIPELINES_MAPPING, orig_class_name)
  File "/usr/local/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 214, in _get_task_class
    raise ValueError(f"AutoPipeline can't find a pipeline linked to {pipeline_class_name} for {model_name}")
ValueError: AutoPipeline can't find a pipeline linked to FluxPipeline for flux
```

**Comment by apolinario** [comment]
Oops. Nevermind.
