### ISSUE TITLE
Can't upscale anything. Keep getting "KeyError: 'middle_block_out.0.weight'" error/

### ISSUE THREAD

**Issue by evanerichards** [huggingface/diffusers#9505]
### Describe the bug

I have a newly installed version of Invoke v5.0.0.rc1. I take a simple image and try to upscale but I recieve this error message:

```
[2024-09-23 15:05:39,510]::[InvokeAI]::ERROR --> Error while invoking session 9f8db22a-dc2e-4fef-b19b-5e9672a7e259, invocation d3477dbe-f38e-4ea6-b5bb-bc1c3232d273 (denoise_latents): 'middle_block_out.0.weight'
[2024-09-23 15:05:39,511]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 790, in invoke
    return self._old_invoke(context)
  File "E:\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\evane\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 1022, in _old_invoke
    controlnet_data = self.prep_control_data(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 437, in prep_control_data
    control_model = exit_stack.enter_context(context.models.load(control_info.control_model))
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 369, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\controlnet.py", line 31, in _load_model
    return ControlNetModel.from_single_file(
  File "E:\invokeai\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\controlnet.py", line 124, in from_single_file
    component = create_diffusers_controlnet_model_from_ldm(
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 973, in create_diffusers_controlnet_model_from_ldm
    diffusers_format_controlnet_checkpoint = convert_controlnet_checkpoint(checkpoint, diffusers_config)
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 937, in convert_controlnet_checkpoint
    new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
KeyError: 'middle_block_out.0.weight'
```

### Reproduction

After install I picked a small images and clicked "invoke" to upscale it (after setting up the upscaler)

### Logs

```shell
[2024-09-23 15:05:39,510]::[InvokeAI]::ERROR --> Error while invoking session 9f8db22a-dc2e-4fef-b19b-5e9672a7e259, invocation d3477dbe-f38e-4ea6-b5bb-bc1c3232d273 (denoise_latents): 'middle_block_out.0.weight'
[2024-09-23 15:05:39,511]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 790, in invoke
    return self._old_invoke(context)
  File "E:\invokeai\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\evane\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 1022, in _old_invoke
    controlnet_data = self.prep_control_data(
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\invocations\denoise_latents.py", line 437, in prep_control_data
    control_model = exit_stack.enter_context(context.models.load(control_info.control_model))
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 369, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 56, in load_model
    locker = self._load_and_cache(model_config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 77, in _load_and_cache
    loaded_model = self._load_model(config, submodel_type)
  File "E:\invokeai\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_loaders\controlnet.py", line 31, in _load_model
    return ControlNetModel.from_single_file(
  File "E:\invokeai\.venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\controlnet.py", line 124, in from_single_file
    component = create_diffusers_controlnet_model_from_ldm(
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 973, in create_diffusers_controlnet_model_from_ldm
    diffusers_format_controlnet_checkpoint = convert_controlnet_checkpoint(checkpoint, diffusers_config)
  File "E:\invokeai\.venv\lib\site-packages\diffusers\loaders\single_file_utils.py", line 937, in convert_controlnet_checkpoint
    new_checkpoint["controlnet_mid_block.weight"] = controlnet_state_dict.pop("middle_block_out.0.weight")
KeyError: 'middle_block_out.0.weight'
```

### System Info

- `diffusers` version: 0.25.0
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.11
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- Huggingface_hub version: 0.20.1
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.23.post1+cu118
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Don't know

### Who can help?

@sayakpaul @DN6

**Comment by asomoza** [comment]
Hi, you should open an issue in the Invoke repository, even though Invoke uses diffusers as a backend, it adds a lot more code on top of it.

If you can reproduce the same error with a pure diffusers code snippet, we'll gladly help you.

**Comment by evanerichards** [comment]
Thanks. Sorry about posting here. I have absolutely know idea how that happened.
