### ISSUE TITLE
FluxImg2ImgPipeline and FluxInpaintPipeline image batching error (0.31.0.dev)

### ISSUE THREAD

**Issue by Teriks** [huggingface/diffusers#9611]
### Describe the bug

Providing multiple input images, i.e. a batch number other than 1 to ``FluxImg2ImgPipeline`` or ``FluxInpaintPipeline`` results in a tensor shape error.

### Reproduction

Img2Img:

```python 
import PIL.Image
import diffusers
import torch


# img2img

pipe = diffusers.FluxImg2ImgPipeline.from_pretrained('black-forest-labs/FLUX.1-schnell', torch_dtype=torch.bfloat16)

pipe.enable_sequential_cpu_offload(device='cuda')

image = PIL.Image.new('RGB', (1024, 1024))

result = pipe(prompt='hello world', image=[image, image])
```

Inpainting:

``` python
import PIL.Image
import diffusers
import torch

# inpaint

pipe = diffusers.FluxInpaintPipeline.from_pretrained('black-forest-labs/FLUX.1-schnell', torch_dtype=torch.bfloat16)

pipe.enable_sequential_cpu_offload(device='cuda')

image = PIL.Image.new('RGB', (1024, 1024))
mask = PIL.Image.new('RGB', (1024, 1024))

result = pipe(prompt='hello world', image=[image, image], mask_image=[mask, mask])

```

### Logs
Img2Img:

```shell

REDACT\venv\Scripts\python.exe REDACT\test.py 
Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:02,  2.22it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...:  57%|█████▋    | 4/7 [00:00<00:00,  7.20it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  9.78it/s]
Loading pipeline components...: 100%|██████████| 7/7 [00:01<00:00,  6.47it/s]
REDACT\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py:480: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Traceback (most recent call last):
  File "REDACT\test.py", line 14, in <module>
    result = pipe(prompt='hello world', image=[image, image])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_img2img.py", line 761, in __call__
    latents, latent_image_ids = self.prepare_latents(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_img2img.py", line 553, in prepare_latents
    latents = self._pack_latents(latents, batch_size, num_channels_latents, height, width)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_img2img.py", line 489, in _pack_latents
    latents = latents.view(batch_size, num_channels_latents, height // 2, 2, width // 2, 2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 16, 64, 2, 64, 2]' is invalid for input of size 524288

Process finished with exit code 1
```

Inpainting:

```shell

REDACT\venv\Scripts\python.exe REDACT\test.py 
Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  9.99it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  9.64it/s]
Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:01,  2.58it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|██████████| 7/7 [00:01<00:00,  5.74it/s]
REDACT\venv\Lib\site-packages\transformers\models\clip\modeling_clip.py:480: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Traceback (most recent call last):
  File "REDACT\test.py", line 26, in <module>
    result = pipe(prompt='hello world', image=[image, image], mask_image=[mask, mask])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_inpaint.py", line 892, in __call__
    latents, noise, image_latents, latent_image_ids = self.prepare_latents(
                                                      ^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_inpaint.py", line 578, in prepare_latents
    image_latents = self._pack_latents(image_latents, batch_size, num_channels_latents, height, width)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACT\venv\Lib\site-packages\diffusers\pipelines\flux\pipeline_flux_inpaint.py", line 510, in _pack_latents
    latents = latents.view(batch_size, num_channels_latents, height // 2, 2, width // 2, 2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 16, 64, 2, 64, 2]' is invalid for input of size 524288

Process finished with exit code 1
```
```


### System Info

diffusers==0.31.0.dev (main branch)
torch==2.4.1+cu124
transformers==4.44.0

### Who can help?

@yiyixuxu @DN6

**Comment by Teriks** [comment]
I believe this is because the number of input images just is not taken into account for batch_size

**Comment by Teriks** [comment]
User error, false alarm :)

You need to set ``num_images_per_prompt`` manually to the number of input images in order to have the correct batch size, as it is not inferred from the arguments.
