### ISSUE TITLE
Inpainting example not working

### ISSUE THREAD

**Issue by seann999** [huggingface/diffusers#964]
### Describe the bug

```
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 45756.04it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 707, in convert_to_tensors
    tensor = as_tensor(value)
RuntimeError: Could not infer dtype of NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inpaint.py", line 37, in <module>
    image = pipe(prompt=prompt, image=init_image, mask_image=mask_image).images[0]
  File "/home/sean/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sean/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 243, in __call__
    text_inputs = self.tokenizer(
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2497, in __call__
    return self.encode_plus(
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2570, in encode_plus
    return self._encode_plus(
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 649, in _encode_plus
    return self.prepare_for_model(
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3048, in prepare_for_model
    batch_outputs = BatchEncoding(
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 209, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/sean/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 723, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.
```

### Reproduction

Copy-paste the inpainting code in the readme or tutorial

### System Info

- `diffusers` version: 0.6.0
- Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.14.0.dev20221021+cu117 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.19.2
- Using GPU in script?: 3080
- Using distributed or parallel set-up in script?: no

**Comment by seann999** [comment]
Installing a different version fixed it
