### ISSUE TITLE
Schedulers not compatible with OnnxStableDiffusionPipeline: TypeError: unsupported operand

### ISSUE THREAD

**Issue by Tnifey** [huggingface/diffusers#967]
### Describe the bug

Hi,
I tried to use different schedulers with OnnxStableDiffusionPipeline, but it throw errors.
Schedulers are not compatible with numpy used in onnx pipeline.

Onnx checkpoints converted with: [convert_stable_diffusion_checkpoint_to_onnx.py](https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py)

I have found a solution, but it is probably not optimal, because torch usage inside pipeline __call__.

Solution works with:
- `CompVis/stable-diffusion-v1-4`
- `hakurei/waifu-diffusion`

First error:
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 152, in __call__
  latents = latents * self.scheduler.init_noise_sigma
TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
```

If I cast latents to torch.tensor, before init_noise_sigma:
```py
latents = torch.tensor(latents)
latents = latents * self.scheduler.init_noise_sigma
```
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 171, in __call__
  noise_pred = self.unet(
File "C:\...\diffusers\onnx_utils.py", line 46, in __call__
  return self.model.run(None, inputs)
File "C:\...\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
  return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(int64))
```

If I add dtype=np.int64 to timestep in unet args:
```py
# predict the noise residual
noise_pred = self.unet(
  sample=latent_model_input,
  timestep=np.array([t], dtype=np.int64),
  encoder_hidden_states=text_embeddings,
)
```
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 184, in __call__
  latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
File "C:\...\diffusers\schedulers\scheduling_lms_discrete.py", line 224, in step
  pred_original_sample = sample - sigma * model_output
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Tensor'
```

And if I cast latents to torch.tensor, before passing them into scheduler.step, it is working again:
```py
# compute the previous noisy sample x_t -> x_t-1
latents = torch.tensor(latents)
latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
latents = np.array(latents)
```

### Reproduction

```py
from diffusers import OnnxStableDiffusionPipeline, LMSDiscreteScheduler

lms = LMSDiscreteScheduler()

pipe = OnnxStableDiffusionPipeline.from_pretrained(
    model_path,
    provider="DmlExecutionProvider",
    scheduler=lms,
    local_files_only=True,
)

image = pipe("prompt")[0]
```

### System Info

- `diffusers` version: 0.6.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.7
- PyTorch version (GPU?): 1.12.1+cpu (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: DmlExecutionProvider
- Using distributed or parallel set-up in script?: <fill in>

- GPU: AMD RX 6900 XT 16GB

**Comment by patrickvonplaten** [comment]
@anton-l could you take a look here?

**Comment by averad** [comment]
@anton-l @patrickvonplaten only schedular that currently works out of the box with the Onnx Pipeline is PNDMScheduler. Is there a fix for this in Diffusers 0.7.0 beta?

**Comment by anton-l** [comment]
Sorry for missing this, will be fixed in 0.7.1 in a couple of days!

**Comment by averad** [comment]
@anton-l you and your team members are the best, thank you.

**Comment by averad** [comment]
@anton-l I installed diffusers 0.7.1 and tested the following schedulers using the Onnx pipeline

```
scheduler = PNDMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear")
scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False, set_alpha_to_one=False)
scheduler = LMSDiscreteScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000) 
```

Log ()
```
Traceback (most recent call last):
  File "D:\ai\txt_to_img.py", line 130, in <module>
    txt_to_img(prompt, negative_prompt, int(num_inference_steps), int(width), int(height), seed)
  File "D:\ai\txt_to_img.py", line 79, in txt_to_img
    image = pipe(
  File "D:\ai\sd_env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 206, in __call__
    noise_pred = self.unet(
  File "D:\ai\sd_env\lib\site-packages\diffusers\onnx_utils.py", line 46, in __call__
    return self.model.run(None, inputs)
  File "D:\ai\sd_env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(int64))

```
