### ISSUE TITLE
Problem when install the nodes.. [ERROR] An error occurred while retrieving information for the 'controlaux...

### ISSUE THREAD

**Issue by inglob** [huggingface/diffusers#9745]
FETCH DATA from: D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'controlaux_hed' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_midas' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_mlsd' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_openpose' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_pidi' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_dwpose' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_normal_bae' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_lineart_anime' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_zoe' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_sam' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_leres' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_canny' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_content' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[ERROR] An error occurred while retrieving information for the 'controlaux_face_detector' node.
Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\server.py", line 532, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

[]
[]

**Comment by a-r-r-o-w** [comment]
This looks like an error you should report at ComfyUI/controlnet_aux repositories and doesn't seem related to diffusers.

**Comment by inglob** [comment]
Yes, sorry, my mistake
