### ISSUE TITLE
Training DreamBooth SDXL LoRA script failed

### ISSUE THREAD

**Issue by zyf2316** [huggingface/diffusers#9970]
### Describe the bug

I used the default script for training a SDXL with Lora with dog dataset, but it output the following error: 
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'thresholding', 'rescale_betas_zero_snr', 'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zyf/Documents/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1994, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/zyf/Documents/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1111, in main
[rank0]:     text_encoder_one = text_encoder_cls_one.from_pretrained(
[rank0]:   File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2362, in from_pretrained
[rank0]:     model = cls(config, *model_args, **model_kwargs)
[rank0]: TypeError: __init__() got an unexpected keyword argument 'variant'

### Reproduction

export MODEL_NAME="stabilityai/stable-diffusion-xl-base-1.0"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="lora-trained-xl"
export VAE_PATH="madebyollin/sdxl-vae-fp16-fix"

accelerate launch train_dreambooth_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --pretrained_vae_model_name_or_path=$VAE_PATH \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --instance_prompt="a photo of sks dog" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="0" \
  --push_to_hub

### Logs

```shell
bash script_sdxl.sh 
Using RTX 4000 series which doesn't support faster communication speedups. Ensuring P2P and IB communications are disabled.
11/20/2024 14:05:48 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: fp16

/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'thresholding', 'rescale_betas_zero_snr', 'dynamic_thresholding_ratio', 'variance_type', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zyf/Documents/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1994, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/zyf/Documents/diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py", line 1111, in main
[rank0]:     text_encoder_one = text_encoder_cls_one.from_pretrained(
[rank0]:   File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2362, in from_pretrained
[rank0]:     model = cls(config, *model_args, **model_kwargs)
[rank0]: TypeError: __init__() got an unexpected keyword argument 'variant'
[rank0]:[W1120 14:05:51.927567657 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1120 14:05:52.257831 16803 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 16915) of binary: /home/zyf/anaconda3/envs/myenv/bin/python
Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/myenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zyf/anaconda3/envs/myenv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_dreambooth_lora_sdxl.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_14:05:52
  host      : a03436ebd9bc
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 16915)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### System Info

transformers              4.26.0                   pypi_0    pypi
python                    3.9.20               he870216_1  
diffusers                 0.32.0.dev0              pypi_0    pypi
numpy                     1.22.3                   pypi_0    pypi
torch                     2.5.1                    pypi_0    pypi
torchaudio                0.12.1+cpu               pypi_0    pypi
torchvision               0.20.1                   pypi_0    pypi

NVIDIA GeForce RTX 4090  
NVIDIA-SMI 535.183.01             
Driver Version: 535.183.01   
CUDA Version: 12.2

Ubuntu 20.04.3 LTS

### Who can help?

@sayakpaul @yiyixuxu

**Comment by sayakpaul** [comment]
Can you upgrade your transformers installation?

**Comment by zyf2316** [comment]
pip install --upgrade transformers
upgrading transformers from 4.26.0 to 4.46.3 works.

**Comment by zyf2316** [comment]
close
